### ISSUE TITLE
Staled Twitter icon

### ISSUE THREAD

**Issue by Ayush9026** [opentofu/opentofu#1025]
### OpenTofu Version

```shell
Website
```

### Description 

Twitter icon on Header section is old twitter is now 'X' corp.

**Solution**
Update with new one.

### Attempted Solutions

No i don't attempted this issue.

### Proposal

Change with new icon.

### References

Screenshot

![Open-tofu Websites](https://github.com/opentofu/opentofu/assets/114745463/3cb12d79-4542-4f35-a9d2-2193b965ff84)

**Comment by Dev79844** [comment]
I am interested to work on this but I have a doubt. Should I make a PR at opentofu.org repo as the code for the website is available there? I couldn't find the code for the website in this repo other than docs.

**Comment by janosdebugs** [comment]
@Dev79844 yes please, the website is located in the repo you mentioned. I've assigned the issue to you. Thank you for your help!

**Comment by Dev79844** [comment]
@janosdebugs I have made a PR in other repo. Please check it

**Comment by janosdebugs** [comment]
Resolved in opentofu/opentofu.org#267
