### ISSUE TITLE
tofu force-unlock should not fail on tofu version mismatch with remote backend

### ISSUE THREAD

**Issue by RLRabinowitz** [opentofu/opentofu#1026]
### OpenTofu Version

```shell
OpenTofu v1.6.0-dev
```

### OpenTofu Configuration Files

Any configuration with remote backend

### Debug Output

.

### Expected Behavior

`tofu force-unlock lock_id` should work even if local tofu version mismatches the version in remote backend

### Actual Behavior

`tofu force-unlock` removes the lock but fails:

```
│ Error: OpenTofu version mismatch
│
│ The local OpenTofu version (XXX) does not match the configured version for remote workspace WORKSPACE (YYY). If you're sure you want to upgrade the state, you can force OpenTofu to continue using the
│ -ignore-remote-version flag. This may result in an unusable workspace.
```

### Steps to Reproduce

1. `tofu force-unlock lock_id` on a state lock

### References

Related issue in the Terraform repository - https://github.com/hashicorp/terraform/issues/28853

**Comment by jjshanks** [comment]
I'd like to work on this
