### ISSUE TITLE
Add YouTube Channel Link and Update Twitter Icon in Footer

### ISSUE THREAD

**Issue by Ayush9026** [opentofu/opentofu#1028]
### OpenTofu Version

```shell
Website
```

### Use Cases

It would be beneficial to include a link to our YouTube channel in the project's footer and update the Twitter icon for a more cohesive look. These additions will not only improve user engagement but also streamline our social media visibility.

### Attempted Solutions

No i not attempted this issue.

### Proposal

**Proposed Changes**
Add YouTube Channel Link to Footer: As marked in screenshot.

Add a hyperlink to our official YouTube channel in the project's footer and also custom icon.

**Update Twitter Icon:**

Replace the current Twitter icon in the footer with an updated version for a more modern and polished appearance.

**Benefits**
Enhanced User Engagement: Providing easy access to our YouTube channel encourages users to explore additional content, fostering a stronger connection with our project.
Improved Aesthetics: Updating the Twitter icon ensures a visually appealing and consistent design in the project's footer.

### References

**Screenshot**

![Open-Tofu website](https://github.com/opentofu/opentofu/assets/114745463/7b3c2eca-3e71-4329-818f-3ad6e4f5377e)

**Comment by janosdebugs** [comment]
I believe this has been addressed.
