### ISSUE TITLE
Implement State Encryption

### ISSUE THREAD

**Issue by cube2222** [opentofu/opentofu#1030]
Issue to track the implementation of #874 

## Subtasks

- [ ] #1063
  - [x] #1160
    - [x] #1161
    - [x] #1162
    - [x] #1163
    - [x] #1164
    - [x] #1165
  - [x] #1166
    - [x] #1167
    - [x] #1168
    - [x] #1169
      - [x] #1170
    - [ ] #1171
    - [x] #1172
    - [x] #1173
    - [x] #1174
- [ ] #1175

**Comment by StephanHCB** [comment]
A Comment
