### ISSUE TITLE
Missing ssh in docker image

### ISSUE THREAD

**Issue by janosdebugs** [opentofu/opentofu#1031]
### Discussed in https://github.com/orgs/opentofu/discussions/1029

<div type='discussions-op-text'>

<sup>Originally posted by **tgauweiler** December 18, 2023</sup>
Hi,

while trying out opentofu as replacement for terraform we noticed that the opentofu Docker image doesn't have `ssh` installed, [see here](https://github.com/opentofu/opentofu/blob/v1.6.0-beta5/Dockerfile#L8).

The terraform image, [here](https://github.com/hashicorp/terraform/blob/v1.6.6/Dockerfile#L16), has `ssh` installed.

We need `ssh` as we pull terraform modules with ssh [tf docs](https://developer.hashicorp.com/terraform/language/modules/sources#github), so for now we will just build our own Docker image with `ssh` included.

But as opentofu aims to be a `drop-in replacement for Terraform`, please consider adding `ssh` to the docker image.

</div>

**Comment by cam72cam** [comment]
It looks like it was removed in https://github.com/opentofu/opentofu/pull/173 by @mbialon
