### ISSUE TITLE
Add support for `removed` block

### ISSUE THREAD

**Issue by RLRabinowitz** [opentofu/opentofu#1032]
### OpenTofu Version

```shell
1.6.0-dev
```

### Use Cases

Similarly to the `import` and `moved` blocks, which help manage changing the state through IaC without making any changes in the infrastructure or without using explicit `tofu` commands, it would be helpful if OpenTofu could support a `removed` block, which would be used to remove an object from the tofu state (doing `tofu state rm`)

### Attempted Solutions

Today, the only way to remove an object from state is to `tofu state rm`, and cannot be done in pure IaC

### Proposal

Similarly to `import` or `moved`, create a `removed` block:

```
removed {
  from = "resource.address"
}
```

`tofu` could check that there are no references to the resource address, and remove it from state during `apply`

### References

Related issues - https://github.com/hashicorp/terraform/issues/33226, https://github.com/opentofu/opentofu/issues/996
Related issue in the Terraform repository - https://github.com/hashicorp/terraform/issues/34402,

**Comment by lorengordon** [comment]
I had transferred the related terraform issue earlier, https://github.com/opentofu/opentofu/issues/299, but the content was wiped out when external references were removed. I'll close that issue in favor of this one.
