### ISSUE TITLE
Best way to verify the SHA256SUMS file is valid with the ".sig" and/or ".pem" files?

### ISSUE THREAD

**Issue by junktext** [opentofu/opentofu#1035]
### OpenTofu Version

```shell
OpenTofu v1.6.0-beta5
on linux_amd64
```

### Use Cases

Recommended way to manually ensure that the SHA256SUMS file provided on the Releases area are cryptographically verified with the provided ".sig" and/or ".pem" files.

Note: I manually downloaded the following files from https://github.com/opentofu/opentofu/releases/tag/v1.6.0-beta5:
- `tofu_1.6.0-beta5_linux_amd64.zip`
- `tofu_1.6.0-beta5_SHA256SUMS`
- `tofu_1.6.0-beta5_SHA256SUMS.pem`
- `tofu_1.6.0-beta5_SHA256SUMS.sig`

### Attempted Solutions

I've tried running various GPG and OpenSSL commands as suggested on various non-OpenTofu related websites (listed below) to confirm that the SHA256SUMS file (e.g., `tofu_1.6.0-beta5_SHA256SUMS`) can be verified with the associated ".sig" (e.g., `tofu_1.6.0-beta5_SHA256SUMS.sig`) and ".pem" (e.g., `tofu_1.6.0-beta5_SHA256SUMS.pem`) files, but it is not obvious to me how to do this properly for OpenTofu. I am sure I am doing something wrong on my end, so I would appreciate a short how-to guide.

To be clear, I am able to generate the same SHA-256 hash as mentioned in the SHA256SUMS file which I did this for `tofu_1.6.0-beta5_linux_amd64.zip`, so this feature request is not about the basic concept of checking the hash locally. Instead, it is to confirm that the hash file itself is an authoritative copy signed by the OpenTofu team.

Because I am more familiar with verifying packages signed with GPG, I attempted to use the ".sig" file with this process. So, I grabbed and imported the public GPG key for OpenTofu based upon the installation instructions for using the DEB package, which in the script described refers to: https://packages.opentofu.org/opentofu/tofu/gpgkey

Though, attempting the GPG route, I get the following:

```
$ gpg --verify tofu_1.6.0-beta5_SHA256SUMS.sig tofu_1.6.0-beta5_SHA256SUMS
gpg: no valid OpenPGP data found.
gpg: the signature could not be verified.
Please remember that the signature file (.sig or .asc)
should be the first file given on the command line.
```

So, then I tried dealing with an OpenSSL verification process as suggested on the following websites, but nothing seems to be helpful:

- https://www.ibm.com/docs/en/nasm/1.1.10?topic=verify-digital-signatures
- https://stackoverflow.com/questions/2385320/verifying-a-file-signature-with-openssl-dgst
- https://stackoverflow.com/questions/40565364/generating-signing-and-verifying-digital-signature
- https://pagefault.blog/2019/04/22/how-to-sign-and-verify-using-openssl/
- https://www.zimuel.it/blog/sign-and-verify-a-file-using-openssl
- https://www.eclipsesource.com/blogs/2016/09/07/tutorial-code-signing-and-verification-with-openssl/
- https://stackoverflow.com/questions/11036863/signing-and-verifying-with-openssl
- https://security.stackexchange.com/questions/8956/openssl-verify-signature

### Proposal

Please just post a quick explanation of the best way to manually verify that the SHA256SUMS file for a particular release has been digitally-signed by the OpenTofu maintainers. Some possible areas to describe this could be either on the _portable binary_ installation method (https://opentofu.org/docs/intro/install/portable) or on the main README of the OpenTofu project. In particular, please address the following:

1. If required: Where/how to download or import the necessary public key(s) for the verification process to succeed in the end.
2. Command(s) needed to verify the `SHA256SUMS` file with the provided `SHA256SUMS.sig` and/or `SHA256SUMS.pem` files.

Thank you!
  --William

**Comment by janosdebugs** [comment]
Hi @junktext the SUMS file is signed with cosign, not GPG. That being said, I think we are now in a position to also sign it with GPG if that is more convenient. The manual installation instructions should indeed include verifying the signature. I'm marking this as a docs issue and assigning it to myself.

**Comment by dflook** [comment]
I mostly want to verify the SHA256SUMS file while using OpenTofu in an ephemeral CI environment.
Cosign makes this more difficult because it is not typically installed on ephemeral CI environments, unlike gpg.

I can include a trusted cosign binary in my build process, but it is a nearly 90MB binary.
Verifying the SHA256SUMS file then typically takes about 2 seconds, and requires internet access.

If I could verify the SHA256SUMS file using a known public PGP key this would be quicker and more reliable. I think people would be more likely to verify it using gpg.

**Comment by janosdebugs** [comment]
@dflook that's a valid point. I'll take a look if we can add GPG signatures alongside the existing cosign ones people are already using. It would also be helpful for [this script](https://github.com/opentofu/get.opentofu.org/pull/1).

**Comment by janosdebugs** [comment]
Updating this issue, in #1065 we are adding GPG signing for the stable release. This should make it a lot easier to verify binaries from GitHub.

**Comment by junktext** [comment]
Awesome! Thanks, @janosdebugs!
