### ISSUE TITLE
missing syntax highlight in install page

### ISSUE THREAD

**Issue by ty-v1** [opentofu/opentofu#1056]
Install command in [Installing OpenTofu via Homebrew](https://opentofu.org/docs/intro/install/homebrew) is not color coded.

<img width="2048" alt="brew" src="https://github.com/opentofu/opentofu/assets/23548312/3a28b3f7-4dee-40ee-a26b-0db934583293">

## My enviroment

- OS: macOS 14.1
- Browser: Sidekick 118.55.1.36995

**Comment by janosdebugs** [comment]
Hi @ty-v1 thank you for this issue. What highlighting would you expect for a simple command like this?

**Comment by ty-v1** [comment]
> Hi @ty-v1 thank you for this issue. What highlighting would you expect for a simple command like this?

I think it is preferable that the command is color coded like [Installing OpenTofu via Snapcraft](https://opentofu.org/docs/intro/install/snap/) page and has a copy button.

![snap](https://github.com/opentofu/opentofu/assets/23548312/40127b6e-7cb7-41e4-a232-cd585b43f131)

**Comment by janosdebugs** [comment]
@ty-v1 I see, that makes sense, thank you. Feel free to submit a PR if you like, or I'll update it the next time I work on the install instructions in January.
