### ISSUE TITLE
`tofu login` cannot be interrupted

### ISSUE THREAD

**Issue by leg100** [opentofu/opentofu#1058]
### OpenTofu Version

```shell
OpenTofu v1.7.0-dev
on linux_amd64
```

### OpenTofu Configuration Files

N/A

### Debug Output

https://gist.github.com/leg100/ac9548f268fba721d692b7928409f46b

### Expected Behavior

When running `tofu login <login.server>`, sending it a Ctrl-C is expected to terminate the process

### Actual Behavior

Nothing happens.

### Steps to Reproduce

1. Run a service that advertises [OAuth endpoints via remote service discovery](https://developer.hashicorp.com/terraform/internals/login-protocol), for example:

```golang
package main

import (
	"net/http"
)

func main() {
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-type", "application/json")
		w.Write([]byte(`{
	"login.v1": {
		"client": "terraform-cli",
		"grant_types": ["authz_code"],
		"authz": "/oauth/authorization",
		"token": "/oauth/token",
		"ports": [10000, 10010]
	}
}`))
	})
	http.ListenAndServeTLS("localhost:8080", "cert.pem", "key.pem", nil)
}
```
2. Run `tofu login` and enter `yes`:

```
137> tofu login localhost:8080
OpenTofu will request an API token for localhost:8080 using OAuth.

This will work only if you are able to use a web browser on this computer to
complete a login process. If not, you must obtain an API token by another
means and configure it in the CLI configuration manually.

If login is successful, OpenTofu will store the token in plain text in
the following file for use by subsequent commands:
    /home/louis/.terraform.d/credentials.tfrc.json

Do you want to proceed?
  Only 'yes' will be accepted to confirm.

  Enter a value: yes
```
3. `tofu` opens a browser; ignore and instead attempt to terminate the `tofu` process by entering `Ctrl-C`. Nothing will happen.
4. You are forced to open another terminal and send the `tofu` process a SIGKILL.

```
1> pkill -9 tofu
```

```
OpenTofu will now wait for the host to signal that login was successful.

^C^C^CKilled
```

### Additional Context

This has long been a problem with `terraform login` as well.

The problem does _not_ occur when the given login server hostname is `app.terraform.io` because the code has a special branch for that hostname that skips OAuth.

**Comment by janosdebugs** [comment]
Thank you for this issue @leg100 ! We will review pending issues in January as most of the team is not working over the holidays.

**Comment by cube2222** [comment]
Thanks for submitting this bug!

I can confirm this issue (encountered it many times) and definitely agree `tofu login` could use improvements.

**Comment by maksym-nazarenko** [comment]
hello @cube2222 @janosdebugs , is this issue `accepted` for development?
I've created a very first PR in this repo to address this issue, so let me know if it doesn't fit contribution requirements

**Comment by janosdebugs** [comment]
Hey @maksym-nazarenko sorry for the delay. I marked the issue as accepted now.
