### ISSUE TITLE
Allow defining of empty objects with type definitions

### ISSUE THREAD

**Issue by alex067** [opentofu/opentofu#1061]
### OpenTofu Version

```shell
OpenTF v1.6.0-dev
on darwin_arm64
```

### Use Cases

It's been a while since I've been following with the development, apologies if this feature has already been implemented. 

One of the weakpoints in Terraform is clean type definitions, especially as it pertains to objects. Here is an example:
```hcl
variable "dynamo_global_secondary_index" {
  type = object({
    name               = string
    hash_key           = string
    range_key          = optional(string, null)
    write_capacity     = optional(number)
    read_capacity      = optional(number)
    projection_type    = string
    non_key_attributes = optional(list(string), null)
  })
  default = {}
  description = "Describe a GSI for the table; subject to the normal limits on the number of GSIs, projected attributes, etc."
}
```
The default value of an empty object does not work in Terraform, because I have clearly defined the object type and its expectancies. However this doesn't make much sense because objects in their nature are dynamic. We should be allowed to define the entire object as optional, however if the object is present, here are the keys we expect. 

The error we receive:
```
│ This default value is not compatible with the variable's type constraint: attributes "hash_key", "name", and "projection_type" are required.
╵
```

The workaround is to define more inline conditionals that checks if the required keys don't equal null or empty, which is fine, but the readability is terrible especially if we can define those guard rails in the type definition. 

### Attempted Solutions

I am happy to take a look at this if this isn't a problem that's already being solved.

**Comment by janosdebugs** [comment]
Hey @alex067 this sounds interesting. I have a question about your example though: how would you expect your syntax to look like to mark the entire objext as optional? Also, specifying `{}` does provide an object, an empty one, so the behavior is factually correct. A different default value would be needed to mark the actual lack of an object. The point being that the default value should always comply with the schema, otherwise a change like this eould lead to bugs.

**Comment by alex067** [comment]
Thanks everyone for the feedback! 

@janosdebugs ideally the syntax should remain as `{}` rather than `null` to preserve the type constraint. Even though the type specifies what keys it expects if the object is defined. The issue is due to the declarative nature of HCL, it results in "hacks" to check if the object is provided. 

For example with the object schema I provided, we would have to do:
`var.dynamo_global_secondary_index.name != ""` 

as opposed to something like: `try(var.dynamo_global_secondary_index, {})` 

I'm curious to why this would lead to bugs, although I understand the way it is now is correct and there's nothing inherently wrong with it.

**Comment by janosdebugs** [comment]
@alex067 to me, this doesn't seem to be a good way of moving forward. On one hand, you have a default value of an empty object, on the other hand the schema describes an object that must contain certain fields. In my mind, the schema should always cover the default value of a variable.

How this can lead to bugs: assume, you are writing a module without robust testing practices. (Yes, you should be testing, but let's be honest, nobody tests every edge case.) You pass `{}` for a default value, but you never test the default value actually being used. Your code relies on those object fields to be set and has no handling for the case when they are not. There is no way any linting tool or other utilities can warn you about this scenario, unless they specifically account for the default value being non-compliant with the schema.

In my mind, the default value should always be compliant with the schema. If you need to allow for empty objects, then the schema should, in some way, shape or form, allow for an empty object to be passed. Maybe the way to do that is to include a mechanism similar to the `oneOf` in OpenAPI that allows alternative variable types.

**Comment by Yantrio** [comment]
In my opinion this is trying to solve a similar problem to `undefined` vs `null` in javascript/typescript. And this point already causes a lot of confusion in those areas too. Overall whilst I like the advantage of the type safety, I feel like @janosdebugs' comment is very valid.

> In my mind, the default value should always be compliant with the schema

Without us having the concept of an "unknown" or "undefined" value for the variable, we are ensuring that consumers of the variable can always use it knowing that the schema can act as documentation.

If we bring in the idea of allowing empty objects with non-defined required properties, a consumer of this variable may be shocked to find that it is an empty object.

Overall, I understand the idea of the proposal, but I think that it brings a lot more complications for larger projects being worked on by multiple people, than it does bring any advantages.

**Comment by alex067** [comment]
Thank you @Yantrio and @janosdebugs for your feedback! I understand the drawbacks and why this could inadvertently cause more issues than solving them. 

Thanks again for the discussion, will close this one out.
