### ISSUE TITLE
Nephio OpenTofu Integration 

### ISSUE THREAD

**Issue by ssharmasandeep** [opentofu/opentofu#1080]
### Summary

Automate the creation and modification of Terraform plans for various kinds of infrastructure based on the high level intent specified for end-to-end infrastructure topology deployment.

### Problem Statement

Edge deployments can have 10s of thousands of locations as opposed to just a few for cloud deployments. Edge deployments can also consist of multiple vendors as opposed to cloud deployments that are a lot more homogeneous. This combination means that the scale is much larger, could be 100,000x greater. The scale has multiple implications on a traditional Terraform based IaC approach. The below list is a result of learnings from the LF Edge Akraino [Public Cloud Edge Interface](https://wiki.akraino.org/display/AK/Public+Cloud+Edge+Interface+%28PCEI%29+Blueprint+Family) (PCEI) project on the limitations of using a Terraform only approach:

Creating and modifying Terraform plans manually for each edge environment is impractical
Managing dependencies manually between different orchestrated elements is impractical
In the PCEI project, we would routinely have to run Terraform Plan A, then copy the result of that (e.g. keys) into another Terraform Plan B and then run that plan, so on and so forth.
When these complex deployments would fail, the use of declarative + imperative constructs makes it very difficult to debug Terraform plans
The pure Terraform based approach would be good for Day 0 only esp. when there were multiple domains and multiple automation tools were used e.g. Ansible, Netconf etc.
The pure Terraform based approach would make it difficult to couple workload orchestration along with infrastructure orchestration, esp. when other tools were used such as Helm

### User-facing description

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-96e7e58e-7fff-5364-4879-b6bc3356e6b5"><div dir="ltr" style="margin-left:0pt;" align="left">
Declarative intent | Convert IaC to IaD/CaD (infrastructure-as-data or configuration-as-data) At scale, mixing declarative and imperative can make it difficult to define the intent and to troubleshoot failures
-- | --
Business intent to technical intent mutation | The Nephio architecture allows for intermediate Controllers and KRM functions to mutate the intent
Dependency handling | Nephio handles dependencies in a distributed/asynchronous manner so that these dependencies don’t have to be defined or hard-coded apriori.
Day 1, 2 | By changing the intent, Nephio will automatically reconcile the intended state with the actual state.
Infra + workload | Nephio can orchestrate the workload and the underlying infra while understanding dependencies

</div><br /></b>

### Technical Description

<img width="736" alt="OpenTofu" src="https://github.com/opentofu/opentofu/assets/72006175/a9b79754-4082-41f5-823d-b40ab59e01b7">

The diagram describes how Nephio can automate the deployment of infrastructure using OpenTofu under the hood.  We can break the diagram into individual pieces:

Intent: The high level intent declares the user requirement. The intent is purely declarative. In this example, the intent is to create a topology comprising infrastructure which is a bare-metal service at an edge location connected to the application server hosted on a VM in the Azure cloud via Equinix Fabric and Azure ExpressRoute.
Nephio Controllers Reconcile the intents: A Controller initiates a pipeline which is executed by a set of other Nephio Controllers and KRM functions. The Controllers synchronize using Kubernetes status conditions. 
We propose KRM functions that can automate the generation of OpenTofu plans. In this example let us assume that we have functions which can create OpenTofu plans for Equinix Metal, Azure VM, Equinix Fabric and all the other resources required to create this kind of topology including VLANs, Azure ExpressRoute, BGP gateways etc.
Please note that the VLANs, Azure ExpressRoute, and BGP gateways are not specified in the intent by the user; rather these are the resources which are inferred by the Nephio Specializer Controllers. The Specializer Controllers create an inventory plan in order to accomplish the user intent. This plan then becomes input to the KRM functions which know how to generate OpenTofu plans for different providers.
Management staging repo: The name of this repo is just an example, but the purpose of this repo is to host the curated packages which consist of all the OpenTofu plans that are required to create the required infrastructure topology. These packages are version controlled. 
ConfigSync: Reconciles the packages from management staging repo; the packages have three lifecycle stages – proposed, approved, and published. These lifecycle stages are managed by the Nephio Controllers which push packages to these repositories. ConfigSync reconciles the packages that are in published state. 
OpenTofu Executor (Runtime): Executes the OpenTofu plans, and hence realizes the infrastructure resources.
Kubernetes Cluster Bootstrap: Nephio has a Controller which uses cluster API internally for provisioning Kubernetes clusters and bootstrapping the clusters to make them ready for workload orchestration by Nephio. What bootstrapping essentially means is to deploy ConfigSync, at a minimum, to the target cluster and point it to the repo it should reconcile to.

For the active reconciliation between the Intent and the state of the infrastructure, the solution can rely on the OpenTofu State Management. But the Nephio Controllers have to make sure that the Terraform State to resources instance mappings are maintained as per the expectation of Terraform Plans. The following diagram explains how Terraform can manage the drift from desired state to the actual state of the infrastructure. But this state machine might require some management from outside which might require development of some Kubernetes ( Nephio) controllers.

### Rationale and alternatives

Crossplane’ Terraform provider https://github.com/upbound/provider-terraform can run terraform code, but we still will require the automation which can create/curate the terraform plans for terraform KRMs for bulk fanout. The pain points have to be addressed manually.

**Comment by ssharmasandeep** [comment]
Hi @Yantrio,
 The RFC is essentially proposing a solution to automate the creation/manipulation of the terraform plans following the Nephio design principles.  Imagine an end-to-end service deployment which requires infrastructure to be created/managed, and or applications to be deployed on the created infra.
In Nephio the request for service deployment is specified as high-level inent, which is realised with the help of multiple Kubernetes controllers and KRM functions which automatically generate application deployment configuration example a Deployment.yaml for a UPF in 5G core.
For infrastructure automation also if create Kubernetes controllers+KRM function which will generate terraform plans based on the user intent, then we can achieve the automation of infra+application in the same flow all using a uniform API which is Kubernetes. 
Also there is continuous reconciliation, to the intent specified by the user. CI/CD is implicit in this methodology.  As the description above says, managing the terraform plans at scale is key feature of this proposal.

I get your point that this proposal is not enhancing Opentofu itself, rather the proposal is to enable consumers to use Opentofu at scale in a cloud-native way using Kubernetes, following the Nephio architecture. 

The work will be to write Kubernetes controllers+KRM functions which will produce and deploy the terraform plans.
-Sandeep

**Comment by cube2222** [comment]
Thanks for submitting the issue!

> I get your point that this proposal is not enhancing Opentofu itself, rather the proposal is to enable consumers to use Opentofu at scale in a cloud-native way using Kubernetes, following the Nephio architecture.
The work will be to write Kubernetes controllers+KRM functions which will produce and deploy the terraform plans.

I believe this is out of scope for the core OpenTofu project, then, and should instead be done as a separate project building on OpenTofu.
