### ISSUE TITLE
Support passing variables in `tofu test`

### ISSUE THREAD

**Issue by be-aws-architect** [opentofu/opentofu#1091]
### OpenTofu Version

```shell
OpenTofu v1.6.0-rc1
on darwin_arm64
```

### Use Cases

I was testing the difference between the terraform test command and the opentofu test command, in lieu of deciding with which HCL to continue.

I noticed already some functionality like passing variables is not supported yet in OpenTofu. 

Is there some kind of roadmap where one can see when features will be released, or some timeframe on when you expect to match Terraform's future functionality roll-outs?

### Attempted Solutions

-

**Comment by Evi1Pumpkin** [comment]
Hi @be-aws-architect,
The 1.6.0 terraform `test` command and the OpenTofu 1.6.0 `test` command are in 1.6 and should cover the same features.
Thank you for letting us know about this gap; we just recently found it, and as far as we know, it's the only one. We'll make sure to include it in our next 1.6.1 version.
I'll open an issue about it tomorrow (you are also welcome if you have the time).
But generally, we don't aim to match Terraform's features in OpenTofu's future versions. We'll triage issues based on the community's needs. So, if you find something missing in OpenTofu, please open an issue about it, and we'll address it.
We'll soon create a new milestone for future releases in our [milestones section](https://github.com/opentofu/opentofu/milestones), and you'll be able to follow our roadmap there.

**Comment by Evi1Pumpkin** [comment]
Hi,
So apparently, we have an existing issue about it [here](https://github.com/opentofu/opentofu/issues/1045).
@be-aws-architect can you please validate this is the functionality you are missing?

**Comment by be-aws-architect** [comment]
Hi @Evi1Pumpkin, appreciate the quick feedback! That is indeed the exact issue. I will close this issue then. Thank you!
