### ISSUE TITLE
Support idiomatic release artifact formats

### ISSUE THREAD

**Issue by stevehipwell** [opentofu/opentofu#1097]
### OpenTofu Version

```shell
OpenTofu v1.6.0
on windows_amd64
```

### Use Cases

I'd like the `linux` & `darwin` release artifacts to be in `.tar.gz` format instead of `.zip` format as this is the idiomatic pattern.

### Attempted Solutions

N/A

### Proposal

Update the GoReleaser config to only use the `.zip` format for Windows; `.tar.gz` is the default format for both `linux` & `darwin` but this is overridden by the config linked below.

https://github.com/opentofu/opentofu/blob/4ac1af3fbc818b458c71a17ad6b31025ad7cba3f/.goreleaser.yaml#L60

**Comment by Yantrio** [comment]
We discussed this as the core engineer team, and we think that this is valid and we should also ship .tar.gz alongside .zip, as to not break existing processes.

**Comment by namgyalangmo** [comment]
I would like to resolve this.

**Comment by Yantrio** [comment]
Thanks @namgyalangmo , I've assigned you to the issue. Please let us know if you hit any issues.

**Comment by stevehipwell** [comment]
@yantro it might be worth only building the additional _.zip_ file for a set period as deprecated functionality. It makes sense to keep the behaviour for a while, but I can't think of a case where _.zip_ is preferential to a _.tar.gz_ on a non-Windows system.

**Comment by janosdebugs** [comment]
@stevehipwell we discussed this too with the core team when discussing this issue, there's a large amount of tooling that relies on the format being the same. We currently have no plans to deprecate the zip release artifact.
