### ISSUE TITLE
Support shell completion

### ISSUE THREAD

**Issue by chenrui333** [opentofu/opentofu#1098]
Add shell completion for bash, zsh, fish, powershell and etc.

**Comment by cam72cam** [comment]
Hi!  Give the instructions here a try: https://opentofu.org/docs/cli/commands/#shell-tab-completion

**Comment by chenrui333** [comment]
Is there a way to customize the shell completion location, like installing as `opentofu` into `/opt/homebrew/etc/bash_completion.d`?

**Comment by cam72cam** [comment]
Under the hood (and through a few dependencies), it looks like it's hardcoded in the user's home directory: https://github.com/posener/complete/blob/v1/cmd/install/install.go#L143

It uses `complete -C $TOFU_COMMAND` and I'm not sure how to place that in bash_completion.d, even manually.

**Comment by chenrui333** [comment]
yeah, that code ref is helpful, I will have to also learn about how to make it bit configurable :)

**Comment by chenrui333** [comment]
also off top of you head, do you know is there any manpage support for the cli?

**Comment by cam72cam** [comment]
At this point we don't interact with either the man or info systems.  `--help` can get people started and the docs website takes care of the rest: https://opentofu.org/docs/cli

**Comment by chenrui333** [comment]
noted, thanks!

**Comment by cam72cam** [comment]
At this point, I'm going to close this issue as the initial question has been answered.  If you have more specific suggestions / feature requests, feel free to open another issue or request this one to be reopened!

**Comment by chenrui333** [comment]
yeah, sounds good, thanks!
