### ISSUE TITLE
Release support policy

### ISSUE THREAD

**Issue by chenrui333** [opentofu/opentofu#1099]
👋 Congrats on the 1.6 GA release, this issue might be just some placeholder, but useful for later addition into `endoflife-date/endoflife.date` to consume the CLI app lifecycle management.

**Comment by skyzyx** [comment]
Yeah. Understanding the support guidelines for OpenTofu would be a good idea.

By "support", I'm not referring to "it works". By "support", I mean _who is on the hook when something goes wrong?_ Understanding where the lines are will help organizations make intelligent decisions about upgrade paths.

**Comment by Yantrio** [comment]
Hi @chenrui333, This had been decided on by the TSC and you can find information about this in this document: https://github.com/opentofu/opentofu/blob/main/TSC_SUMMARY.md#2024-01-22-async

**Comment by chenrui333** [comment]
@Yantrio thanks, that is helpful.

**Comment by chenrui333** [comment]
is there any way that we can also create a RELEASE.md or any release page from it?

**Comment by SweetGeneral** [comment]
Hi @cam72cam , I am new to OSS scene and would like to contribute here. Would it be possible to assign and guide me on this issue?

**Comment by SweetGeneral** [comment]
Hi @janosdebugs, I have created a PR for the same, Could you please review and let me know if any change is required?
