### ISSUE TITLE
Set up documentation website.

### ISSUE THREAD

**Issue by cube2222** [opentofu/opentofu#11]
- This should involve a cleanup of the website directory to get rid of any kind of "marketing material".
- It might require design + frontend work to change the styling.
- Set it up on some hosting, could even be github actions.

**Comment by eranelbaz** [comment]
@cube2222 @Roma36 @tomasmik Does this issue can be considered as resolved?
we have https://opentofu.org/docs

**Comment by Roma36** [comment]
@eranelbaz this issue was created to handle the initial development activities for the website. So I assume we could close the issue. @damianstasik wdyt?
