### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by digitalghost-dev** [opentofu/opentofu#1100]
### OpenTofu Version

```shell
NA
```

### OpenTofu Configuration Files

```hcl
...tofu config...
```

### Debug Output

NA

### Expected Behavior

This page in the docs has a broken link: https://opentofu.org/docs/language/settings/tf-cloud
The first link: CLI-driven run workflow

### Actual Behavior

404: Page no found

### Steps to Reproduce

NA

**Comment by Evi1Pumpkin** [comment]
Hi @digitalghost-dev,
Thank you for letting us know. I'm fixing it now 🙃
