### ISSUE TITLE
Create integration with hashicorp terraform consul

### ISSUE THREAD

**Issue by Adesoji1** [opentofu/opentofu#1101]
### OpenTofu Version

```shell
Latest version
```

### Use Cases

For managing Elastic container service in AWS 

### Attempted Solutions

No solution attempted yet

### Proposal

Create Opentofu version of terraform consul https://registry.terraform.io/providers/hashicorp/consul/latest/docs

### References

None

**Comment by RLRabinowitz** [comment]
Hey @Adesoji1 ,

OpenTofu supports Consul as a provider. You could use it exactly as you would in Terraform.
Could you please elaborate on the use-case here, and what's missing in OpenTofu for you?
