### ISSUE TITLE
Body

### ISSUE THREAD

**Issue by AmerAlkaki** [opentofu/opentofu#1109]
### Discussed in https://github.com/orgs/opentofu/discussions/1108

<div type='discussions-op-text'>

<sup>Originally posted by **AmerAlkaki** January 12, 2024</sup>
Start  in General </div>

**Comment by janosdebugs** [comment]
Hey @AmerAlkaki I'm not entirely sure what this is supposed to mean. Please edit this issue so we can properly respond to it.
