### ISSUE TITLE
Automate backports with a bot

### ISSUE THREAD

**Issue by cube2222** [opentofu/opentofu#1112]
Right now the backporting process requires a bunch of manual labour.

In practice, we put the backporting targets in the pull request description, so we should be able to automate this process.

**Comment by janosdebugs** [comment]
@kishaningithub not in this case because we are only backporting PRs that have been added to OpenTofu in the first place. We are not backporting Terraform PRs this way.

**Comment by ilmax** [comment]
Asp.net core also has an interesting action for this, I think it's base on a comment on the PR, like back port to {version} it may be an alternative to labels

**Comment by siddharthasonker95** [comment]
> The easiest way to tackle this would be [a GitHub Action](https://github.com/tibdex/backport) that relies on a label on the PR `backport v1.6` for example.
> 
> However, if we'd like to determine the version from the description's target, we'd have to do some work ourselves + rely on a description template that might change (or people might ignore).
> 
> Personally I'm leaning more towards relying on labels for backporting. WDYT @cube2222 @janosdebugs ?

As per the mentioned [GitHub Action](https://github.com/tibdex/backport), it has a [bug](https://github.com/tibdex/backport/issues/91) which I was also able to reproduce on my side. Though I liked the approach, and I will figure out more solutions based on a custom GitHub Action workflow for backporting.
