### ISSUE TITLE
Iterator over provider configurations [`for_each` for the `provider` block]

### ISSUE THREAD

**Issue by Sysa** [opentofu/opentofu#1113]
### OpenTofu Version

```shell
OpenTofu v1.6.0
on linux_amd64
+ provider registry.opentofu.org/gavinbunney/kubectl v1.14.0
```

### Use Cases

Example of use case: Imagine you have multiple kubernetes clusters and you want to submit an infrastructure change which will be reflected over all your kubernetes clusters and environments. But, currently it is not possible to do a kubernetes or kubectl provider config for multiple clusters and provide different Kube configs to the terraform due to limitations of for_each keyword.

Example to reproduce:

catalogue tree:
```
.
├── main.tf
└── providers.tf
```

main.tf:
```
provider "kubectl" {
    for_each = toset(["dev", "pd"])
  config_path = "~/.kube/config" # it should be gathered from the keyvault and be different for each environment
}
```
providers.tf
```
terraform {
  required_providers {
    kubectl = {
      source  = "gavinbunney/kubectl"
      version = ">= 1.7.0"
    }
  }
}
```

### Attempted Solutions

See Use case example description for more details.

### Proposal

It would be really nice and time saver if some kind of iterator over provider configurations will be available

### References

- might be related: #1033

**Comment by cube2222** [comment]
Hey, thanks for creating the issue @Sysa!

I think this is mainly related to https://github.com/opentofu/opentofu/issues/1042. However, I know it won't be in the initial version at least. The way for_each with e.g. modules works right now it doesn't actually create a copy of the provider for each "each", and changing this would require some non-trivial changes. Not saying no, though! Just giving some background on why this isn't trivial.

This is definitely a use-case we want to tackle eventually.

**Comment by Sysa** [comment]
Thank you, @Yantrio
