### ISSUE TITLE
Broken link in the migration guide

### ISSUE THREAD

**Issue by bencurio** [opentofu/opentofu#1116]
# Details

I found a broken link in the migration guide:

https://opentofu.org/docs/intro/migration

Page edit:

https://github.com/opentofu/opentofu/edit/main/website/docs/intro/migration.mdx

Edit: Maybe a routing error? Sometimes it works, sometimes not.

# Reproducation

1. Click on the `OpenTofu` logo.
2. Click on the `Try it out` button.
3. Click on `Migrate to OpenTofu`.
4. Click on the link in step 2.

# Screenshots

![image](https://github.com/opentofu/opentofu/assets/7604637/f7acea1f-423e-4ecd-b669-891709cbfe12)

![image](https://github.com/opentofu/opentofu/assets/7604637/bb966b4c-49e0-43af-bbc2-50dd3e10f9d6)

**Comment by Evi1Pumpkin** [comment]
Hi @bencurio,
Thanks for letting us know!
I believe we already [fixed this here](https://github.com/opentofu/opentofu/pull/1093/files). I tested it now and it works.

**Comment by Evi1Pumpkin** [comment]
I'm sorry. I indeed didn't see this part
> Maybe a routing error? Sometimes it works, sometimes not.
Sounds like we need to get to the bottom of it.

**Comment by bencurio** [comment]
Yes, this works because if you put the slash at the end, the server actually responds with `index.html` and may bypasses the routing provided by JavaScript.
 
- `https://opentofu.org/docs/intro/migration/` means `https://opentofu.org/docs/intro/migration/index.html`

The JavaScript routing still redirects you to the old URL for some reason in static version (with cache disabled).

However, in developer mode (`npm run start`) there is no such error.

I'll try to figure out if it's a server-side problem, and upload the static version to my own server to see if the problem occurs there.

https://github.com/opentofu/opentofu/assets/7604637/f7738a81-5c6c-49f2-a135-d3e7c24b7338

**Comment by bencurio** [comment]
Hmm... that's weird 🤔. The problem could not be reproduced on my own server.

- https://opentofu-preview-ffa47336.nf.hu/ (indexing disabled in `robots.txt`)

The server uses `Apache 2.4.58`.

Built with: `npm run build`

**Comment by bencurio** [comment]
Not sure if it is related, but I found this in the Docusaurus docs:

> GitHub Pages adds a trailing slash to Docusaurus URLs by default. It is recommended to set a `trailingSlash` config (`true` or `false`, not `undefined`).

This seems to be missing from the OpenTofu web configuration: 
 
- https://github.com/opentofu/opentofu.org/blob/main/docusaurus.config.ts

Docs: https://docusaurus.io/docs/deployment#docusaurusconfigjs-settings

**Comment by bencurio** [comment]
Okaaaay! Got it.

If I set the `trailingSlash` to `true` on a dev machine, the issue can be reproduced. If I set it to `false`, then it works.

Try setting it to `false` on the production site, and I think the issue will be resolved.

**Comment by cam72cam** [comment]
As a note, the production deployment adds a '/' at the end of all of the bare paths.  The setting now defaults to true to match this.
