### ISSUE TITLE
Trivial: Old terraform logo is present in codebase

### ISSUE THREAD

**Issue by IgnorantSapient** [opentofu/opentofu#1121]
### OpenTofu Version

```shell
Not applicable.

Git commit hash fcd241c on the main branch
```

### OpenTofu Configuration Files

NA

### Debug Output

NA

### Expected Behavior

Have the new Opentofu logo in the codebase

### Actual Behavior

Location: `/internal/lang/funcs/testdata/icon.png` 

The old terraform icon is present.

### Steps to Reproduce

Open file located at after cloning opentofu repo `/internal/lang/funcs/testdata/icon.png`

### Additional Context

NA

### References

NA

**Comment by janosdebugs** [comment]
Hey @IgnorantSapient thank you, if you're up for a PR please remove it.

**Comment by IgnorantSapient** [comment]
On it 🖖
