### ISSUE TITLE
Improve the consistency of `state` subcommands

### ISSUE THREAD

**Issue by SkypLabs** [opentofu/opentofu#1136]
### OpenTofu Version

```shell
OpenTofu v1.6.0
on linux_amd64
```

### Use Cases

Below is the list of `state` subcommands:

```raw
Subcommands:
    list                List resources in the state
    mv                  Move an item in the state
    pull                Pull current state and output to stdout
    push                Update remote state from a local state file
    replace-provider    Replace provider in the state
    rm                  Remove instances from the state
    show                Show a resource in the state
```

I think there are some inconsistencies in terms of subcommand names since `list` is a full word whereas `mv` is an abbreviation. Same story for `rm`.

Being used to UNIX commands, I'm tempted to write `terraform state ls` but then, when I realise it is in fact `list`, my reflex is to write `terraform state move` afterwards instead of `terraform state mv` for example.

It is not a big deal of course but I think aliases would be very welcome to improve the overall consistency of these subcommands.

### Attempted Solutions

N/A

### Proposal

Adding the following aliases to the `state` subcommands:

* `ls` to `list`
* `move` to `mv`
* `remove` to `rm`

### References

Issue originally created for Terraform 4 years ago: https://github.com/hashicorp/terraform/issues/20998

**Comment by janosdebugs** [comment]
Hey @SkypLabs thank you for this issue! It seems you hit a nerve, everyone we asked said that this is a pain.

**Comment by HubbardHarvey3** [comment]
I would like to tackle this issue.  This will be my first open source contribution, but I will reach out on the Slack channel with any questions.

**Comment by janosdebugs** [comment]
Hey @HubbardHarvey3 thank you very much, I've assigned you.

**Comment by lettucemode** [comment]
I'd like to tackle this if that's alright.

Is it worth renaming the rest of the file/function names from `mv` to `move`, for example?

There's a license statement at the top of the files in `internal/command`. If I modify those files, does the statement need to be modified or removed?

**Comment by janosdebugs** [comment]
Hey @lettucemode thank you very much, I've assigned you. The current issue is only about adding command aliases, a renaming should not be necessary as we are not making the new names the primary versions. Regarding licensing, that's a separate issue #454, for now let's keep the license headers as they are.
