### ISSUE TITLE
Add VS Code tour based on architecture doc

### ISSUE THREAD

**Issue by jjshanks** [opentofu/opentofu#1137]
### OpenTofu Version

```shell
n/a
```

### Use Cases

The CodeTour plugin is meant to help onboard people to a code base by guiding them through the codebase directly in the IDE.

### Attempted Solutions

Not yet.

### Proposal

Translate https://github.com/opentofu/opentofu/blob/main/docs/architecture.md to be a VS Code tour using https://marketplace.visualstudio.com/items?itemName=vsls-contrib.codetour

### References

Inspired by a slack message in general about learning opentofu internals.

**Comment by janosdebugs** [comment]
Hey @jjshanks thank you for the suggestion. This sounds like something that will need more or less continuous maintenance. I also wonder if something that amounts to an interactive tutorial is really all that helpful for a codebase of 300k+ lines of code. I don't think the OpenTofu codebase is something someone can easily pick up by going through a tour in a few minutes, it will require a bit of reading.

**Comment by jjshanks** [comment]
I did have similar maintenance concerns but the architecture doc hasn't been updated for 3 years (outside of recent fork changes for naming) so wasn't to worried. The goal wouldn't be to cover everything but used as an introduction to the codebase to help new contributors understand how things fit together so they have a starting point/foundation.

I thought it might help lower the barrier to entry but there are existing docs so not necessary.

**Comment by Yantrio** [comment]
The core team has decided that we should close this in the meantime as we think it could be a lot of work to maintain and there isn't a significant community requirement behind this.

We'll be happy to re-visit this if the issue pops up again or more people request this. 

Community members: If you are in support of this and want to show us, please add a thumbs up reaction to the issue

**Comment by janosdebugs** [comment]
Maybe a little bit of an addition. It's not quite a walkthrough / tour as envisioned, but we started adding README.md files to the new encryption feature, see [here](https://github.com/opentofu/opentofu/tree/main/internal/encryption/keyprovider) as an example. This is easier to maintain and hopefully people will actually read it when they stumble upon the directory.
