### ISSUE TITLE
When Migrating from Terraform, `tofu show` fails to load correct schema from opentofu registry providers

### ISSUE THREAD

**Issue by Yantrio** [opentofu/opentofu#1139]
### OpenTofu Version

```shell
1.6.0
```

### OpenTofu Configuration Files

```hcl
terraform {
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "2.4.1"
    }
  }
}

provider "local" {
  # Configuration options
}

resource "local_file" "foo" {
  content  = "foo!"
  filename = "${path.module}/foo.bar"
}

```

### Debug Output

```
tofu show
╷
│ Error: Failed to load plugin schemas
│ 
│ Error while loading schemas for plugin components: Failed to obtain provider schema: Could not load the schema for provider
│ registry.terraform.io/hashicorp/local: failed to instantiate provider "registry.terraform.io/hashicorp/local" to obtain schema: unavailable provider
│ "registry.terraform.io/hashicorp/local"..
```

### Expected Behavior

Should correctly show the state file

### Actual Behavior

Instead it errors

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. `tofu init`
4. `tofu show`

### Additional Context

It looks like the provider schema listed in the statefile is hashicorp's registry and not the opentofu registry.

This is due to the fact that we decided to not re-write the statefile as part of the migration path into OpenTofu from Terraform.

**Comment by Yantrio** [comment]
Please note that any changes to the statefile made by opentofu fixes this.

For example, if you successfully run `tofu apply` and then `tofu show` it will work.

**Comment by cam72cam** [comment]
Do we want to migrate the state but not persist it for `show` ?

**Comment by cube2222** [comment]
@cam72cam the approach I'm taking is similar to plan and init. tofumigrate in memory.

**Comment by jcollie** [comment]
Does the fix for this not work if I'm using the PostgreSQL backend?

**Comment by cam72cam** [comment]
@jcollie this should function identically on all backends

**Comment by jcollie** [comment]
> @jcollie this should function identically on all backends

Fixed my problem, I was explicitly listing the full URL (`source  = "registry.terraform.io/hashicorp/local"`). When I removed the `registry.terraform.io` hostname it started working.
