### ISSUE TITLE
[Feature Request] Add "deleted_by" meta-argument to resource lifecycle

### ISSUE THREAD

**Issue by cybershoe** [opentofu/opentofu#1147]
### OpenTofu Version

```shell
OpenTofu v1.6.0-alpha3
on linux_amd64
```

### Use Cases

This is copied from https://github.com/hashicorp/terraform/issues/34530

With some providers, deleting a resource also deletes subordinate objects associated with that resource (e.g: deleting a resource group deletes its contents, deleting an NGINXaaS for Azure deployment deletes its configurations and certificates, etc.). Where that behaviour is expected, a user should be able to specify in a resource's lifecycle block that deleting a related resource will also delete the subordinate resource; in that case `tofu destroy` should not explicitly delete the subordinate resource if it is already planning on deleting the parent resource.

There are two main benefits to this approach:
1) The destroy process is simplified. The resource provider presumably has a better understanding of the best order of operations to delete its subordinate resources. So long as the user is confident that the provider will properly perform the deletion, the implementation details should be left to the provider.

2) For providers with a less-than-perfect API success rate, this reduces the number of API calls, and therefore the chances of a failure preventing the destroy operation from succeeding.

### Attempted Solutions

Currently, to prevent removal of a resource, I must delete it from the OpenTofu state with `tofu state rm`. This works, but it is an extra imperative step that should be handled by OpenTofu's order of operations planning.

### Proposal

Add a "deleted_by" meta-parameter to the lifecycle block. The value of this parameter is another resource that, when deleted, will also destroy the resource in question. When `tofu destroy` is run, OpenTofu will not explicitly destroy the subordinate resource if it is already planning to destroy the parent resource.

This should be an explicit meta-parameter. OpenTofu may not be able to know in all cases whether a subordinate resource is deleted by a particular parent resource, and in any event this behaviour may not even be desired, so it should be left to the discretion of the user.

### References

Copied from:
- [[Feature Request] Add "deleted_by" meta-argument to resource lifecycle hashicorp/terraform#34530](https://github.com/hashicorp/terraform/issues/34530)

Implements a use case from:
- [feature request: inverse targeting / exclude hashicorp/terraform#2253](https://github.com/hashicorp/terraform/issues/2253) 

Relates to:
- [prevent_destroy should let you succeed hashicorp/terraform#3874](https://github.com/hashicorp/terraform/issues/3874)
- [Exclude resources from the destroy process hashicorp/terraform#23547](https://github.com/hashicorp/terraform/issues/23547)

**Comment by janosdebugs** [comment]
Hi @cybershoe thank you for this issue. I absolutely understand the frustration of waiting for API calls to do their job and cutting down on unnecessary ones is definitely something we should aim for. However, I think that the proposed solution could be improved. (Speaking for myself and not on behalf of the core team for the moment, please don't take this as a final decision.)

If I'm understanding this correctly, this proposal is suggesting that OpenTofu, when this meta parameter is present, should skip deleting the subordinate resource and just delete the parent resource. Assuming that is the case, this seems incredibly risky to me. Providers are allowed to have internal states and this internal state is then not correctly updated and may lead to severe and hard to trace bugs. A provider has the rightful expectation of being the sole arbiter when something is created or deleted, and this would break that expectation.

I feel like this could also lead to a "footgun" situation where we are giving users a tool that is easily misunderstood and could lead to leftover resources that incur continuous costs until discovered.

The right solution here would probably be to allow the provider to declare that it's ok to do this and that a certain field is intended to provide a dependency so OpenTofu can safely skip the deletion between the two resources. However, this would require provider authors to use an OpenTofu-specific SDK/framework, which we at the moment don't have and the burden of shipping separate binaries shouldn't be put on provider authors. At any rate, this would require an RFC with the corner cases and implementation covered.

**Comment by cybershoe** [comment]
I agree that we need to be cautious with how this would be implemented, if it were implemented at all. I think there is an argument to be made that this is users already have this "footgun" in the form of the state rm command, but that also carries an inherent connotation that the user is violating the idea of an internally consistent state. My personal opinion is that users should have the option of explicitly declaring that they know how the provider behaves and want this behaviour anyways, but I also understand that it opens a bigger can of worms.

Regardless, I also agree that extending the provider framework is the "right" way to accomplish this long-term. I have the same issue open with the hashicorp project; hopefully there can be a mutually-compatible implementation of this at some point without breaking portability unnecessarily.

**Comment by Yantrio** [comment]
We believe this may be resolved by https://github.com/opentofu/opentofu/issues/1032 in the short term, and in the long term we can discuss options.

Please let me know if this does not cover all of the requirements here and we'll be happy to re-open.
