### ISSUE TITLE
[Feature] Support of the TerraForm CDK functionality inside the OpenTofu eco system

### ISSUE THREAD

**Issue by ZPascal** [opentofu/opentofu#1150]
### Discussed in https://github.com/orgs/opentofu/discussions/1149

<div type='discussions-op-text'>

<sup>Originally posted by **ZPascal** January 19, 2024</sup>
Hello Community,

is there anything planned to also support an opentofo-cdk like the [TF CDK](https://github.com/hashicorp/terraform-cdk) to use programming languages [natively](https://developer.hashicorp.com/terraform/tutorials/cdktf/cdktf-build?in=terraform%2Fcdktf&variants=cdk-language%3Apython) to manage resources?  </div>

**Comment by janosdebugs** [comment]
Hi @ZPascal you can use cdktf by setting the `TERRAFORM_BINARY_NAME` environment variable to `tofu`, see [this issue](https://github.com/opentofu/opentofu/issues/601). I'll close this issue, but we'll reopen it if it doesn't work.

**Comment by ZPascal** [comment]
Hi @janosdebugs, thank you for the quick response. Sounds great, I'll give it a try.

**Comment by KeeganJustis** [comment]
There will be a bigger delta between Terraform and OpenTufu over time. Would it make sense to fork Terraform CDK and make an Open Tufu CDK instead to support the relevant features ?

**Comment by commiterate** [comment]
CDKTF has been [deprecated](https://github.com/hashicorp/terraform-cdk/commit/a0c56138e2b4c7b6c128bd7ba08a8e317df852af).

**Comment by so0k** [comment]
I set up a fork here
https://github.com/terraconstructs/terraform-cdk

will update with release soon

**Comment by so0k** [comment]
> I set up a fork here https://github.com/terraconstructs/terraform-cdk
> 
> will update with release soon

for future visitors - community effort is gathering at https://cdk.dev -> `#terraform-cdk` channel

**Comment by so0k** [comment]
future visitors may note https://cdktn.io has monthly releases fixing CDKTF CVEs and is actively being updated
