### ISSUE TITLE
Add a command option alias `-no-colour`

### ISSUE THREAD

**Issue by TFCresset** [opentofu/opentofu#1151]
### OpenTofu Version

```shell
OpenTofu v1.6.0
on darwin_arm64
+ provider registry.opentofu.org/hashicorp/aws v5.33.0
```

### Use Cases

Colour is the *correct* spelling, PLEASE, with a cherry on top, add this as a usable option! I've worked with Terraform for almost a decade now, and I STILL (!!) gets triggered by this!! :D :D

### Attempted Solutions

```
bash-3.2$ tofu plan -no-colour
╷
│ Error: Failed to parse command-line flags
│
│ flag provided but not defined: -no-colour
```

### Proposal

Checking if `-no-color` or `-no-colour` is used on the command line shouldn't (CAN'T!) be that hard.. ?

**Comment by Yantrio** [comment]
As an Englishman and a dev, this is an issue we commonly hit. However I think we have to just accept that we live in a world where the spelling `color` is used. 

There are lots of other cases of i18n and l10n that we could solve with different spellings but I believe it would add a lot of overhead to the support load.

Overall, As much as I hate saying it, I think we should grit our teeth and get used to spelling it as `color`, and using a z in `finalize` etc.

I don't think that OpenTofu should add the alias here. I'm sorry.

**Comment by TFCresset** [comment]
I do understand the reasoning behind it when it comes to output etc, but adding this as a command line option can't be _that_ much overhead, surely?

**Comment by janosdebugs** [comment]
Hi @TFCresset it would be a minimal amount of code, but the logical thing to do then would be to examine all our spellings and provide adequate aliases for all command options and language elements. This opens the door for further requests for localization (e.g. why wouldn't we start providing Spanish aliases then, which more people use than British English).

**Comment by TFCresset** [comment]
That is a fallacy, a logical error.

It is well established that command options are _only_ in English. In ALL softwares. There _is_ no localisation of command options.
