### ISSUE TITLE
Support for mocking providers in opentofu test

### ISSUE THREAD

**Issue by tv-sister** [opentofu/opentofu#1155]
### OpenTofu Version

```shell
OpenTofu v1.6.0
```

### Use Cases

Test OpenTofu code offline.

### Attempted Solutions

Using fake credentials in your provider in the testfile does not always work, the newly implemented _mock_ provider by Terraform has a broader usecase, as it allows faking data sources etc.

https://developer.hashicorp.com/terraform/language/tests/mocking

For example, using fake credentials and trying to retrieve an AMI with

```
data "aws_ami" "ubuntu" {
  most_recent = true

  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }

  owners = ["099720109477"] # Canonical
}
```

Returns the following error

```
reading EC2 AMIs: AuthFailure: AWS was not able to validate the provided access credentials
```

### Proposal

Add support for mocking providers, resources, and data sources.

**Comment by cube2222** [comment]
Thanks for submitting the issue @tv-sister!

We've agreed that this makes sense for compatibility purposes, and the core team will pick it up with the goal being a release of this alongside 1.7.0.

**Comment by RLRabinowitz** [comment]
Also - keep this possible crash in mind - https://github.com/hashicorp/terraform/issues/34601
