### ISSUE TITLE
terraform.workspace should be tofu.workspace

### ISSUE THREAD

**Issue by paul-civitas** [opentofu/opentofu#1156]
### OpenTofu Version

```shell
OpenTofu v1.6.0
on darwin_arm64
+ provider registry.opentofu.org/hashicorp/aws v5.33.0
```

### OpenTofu Configuration Files

```hcl
locals {
  workspace = local.workspaces[tofu.workspace]
  workspaces = {
    prod = {
       ...
    }
  }
}
```

Versus

```hcl
locals {
  workspace = local.workspaces[terraform.workspace]
  workspaces = {
    prod = {
       ...
    }
  }
}
```

### Debug Output

Not needed

### Expected Behavior

"tofu.workspace" version works, due to the power of trademark law.

### Actual Behavior

A managed resource "tofu" "workspace" has not been declared in the root module.

It's required to use `terraform.workspace` instead.

### Steps to Reproduce

Have code that uses `terraform.workspace` interpolation thingy.

### Additional Context

tofu fmt should replace any instnaces of terraform.workspace w/ opentofu compatible interpolation sequences.

**Comment by Yantrio** [comment]
We're happy to accept community contributions on this one. It is valid, however when we discussed it when triaging this issue, we did think that when someone runs `tofu fmt` that it should not favor either option. It should happily accept both variations.

**Comment by yindia** [comment]
@Yantrio, could you kindly assign this issue to me? Additionally, I'd appreciate some more details about the changes required.

**Comment by janosdebugs** [comment]
Hey @yindia thank you for volunteering, I've assigned this issue to you. Please let us know your rough timeline for implementing this so we can un-assign in case we don't hear back from you.

As far as the implementation details are concerned, the acceptance criteria would be that when referencing `${tofu.workspace}`, it should resolve the same way as `${terraform.workspace}` and output the same value. However, as indicated above, `tofu fmt` should not replace one with the other.

**Comment by yindia** [comment]
@janosdebugs Could you guide me to the code responsible for parsing logic?

**Comment by janosdebugs** [comment]
Hi @yindia unfortunately, I do not have any specific advice to give on this issue. If you are unable to find the code paths that need to be implemented, please let us know so we can free up the issue for another contributor.

**Comment by yindia** [comment]
Yeah sure

**Comment by janosdebugs** [comment]
@yindia have you made any progress on this issue? If not, would you mind @Ericwww trying to solve it?

**Comment by yindia** [comment]
I haven't started working on this, You can assign this to @Ericwww

**Comment by Ericwww** [comment]
Hi @janosdebugs 

The PR is ready, and you can assign this issue to me. 

Thank you.

😃 😃 😃

**Comment by janosdebugs** [comment]
Thank you for volunteering @Ericwww , I've assigned you. Please read [the "I've been assigned an issue, now what?" section of the contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md#ive-been-assigned-an-issue-now-what) before you begin working.
