### ISSUE TITLE
[State Encryption] Methods (partial)

### ISSUE THREAD

**Issue by janosdebugs** [opentofu/opentofu#1170]
**Parent:** #1030
**Depends on:** #1169
**Blueprint PR:** #1132

## Acceptance criteria

1. Implement an encryption method that functions only works with state files and falls back to full encryption for plan files.
2. The encryption should only encrypt sensitive values, but leave all other data unencrypted.

**Comment by cube2222** [comment]
To clarify for future readers: This sub-feature is **not** planned for 1.7.
