### ISSUE TITLE
[State Encryption] Key providers (OpenBAO)

### ISSUE THREAD

**Issue by janosdebugs** [opentofu/opentofu#1174]
**Parent:** #1030
**Depends on:** #1166
**Blueprint PR:** #1132

## Acceptance criteria

1. Implement a key provider that loads an encryption key from OpenBAO.
2. Implement a test integration that spins up an OpenBAO instance for testing purposes on demand.

**Comment by cipherboy** [comment]
@ollevche do you have a design doc for this? Are you planning on using Transit and offloading encryption? Or are you using k/v and fetching the key locally? IMO the former gives better security properties.

**Comment by cipherboy** [comment]
@ollevche That's a good use for data keys! Thank you!

**Comment by ollevche** [comment]
Closing since we implemented it in https://github.com/opentofu/opentofu/pull/1436
