### ISSUE TITLE
Duplicate provider config required for e.g. hashicorp/aws and opentofu/aws

### ISSUE THREAD

**Issue by wiegandf** [opentofu/opentofu#1189]
### OpenTofu Version

```shell
OpenTofu v1.6.1
on darwin_arm64
+ provider registry.opentofu.org/hashicorp/aws v5.33.0
+ provider registry.opentofu.org/opentofu/aws v5.33.0
```

### OpenTofu Configuration Files

```hcl
terraform {
  required_providers {
    aws = {
      source  = "opentofu/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  assume_role {
    role_arn = "arn:aws:iam::xxx:role/admin"
  }
}

resource "aws_s3_bucket" "this" {
  bucket = "test-bucket-otb"
}

module "this" {
  source = "./modules/my-module"
}

### ./modules/my-module/main.tf

terraform {
  required_version = ">= 1.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

resource "aws_s3_bucket" "this" {
  bucket = "test-bucket-2-otb"
}
```

### Debug Output

n/a

### Expected Behavior

Since OpenTofu should be a drop-in replacement, both `hashicorp/aws` and `opentofu/aws` should be able to use the same provider config. A lot of open-source modules are referencing the hashicorp aws provider and thus, it would always require to maintain duplicate provider config information, so that it works.

```hcl
aws-vault exec aad -- tofu import module.this.aws_s3_bucket.this test-bucket-2-otb
module.this.aws_s3_bucket.this: Importing from ID "test-bucket-2-otb"...
module.this.aws_s3_bucket.this: Import prepared!
  Prepared aws_s3_bucket for import
module.this.aws_s3_bucket.this: Refreshing state... [id=test-bucket-2-otb]

Import successful!

The resources that were imported are shown above. These resources are now in
your OpenTofu state and will henceforth be managed by OpenTofu.
```hcl

### Actual Behavior

```hcl
aws-vault exec aad -- tofu import module.this.aws_s3_bucket.this test-bucket-2-otb
module.this.aws_s3_bucket.this: Importing from ID "test-bucket-2-otb"...
module.this.aws_s3_bucket.this: Import prepared!
  Prepared aws_s3_bucket for import
module.this.aws_s3_bucket.this: Refreshing state... [id=test-bucket-2-otb]
╷
│ Error: reading S3 Bucket (test-bucket-2-otb): operation error S3: HeadBucket, https response error StatusCode: 403, RequestID: xyz, HostID: xyz, api error Forbidden: Forbidden
```

### Steps to Reproduce

You have to trigger tofu to check the resource, so that the provider config (assume-role config) is required to be used. E.g. you can use tofu import:
`aws-vault exec aad -- tofu import module.this.aws_s3_bucket.this test-bucket-2-otb`

### Additional Context

aws-vault is used to export the AWS session token for the root account. With that a role in a different AWS account is assumed.

This works when adding a provider config for both providers `hashicorp/aws` and `opentofu/aws`. E.g.: 
```hcl
# main.tf
terraform {
  required_providers {
    opentofuaws = {
      source  = "opentofu/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  assume_role {
    role_arn = "arn:aws:iam::xxx:role/admin"
  }
}

provider "opentofuaws" {
  assume_role {
    role_arn = "arn:aws:iam::xxx:role/admin"
  }
}

# ./modules/my-module/main.tf
terraform {
  required_version = ">= 1.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}
```

**Comment by cube2222** [comment]
Hey, thanks for creating the issue! There is generally no particular reason to use `opentofu/aws` right now.

We intentionally **didn't** change the default namespace to opentofu actually, to avoid people running into the behaviour above by accident.

Using `hashicorp/aws` is completely fine in your configs, and I think we should do a better job of emphasizing that in the docs.

**Comment by cam72cam** [comment]
Double check your `tofu init`.  There should be a warning about this exact case :)

**Comment by Yantrio** [comment]
I'm closing as we think that the warning from `tofu init` should cover an explanation here about steps forward.
