### ISSUE TITLE
Consolidating home directory detection in OpenTofu

### ISSUE THREAD

**Issue by mikelolasagasti** [opentofu/opentofu#1196]
### Summary

Multiple ways to work with $home and other config dirs without a clear preferred.

### Problem Statement

There are two distinct approaches to detecting $home and other user directories.

1. The first approach involves the `homeDir()` function defined in `internal/command/cliconfig/config_unix.go` and `internal/command/cliconfig/config_windows.go`, utilized by `configDir()` and `cliconfig.ConfigDir()`.
2. The second approach relies on the `github.com/mitchellh/go-homedir` library

Related to this there is an ongoing PR #1145 for implementing XDG dirs that relies and extends the first approach.

### User-facing description

Current detection of home and config dirs require some manual tricks that could be fixed by consolidating in a new approach that would allow easier code and access to XDG specification.

### Technical Description

I propose adopting the `https://github.com/adrg/xdg` library to handle home and different XDG directory detection. 

This library provides robust support for Linux, MacOS, Windows, and other platforms. 

### Rationale and alternatives

Consolidating both approaches into one would simplify the codebase and offer additional benefits, especially for detecting XDG dirs.

This RFC would extend #303

### Downsides

One little caveat would be that if the usage of `github.com/mitchellh/go-homedir` is dropped, there is a `Expand()` function that is being used actually that has no replacement, but could be fixed by minimal portion of its code directly from [source](https://github.com/mitchellh/go-homedir/blob/main/homedir.go#L58-L77).

### Related Issues

#303

**Comment by janosdebugs** [comment]
Hey @mikelolasagasti if I'm reading this correctly this sounds to be linked to the discussion in #303, possibly a duplicate?

**Comment by mikelolasagasti** [comment]
@janosdebugs was not sure so I opted to create a new issue. I can understand to see this as a dupe, but also covers other things.

@cam72cam is it closed as "not planned" because it is considered a dupe or because it doesn't make sense to adopt a new library and consolidate the code for path detection?

**Comment by janosdebugs** [comment]
Hey @mikelolasagasti thank you for the update. As the XDG part is already in the works, could you elaborate on what is not being covered in that issue? (Also, feel free to reopen issues if they are not addressed adequately.)

**Comment by mikelolasagasti** [comment]
The approach in #303 is to add XDG support based in one of the two options Opentofu has to detect $home dirs. This is a great feature to add and having backwards compatibility makes the PR even better. Nothing to complain about the goal.

But Opentofu having two options to detect $home dirs, one based on custom code and the other based on `github.com/mitchellh/go-homedir` doesn't seem optimum.

- `github.com/mitchellh/go-homedir` is a library just to detect $home dirs, doesn't have any XDG logic on top.
- Opentofu has custom code in [internal/command/cliconfig/config_unix.go](https://github.com/opentofu/opentofu/blob/main/internal/command/cliconfig/config_unix.go#L37-L59) to detect `$home` in Linux. The PR in #303 extends this code to add cheks for XDG paths.
- The code in [internal/command/cliconfig/config_windows.go](https://github.com/opentofu/opentofu/blob/main/internal/command/cliconfig/config_windows.go#L43-L53) to detect `$home` in Windows enviroments is using deprectated functions:

~~~
Deprecated. Gets the path of a folder identified by a CSIDL value.
Note  As of Windows Vista, this function is merely a wrapper for SHGetKnownFolderPath. The CSIDL value is translated to its associated KNOWNFOLDERID and then SHGetKnownFolderPath is called. New applications should use the known folder system rather than the older CSIDL system, which is supported only for backward compatibility.
~~~

The proposal is to consolidate codepaths using `https://github.com/adrg/xdg`,  reduce the number of custom code in Opentofu and drop `github.com/mitchellh/go-homedir`. This can can be done on top of #303.

**Comment by janosdebugs** [comment]
@mikelolasagasti thank you for the explanation. I think this discussion needs to happen mainly on #303 and the linked PR #1200 since there's already a lot of info on how to best preserve backwards compatibility. Not opposing reopening this issue, but could you please raise concerns over there so all participants are aware?
