### ISSUE TITLE
Problem referencing output from test run in local variables block (tofu test)

### ISSUE THREAD

**Issue by crayfishx** [opentofu/opentofu#1212]
### OpenTofu Version

```shell
OpenTofu v1.6.1
on darwin_arm64
+ provider registry.opentofu.org/hashicorp/aws v5.34.0
+ provider registry.opentofu.org/hashicorp/http v3.4.0
```

### OpenTofu Configuration Files

Extract from  https://github.com/crayfishx/tofu-test-demo/blob/main/tests/website.tftest.hcl

```hcl
run "deploy_html" {
  command = apply
  
  assert {
    condition = aws_s3_object.index.etag == filemd5("./site/index.html")
    error_message = "index.html MD5 hash does not match source"
  }
}

run "resolve_endpoint" {
  command = plan

  module {
    source = "./tests/e2e"
  }

  variables {
    endpoint_url = run.deploy_html.endpoint_url
  }

  assert {
    condition = data.http.request.status_code == 200
    error_message = "HTTP code ${data.http.request.status_code} returned from endpoint"
  }

}
```

### Debug Output

```
│ Error: Variables not allowed
│ 
│   on tests/website.tftest.hcl line 52, in run "resolve_endpoint":
│   52:     endpoint_url = run.deploy_html.endpoint_url
│ 
│ Variables may not be used here.
╵
```

### Expected Behavior

The variable should be assigned with the value of the endpoint_url output generated in the `deploy_html` run

### Actual Behavior

It seems that when trying to reference the output of the apply run deploy_html OpenTofu doesn't want to use a variable to assign it and gives me the above error that I cannot interpolate a variable here.

### Steps to Reproduce

1. `tofu init`
2. `tofu test`

### Additional Context

I'm trying to get this use case working based on existing tutorials I've seen - my understanding is that the module output endpoint_url should be able to be resolved from another run block as `run.deploy_html.endpoint_url`  - I understand this feature should be compatible with the test feature in Terraform, but I don't get this error when running under Terraform.

The repo used for this example is at https://github.com/crayfishx/tofu-test-demo

The offending block is: https://github.com/crayfishx/tofu-test-demo/blob/main/tests/website.tftest.hcl#L51-L53

**Comment by janosdebugs** [comment]
Hey @crayfishx thanks for this issue, it will be hopefully fixed in 1.6.2.

**Comment by crayfishx** [comment]
I've been working to reproduce this problem in the most minimalistic way to highlight the issue.  The repo referenced earlier is more "real world" but I've set up a completely skeleton use case here that shows how to reproduce this, and it's a bit strange.....

https://github.com/crayfishx/opentofu-issue-1212

Running `tofu init && tofu test` against this repo works....

```
craig@Craigs-MacBook-Pro-2 tofu-1212 % tofu test                
tests/test.tftest.hcl... pass
  run "first"... pass
  run "second"... pass
```

However, when I include my module by uncommenting this code block:  https://github.com/crayfishx/opentofu-issue-1212/blob/main/tests/test.tftest.hcl#L8-L13  the variable in the second test doesn't get assigned and I get the error

```
│ Error: Variables not allowed
│ 
│   on tests/test.tftest.hcl line 16, in run "second":
│   16:     foo = run.first.foo
│ 
│ Variables may not be used here.
╵
╷
│ Error: No value for required variable
│ 
│   on tests/testmodule/main.tf line 3:
│    3: variable "foo" {
```

Hopefully this helps.... thanks.

**Comment by janosdebugs** [comment]
Thanks @crayfishx !
