### ISSUE TITLE
urldecode function

### ISSUE THREAD

**Issue by simongottschlag** [opentofu/opentofu#1234]
### OpenTofu Version

```shell
OpenTofu v1.6.1
on linux_amd64
+ provider registry.opentofu.org/hashicorp/azuread v2.47.0
+ provider registry.opentofu.org/hashicorp/azurerm v3.87.0
+ provider registry.opentofu.org/hashicorp/local v2.4.1
+ provider registry.opentofu.org/hashicorp/random v3.6.0
```

### Use Cases

There are some scenarios where we need to urldecode strings. My scenario is extracting the token from the uri of `azurerm_automation_webhook`, urldecoding the token and then passing it to a `azurerm_logic_app_action_http`.

### Attempted Solutions

Right now, I have to do something like `replace(replace(replace(local.webhook_token, "%3d", "="), "%2f", "/"), "%2b", "+")` - but would be really nice to have the function.

### Proposal

Add `urldecode()` function.

### References

`urlencode` already exists: https://developer.hashicorp.com/terraform/language/functions/urlencode

**Comment by sshiv5768** [comment]
Hey, @simongottschlag I would like to take up this issue.

**Comment by simongottschlag** [comment]
> Hey, @simongottschlag I would like to take up this issue. 

Hi @sshiv5768!

Go for it 😊⭐️

**Comment by sshiv5768** [comment]
Thanks, @simongottschlag. From where i can get started to work on this issue?

**Comment by simongottschlag** [comment]
> Thanks, @simongottschlag. From where i can get started to work on this issue?

Not sure myself, haven't looked into it deeper. But I would guess you can start with the urlencode function and work your way from there 😊

https://github.com/opentofu/opentofu/blob/80f72cecfea3c884f5342f97f425f356db5c8d6d/internal/lang/funcs/encoding.go#L280

**Comment by janosdebugs** [comment]
Hi @sshiv5768 thank you for volunteering for this issue, I've assigned you. Could you please let us know roughly by when you estimate this will be finished? We ask this so we can assign other community members who want to work on this issue in case we don't hear back from you.

**Comment by pooriaghaedi** [comment]
@janosdebugs Could you please assign this task to me? I've already written the code.

**Comment by Yantrio** [comment]
Hi @pooriaghaedi, normally (as per our [contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md)) we ask people to not attempt work until an issue is assigned to them to reduce duplicated efforts.

However in this case it looks like @sshiv5768 has not responded so I am happy to be flexible and assign you this issue. 

Thank you, and in the future please reach out to us to get issues assigned to you first! :D

**Comment by pooriaghaedi** [comment]
Hi @Yantrio, 
Sure, Sorry for that.
