### ISSUE TITLE
Allow setting lists and maps through different TF_VAR variables

### ISSUE THREAD

**Issue by atorrescogollo** [opentofu/opentofu#1238]
### OpenTofu Version

```shell
OpenTofu v1.6.1
on darwin_arm64
```

### Use Cases

I need to create a list/map by combining multiple env vars that come from different sources.

The actual issue is in Spacelift when trying to merge outputs from different stacks into a single stack:

If I have two stacks that output different IDs (e.g.: `stack1->id1` and `stack2->id2`), I have no way to make a list from that. I can only create two different variables in my third stack (e.g.: `var.id1` and `var.id2`), but this is not scalable at all

### Attempted Solutions

I didn't find a way to do this natively

### Proposal

* For lists:

These env vars:
```
export TF_VAR_ids__list0='a'
export TF_VAR_ids__list1='b'
export TF_VAR_ids__list2='c'
```
Can result into a list like as I did:
```
export TF_VAR_ids='["a", "b", "c"]'
```

* For maps:

These env vars:
```
export TF_VAR_ids__mapaaa='a'
export TF_VAR_ids__mapbbb='b'
export TF_VAR_ids__mapccc='c'
```
Can result into a map like as I did:
```
export TF_VAR_ids='{"aaa": "a", "bbb": "b", "ccc": "c"]'
```

**Comment by atorrescogollo** [comment]
Wow, that actually works for me. I didn't know it was even possible. Thanks so much.

On the other hand, it sounds very tricky to do when creating the spacelift stack (I'm using a module but I hope that's clear):
```hcl
locals {
  selected_items = {
    for name, ... in ... :
    name => {
      stack_id = module.other_group_stacks[name].stack_id
    }
    if <<filter condition>>
  }
}

module "demo_stack" {
  source = "../../modules/spacelift/stack"

  << REDACTED >>

  environment_variables = merge(
    {
      TF_VAR_ids = {
        value = jsonencode([
          for idx in range(length(local.selected_items)) :
          format("$${TF_VAR_ids__list%s}", idx)
        ])
      }
    },
  )

  dependencies = {
    for name, item in local.selected_items :
    format("item-%s", name) => {
      stack_id = item.stack_id
      references = [
        {
          output_name = "id"
          input_name  = format("TF_VAR_ids__list%s", index(keys(local.selected_items), name))
        }
      ]
    }
  }
}
```

I think it's pretty reasonable to be able to avoid that extra TF_VAR_ids environment variable with the jsonencode (to ensure the correct format). If opentofu eventually supports it natively, you can focus on creating that list, that can be challenging enough in some cases.

I would like to know your opinion though. At least with your suggestion this is no longer a stopper for me.

**Comment by Yantrio** [comment]
_Replying as a Spacelift employee now!_

I'd love to discuss approaches with you more through our support channels to find the best approach, please feel free to reach out to spacelift support and I'll pick this up there.

I agree that what you have here is great but could work in a better way.

It's also possible to define a pre-init hook that exports the environment variable in your run instead of defining the environment variables at creation time, this may make things a little bit cleaner overall.

For example you could add a pre-init hook of `export TF_VAR_ids="[\"${TF-VAR_ids__list0}\", \"${TF_VAR_ids__list1}\"]"` and that environment variable would be available throughout all the stages of your Spacelift run. However this wouldn't be able to be dynamically sized like yours is now.

**Comment by Yantrio** [comment]
Whilst I agree it's a useful feature for TACOS to consume. I feel like this is quite a niche use case. 

I would love to leave this issue here to see if other members of the community have similar use cases!

**Comment by cam72cam** [comment]
Closing as there is a reasonable workaround

**Comment by chrisbecke** [comment]
is it reasonable though?

Given some terraform that looks like this:

```
runners = {
  first = {
    name = "first-gitlab-runner"
    token = "redacted"
  }
  second = {
    name = "another gitlab runner"
    privileged = "true"
    tags = "docker, etc"
  }
}
```
being deployed from a CI pipeline, I need to be able to not commit tokens to source control. So, alongside the actual TF I would rather like to:

`TF_VAR_runners_first_token = "girt-012345"`
`TF_VAR_runners_second_token = "glrt-123456"`

**Comment by cam72cam** [comment]
In that example, how would you differentiate between runners_first_token, runners.first_token and runners.first.token.  Providing a map in an env var is the accepted solution here.  You could ease the ergonomics of this by creating a script that constructs this environment variable.

**Comment by atorrescogollo** [comment]
Additionally, it's especially tricky when interpolating more complex objects, since that's not even a json that jq can understand:
```
TF_VAR_runners = <<EOF
{
  "first": ${TF_VAR_first_runner},
  "second": ${TF_VAR_second_runner}
}
EOF
```

But that also kind of works
