### ISSUE TITLE
GCS/S3 backends: Create state bucket automatically if it does not exist

### ISSUE THREAD

**Issue by dottedmag** [opentofu/opentofu#1268]
### OpenTofu Version

```shell
1.6.1
```

### Use Cases

The salient case is initializing Tofu state for developers' or CI environments. Without automatic bucket creation one either has to share a bucket between several states (thus opening a venue for confusion in case of misconfiguration), or add automation on top of Terraform to initialize these buckets (such as Terragrunt).

### Attempted Solutions

Terragrunt carries this code to automatically create and configure state bucket if it does not exist:

- https://github.com/gruntwork-io/terragrunt/blob/master/remote/remote_state_gcs.go#L165
- https://github.com/gruntwork-io/terragrunt/blob/master/remote/remote_state_s3.go#L288

### Proposal

Add an option to GCS/S3 backends to create a state bucket if it does not exist (plus attendant options to configure this bucket, similar to Terragrunt solution).

**Comment by janosdebugs** [comment]
Hey @dottedmag we discussed this issue in the core team and we will not pick this up at this time. The main reason is that the setup related to S3 is fairly complex (all the options for S3 buckets, DynamoDB settings, access keys, etc) and we do not feel that the effort required to keep this updated, new fields added is duplicating the effort of configuring S3 in the AWS provider.

If #382 is accepted, the community is welcome to implement custom features for backends as a plugin.
