### ISSUE TITLE
Docs for 'Authenticate using a Service Principal'

### ISSUE THREAD

**Issue by neilmartindev** [opentofu/opentofu#1269]
### OpenTofu Version

```shell
1.6.1
```

### OpenTofu Configuration Files

```hcl
...tofu config...
```

### Debug Output

$ tofu init -migrate-state

Initializing the backend...
Backend configuration changed!

OpenTofu has detected that the configuration specified for the backend
has changed. OpenTofu will now check for existing state in the backends.

╷
│ Error: Error building ARM Config: Authenticating using the Azure CLI is only supported as a User (not a Service Principal).
│ 
│ To authenticate to Azure using a Service Principal, you can use the separate 'Authenticate using a Service Principal'
│ auth method - instructions for which can be found here: https://registry.opentofu.org/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secret
│ 
│ Alternatively you can authenticate using the Azure CLI by using a User Account.
│ 
│ 
╵

### Expected Behavior

The URL should work instead of 404 error: 

https://registry.opentofu.org/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secret

### Actual Behavior

404 Error

### Steps to Reproduce

I have local tfstate and looking to migrate it to the cloud in Azure through a storage container. However, I have to do this via a Service Principal. I can authenticate with the Service Principal fine with no issues on it's own using az login.

I've added some images of my configuration and then the following error message:

![example backend](https://github.com/opentofu/opentofu/assets/87085416/b86fa631-6b42-49e8-92de-201fded90b7e)
![bug](https://github.com/opentofu/opentofu/assets/87085416/b8ec456b-b906-4437-975a-2024db27a278)

tofi init 

tofu init -migrate-state

![error](https://github.com/opentofu/opentofu/assets/87085416/04ab52ad-e3d7-4116-94f2-014b99259084)

### Additional Context

I can't use my local Azure account due to work restrictions so that as an alternative isn't an option for the moment so the documentation would be useful. Open to any advice or pointers though :)

**Comment by janosdebugs** [comment]
Hey @neilmartindev I believe this may be related to #1198. Currently, I believe authenticating with service principals is not supported on Azure.

**Comment by Yantrio** [comment]
Actually I think this is an issue where we're not using the terraform registry URLs anymore, and we do not yet have a web user interface for our OpenTofu registry.

You can find the instructions here for now: https://github.com/opentofu/terraform-provider-azurerm/blob/main/website/docs/guides/service_principal_client_secret.html.markdown or you can find them elsewhere on the internet if you search "azurerm creating a service principal"

**Comment by neilmartindev** [comment]
Thanks for the input!
