### ISSUE TITLE
Switch Docker images to multi-platform images

### ISSUE THREAD

**Issue by skyzyx** [opentofu/opentofu#1273]
### OpenTofu Version

```shell
N/A
```

### Use Cases

As discovered in [1] and [2], while we have Docker images containing OpenTofu builds, they are not multi-platform. This means that instead of being able to do:

```bash
docker pull ghcr.io/opentofu/opentofu:1.6.1
```

…you have to do this:

```bash
docker pull ghcr.io/opentofu/opentofu:1.6.1-amd64
```

In multi-platform environments (e.g., developer Dockerfiles specifying `FROM`, where some users are on Intel chips and others are on Apple Silicon chips), this becomes highly cumbersome.

### Attempted Solutions

None yet.

### Proposal

1. Update the `Dockerfile` with syntax which instructs BuildKit to build multi-platform images.
2. Update the GoReleaser config to pass the necessary `--platform` flags to BuiltKit when triggering the build.

### References

* [1] https://github.com/opentofu/opentofu/pkgs/container/opentofu
* [2] https://opentofucommunity.slack.com/archives/C05R0FD0VRU/p1708027538606529?thread_ts=1708027313.125469&cid=C05R0FD0VRU

**Comment by tedivm** [comment]
It looks like there is a simple path to this with a [tweak to the goreleaser configuration](https://goreleaser.com/cookbooks/multi-platform-docker-images/#creating-multi-platform-docker-images-with-goreleaser).

**Comment by tedivm** [comment]
It looks like they already *are* multi platform images.

Here's [the manifest](https://github.com/opentofu/opentofu/pkgs/container/opentofu/170597496?tag=1.6.1) for the tag `1.6.1`.

![Screenshot 2024-02-17 at 2 46 35 PM](https://github.com/opentofu/opentofu/assets/121709/2ed28a5b-a28c-4d97-a119-34f905f26a45)

That tag maps to four different platforms: 

* linux/386
* linux/amd64
* linux/arm/v7
* linux/arm64

I just confirmed that running `docker pull ghcr.io/opentofu/opentofu:1.6.1`, as per the first example, pulls down a workable image for my platform without having to specify the specific platform tag.

**Comment by janosdebugs** [comment]
Thanks @tedivm, I guess this issue can be closed then. :)
