### ISSUE TITLE
OpenTofu-specific code override

### ISSUE THREAD

**Issue by janosdebugs** [opentofu/opentofu#1275]
### OpenTofu Version

```shell
N/A
```

### Use Cases

Currently, OpenTofu is trying to keep compatibility as much as possible with Terraform so that module authors can ship modules for both. This prevents us from adding features such as #1005 in Terraform-incompatible ways.

### Attempted Solutions

See #1005 and the hacks suggested there.

### Proposal

In addition to loading `.tf` files, OpenTofu should also load `.otf` files. When there are two files with the same name with both extensions, OpenTofu should ignore the `.tf` file and only load the `.otf` file. This would gove module authors a simple way to use OpenTofu-specific features but still keep compatibility with Terraform.

In order to support all operating systems, the filename comparison should be performed case-insensitive.

### References

- #1005

**Comment by janosdebugs** [comment]
@cube2222 I believe this should be presented to the TSC alongside #1005 .

**Comment by RLRabinowitz** [comment]
Another possible advantage of this approach is for auto-complete in IDEs. This'll allow IDEs to determine the configuration as an OpenTofu configuration, and then allow auto-complete for OpenTofu-specific configuration (like the upcoming state encryption)

**Comment by cube2222** [comment]
@janosdebugs I like this whole-file based approach a lot. Much nicer than some weird preprocessing. I've submitted it to the TSC for review, iirc they are meeting his week.

**Comment by cube2222** [comment]
Fwiw, with .otf we'd have a conflict with OpenType Font files.

.of is free though, according to https://en.wikipedia.org/wiki/List_of_filename_extensions_(M–R)

**Comment by marcinwyszynski** [comment]
I personally really like the idea of using a different extension (extensions, because there are also `.tf.json` files) and having `.otf` files explicitly override `.tf` files with the same base name.

**Comment by cube2222** [comment]
Also, I think we need to do something similar for `tofu test` files.

**Comment by janosdebugs** [comment]
RFC is up: #1328
