### ISSUE TITLE
Run providers in a separate mount namespace to protect local files

### ISSUE THREAD

**Issue by chenzejun** [opentofu/opentofu#1290]
### OpenTofu Version

```shell
OpenTofu v1.6.1
```

### Use Cases

Some files in my machine may be sensitive(eg: kubeconfig, password...)
The providers download form registration was from multifarious authors(not so trusted) so I don t want providers to access files on my machine

### Attempted Solutions

no attempted solutions

### Proposal

When start provider process, start it in a separate mount namespace
Add a envionment variables like TF_PROVIDER_ISOLATION as a toggle

**Comment by janosdebugs** [comment]
Hi @chenzejun thank you for this issue. We haven't discussed this idea in the core team yet, but I feel that this is going into the direction of implementing a container engine inside OpenTofu. Even if it starts only with a mount namespace, there are legitimate reasons for wanting to isolate other aspects of the providers too, such as the network or PID namespace. I have implemented a [toy container runtime](https://github.com/janosdebugs/demo-container-runtime) previously and I can safely say, I wouldn't feel comfortable shipping a production-ready container engine without extensive work on the security side, even if it only incorporated some aspects of containerization. This would also need continuous maintenance as the Linux kernel develops.

Specifically about mount namespaces, using these requires root privileges (`CAP_SYS_ADMIN` capability), which has the potential for much more destruction than simple file access. You can test this out by running the demo in the `demo/namespaces/mount` folder in the linked project. You will get an "Operation Not Permitted" error unless you run the demo with root.

Even if we were willing to maintain something this complex in the long run, the current architecture of OpenTofu is not separated cleanly in a way that would allow only the execution to take place in a privileged context and would require major refactoring before it can be done.

On a practical note, I think #1138 is a much more viable route and even that is a stretch given the current architecture (see #1221). That being said, let's wait for the other members of the core team to have a chance to take a look at it.

**Comment by chenzejun** [comment]
Thanks @janosdebugs for reply, let me bring this topic a little back to the initial requirement, do you have any idea how to avoid providers access local file?

**Comment by janosdebugs** [comment]
Hey @chenzejun we discussed this in the core team and given that this feature is limited to Linux users and given the complexity, we decided not to pick up this issue at this time. For the time being, please run OpenTofu in a container if you need isolation from the rest of your system.
