### ISSUE TITLE
Allow using vault as a source of key/secret content for backends, not just data/resource

### ISSUE THREAD

**Issue by nneul** [opentofu/opentofu#1331]
### OpenTofu Version

```shell
NA
```

### Use Cases

Goal is to be able to have a minimal configuration in TF content, and a bare minimum of external environment requirements. Typical answer is "use an AWS session", but that in many environments triggers a LOT of extra complexity as compared to just "be logged into vault". 

### Attempted Solutions

Various implementation options exist leveraging third party services for this such as "must have an AWS session and then use S3/Dynamodb" or the Azure or GCP equivalents. 

I'm asking for "be logged into vault" to be a generalized solution to this that could feed credentials even to other providers like AWS/Azure/GCP/Generic/etc. 

### Proposal

Currently, there is a chicken and egg situation that overlaps with all of the discussions about state encryption, providers, etc. requiring use of AWS S3 or other "storage" areas. While I'm in support of the state encryption and other proposals, I believe it would be much simpler to just "support loading configuration for providers from vault". 

Example:

```
terraform {
  backend "s3" {
    bucket         = "blah-tfstate"
    key            = "BlahBlah/aws/terraform.tfstate"
    region         = "us-west-2"
    dynamodb_table = "tfstate_lock"
    access_key = vault("secret/path/my/aws/creds", "access_key")
    sec = vault("secret/path/my/aws/creds", "secret_key")
  }
```

(And yes, I realize that using S3 as the example has _other options_ - but it's just a convenient example to show how it might be used. Equivalent would be say using one of the remote http providers and specifying a username/password.)

Above doesn't work to my knowledge - you can't use anything dynamic as a source for any information for backend configuration. 

All other examples and "solutions" for this in the TF docs call for "Oh, just use a wrapper" or "Put it in a partial configuration using environment variables" -- but I'm *already logged into vault* why should I have to jump through those hoops using non-standard wrapper tools or special environment?

**Comment by janosdebugs** [comment]
Hey @nneul and thank you for this issue! The core team regularly reviews new issues and discusses them, but this can take a little time. Please bear with us while we get to your issue. If you're interested, the contribution guide has a section about the [decision-making process](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md#who-decides-if-a-feature-will-be-implemented-and-how-is-that-decision-made). :)

**Comment by cam72cam** [comment]
There are too many assumptions in OpenTofu that initialize the backend before any remote data is available.  This would require significant and deep refactoring of code/concepts within the project.  Our recommendation for now is to use .aws/credentials or environment variables.
