### ISSUE TITLE
Adjust certain Terraform version assertions to cross-fork OpenTF versions

### ISSUE THREAD

**Issue by roni-frantchi** [opentofu/opentofu#134]
Terraform makes certain assertions on versions before some operations.  

One example is - when trying to `terraform apply` a plan generated by an older version of Terraform.  
Since Terraform <> OpenTF versioning, we should simply fail for the above case if the plan was generated by Hashi Terraform and tried to be applied with OpenTF, as one can simply regenerate the plan and take no risks there.  

### **There may be other cases**, and each should be discussed individually.  

The **definition of done** of this issue is to investigate the codebase and look for such assertions and propose changes to cope with each, possibly in a different way.

**Comment by Yantrio** [comment]
@roni-frantchi @marcinwyszynski Did you guys have any more opinions on this one?

In my opinion we should do some tests to ensure that the compatibility is there to consume a planfile generated by terraform but I don't see much of a need to introduce special logic at this time.

**Comment by marcinwyszynski** [comment]
@Yantrio I think there's no need for special-casing this.
