### ISSUE TITLE
`tofu test` - Should use `.tfvars` files from the test folder

### ISSUE THREAD

**Issue by RLRabinowitz** [opentofu/opentofu#1367]
### OpenTofu Version

```shell
1.6.2
```

### Use Cases

Using `.tfvars` files

Currently when running `tofu test`s, it picks up variables of `terraform.tfvars` and `*.auto.tfvars` files from the root configuration folder.
Being able to also use `terraform.tfvars` and `*.auto.tfvars` from the test folder would make sense, to help set values specific for test suites

### Attempted Solutions

A workaround could be using `TF_VAR_` environment variables, which isn't so nice, or setting static `variables` blocks in the `testtf.hcl` file, but that would necessitate copying that `variables` block between test files

### Proposal

Alongside using `terraform.tfvars`, `terraform.tfvars.json`, `*.auto.tfvars`, `*.auto.tfvars.json` files from the root directory, also take variables from the same files in the test folder.

If a variable appears both in a `.tfvars` file in the root configuration and in the test folder, the one in the test folder should take precedence. If a variable appears only in one `.tfvars` file, be it in the root configuration or in the test folder, then this variable should be available as such in the test

**Comment by janosdebugs** [comment]
Thank you for volunteering @sanskruti-shahu , I've assigned you. Please read [the "I've been assigned an issue, now what?" section of the contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md#ive-been-assigned-an-issue-now-what) before you begin working.

**Comment by jasonyoung-pearl** [comment]
This change seems to result in tfvars in the `tests/` directory _always_ being automatically used, even when simply running `tofu apply`, not just `tofu test`. This means if we create a `test.auto.tfvars` in our module's `tests/` directory, they are included whenever the module is used. Hard to see how this could be expected behavior, so assuming this should be raised as a bug?

**Comment by cam72cam** [comment]
Actually, I'm going to re-open this as there are a few bugs in this functionality

**Comment by AdosH1** [comment]
Hey @cam72cam, I'd like to take a look at this
You mentioned a few bugs in this functionality - would you mind elaborating the specific issues?

From what I understand the current implementation simply overwrites variables with test ones regardless of the command used eg. `tofu apply` vs `tofu test`
Are there other problems in the implementation that you saw?

**Comment by AdosH1** [comment]
@cam72cam 
On looking deeper, it seems you may have solved this issue in #2039 
I'm quite new to this repo, I've written a test #2106, is this supposed to fail with the new implementation?

**Comment by ollevche** [comment]
Hey @AdosH1! Thanks for taking a look, let me assign you to this issue. I will comment on your PR shortly.

**Comment by ollevche** [comment]
This bug is already fixed in https://github.com/opentofu/opentofu/pull/2039. Sorry for the confusion.
