### ISSUE TITLE
Add an `issensitive` function, checking whether a value is sensitive or not

### ISSUE THREAD

**Issue by RLRabinowitz** [opentofu/opentofu#1370]
### OpenTofu Version

```shell
1.6.2
```

### Use Cases

It would be useful if we could tell whether or not a value is sensitive programatically. A use-case for that is if you'd like to filter all sensitive data for an output of a module

### Attempted Solutions

Before [this change](https://github.com/opentofu/opentofu/issues/394), `nonsensitive` used to error if a value is already not sensitive. So, you could use `!can(nonsensitive(value))` to tell you if a value is sensitive. However, that no longer works in 1.7.0

### Proposal

Add a function `issensitive` that does that explicitly - return a boolean saying whether or not a value is sensitive

### References

Related issue in the Terraform registry - https://github.com/hashicorp/terraform/issues/34572,

**Comment by JonasBak** [comment]
Hi, I would like to work on this 🙋

**Comment by cam72cam** [comment]
Thanks @JonasBak, I've assigned the issue to you.  Please take a quick look at our [contributing guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md#ive-been-assigned-an-issue-now-what) and let us know if you have any questions.

We also want to be very careful that anyone who works on this issue **does not** read any related terraform source code or use AI code generation tools.

**Comment by JonasBak** [comment]
Thanks 🙌 I've started working on it, and I think I've got the feature working. I'll just write some docs then I'll open a PR. Hopefully I'll get time to finish it within a few days.
