### ISSUE TITLE
When generating configuration, wrap JSON data with `jsonencode`

### ISSUE THREAD

**Issue by RLRabinowitz** [opentofu/opentofu#1371]
### OpenTofu Version

```shell
1.6.2
```

### Use Cases

Currently, generated code that contains stringified JSON is generated as a stringified JSON string. For example, a generated `aws-iam-group-policy` would have a `policy` that's `"{\"Version\":\"2012-10-17\",\"Statement\";[{...}]}"`.

It would look nicer if it was instead:
```
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      ...
    }]
  })
```

Just for a better aesthetic look for generated configuration

### Attempted Solutions

.

### Proposal

See "Use Cases"

### References

Related issue in the Terraform repository - https://github.com/hashicorp/terraform/issues/34444

**Comment by janosdebugs** [comment]
Thank you for volunteering @SypherSP , I've assigned you. Please read [the "I've been assigned an issue, now what?" section of the contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md#ive-been-assigned-an-issue-now-what) before you begin working.

**Comment by SypherSP** [comment]
I think ill be able to have a solution ready by next week.

**Comment by ChihweiLHBird** [comment]
Any update? What happens to this issue and the closed PR? It would be much nicer if things can be a little bit more transparent here.

**Comment by cube2222** [comment]
@ChihweiLHBird Hey! We're generally trying to be very transparent, but in this case the problem was of a nature that we've communicated with the author privately and forced us to close the PR.

The issue will now be handled by a core team member.
