### ISSUE TITLE
[State Encryption] Footgun: statefile{} vs backend{} responsibilities unclear

### ISSUE THREAD

**Issue by janosdebugs** [opentofu/opentofu#1385]
Currently, the `statefile{}` block only affects the state *cache* file located at `./terraform/terraform.tfstate`, but not the local state file located at `./terraform.tfstate`. In contrast the `backend{}` block encrypts state files written to both remote backends and to the local state file located at `./terraform.tfstate`, but not the state *cache* file located at `./terraform/terraform.tfstate`.

This behavior is unintuitive and does not conform to an average tofu user's understanding on terminology. The [Backend Configuration](https://opentofu.org/docs/language/settings/backends/configuration/) page only hints to this misunderstanding in one, easy to miss sentence:

> By default, OpenTofu uses a backend called [local](https://opentofu.org/docs/language/settings/backends/local/), which stores state as a local file on disk. You can also configure one of the built-in backends included in this documentation.

## Goal of this issue

The state encryption configuration should be changed such that an average user cannot unintentionally misconfigure the encryption and leave part of the state unencrypted unless specifically desired so. However, in accordance with the original RFC, the functionality to separately configure state and plan file encryption should be retained.

## Threat model

The threat model has two dimensions:

1. Local disk vs. remote state storage. The configuration should allow configuring encryption for either independently.
2. State vs. plan files. While both may contain sensitive data, plan files can be short-lived. Sometimes it may be necessary to not encrypt plan files so other tools can read them.

There is an additional edge case when a user may want to specifically disable encryption for their cache file if the cache file is located in a ramdisk, but this can be expected to be a very small minority of users. However, as a default, users should never end up with an unencrypted state cache file when encryption is configured, unless they specifically request it.

### Solution 1

This solution gets rid of the `backend{}` block entirely, disabling the possibility of configuring remote and local state encryption separately, but it makes sure that users won't accidentally misconfigure encryption. The `statefile{}` block will configure encryption for all state-related encryption, while the `planfile{}` block will configure all plan-related encryption, regardless of where it is stored.

```terraform
terraform {
  encryption {
    statefile {}
    planfile {}
    # Note: no backend{}
  }
}
```

### Solution 2

This solution introduces a local and remote variant for each block:

```terraform
terraform {
  encryption {
    local_statefile {}
    local_planfile {}
    remote_statefile {}
    remote_planfile {}
  }
}
```

### Solution 3

Additionally to solution 1 and 2 above, there can be an extra block called `local_state_cache{}`, which should fallback on `local_statefile{}` / `statefile{}` as a default.

**Comment by cube2222** [comment]
I'm happy with solution 1 for now.
