### ISSUE TITLE
[Release Issue] GoReleaser SnapCraft Grade/Channel not correctly configured

### ISSUE THREAD

**Issue by cam72cam** [opentofu/opentofu#1403]
In the 1.7.0-alpha1 release, we ran into an issue with setting the grade / channel correctly:
https://github.com/opentofu/opentofu/actions/runs/8282888828/job/22664796648

We should either use the GoReleaser includes, or go template if statements to correctly set the snapcraft channel and grade.  This is a follow up to the work done in https://github.com/opentofu/opentofu/pull/1235.

**Comment by cube2222** [comment]
Also, we should be releasing the 1.7 docker image tag when doing a 1.7.0 prerelease. It should only do the full literal tag, so 1.7.0-alpha1.

Also, we need a separate input variable for `latest`, because right now any stable release gets marked as latest, even if it's a backport release.

**Comment by bunniseng** [comment]
I would like to work on this issue, @cam72cam would you be able to assign me the issue please.

**Comment by cam72cam** [comment]
Hey @bunniseng  thank you for volunteering! Please read [the "I've been assigned an issue, now what?" section of the contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md#ive-been-assigned-an-issue-now-what) before you begin working.

We are in a bit of a time crunch on this issue and are hoping to put out a second alpha next week, which would benefit from this fix.  if you feel like that timeline is too aggressive, we can try to find another issue that is not time dependent.

**Comment by bunniseng** [comment]
Timeline should be okay, I'll start working on this today.

**Comment by bunniseng** [comment]
Hey @cam72cam

I started to look at this and probably need a bit of time to get familiar with all of it, given the timeline this would be best picked up by someone who's familiar with the setup.

I can find another issue to contribute that's not so time dependent.

Thanks
David

**Comment by bunniseng** [comment]
Hi @cam72cam

I have an initial PR ready for review: https://github.com/opentofu/opentofu/pull/1450

This resolves the initial issue of configuring the snapcraft grade / channel for prerelease and stable releases.

As noted in the PR, there is a problem with creating a developer account on snapcraft.io, I am waiting for an issue to be resolved so I can setup a full e2e workflow. 

I have been able to run the "Run GoReleaser" task and set the grade / channel correctly as shown in the publishing targets screenshots for prelease and stable releases on the PR.

I will look at the docker image tagging comments which @cube2222 has raised and create a new PR for that.

Please have a look over the PR when you have time and let me know.

Thanks
David
