### ISSUE TITLE
[State Encryption] Consider unlikely failure scenarios when writing state

### ISSUE THREAD

**Issue by cam72cam** [opentofu/opentofu#1404]
### Configuration
```hcl 
encryption {
                key_provider "aws_kms" "basic" {
                        // configured
                }
                method "aes_gcm" "example" {
                        keys = key_provider.aws_kms.basic
                }
                state {
                        method = method.aes_gcm.example
                }

}
```
### Current Code Path `tofu apply`
* init apply command
  * load root module
  * construct encryption interface
  * construct state backend w/ state encryption
  * read state
    * call aws_kms key provider with given state metadata
    * call aes_gcm with keys
    * decrypt state
  * plan graph
  * apply graph
    * partial apply infrastructure changes
    * checkpoint write state
      * call aws_kms key provider
         * ERROR: US-EAST-1 is DOWN!
         * bubble error state all the way back to command package
  *  Call error handler `backend_apply:backupStateForError`
    * **Write state to "errored.tfstate"**
       * Use backend state encryption
          * aws_kms fails again!
    * **Write state to stderr**
       * Use backend state encryption
          * aws_kms fails again!
    * **State with partial changes is lost!!!!**
    
#### Don't encrypt either errored.tfstate or stderr state

This gives the user an easy to understand state file that they can read, manipulate, and react to.  The main downside is that the state will now be accessible to anyone who has access to that machine or even potentially backed up as part of a CI workflow.

#### Only try to encrypt errored.tfstate and if that fails write state to stderr unencrypted

This is similar to the previous solution, and still has the issue where if stderr is captured as part of CI it can expose secrets in the state.  However, it provides a file that can be manually put into the backend state store and potentially reduces the overhead of recovery.

#### Only generate the new encryption keys for a provider once per tofu invocation

We always need to be dynamic with how we Decrypt state files, the configuration depends on the provided state's metadata. However, we don't necessarily need to generate a new encryption key for a given key provider during the same invocation of tofu.  It would write variations of the state file using the same encryption key that is generated during the encryption interface init.  This would write more data with the same key which may have safety implications that I am personally not qualified to evaluate.

**Comment by cube2222** [comment]
I think it would make sense to dump the errored.tf file, but it should not be unencrypted.

Instead, we should generate an additional encryption key at the beginning of the execution, to be used in case we need to dump the errored.tf file later.

**Comment by StephanHCB** [comment]
Please do not dump state to stdout or stderr in commands where this is not the user expectation (such as state pull).

If unencrypted, this will most definitely cause security incidents.

Even if encrypted, this can still cause (much more limited) security incidents, if the output shows up in CI to a user who has access to the key.

"Only generate the new encryption keys for a provider once per tofu invocation" actually sounds good, but only really solves the problem if tofu does so early enough. Maybe do that for commands that typically write state. It would come at the expense of a key creation for failed runs, but that isn't a huge concert imho.

**Comment by cube2222** [comment]
> "Only generate the new encryption keys for a provider once per tofu invocation" actually sounds good, but only really solves the problem if tofu does so early enough. Maybe do that for commands that typically write state. It would come at the expense of a key creation for failed runs, but that isn't a huge concert imho.

We can't generate keys once and reuse them, as AES keys have a limited amount of data they can be used to encrypt. Since Tofu persists the statefile during applying every 15-30 seconds by default, we need to generate keys dynamically.

Since dumping the statefile is what tofu currently does when the state backend is down, I think it makes sense to dump an (**encrypted**!) statefile to disk in such a situation. Remote state backends create a local-filesystem cache of the state file anyway afaik (which is encrypted as well).

**Comment by janosdebugs** [comment]
We talked with @cam72cam and currently, the key is being refresh every time the state is being persisted to the local cache (~every 30 seconds during a run). However, I am very confident that this is not necessary and we can safely use the same key to persist throughout the entire run and we would still be very far away from AES-GCM exhaustion. (Taking it to the extreme, 100 MB state file with a 1-hour run would still only result in ~12 GB of data written.)

Our current thinking is that the encryption method will be initialized once and will be used every time the state is written during a single apply. The next apply would, of course, ask the key provider again and result in a new key.
