### ISSUE TITLE
[State Encryption] allow separately enabling statefile encryption and remote state encryption

### ISSUE THREAD

**Issue by StephanHCB** [opentofu/opentofu#1413]
### Did you test the state encryption?

Tested, worked

### Additional feedback / details on the state encryption

Right now there is no way to separately disable local statefile encryption when using a remote state backend (using azure storage account). The two things are configured with the same configuration block.

However, even when using a remote state backend, there are cases where local state is still written to disk.

- The user may wish to have access to unencrypted local state
- I also believe this may ease the transition to encrypted state for TACO vendors if this can be configured separately

**Comment by janosdebugs** [comment]
We had a chat with @cam72cam and we have two possible ways to make this happen:

## Solution 1

We add a flag to the `state` block that disables encryption for both the local state cache and the local backend:

```hcl
terraform {
  encryption {
    state {
      method = ...
      disable_local_encryption = true # Default: false
    }
  }
}
```

## Solution 2

Here we define completely separate blocks for local state cache and the local backend:

```hcl
terraform {
  encryption {
    local_state { #Affects both local state cache and local backend
      method = ...
    }
    remote_state { #Affects only non-local backend
      method = ...
    }
  }
}
```

Personally, I'm happy with both solutions, but solution 2 would require this feature to be shipped before 1.7.0 stable as it will be a syntax change.

/cc @Yantrio

**Comment by StephanHCB** [comment]
> Personally, I'm happy with both solutions, but solution 2 would require this feature to be shipped before 1.7.0 stable as it will be a syntax change.

Thanks. I'm happy with either solution.

**Comment by Yantrio** [comment]
I prefer the first solution here, I think we should also think about the name of this property to make it clear what it does too.

**Comment by cam72cam** [comment]
I'm also leaning toward option #1, but don't know that it needs to make it into 1.7.0
