### ISSUE TITLE
Support Authorization Bearer token for HTTP backend

### ISSUE THREAD

**Issue by svivekkrishna** [opentofu/opentofu#1427]
### OpenTofu Version

```shell
OpenTofu v1.6.0
on linux_amd64
```

### Use Cases

`tofu` is used from CI/CD workflows where an HTTP state backend is used; the choice of backend being HTTP because not everyone can provision a cloud service based backend and could be using `tofu` for managing infrastructure that may not even be public cloud.

The current HTTP backend supports `username`  and `password` with Basic authentication. OIDC is a popular choice for credential-less authorized interactions between machines. The auth token used with OIDC is a JWT, which is generally exchanged using the `Authorization: Bearer <token>` header. Introducing this feature would allow the JWT to set as it is instead of pushing it into a Base64 structure.

### Attempted Solutions

Currently, we spoof the username field and pass the bearer token in the password field so that tofu/terraform can base64 encode it through the httpClient.  

### Proposal

- Support `bearer_token` as an optional input for the HTTP backend.
- The validation should ensure that both username + password, and `bearer_token` must not be present together.
- Build the httpClient adding the `Authorization: Bearer <bearer_token>` header, if set.

**Comment by janosdebugs** [comment]
Hey @svivekkrishna thank you for this issue! The core team regularly reviews new issues and discusses them, but this can take a little time. Please bear with us while we get to your issue. If you're interested, the contribution guide has a section about the [decision-making process](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md#who-decides-if-a-feature-will-be-implemented-and-how-is-that-decision-made).

**Comment by bunniseng** [comment]
Hi @Yantrio 

I would like to work on this issue, can you please assign it to me.

Thanks
David

**Comment by Yantrio** [comment]
Sure I'm happy to assign this to you. Before you begin development, please see our Contributing guidelines here before beginning working on this task: https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md#ive-been-assigned-an-issue-now-what.

I think one of the first steps may be a bit of a conversation here about how we name things and what the end user would define in their configuration.

Do you have any ideas about how you would like to be able to configure headers for the http backend?

**Comment by Ericwww** [comment]
I propose this example. And this is also the easiest example to think of.

```hcl
terraform {
  backend "http" {
    address = "http://myrest.api.com/foo"
    lock_address = "http://myrest.api.com/foo"
    unlock_address = "http://myrest.api.com/foo"
    custom_header = {
        header_a = foo
        header_b = bar
    }
  }
}
```

But I also propose load custom header from env because some information in header may be sensitive. 
We can provider such a env prefix for user like `TOFU_BACKEND_HTTP_CUSTOM_HEADER_`. (It's very long I have to say. We could have a better naming.)

User can provider some env like this:

```shell
export TOFU_BACKEND_HTTP_CUSTOM_HEADER_AUTHORIZATION="Bearer <Your Token>"
export TOFU_BACKEND_HTTP_CUSTOM_HEADER_X-Request-Id="xxxxxx" 
```

It seems dash can not work in some command line....... But I saw some example from hashicorp for [env credential](https://developer.hashicorp.com/terraform/cli/config/config-file#environment-variable-credentials). It's weird.

Anyway, I think we should support user define their custom header in env and tf file. And the loading priority of env should be the highest.

**Comment by janosdebugs** [comment]
Regarding sensitive values, the user could read them from a variable. I would try to avoid adding new environment variables as much as possible, the current code already has an unmanagable array of environment variables.

**Comment by cam72cam** [comment]
You can use -backend-config, but variables are not (currently) allowed in backend configs.

**Comment by bunniseng** [comment]
I was thinking a structure similar to @Ericwww 

```
terraform {
  backend "http" {
    address = "http://myrest.api.com/foo"
    lock_address = "http://myrest.api.com/foo"
    unlock_address = "http://myrest.api.com/foo"
    headers = {
          a = foo
          b = bar
       }
    }
  }
}
```

Header field names are restricted to `a-zA-Z09-_` characters
Header field values are restricted to ASCII

I had a quick look over a HTTP1.1 and HTTP2 RFC to see what the "formal" specification is for defining header field names and values, there is a slight difference in the handling of field names in which HTTP1.1 spec allows for case insensitive field names whereas HTTP2 spec defines field names all as lower-case.

[HTTP1.1 - RFC-7230](https://www.rfc-editor.org/rfc/rfc7230#section-3.2.4)
[HTTP2 - RFC-7540](https://datatracker.ietf.org/doc/html/rfc7540#section-8.1.2)

We can probably leave the field names casing to be up to the user and just simply send through whatever is defined in the headers object or add the ability to configure a compliance like mode via the use of options

```
terraform {
  backend "http" {
    address = "http://myrest.api.com/foo"
    lock_address = "http://myrest.api.com/foo"
    unlock_address = "http://myrest.api.com/foo"
    headers = {
       fields = {
          a = foo
          b = bar
       }
       options = {
         compatibility = http2
       }
     }
    }
  }
}
```
This should be configurable using the currently supported methods / limitations and I also agree with restricting the use of introducing environment variables.

I'm also thinking we should have validation on the header field names to restrict the use of any headers that are used in the application code base, either that or headers defined in the application code base override user defined headers but I can see that causing a headache for users debugging issues.

**Comment by bunniseng** [comment]
@Yantrio : can you review over the comments and let me know if I am good to get started ?

**Comment by bunniseng** [comment]
Agreed.

**Comment by bunniseng** [comment]
Hi @janosdebugs 

The PR for this functionality is ready to review: [1487](https://github.com/opentofu/opentofu/pull/1487)

**Comment by ag-TJNII** [comment]
Was the documentation updated to reflect this?  I don't see custom header options in https://opentofu.org/docs/language/settings/backends/http/, am I confused?
