### ISSUE TITLE
Unix/Linux encryption configuration exits with error

### ISSUE THREAD

**Issue by dotemacs** [opentofu/opentofu#1462]
### Did you test the state encryption?

Tested, worked

### Additional feedback / details on the state encryption

# Exit code 1, in bash

Following the example for creating the encryption configuration: 

https://1-7-0-alpha1.opentofu.pages.dev/docs/language/state/encryption/#configuration

the exit code is always 1.

This can be annoying on a CI, which expects all the commands to have the exit code of 0.

See:

```
$ read -d '' TF_ENCRYPTION << EOF
> terraform {
>   encryption {
>     key_provider "some_key_provider" "some_name" {
>       # Key provider options here
>     }
>
>     method "some_method" "some_method_name" {
>       # Method options here
>       keys = key_provider.some_key_provider.some_name
>     }
>
>     state {
>       # Encryption/decryption for state data
>       method = method.some_method.some_method_name
>     }
>
>     plan {
>       # Encryption/decryption for plan data
>       method = method.some_method.some_method_name
>     }
>
>     remote_state_data_sources {
>       # See below
>     }
>   }
> }
> EOF
[alex@/tmp]$ echo $?
1
```

### Did you test the removed block?

Did not test

### Did you test the testing feature changes?

Did not test

### Did you test the built-in functions?

Did not test

### Did you test the CLI changes?

Did not test

**Comment by Yantrio** [comment]
this for submitting this issue @dotemacs 

I've found that using `cat` works better here than read with `-d`

```bash
TF_ENCRYPTION=$(cat <<EOF
terraform {
  encryption {
    key_provider "some_key_provider" "some_name" {
      # Key provider options here
    }

    method "some_method" "some_method_name" {
      # Method options here
      keys = key_provider.some_key_provider.some_name
    }

    state {
      # Encryption/decryption for state data
      method = method.some_method.some_method_name
    }

    plan {
      # Encryption/decryption for plan data
      method = method.some_method.some_method_name
    }

    remote_state_data_sources {
      # See below
    }
  }
}
EOF
)
```
![image](https://github.com/opentofu/opentofu/assets/237469/cbd9665e-bf6b-4ddb-8fb2-d8525c81aae4)

**Comment by dotemacs** [comment]
I think that we just spoke on Slack about this...

That's what I did too.

But since issues need to be reviewed first before being listed for a PR, I figured to create this first.
