### ISSUE TITLE
Merge duplicate diagnostics to avoid diagnostics flood

### ISSUE THREAD

**Issue by chenzejun** [opentofu/opentofu#1480]
### OpenTofu Version

```shell
any
```

### Use Cases

When I use the template to run a plan 
```
output "out" {
  value = [for i in range(50): length([for i in range(50):bad()])]
}
```
I get 2500 same diagnostics :
![image](https://github.com/opentofu/opentofu/assets/26278304/8da03290-2025-40f6-ba25-38a18bc53104)

### Attempted Solutions

merge them
or wait upstream(hcl) fix it

**Comment by cam72cam** [comment]
This would touch similar functionality as #364.

**Comment by chenzejun** [comment]
@cam72cam  That's true, we need also have a flag here to toggle this feature, it can be `--unique-error` or othere better name.
And I am happy to have a deep dive into how this part will work and help work on it, if we decide to accept this issue.

**Comment by chenzejun** [comment]
Hi @janosdebugs, can you assign it to me?

**Comment by Ericwww** [comment]
Well, it seems that upstream(hcl) close related issue and suggest us implement it in tofu.

https://github.com/hashicorp/hcl/issues/674

**Comment by cam72cam** [comment]
Yeah, that definitely makes sense.  We don't want to deal with pushing that code into upstream libraries.  There's already code in OpenTofu that deals with compacting warnings which should be expanded for that use case.  Had I known you were taking this approach, I would have intervened sooner.

**Comment by cam72cam** [comment]
I'm also in the process of rebasing and updating https://github.com/opentofu/opentofu/pull/399 which touches very similar code.

**Comment by cam72cam** [comment]
@chenzejun do you mind if I take on this issue as I'm already doing a lot of work in this area for #399?

**Comment by chenzejun** [comment]
@cam72cam Sure, I still haven't found a good approach yet, too much work around me these days :(

**Comment by cam72cam** [comment]
No problem, you have already helped out with a bunch in OpenTofu!
