### ISSUE TITLE
[Refactoring] Review and order locked struct fields

### ISSUE THREAD

**Issue by cam72cam** [opentofu/opentofu#1482]
As discussed in https://github.com/opentofu/opentofu/pull/1439#discussion_r1555971840, we want to reorganize field list to follow the "mutex hat" rule? I.e. placing mutexes on top of the fields they protect.

This should be reviewed throughout the codebase.

**Comment by 1garo** [comment]
I am new to the project but wanted to contribute, you thing it's okay for a newcomer to take this issue? I imagine that would change a lot of places, if okay I'm open to try it.

**Comment by cam72cam** [comment]
Sure, feel free to take a pass at it!

I've assigned the issue to you. Please take a quick look at our [contributing guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md#ive-been-assigned-an-issue-now-what) and let us know if you have any questions.

**Comment by 1garo** [comment]
> Sure, feel free to take a pass at it!
> 
> I've assigned the issue to you. Please take a quick look at our [contributing guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md#ive-been-assigned-an-issue-now-what) and let us know if you have any questions.

Thank you! I did take a look at the contributing guide and will start implementing today.
