### ISSUE TITLE
"Error: Insufficient features blocks" Is a terrible error message

### ISSUE THREAD

**Issue by ImIOImI** [opentofu/opentofu#1484]
### OpenTofu Version

```shell
OpenTofu v1.6.1
on linux_amd64
```

### Use Cases

When something is wrong with the provider reference in a resource the user often gets the following error:

```
╷
│ Error: Insufficient features blocks
│ 
│   on <empty> line 0:
│   (source code not available)
│ 
│ At least 1 "features" blocks are required.
╵
```

This is bad for two reasons:
1) there is no reference to the filename or line of code that causes the error
2) its very often wrong

For example. something as simple as the following code can cause the error:

```
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
    }
  }
}

provider "azurerm" {
  alias = "example"
  features {}

  subscription_id = var.subscription_id
  tenant_id       = var.tenant_id
}
```

Here, the problem is that the azurerm provider is aliased and there isn't an azurerm unaliased provider available. While this example is trivial, when a mistake is made buried several modules deep, the process to find what might cause the error is excruciating.

### Attempted Solutions

In a large codebase the "best" way to fix this error is to use `git bisect` and run the plan against various commits and try to narrow down the change that caused the error. If, for example, you introduce a lot of code all at once (perhaps by including a new module that has the error) the "best" way to find the error is to comment out code and gradually uncomment it and running plans to narrow down the root of the error.

### Proposal

This error is rather unhelpful, even for its intended use case, but let's separate the cases that this error protects against into 3 categories:
1) a provider is defined in the terraform block but no provider block is defined: Here I think the error should mention that the provider (in this case `azurerm`) is missing a configuration. Ideally the code reference would lead back to the provider definition in the terraform block
2) a provider block is defined, but the defined features are not sufficient: In this case the error should mention the inadiquate provider block and reference it in code
3) a resource doesn't have a defined provider (usually because all the providers are aliased) : In this case, the error message should mention the provider that is missing and point back to the resource that is causing the error

**Comment by ImIOImI** [comment]
This has been around for so long, I just assumed it was functioning as intended... but I think there's a strong argument that its a bug as well.

**Comment by ers81239** [comment]
I'm interested in taking a look at this issue.  At first glance, it doesn't seem that the phrase "feature blocks" occurs in the codebase, and the instances of "Insufficient" aren't related.    This is my first stab at contributing to OpenTofu, please point me in the right direction if you know it.

I did go look at the azurerm codebase and the message doesn't seem to originate there.  I did note that [azurerm #22133](https://github.com/hashicorp/terraform-provider-azurerm/issues/22133) is most likely a duplicate.

**Comment by cam72cam** [comment]
I've assigned you @ers81239, give it a spin.  I'll keep an eye on this issue if you have additional questions.

**Comment by cam72cam** [comment]
Hey @ers81239!  How's it going?  Do you need a hand with anything?

**Comment by ers81239** [comment]
I haven't been able to sort out how this code works. It does seem like we
are supposed to pass in additional range/context.

**Comment by cam72cam** [comment]
I took a look at this and came up with this so far:
```diff
diff --git a/internal/tofu/eval_provider.go b/internal/tofu/eval_provider.go
index 7b17369bf6..26f428d1b8 100644
--- a/internal/tofu/eval_provider.go
+++ b/internal/tofu/eval_provider.go
@@ -10,9 +10,11 @@ import (
        "log"
 
        "github.com/hashicorp/hcl/v2"
+       "github.com/zclconf/go-cty/cty"
 
        "github.com/opentofu/opentofu/internal/addrs"
        "github.com/opentofu/opentofu/internal/configs"
+       "github.com/opentofu/opentofu/internal/configs/hcl2shim"
        "github.com/opentofu/opentofu/internal/providers"
 )
 
@@ -40,7 +42,8 @@ func buildProviderConfig(ctx EvalContext, addr addrs.AbsProviderConfig, config *
                return inputBody
        default:
                log.Printf("[TRACE] buildProviderConfig for %s: no configuration at all", addr)
-               return hcl.EmptyBody()
+               addr := fmt.Sprintf("%s with no configuration", addr)
+               return hcl2shim.SynthBody(addr, make(map[string]cty.Value))
        }
 }
```

Due to how providers are handled within the code, there's no good place to suggest where the missing configuration should live.

Perhaps next steps could be to come up with example configurations for the 3 scenarios above and see if this code is sufficient?

**Comment by hassannmoussaa** [comment]
Is help needed here ? I would love to br assigned :)

**Comment by ers81239** [comment]
Yes, feel free to take this one over from me

**Comment by hassannmoussaa** [comment]
@cam72cam kindly assign me on this
