### ISSUE TITLE
Is it legal that terraform word is still used in naming? For example, cache folder, tfstate-file, lock-file (check the attached screenshot)

### ISSUE THREAD

**Issue by kolesaev** [opentofu/opentofu#1508]
### Did you test the state encryption?

Did not test

### Did you test the removed block?

Did not test

### Did you test the testing feature changes?

Did not test

### Did you test the built-in functions?

Did not test

### Did you test the CLI changes?

Did not test

### Would you like to add anything else?

I've been making a test of using opentofu instead of terraform. We use Gitlab-CI to execute our Plan, I forgot to check a new name of cache files, but any way tried to run our Apply job, and, I was surprised that caches are there in their old locations. After that I've pulled a public image with 1.7.0-alpha to check if it's moved to a new naming, then wrote a simpliest plan there, but it still has old naming.

![image](https://github.com/opentofu/opentofu/assets/31689563/2fa1c2b4-053f-4287-852d-b463dac75950)

**Comment by jamengual** [comment]
Using the name is not illegal in this case, so I do not see how this could be?

**Comment by cube2222** [comment]
Hey @kolesaev!

Based on our conversations with legal counsel we believe it's absolutely fine.
