### ISSUE TITLE
Support Generated Plan Files on Remote Backends

### ISSUE THREAD

**Issue by Jellayy** [opentofu/opentofu#1513]
### OpenTofu Version

```shell
OpenTofu v1.6.2
```

### Use Cases

Using `tofu plan -out=FILE` and `tofu apply FILE` is a pretty popular flow in Terraform and now I imagine in OpenTofu as well. Things like the [GitLab OpenTofu Component](https://gitlab.com/components/opentofu) are able to depend on this heavily as they use an HTTP backend.

I was looking to implement this to optimize some of the deploy pipelines I manage that use remote backends. These plan files allow you to skip the redundant plan phase that's run with each apply even when you use `--auto-approve`. This would be pretty helpful with some of the SaaS TACOS (such as Scalr) as you're billed on both runs and run minutes. Especially helpful in some of the workspaces I work with that have particularly large statefiles.

These files can also be converted to JSON with `tofu show` to generate change reports in things like GitLab merge requests.

Unfortunately, I've only tested this being currently supported in local, http, and s3 backends, not remote backends.

The OpenTofu documentation for both the [plan command](https://opentofu.org/docs/cli/commands/plan/) and the [apply command](https://opentofu.org/docs/cli/commands/apply/) state that: "You may want to use this two-step workflow when running OpenTofu in automation." I can't speak for other organizations, but I've found remote backends to be very popular in automated workflows so coverage of this feature in remote backends would likely be useful to a lot of users.

### Local Backend
Backend File:
```
none
```

Plan Output:
```shell
❯ tofu plan -out=tfplan

OpenTofu used the selected providers to generate the following execution plan. Resource actions are indicated with the
following symbols:
  + create

OpenTofu will perform the following actions:

  # random_pet.test will be created
  + resource "random_pet" "test" {
      + id        = (known after apply)
      + length    = 3
      + separator = "-"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + test_name = (known after apply)

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Saved the plan to: tfplan

To perform exactly these actions, run the following command to apply:
    tofu apply "tfplan"
```

### Remote Backend (hosted at Scalr.io)
Backend File:
```hcl
terraform {
  backend "remote" {
    hostname = "jellayy.scalr.io"
    organization = "test-env"

    workspaces {
      name = "tofu-test"
    }
  }
}
```

Plan Output:
```shell
❯ tofu plan -out=tfplan
╷
│ Error: Saving a generated plan is currently not supported
│
│ The "remote" backend does not support saving the generated execution plan locally at this time.
╵
```

### Proposal

Support for saving generated plan files on "remote" backends was also not present in Terraform, so this would be a new feature buildout that could help to differentiate OpenTofu from it's base.

This may also require collaboration from TACOS running in remote execution mode to make this file available for the Tofu CLI to pull down after a plan.

### References

This feature was also requested for Terraform in 2022 with some other valid usecases for the feature being described, but no progress seems to have been made:
- https://github.com/hashicorp/terraform/issues/32138

**Comment by cam72cam** [comment]
Documented why I assigned @ollevche a month ago, he is going to take a look at the difference between the cloud and remote backends and at their migration path.

**Comment by ollevche** [comment]
Hey @Jellayy, thank you for submitting the issue!

We recommend using the [cloud built-in integration](https://opentofu.org/docs/cli/cloud/settings/) instead of the remote backend. The cloud option includes an improved UX and more features, including support for plan files in both plan and apply commands.

Configuration for cloud backend is pretty similar, here is an updated version of your example:
```
terraform {
  cloud {
    hostname = "jellayy.scalr.io"
    organization = "test-env"

    workspaces {
      name = "tofu-test"
    }
  }
}
```

Please let us know if it covers your needs.
