### ISSUE TITLE
Extract string interpolation code as a standalone library

### ISSUE THREAD

**Issue by skyzyx** [opentofu/opentofu#1518]
### OpenTofu Version

```shell
N/A
```

### Use Cases

Was looking at the docs for [`templatestring()`](https://1-7-0-beta1.opentofu.pages.dev/docs/language/functions/templatestring/). For the code that parses string interpolation with custom constructs (e.g., `${ … }`) and statements (e.g., `for`, `join`), is that code still embedded deeply inside the codebase? Or is that easy to import as a standalone library?

Wanting to leverage this parsing from a provider, and don't see anything in the Terraform Plugin Framework that sounds like it matches.

### Attempted Solutions

Asking first before I go spelunking through the source code.

### Proposal

Proposal is to extract this code out into a standalone library that can be imported on its own. OpenTofu, as well providers and other software, would be able to import this Go library.

**Comment by cam72cam** [comment]
At it's core this a wrapper around hclsyntax.ParseTemplate.  The only major additions tofu makes are error handing around variables in expressions and handling templatefile recursion.

Perhaps you could give hclsyntax.ParseTemplate a spin and see how that works for your use case?

**Comment by cam72cam** [comment]
Closing this as even if we were to expose it as a library, it would not work easily with providers which use tftypes.
