### ISSUE TITLE
Refactor LockInfo ID generation

### ISSUE THREAD

**Issue by mikelolasagasti** [opentofu/opentofu#1523]
Current LockInfo ID generation in `internal/states/statemgr/locker.go` uses a UUID string created in a non-cryptographically secure way.

By refactoring to use the more performant and cryptographically safe `NewRandom()` from Google's uuid module the same behavior can be achieved.

**Comment by Evi1Pumpkin** [comment]
Thank you for opening this issue!
The core team discussed and decided to close it because of the following reasons:
1. This is, at best, a very minor improvement.
2. Currently, we don't have an easy way to test the performance improvement.

We still thank you for your time and contribution.
