### ISSUE TITLE
Cannot use variable as input for passphrase

### ISSUE THREAD

**Issue by david-garcia-garcia** [opentofu/opentofu#1538]
### Did you test the provider-defined functions?

Did not test

### Did you test the `for_each` on the import block?

Did not test

### Did you test the state encryption?

Tested, did not work / had problems

### Additional feedback / details on the state encryption

Using this in a terraform file:

```
variable "STATE_ENCRYPTION_KEY" {
  type = string
}

terraform {
  encryption {
    key_provider "pbkdf2" "my_passphrase" {
      passphrase = var.STATE_ENCRYPTION_KEY
    }
    method "aes_gcm" "my_method" {
      keys = key_provider.pbkdf2.my_passphrase
    }
    method "unencrypted" "migration" {
    }
    state {
      method = method.aes_gcm.my_method
      #enforced = true
      fallback {
        method = method.unencrypted.migration
      }
    }
  }
}
```

yields

```
│ Error: Invalid key_provider reference
│
│   on main.tf line 21, in terraform:
│   21:       passphrase = var.STATE_ENCRYPTION_KEY
│
│ Expected reference in form key_provider.type.name
```

if i hardcode the passphrase it works.

### Did you test the removed block?

Did not test

### Did you test the testing feature changes?

Did not test

### Did you test the built-in functions?

Did not test

### Did you test the CLI changes?

Did not test

**Comment by cam72cam** [comment]
#1042 would provide a fairly straightforward path here once it's implemented.

**Comment by cam72cam** [comment]
We also need to update the documentation for TF_ENCRYPTION, see https://github.com/opentofu/opentofu/pull/1644

**Comment by cam72cam** [comment]
Given that encryption is required to read the state, it's a bit of a chicken and egg problem here.  We are adding support for passing in secrets via -var and -var-file per the PR linked above.  If you don't want to deal with the command line, TF_ENCRYPTION can provide a partial config that's ephemeral which defines the key-provider.
