### ISSUE TITLE
Docker Container Instructions Incomplete / Missing Vital Information 

### ISSUE THREAD

**Issue by My-Random-Thoughts** [opentofu/opentofu#1556]
### OpenTofu Version

```shell
"ghcr.io/opentofu/opentofu:latest"
```

### OpenTofu Configuration Files

None

### Debug Output

N/A

### Expected Behavior

Following the instructions exactly at https://opentofu.org/docs/intro/install/docker/ results in the following message...

    OpenTofu initialized in an empty directory!

    The directory has no OpenTofu configuration files. You may begin working
    with OpenTofu immediately by creating OpenTofu configuration files.

There is nothing in the documentation about this

### Actual Behavior

Any and all default configuration should be automatically created or at least have questions asked to create them.

### Steps to Reproduce

1. docker pull ghcr.io/opentofu/opentofu:latest
2. docker run \
    --workdir=/srv/workspace \
    --mount type=bind,source=.,target=/srv/workspace \
    ghcr.io/opentofu/opentofu:latest \
    init

**Comment by edualb** [comment]
Hello @My-Random-Thoughts and @janosdebugs, I am interesting in contribute with it. I have created a fork and updated the content of the documentation:
![Screenshot from 2024-06-04 20-09-46](https://github.com/opentofu/opentofu/assets/39157101/a2469984-6b91-42b0-9e7c-0c6716563426)

Do you think it is more clear? Any feedback?
