### ISSUE TITLE
Broken links on website

### ISSUE THREAD

**Issue by janosdebugs** [opentofu/opentofu#1563]
The website build has a few broken links that need fixing:

```
website-1  | - Broken link on source page path = /docs/cli/cloud/migrating/:
website-1  |    -> linking to /slack/
website-1  |    -> linking to ../../language/settings/backends/configuration.mdx/ (resolved as: /docs/cli/language/settings/backends/configuration.mdx/)
```

This needs to be backported to v1.7 and v1.6.

**Comment by phoenixxbasit** [comment]
Can you assign this issue to me

**Comment by cam72cam** [comment]
Sure, thanks for having a go at it @phoenixxbasit!

**Comment by phoenixxbasit** [comment]
Can I get a more context regarding this issue. Any specifics?

**Comment by jiawei-hong** [comment]
Hi @phoenixxbasit, are you still working on this issue? If not, I think @janosdebugs can be assigned to me

**Comment by phoenixxbasit** [comment]
@jiawei-hong I am will push the update on weekend

**Comment by cam72cam** [comment]
@jiawei-hong are you up for taking a shot at this?

**Comment by jiawei-hong** [comment]
@cam72cam I think I can try it！Thank you 👍

**Comment by cam72cam** [comment]
Thanks @jiawei-hong!

**Comment by cam72cam** [comment]
```
Run npm run lint

> website@0.0.0 lint
> eslint --cache "**/*.{js,jsx,ts,tsx}"

Warning: React version not specified in eslint-plugin-react settings. See https://github.com/jsx-eslint/eslint-plugin-react#configuration .

/home/runner/work/opentofu.org/opentofu.org/src/components/Accordion/Item.tsx
Warning:   98:6  warning  React Hook useEffect has missing dependencies: 'id', 'isHashEnabled', and 'location.hash'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

/home/runner/work/opentofu.org/opentofu.org/src/theme/DocItem/Layout.tsx
Error:   5:8  error  'DocVersionBadge' is defined but never used  @typescript-eslint/no-unused-vars

/home/runner/work/opentofu.org/opentofu.org/versioned_docs/version-main/intro/install/buildkite.jsx
Error:   11:16  error  Component definition is missing display name  react/display-name
Error:   11:18  error  'children' is defined but never used          @typescript-eslint/no-unused-vars
Error:   11:28  error  'color' is defined but never used             @typescript-eslint/no-unused-vars

/home/runner/work/opentofu.org/opentofu.org/versioned_docs/version-v1.6/intro/install/buildkite.jsx
Error:   4:16  error  Component definition is missing display name  react/display-name
Error:   4:18  error  'children' is defined but never used          @typescript-eslint/no-unused-vars
Error:   4:28  error  'color' is defined but never used             @typescript-eslint/no-unused-vars

/home/runner/work/opentofu.org/opentofu.org/versioned_docs/version-v1.7/intro/install/buildkite.jsx
Error:   11:16  error  Component definition is missing display name  react/display-name
Error:   11:18  error  'children' is defined but never used          @typescript-eslint/no-unused-vars
Error:   11:28  error  'color' is defined but never used             @typescript-eslint/no-unused-vars

✖ 11 problems (10 errors, 1 warning)

Error: Process completed with exit code 1
```

**Comment by jiawei-hong** [comment]
> This is not resolved yet, it needs the other links fixed too.

Hi, @janosdebugs

I'm a little unsure. It seems to me that if I write `[OpenTofu Slack](/slack/)`, mdx will think that it is looking for `slack.mdx` file instead of the https://opentofu.org/slack/ link. , do you mind if I use the OpenTofu full slack link directly?

**Comment by jiawei-hong** [comment]
> ```
> Run npm run lint
> 
> > website@0.0.0 lint
> > eslint --cache "**/*.{js,jsx,ts,tsx}"
> 
> Warning: React version not specified in eslint-plugin-react settings. See https://github.com/jsx-eslint/eslint-plugin-react#configuration .
> 
> /home/runner/work/opentofu.org/opentofu.org/src/components/Accordion/Item.tsx
> Warning:   98:6  warning  React Hook useEffect has missing dependencies: 'id', 'isHashEnabled', and 'location.hash'. Either include them or remove the dependency array  react-hooks/exhaustive-deps
> 
> /home/runner/work/opentofu.org/opentofu.org/src/theme/DocItem/Layout.tsx
> Error:   5:8  error  'DocVersionBadge' is defined but never used  @typescript-eslint/no-unused-vars
> 
> /home/runner/work/opentofu.org/opentofu.org/versioned_docs/version-main/intro/install/buildkite.jsx
> Error:   11:16  error  Component definition is missing display name  react/display-name
> Error:   11:18  error  'children' is defined but never used          @typescript-eslint/no-unused-vars
> Error:   11:28  error  'color' is defined but never used             @typescript-eslint/no-unused-vars
> 
> /home/runner/work/opentofu.org/opentofu.org/versioned_docs/version-v1.6/intro/install/buildkite.jsx
> Error:   4:16  error  Component definition is missing display name  react/display-name
> Error:   4:18  error  'children' is defined but never used          @typescript-eslint/no-unused-vars
> Error:   4:28  error  'color' is defined but never used             @typescript-eslint/no-unused-vars
> 
> /home/runner/work/opentofu.org/opentofu.org/versioned_docs/version-v1.7/intro/install/buildkite.jsx
> Error:   11:16  error  Component definition is missing display name  react/display-name
> Error:   11:18  error  'children' is defined but never used          @typescript-eslint/no-unused-vars
> Error:   11:28  error  'color' is defined but never used             @typescript-eslint/no-unused-vars
> 
> ✖ 11 problems (10 errors, 1 warning)
> 
> Error: Process completed with exit code 1
> ```

Hi, @cam72cam  I could be wrong, it doesn't look like this is happening because of the Slack link I changed?

**Comment by cam72cam** [comment]
Those are other issues that need to be fixed as part of this issue, the slack link was only the first in the list

**Comment by cam72cam** [comment]
@jiawei-hong looks like there are still some issues:
```
 ✔ Container opentofuorg-website-1  Recreated                                                                                                                                                                                                                                                                          0.1s 
Attaching to website-1
website-1  | 
website-1  | > website@0.0.0 lint
website-1  | > eslint --cache "**/*.{js,jsx,ts,tsx}"
website-1  | 
website-1  | Warning: React version not specified in eslint-plugin-react settings. See https://github.com/jsx-eslint/eslint-plugin-react#configuration .
website-1  | 
website-1  | /work/versioned_docs/version-main/intro/install/buildkite.jsx
website-1  |   11:16  error  Component definition is missing display name  react/display-name
website-1  |   11:18  error  'children' is defined but never used          @typescript-eslint/no-unused-vars
website-1  |   11:28  error  'color' is defined but never used             @typescript-eslint/no-unused-vars
website-1  | 
website-1  | /work/versioned_docs/version-v1.6/intro/install/buildkite.jsx
website-1  |   4:16  error  Component definition is missing display name  react/display-name
website-1  |   4:18  error  'children' is defined but never used          @typescript-eslint/no-unused-vars
website-1  |   4:28  error  'color' is defined but never used             @typescript-eslint/no-unused-vars
website-1  | 
website-1  | /work/versioned_docs/version-v1.7/intro/install/buildkite.jsx
website-1  |   11:16  error  Component definition is missing display name  react/display-name
website-1  |   11:18  error  'children' is defined but never used          @typescript-eslint/no-unused-vars
website-1  |   11:28  error  'color' is defined but never used             @typescript-eslint/no-unused-vars
website-1  | 
website-1  | ✖ 9 problems (9 errors, 0 warnings)
```

**Comment by jiawei-hong** [comment]
@cam72cam I see that the `opentofu-repo` link of `https://github.com/opentofu/opentofu.org` is old.

Is there any document that allows me to update these submodule files?

**Comment by cam72cam** [comment]
Ah, my mistake.  I'll take care of it!

**Comment by jiawei-hong** [comment]
@cam72cam Thank you ❤️
