### ISSUE TITLE
Migration guide index page doesn't have a title

### ISSUE THREAD

**Issue by ghost** [opentofu/opentofu#1565]
The migration guide index page doesn't have a title:

![image](https://github.com/opentofu/opentofu/assets/86970079/e1f9e3bf-a9d9-4f4f-9590-ac5de940faed)

This needs to be backported into 1.7 and 1.6

**Comment by andrewpollack** [comment]
Happy to take a crack at this

**Comment by andrewpollack** [comment]
Which migration guide is the issue's screenshot referencing? 
Checked https://opentofu.org/docs/v1.6/intro/migration/ , and title looked setup appropriately:
<img width="1482" alt="Screenshot 2024-05-03 at 2 09 54 PM" src="https://github.com/opentofu/opentofu/assets/24868505/455955d3-321b-4392-8fff-170caad90e58">
