### ISSUE TITLE
Make persistence interval configurable for the remote state backend

### ISSUE THREAD

**Issue by alexott** [opentofu/opentofu#1568]
### OpenTofu Version

```shell
1.7.0
```

### Use Cases

When state size increases, the persistence of the state becomes a bottleneck as it happens synchronously. Currently, the persist interval is [hardcoded in local apply backend](https://github.com/opentofu/opentofu/blob/main/internal/backend/local/backend_apply.go#L87) to 20 seconds, and as state size increases, it becomes a significant amount of time spent on the persisting. 

For remote apply backend it's possible to disable intermediate persistence completely, but it's not possible to do for the local apply backend.

### Attempted Solutions

I have code changes that allow to specify a new persist interval via an environment variable.

### Proposal

Make the persist interval configurable (or allow you to disable it completely) instead of using a hardcoded value. Open question: How to specify it: Is it enough to provide support via an environment variable, or will we need to add support for the command-line option?

Also, maybe it makes sense to make actual cloud write async?

**Comment by alexott** [comment]
My issue is primarily about the `remote` state store (`azurerm`, `s3`, etc.) - as I remember (at least it was half a year ago), the `local` state store actually doesn't use persist interval and instead writes full state after each change (this is significant overhead, but should be handled as a separate issue).

If it's ok, I can submit a simple PR that will do the following:

- if an environment variable is set, use its value to configure the persist interval (this part is isolated from the actual store backend implementation).
- (optionally) maybe disable intermediate persist if environment variable is set to something like `-1`

**Comment by cam72cam** [comment]
I think opening up a draft PR is fine, and that initial proposal sounds good to me.  Please note that the core team currently triages issues once a week (Thursdays) and tend to typically accept that point.

**Comment by alexott** [comment]
Thank you for your guidance, Christian! I'll open PR today or tomorrow.

**Comment by alexott** [comment]
Thank you! I'll make the changes - I really thought about using that default value (20 seconds) as a lower bound...

**Comment by alexott** [comment]
I made default interval (20) as lowest possible value, so people can only use bigger values
