### ISSUE TITLE
Pretty-printed JSON representation of a state increases file size by ~20-25%

### ISSUE THREAD

**Issue by alexott** [opentofu/opentofu#1593]
### OpenTofu Version

```shell
1.8
```

### Use Cases

We have a few use cases when the state size is very big, and we were looking into optimizing performance. What I noticed is that by default, we're using pretty-printed JSON when storing the state, and the resulting file size is much bigger than if we use compact representation, and this make read/write of state slower, not taking into account increased storage and egress costs when using cloud backends.

For example, here is comparison of the state with ~70k objects - original state (`mkdirs.tfstate`) is converted into compact representation by running `jq -c .` on it.

```
84096 -rw-rw-r--@ 1 alex  staff  42996911 Apr 27 10:53 mkdirs-compact.tfstate
114112 -rw-r--r--@ 1 alex  staff  57680266 Apr 27 10:50 mkdirs.tfstate
```

### Attempted Solutions

.

### Proposal

Enable compact representation by default. I can make PR to support it if it's ok

**Comment by Yantrio** [comment]
There was a discussion around something like this here: https://github.com/opentofu/opentofu/pull/397

I still think that this should be an opt-in feature as per my comment here: https://github.com/opentofu/opentofu/pull/397#issuecomment-1719321845
