### ISSUE TITLE
s3 state backend no longer honours `https_proxy` environment variable

### ISSUE THREAD

**Issue by maxb** [opentofu/opentofu#1594]
### OpenTofu Version

```shell
OpenTofu v1.6.2
on linux_amd64
```

### OpenTofu Configuration Files

```hcl
terraform {
  backend "s3" {
    # A configuration using Amazon S3
  }
}
```

### Debug Output

Not needed

### Expected Behavior

When operating in an environment where access to the internet is via a proxy server, and with an `https_proxy` environment variable defined, OpenTofu should use the configured proxy server, **as HashiCorp Terraform v1.5.7 correctly does**.

### Actual Behavior

OpenTofu disregards the environment variable. It tries to reach S3 directly, and eventually times out and fails.

### Steps to Reproduce

Do any command which tries to talk to the state backend (e.g. `tofu init`, `tofu plan`) in an environment with an `s3` backend configured, a `https_proxy` environment variable set, and no access to the S3 service other than through the proxy.

### Additional Context

The environment variables `http_proxy`, `HTTP_PROXY`, etc. are not well standardized. The blog post https://about.gitlab.com/blog/2021/01/27/we-need-to-talk-no-proxy/ provides a good survey of the state of the world.

One of the conclusions there is that **the lowercased variables are preferred by many systems**.

OpenTofu is currently breaking from the prevailing direction by honouring the uppercased variable names exclusively, and this **differs from HashiCorp Terraform** behaviour.

For consistency with other widely deployed software, including HashiCorp Terraform, I believe OpenTofu should honour the lowercased versions of the proxy environment variables.

### References

Looking through Git history, it appears likely this was introduced by #770.

**Comment by maxb** [comment]
#896 concerns adding .tf file attributes - but my report here is not about that, but rather environment variables of the same name.

I believe the correct thing to do here would be to call golang.org/x/net/http/httpproxy.FromEnvironment() instead of accessing particular environment variables manually.

This will ensure this code inherits the default Go behaviour regarding which environment variables to use, which users may expect and be familiar with from other Go programs.

You can then apply whatever additional overriding or defaulting is desired based on .tf file attributes to the values obtained from FromEnvironment().

This matches the behaviour implemented in the underlying code github.com/hashicorp/aws-sdk-go-base/v2/internal/config.(Config).HTTPTransportOptions() when zero-values are passed in for the proxy settings, so will provide the consistency of having the code applying configuration based on .tf file attributes only affect the resulting behaviour if those attributes are set.

**Comment by rishabhToshniwal** [comment]
I too facing similar issue with open tofu 1.6.0 , where my proxies(http_proxy,https_proxy & no_proxy) are set still the request tries to go directly and getting timeout. I checked with curl -v on the same machine and it worked via proxy. 
**https response error StatusCode: 0, RequestID: , request send failed, Post
"https://dynamodb.us-east-1.amazonaws.com/": dial tcp 3.218.181.157:443: i/o timeout**

**Comment by rishabhToshniwal** [comment]
Hi @janosdebugs ,

I tried to set the proxy variable to the same value as my http_proxy, but still failed with the same issue.
Let me know this is what you asked for ?

**backend.tf**

terraform {
  backend "s3" {
    bucket         = "tfstatefiles-strxxx-dev-XXXXXXX-eu-west-1"
    dynamodb_table = "terraform-locks"
    encrypt        = true
    key            = "cid-strxxx/terraform.tfstate"
    region         = "eu-west-1"
  }
}

**Proxies**
export http_proxy=http://myproxy.shared-services.local:8080
export https_proxy=http://myproxy.shared-services.local:8080
export proxy=http://myproxy.shared-services.local:8080

**Comment by maxb** [comment]
> Specifically, it seems to me that the `HTTPProxyMode` is stuck in `HTPProxyModeLegacy`, which links together `http_proxy` and `https_proxy`, but the OpenTofu code has been changed to move the environment variable handling to the new behavior without changing this setting.

I think my bug report has been misunderstood - this not the issue at all.

The real issue is this code:
https://github.com/opentofu/opentofu/blob/07a9185767faab19ff466e2b8d2898cc75503207/internal/backend/remote-state/s3/backend.go#L750-L755

The comment says "we don't need to read env variables explicitly because they are read implicitly by aws-sdk-base-go" and that's a true statement. But the code then goes on to **read the env variables explicitly anyway**, doing so in an incorrect way that doesn't even consider `http_proxy` or `https_proxy`.

Actually, looking at this code again, I think the fix could be as simple as deleting the lines of code quoted above, and instead, **conditionally** filling in the fields in the `Config` struct:
```
	if httpProxy, ok := stringAttrOk(obj, "http_proxy"); ok {
		cfg.HTTPProxy = aws.String(httpProxy)
	}
```
and repeat for the other proxy settings.

The important thing is that you leave the `Config` struct fields set to their zero values unless the user is specifically providing an override in the .tf file attribute, so that the underlying library then takes care of applying expected defaulting from environment variables, following its normal logic.

**Comment by cam72cam** [comment]
@janosdebugs is out today, but will be back tomorrow.  I know he was focused on improving testing to allow for better coverage of this backend overall.

**Comment by maxb** [comment]
> Hey folks, after a lot of testing in #1676, it seems that setting `HTTP_PROXY` and `HTTPS_PROXY` works, but `http_proxy` and `https_proxy` doesn't. I think it is prudent to introduce a fallback here. :)

I am confused why a lot of testing was required to discover the problem that I originally reported? It's quite an unusual turn of phrase to say it's "prudent" to fix a bug!
