### ISSUE TITLE
Create releases for all platforms (Alpine, Debian, Windows, etc.)

### ISSUE THREAD

**Issue by RLRabinowitz** [opentofu/opentofu#160]
After creating an initial release process, and creating OpenTF binaries, we'd like to add support to all other platforms (or at least the major ones)

Alpine, Debian, Windows, etc.

**Comment by thschue** [comment]
We could do at least deb, rpm and APL with go-releaser (not sure about windows). Should I take this over?

**Comment by cube2222** [comment]
Hey, sure @thschue, that would be great!

I'll assign the issue to you.

That said, I'm not sure what an APL archive is? I **think** we only need deb and rpm archives for now. Ideally, you could prepare the packaging process, and we can then set up credentials for publishing them (we have an account ready on https://packagecloud.io).

(btw. there is already a goreleaser file that does the build process and docker images)

**Comment by thschue** [comment]
sorry, this was a typo :-) I meant an apk package ...

**Comment by cube2222** [comment]
Ah, makes sense!

**Comment by JonZeolla** [comment]
I don’t see anything under https://github.com/opentffoundation/opentf/releases

Any reason not to do that also?  I would like to bundle this in a security tool I maintain but I prefer to auto update by monitoring tags or releases.

If this is intentionally not happening, is there a system of record for release versions that include some kind of latest stable metadata?

**Comment by cube2222** [comment]
Hey @JonZeolla!

The releases will be there, we just haven't made any yet.

**Comment by JonZeolla** [comment]
Got it ok thanks
