### ISSUE TITLE
Github action to update top issues fails daily on forks.

### ISSUE THREAD

**Issue by IgnorantSapient** [opentofu/opentofu#1602]
### OpenTofu Version

```shell
N.A
```

### OpenTofu Configuration Files

N.A

### Debug Output

N.A

### Expected Behavior

The GitHub action should not fail on forks.

### Actual Behavior

https://github.com/IgnorantSapient/opentofu/actions/runs/8937484006/workflow

Every morning I wake up to CI pipeline failure notifications and its pollution

### Steps to Reproduce

Fork the opentofu repo.
Wait for cron job to trigger every day.

**Comment by virtualroot** [comment]
Example from today: https://github.com/virtualroot/opentofu/actions/runs/8967363901
