### ISSUE TITLE
encryption method does not change if there is nothing to apply

### ISSUE THREAD

**Issue by aviau** [opentofu/opentofu#1606]
### OpenTofu Version

```shell
1.7.0
```

### Expected Behavior

When running terraform apply, the encryption method should change from `fallback` to `method` even if there is nothing to change.

I had to volountary trigger stage changes by adding bogus outputs to convince it to apply the encryption change.

This is an annoyance more than a serious bug, but I think its important enough to be fixed :)

**Comment by StephanHCB** [comment]
This is actually mentioned in the [State Encryption RFC](https://github.com/opentofu/opentofu/issues/874).

> Note: Depending on situation, you may need to make some change, e.g. to a null_resource, to force a state write.

It is, unfortunately, standard behaviour that no change means no state write. We've had fun with this behaviour when CISO demanded key rotation.

@janosdebugs might be a viable enhancement to have a parameter in the encryption config to force a state write.

**Comment by ollevche** [comment]
Hey @aviau! Could you please provide a test case as an example?

I tried to reproduce your issue with the given `main.tf`:

```hcl
terraform {
  encryption {
    key_provider "pbkdf2" "mykey" {
      passphrase = "imnotgonnachangeyou"
    }

    method "aes_gcm" "new_method" {
      keys = key_provider.pbkdf2.mykey
    }

    method "unencrypted" "migrate" {}

    state {
      method = method.aes_gcm.new_method
      fallback {
        method = method.unencrypted.migrate
      }
    }
  }
}

resource "null_resource" "example-1" {
}
```

I'm able to trigger state write by switching methods in `state` target block. Here is the output from running `tofu apply`:

<img width="883" alt="Screenshot 2024-06-13 at 13 29 03" src="https://github.com/opentofu/opentofu/assets/35274215/66beb945-b9a4-4a29-8e0f-2d7547e1e6d8">

**Comment by cam72cam** [comment]
@ollevche does the state file's encryption change after that method?

**Comment by ollevche** [comment]
@cam72cam yep, it goes from plaintext to encrypted and vice versa

**Comment by cam72cam** [comment]
Hmm, I wonder if that's the case for all backends or just local file?

**Comment by ollevche** [comment]
@cam72cam yep, it doesn't work for an S3 bucket as a backend.

> might be a viable enhancement to have a parameter in the encryption config to force a state write.

I think this is a valid suggestion in that scenario.

**Comment by ollevche** [comment]
The core team discussed the issue at a triage meeting and we agree it should be fixed. However, we are not sure what solution fits best so we need to gather more related use cases and generic feedback from the community.

Here are a couple of potential solutions discussed:
* automatically detect changes in encryption configuration and force state write if needed (can be a bit complex task)
* allow users to set a flag to force trigger state write (simple implementation, not as good from the UX perspective)

**Comment by aviau** [comment]
I think this matters mostly when you are migrating from one encryption scheme to another, which is rare.

Something like `tofu apply -force-reencrypt` would be fine with me.

**Comment by networkhermit** [comment]
Migrating between encryption scheme may not be rare if regular key rotation is required.

I think adding an explicit flag for `apply` to force state write is intuitive (if automatically detect changes in encryption configuration is too hard), but I'm not sure if there are other use cases except reencryption/unencryption, if that is true then `-force-state-write` might be more generic.

P.S.

Is it possible to use [`terraform_data`](https://opentofu.org/docs/language/resources/tf-data/#example-usage-null_resource-replacement) as an alternative workaround besides `null_resource`? I don't have any experience with these resources but I do hope to avoid an provider to manage.

**Comment by Carrvin** [comment]
Adding an output worked for me. Removed it after the migration took place.

```terraform
output "tofu_state_encryption_migrate" {
  value = "We need a change for tofu to be able to migrate the state encryption."
}
```
