### ISSUE TITLE
OpenTofu 1.7 crash when using without state file

### ISSUE THREAD

**Issue by DamianJarzebowski** [opentofu/opentofu#1613]
### OpenTofu Version

```shell
OpenTofu v1.7.0
on linux_amd64
+ provider registry.opentofu.org/hashicorp/azurerm v3.102.0
+ provider registry.opentofu.org/hashicorp/local v2.5.1
+ provider registry.opentofu.org/hashicorp/null v3.2.2
+ provider registry.opentofu.org/hashicorp/tls v4.0.5
```

### OpenTofu Configuration Files

provider "azurerm" {
  features {}
}

terraform {
  backend "inmem" {}
}

### Debug Output

!!!!!!!!!!!!!!!!!!!!!!!!!!! OPENTOFU CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

OpenTofu crashed! This is always indicative of a bug within OpenTofu.
Please report the crash with OpenTofu[1] so that we can fix this.

When reporting bugs, please include your OpenTofu version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/opentofu/opentofu/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! OPENTOFU CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 634 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
        runtime/debug/stack.go:16 +0x13
github.com/opentofu/opentofu/internal/logging.panicHandler({0x2d6afc0, 0x5222870}, {0xc00091d800, 0x49d, 0x800})
        github.com/opentofu/opentofu/internal/logging/panic.go:96 +0xe5
github.com/opentofu/opentofu/internal/tofu.(*Graph).walk.PanicHandlerWithTraceFn.func2()
        github.com/opentofu/opentofu/internal/logging/panic.go:82 +0x90
panic({0x2d6afc0?, 0x5222870?})
        runtime/panic.go:920 +0x270
github.com/opentofu/opentofu/internal/states/statefile.writeStateV4(0xc0007c4da0, {0x39a3860, 0xc001bf5170}, {0x0, 0x0})
        github.com/opentofu/opentofu/internal/states/statefile/version4.go:439 +0xa34
github.com/opentofu/opentofu/internal/states/statefile.Write(0x39a5460?, {0x39a3860?, 0xc001bf5170?}, {0x0?, 0x0?})
        github.com/opentofu/opentofu/internal/states/statefile/write.go:21 +0x4b
github.com/opentofu/opentofu/internal/states/remote.(*State).PersistState(0xc000993650, 0x7febb68257c0?)
        github.com/opentofu/opentofu/internal/states/remote/state.go:224 +0x6fc
github.com/opentofu/opentofu/internal/backend/local.(*StateHook).PostStateUpdate(0xc0006a9810, 0xc001bf4180?)
        github.com/opentofu/opentofu/internal/backend/local/hook_state.go:84 +0x26e
github.com/opentofu/opentofu/internal/tofu.updateStateHook.func1({0x39f0308?, 0xc0006a9810?})
        github.com/opentofu/opentofu/internal/tofu/update_state_hook.go:21 +0x28
github.com/opentofu/opentofu/internal/tofu.(*BuiltinEvalContext).Hook(0xc000e051f0?, 0xc001cd08b0)
        github.com/opentofu/opentofu/internal/tofu/eval_context_builtin.go:107 +0x82
github.com/opentofu/opentofu/internal/tofu.updateStateHook({0x39fc510, 0xc00097a200})
        github.com/opentofu/opentofu/internal/tofu/update_state_hook.go:20 +0xd4
github.com/opentofu/opentofu/internal/tofu.(*NodeApplyableResourceInstance).managedResourceExecute(0xc000e48080, {0x39fc510, 0xc00097a200})
        github.com/opentofu/opentofu/internal/tofu/node_resource_apply_instance.go:380 +0x1b87
github.com/opentofu/opentofu/internal/tofu.(*NodeApplyableResourceInstance).Execute(0x7febb66af8f0?, {0x39fc510?, 0xc00097a200?}, 0x60?)
        github.com/opentofu/opentofu/internal/tofu/node_resource_apply_instance.go:147 +0x9a
github.com/opentofu/opentofu/internal/tofu.(*ContextGraphWalker).Execute(0xc0015b6fc0, {0x39fc510, 0xc00097a200}, {0x7febb68be698, 0xc000e48080})
        github.com/opentofu/opentofu/internal/tofu/graph_walk_context.go:144 +0xbe
github.com/opentofu/opentofu/internal/tofu.(*Graph).walk.func1({0x31fb4e0, 0xc000e48080})
        github.com/opentofu/opentofu/internal/tofu/graph.go:86 +0x370
github.com/opentofu/opentofu/internal/dag.(*Walker).walkVertex(0xc00010d080, {0x31fb4e0, 0xc000e48080}, 0xc000df4480)
        github.com/opentofu/opentofu/internal/dag/walk.go:386 +0x2e5
created by github.com/opentofu/opentofu/internal/dag.(*Walker).Update in goroutine 231
        github.com/opentofu/opentofu/internal/dag/walk.go:309 +0xde8
With go-routine called from:
goroutine 231 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x5e
github.com/opentofu/opentofu/internal/logging.PanicHandlerWithTraceFn(...)
        github.com/opentofu/opentofu/internal/logging/panic.go:72
github.com/opentofu/opentofu/internal/tofu.(*Graph).walk(0xc001594400, {0x39de008, 0xc0015b6fc0})
        github.com/opentofu/opentofu/internal/tofu/graph.go:51 +0x3a
github.com/opentofu/opentofu/internal/tofu.(*Graph).Walk(...)
        github.com/opentofu/opentofu/internal/tofu/graph.go:40
github.com/opentofu/opentofu/internal/tofu.(*Context).walk(0xc001508fb0?, 0xc001750480?, 0xa0?, 0xc001740d98?)
        github.com/opentofu/opentofu/internal/tofu/context_walk.go:58 +0x11c
github.com/opentofu/opentofu/internal/tofu.(*Context).Apply(0xc00060cf30, 0xc001750480, 0xc0007a1ea0)
        github.com/opentofu/opentofu/internal/tofu/context_apply.go:63 +0x471
github.com/opentofu/opentofu/internal/backend/local.(*Local).opApply.func2()
        github.com/opentofu/opentofu/internal/backend/local/backend_apply.go:241 +0xec
created by github.com/opentofu/opentofu/internal/backend/local.(*Local).opApply in goroutine 13
        github.com/opentofu/opentofu/internal/backend/local/backend_apply.go:237 +0x1158

### Expected Behavior

Should not crash on the end run tofu.

### Actual Behavior

Hello,

I am running tofu inside tofu with local exec in main tf file to generate keys and certs for my configuration. I did it without state file using "inmem" config just running second run tofu inside this first. I discovered that this configuration report bug on the end and this bug stopped my main tofu run. I solve problem just run tofu with creating state and delete him in exec but it is not solution which I want :)

### Steps to Reproduce

tofu init
tofu apply

**Comment by cam72cam** [comment]
Will do, this is my top priority for tomorrow!

**Comment by cam72cam** [comment]
Found the issue, inmem was not using a constructor for the remote.State struct init, which was missed during refactoring as all other locations were using the constructor.
