### ISSUE TITLE
tofu force-unlock <lock_id> bug

### ISSUE THREAD

**Issue by DamianJarzebowski** [opentofu/opentofu#1625]
### OpenTofu Version

```shell
OpenTofu v1.7.0
on linux_amd64
+ provider registry.opentofu.org/hashicorp/kubernetes v2.29.0
```

### OpenTofu Configuration Files

```hcl
...tofu config...
```

### Debug Output

tofu force-unlock d475bb4c-506e-d6d5-2b13-15b92b319368

!!!!!!!!!!!!!!!!!!!!!!!!!!! OPENTOFU CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

OpenTofu crashed! This is always indicative of a bug within OpenTofu.
Please report the crash with OpenTofu[1] so that we can fix this.

When reporting bugs, please include your OpenTofu version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/opentofu/opentofu/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! OPENTOFU CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
        runtime/debug/stack.go:16 +0x13
github.com/opentofu/opentofu/internal/logging.panicHandler({0x2d6afc0, 0x5222870}, {0x0, 0x0, 0x0})
        github.com/opentofu/opentofu/internal/logging/panic.go:96 +0xe5
github.com/opentofu/opentofu/internal/logging.PanicHandler()
        github.com/opentofu/opentofu/internal/logging/panic.go:51 +0x88
panic({0x2d6afc0?, 0x5222870?})
        runtime/panic.go:920 +0x270
github.com/opentofu/opentofu/internal/states/statefile.Read({0x39a3880?, 0xc000996240?}, {0x0, 0x0})
        github.com/opentofu/opentofu/internal/states/statefile/read.go:79 +0x165
github.com/opentofu/opentofu/internal/states/remote.(*State).refreshState(0xc000a91420)
        github.com/opentofu/opentofu/internal/states/remote/state.go:167 +0x11c
github.com/opentofu/opentofu/internal/states/remote.(*State).RefreshState(0xc0002b3b80?)
        github.com/opentofu/opentofu/internal/states/remote/state.go:147 +0x79
github.com/opentofu/opentofu/internal/backend/remote-state/azure.(*Backend).StateMgr(0xc00004f920, {0x3230364, 0x7})
        github.com/opentofu/opentofu/internal/backend/remote-state/azure/backend_state.go:104 +0x305
github.com/opentofu/opentofu/internal/backend/local.(*Local).StateMgr(0x0?, {0x3230364?, 0xc00096e420?})
        github.com/opentofu/opentofu/internal/backend/local/backend.go:252 +0x3d6
github.com/opentofu/opentofu/internal/command.(*UnlockCommand).Run(0xc00085d180, {0xc0000721a0?, 0xffffffffffffffff?, 0x0?})
        github.com/opentofu/opentofu/internal/command/unlock.go:82 +0x675
github.com/mitchellh/cli.(*CLI).Run(0xc000a9a140)
        github.com/mitchellh/cli@v1.1.5/cli.go:262 +0x5b8
main.realMain()
        github.com/opentofu/opentofu/cmd/tofu/main.go:347 +0x206b
main.main()
        github.com/opentofu/opentofu/cmd/tofu/main.go:66 +0x13

### Expected Behavior

Just unlock my state :)

### Actual Behavior

error

### Steps to Reproduce

tofu force-unlock d475bb4c-506e-d6d5-2b13-15b92b319368

### Additional Context

I stopped my tofu apply run with ctrl + z and when I tried to unlock state I got this error. Finally, I unlocked state using terraform, but tofu should to do the same, I think.

**Comment by Yantrio** [comment]
This looks like the same as this issue here: https://github.com/opentofu/opentofu/issues/1617

This will be fixed in 1.7.1 which is coming soon!
