### ISSUE TITLE
OpenTofu Test - Support custom command per assertion 

### ISSUE THREAD

**Issue by hassannmoussaa** [opentofu/opentofu#1646]
### OpenTofu Version

```shell
OpenTofu v1.7.1
on windows_amd64
+ provider registry.opentofu.org/hashicorp/google v5.28.0
+ provider registry.opentofu.org/hashicorp/google-beta v5.28.0
```

### Use Cases

Some time while writing big unit tests for our Tofu code, we need to select faster way to run the test for specific resources like running a plan based test for the selected resources as the apply test takes a lot of time to give a feedback. 

Some draft terraform need to be tested as plan based test on each commit to check the feasibility and no apply based test is needed. 

Currently the Tofu only support one command for all assertion while custom command per assertion may provide more flexibility and dynamicity. 

Simple Use Case :

main.tf

```
resource "google_storage_bucket" "test" {
  name          = "my-bucket"
  location      = "US"
  project       = "my-project"
} 
```

tests/my.tftest.hcl

```
run "tests" {
   command = plan
  # Can ve validated in plan
  assert {
    condition     = google_storage_bucket.test.name == "my-bucket"
    error_message = "Invalid bucket name"
  }

  # Can't be validated in plan
  assert {
    condition     = google_storage_bucket.test.self_link == "https://www.googleapis.com/storage/v1/b/my-bucket"
    error_message = "Invalid self link"
  }
}

```

We want here to keep both assertion in the same test but run a plan based test for the first one and an apply based test for the second assertion.

### Attempted Solutions

Writing two tests one as plan and one as apply could be a solution, but its not very flexible and scalable especially using -filter and when i want an overall test for my code and if i want to test some plan on the apply command as an overall test

### Proposal

My Proposal is to add a field per assertion to specify the command to be tested as following 

```
run "tests" {

  # Can validate in plan
  assert {
    condition     = google_storage_bucket.test.name == "my-bucket"
    error_message = "Invalid bucket name"
    command = plan

  }

  # Can't validate in plan
  assert {
    condition     = google_storage_bucket.test.self_link == "https://www.googleapis.com/storage/v1/b/my-bucket"
    error_message = "Invalid self link"
    command = apply
  }
}

```

In that proposal the first assertion can be tested using plan and second one is tested through an apply.

In case the issue is accepted , i'll be happy to be assigned on it and to generate a PR to add this feature :

**Comment by hassannmoussaa** [comment]
Thank u 
Appreciate your support

**Comment by RLRabinowitz** [comment]
Hey @hassannmoussaa 

Regarding your suggestion, you could simply use two separate `run` blocks, one with `command = plan` and one with `command = apply`, and then for each `run` block put the relevant assertions.

Like so:
```
run "plan-tests" {
  command = plan

  assert {
    condition     = google_storage_bucket.test.name == "my-bucket"
    error_message = "Invalid bucket name"
  }
}

run "apply-tests" {
  command = apply

  assert {
    condition     = google_storage_bucket.test.self_link == "https://www.googleapis.com/storage/v1/b/my-bucket"
    error_message = "Invalid self link"
  }
}
```

Adding a `command` option under the `assert` block would add complexity to the design of the testing feature, with some unanswered questions and would not be explicit about the actual number of runs that would be executed when running the test suite

I'm closing this issue for now, but feel free to re-open it if you feel that this suggested solution does not help your specific use-case
