### ISSUE TITLE
Rename all placeholderplaceholderplaceholder occurrences.

### ISSUE THREAD

**Issue by cube2222** [opentofu/opentofu#165]
We've placed a placeholder (`placeholderplaceholderplaceholder`) in the codebase for a couple of things that are not yet finalized:

- Module path `github.com/placeholderplaceholderplaceholder/opentf`, as the organization name is not yet final
- References to docs `placeholderplaceholderplaceholder.io/docs`, as the documentation website is not yet finalized
- Other such miscellaneous changes

We should remove those placeholders, and change them to the actual expected values once everything has been finalized

**Comment by falanger** [comment]
Hey everyone,
Please, take a look at https://github.com/opentffoundation/opentf/pull/279

**Comment by cube2222** [comment]
As mentioned in the PR, we appreciate the contribution @falanger, but please first discuss ownership in issues as is described in the contributing guide. This issue is intentionally left open for now.

**Comment by mgirouard** [comment]
Hey gang, thanks for clarifying. Does it make sense for someone to register the `placeholderplaceholderplaceholder` org to prevent squatting in the meantime?

**Comment by eranelbaz** [comment]
@cube2222 what url do we want to switch it to?

**Comment by cube2222** [comment]
@eranelbaz for docs urls we switch to https://opentofu.org/docs/, while for github urls we switch to github.com/opentofu/opentofu, while for registry urls we switch to registry.opentofu.org

**Comment by eranelbaz** [comment]
After #684 we still have need to alter
```
apt.mdx
yum.mdx
```
which i guess we'll have after we publish the packages

**Comment by eranelbaz** [comment]
We also have 2-3 missing doc links

**Comment by RLRabinowitz** [comment]
> After https://github.com/opentofu/opentofu/pull/684 we still have need to alter

> ```
apt.mdx
yum.mdx
```

Should be taken care off as part of https://github.com/opentofu/opentofu/issues/567

See https://github.com/opentofu/opentofu/issues/567#issuecomment-1750215449

**Comment by RLRabinowitz** [comment]
All that's left is changing the `apt.mdx` and `yum.mdx`, which will be dealt with as part of https://github.com/opentofu/opentofu/issues/567
