### ISSUE TITLE
Support TOML as a native from within HCL package

### ISSUE THREAD

**Issue by itsmontoya** [opentofu/opentofu#1691]
### OpenTofu Version

```shell
Not related
```

### Use Cases

Would be useful to be able to store and load data in a format other than JSON. 

### Attempted Solutions

Currently, external modules can be used to parse toml similar to decodejson. It would be great to be able to do this natively without the use of external modules.

### Proposal

 It would be great to be able to do this natively without the use of external modules.

**Comment by cam72cam** [comment]
It looks like these changes would need to be started in the HCL repo:
https://github.com/opentofu/hcl/tree/main/json

**Comment by cam72cam** [comment]
@itsmontoya have you tried using https://github.com/Tobotimus/terraform-provider-toml?  With provider defined functions you should be able to use this function as if it were a native function in OpenTofu.
