### ISSUE TITLE
Cretes an empty directory w/o any reason

### ISSUE THREAD

**Issue by notorand-it** [opentofu/opentofu#1725]
### OpenTofu Version

```shell
OpenTofu v1.7.2
on linux_amd64
```

### OpenTofu Configuration Files

n/a

### Debug Output

n/a

### Expected Behavior

Just the diagnostics output when run with no HCL file and no options (main option list).

### Actual Behavior

An emtpy directory is created in ${HOME}/.terraform.d *AND* the diagnostics output when run with no HCL file and no options (main option list).

### Steps to Reproduce

1. `tofu`

### Additional Context

Just installed the binary, and ran it into my home with no HCL file available.
It should not touch anything, let alone create anything, if there is nothing to do.

**Comment by notorand-it** [comment]
While I can imagine a "simpler" mainstream execution path is desirable to save some code, I cannot think of case when it makes sense to modify the file system when no actual action is to be performed.

I would create that directory only if I really need to write into it and it's not already there.

I will have a look at the code as I feel weird that the right behavior requires "a major piece of refactoring". I could be badly wrong, of course.

**Comment by cam72cam** [comment]
Closing as not planned. Feel free to re-open if there are scenarios in which this causes a problem.
