### ISSUE TITLE
Add authorization header to all http requests

### ISSUE THREAD

**Issue by sylvainmouquet** [opentofu/opentofu#1755]
### OpenTofu Version

```shell
v1.7.2
```

### Use Cases

By default, all http requests to https://archivist.terraform.io are done without an authorization header. When a user want to create his own remote backend (remote or cloud), some calls must to be defined without the authorization header (logs, ...) and it's not secured at all !

The goal of this issue is to add the authorization header every time.

### Attempted Solutions

In `internal/cloud/backend.go` and `internal/backend/remote/backend.go`, the authorization bearer is added in the default headers :

```
// Add the authorization bearer
cfg.Headers.Set("Authorization", "Bearer "+token)
```

**Comment by sylvainmouquet** [comment]
ok sorry i will try to explain better.

Hashicorp uses url without bearers for url of type blob storage (to access to logs, upload configuration-versions, save the states). They explains it here :
https://developer.hashicorp.com/terraform/cloud-docs/api-docs#blob-storage-authentication

They have chosen to not use a bearer to secure this type of url. When a developer creates a custom remote backend (remote or cloud), the http client don't send the bearer and it's not secured by default.
It's preferable to send the bearer to each requests and to verify it in the api backend. 
I don't know why Hashicorp has chosen to not secure this type of urls with bearer and to use another security system.

ex : https://developer.hashicorp.com/terraform/cloud-docs/api-docs/state-versions#upload-state-and-json-state
```
curl \
  --header "Content-Type: application/octet-stream" \
  --request PUT \
  --data-binary @filename \
  https://archivist.terraform.io/v1/object/4c44d964-eba7-4dd5-ad29-1ece7b99e8da
```
the Authorization bearer is not present in the header.

If we add the bearer in all http requests, it's the accountable of the developer to check it in the backend side.

**Comment by sylvainmouquet** [comment]
If we add this feature, the terraform cli will continues to not send the bearer. The impact is the custom remote backend will be compatible with opentofu but not terraform cli. I will create an issue in terraform cli to ask to Hashicorp teams to add the header

**Comment by sylvainmouquet** [comment]
it's for supporting a third party implementation of the API.

**Comment by RLRabinowitz** [comment]
Hey @sylvainmouquet, adding a default header to the `go-tfe` client would add the header to the upload request, but it will also add it to other requests, where it may not be intended.

Moreover, I did not test it out, but I'm pretty sure that adding such a header would break existing behaviour, and would not work with `archivist.terraform.io` and TFC or a different existing remote backend.

I'd mention that currently, the archivist upload links, which you get as a response from a `create-state-version` call (for example), should be considered as secrets. You can see [Hashicorp's TFC documentation](https://developer.hashicorp.com/terraform/cloud-docs/architectural-details/security-model#treat-archivist-urls-as-secrets) for that

With the current spec, when using OpenTofu and a remote backend, the link that you get back is a one-time URL that contains a signed short-term authentication token. So, for a third-party implementation of the API, it's recommended that you'd do the same, and return a one-time upload URL that contains a signed short-term authentication token, when implementing `create-state-version`.

**Comment by sylvainmouquet** [comment]
yes @RLRabinowitz you are true. I have opened this issue to quickly, I use a generated url as you mention.
i close this issue if you are ok as i don't need it anymore
