### ISSUE TITLE
.terraformrc doesn't interpret $HOME

### ISSUE THREAD

**Issue by cpboyd** [opentofu/opentofu#1756]
### OpenTofu Version

```shell
OpenTofu v1.7.2
on darwin_arm64
```

### OpenTofu Configuration Files

```hcl
...tofu config...
```

### Debug Output

```
│ Error: Failed to resolve provider packages
│ 
│ Could not resolve provider hashicorp/aws: cannot search
│ $HOME/.terraform.d/plugins: lstat $HOME/.terraform.d/plugins: no such file
│ or directory
```

### Expected Behavior

[Per the docs](https://opentofu.org/docs/cli/config/config-file/#configuration-file-syntax)
```
plugin_cache_dir   = "$HOME/.terraform.d/plugin-cache"
```
should work.

### Actual Behavior

When using both `.tofurc` and `.terraformrc`, it seems like the plugin-cache got populated but never actually gets used.
This resulted in the plugin getting re-downloaded each time (but, again, `plugin-cache/` had several versions that had been saved)

After removing `.tofurc`, I was able to find out that `$HOME` wasn't getting expanded for `.terraformrc`. Per `TF_LOG=DEBUG`, each gets loaded at different points perhaps leading to conflicts in if there's issues with one or the other.

### Steps to Reproduce

In `.terraformrc`:
```
plugin_cache_dir = "$HOME/.terraform.d/plugin-cache"
provider_installation {
  filesystem_mirror {
    path = "$HOME/.terraform.d/plugins"
    include = ["*/*/*"]
  }
  direct {
    exclude = ["*/*/*"]
  }
}
```

Run `tofu apply` on a module. Neither directory seems to be interpreted correctly.

### Additional Context

I was keeping both `.tofurc` and `.terraformrc` in case of needing to switch back to `terraform` and had been keeping them in sync.

**Comment by RLRabinowitz** [comment]
Hey there and thank you for this issue! The core team regularly reviews new issues and discusses them, but this can take a little time. Please bear with us while we get to your issue.

If you're interested, the contribution guide has a section about the [decision-making process](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md#who-decides-if-a-feature-will-be-implemented-and-how-is-that-decision-made).

**Comment by RLRabinowitz** [comment]
Hey @cpboyd could you please provider TRACE logs for your execution?

I've tried reproducing the issue locally, and the `.terraformrc` file or `.tofurc` files are able to interpret `$HOME` in the definition of `plugin_cache_dir`

As a side note - your `.terraformrc` file is written in such a way that the `plugin_cache_dir` doesn't matter. Due to the `provider_installation` definition, OpenTofu will always attempt to use the filesystem mirror (which is the same directory), and would technically not really need a `plugin_cache_dir` there. It also means that if there's a new version available in the registry, it will never be spotted in OpenTofu, as it looks for the filesystem_mirror for the available provider versions

**Comment by cpboyd** [comment]
@RLRabinowitz Yes, I'm aware of the current configuration. With each terragrunt operation, I was watching my data usage grow by ~1GB so I intentionally restricted everything to local mirror only via `provider_installation`.

Please find attached the trace from changing the `. terraformrc` back to
```
plugin_cache_dir = "$HOME/.terraform.d/plugin-cache"
provider_installation {
  filesystem_mirror {
    path = "$HOME/.terraform.d/plugins"
    include = ["*/*/*"]
  }
  direct {
    exclude = ["*/*/*"]
  }
}
```

Note: The error in this case is from `filesystem_mirror.path`

[tofu-trace.log](https://github.com/user-attachments/files/16046123/tofu-trace.log)

**Comment by cpboyd** [comment]
I'm unable to reproduce after restoring `~/.tofurc` and `~/.terraformrc`.

It may have also been a Terragrunt issue related to different plugin versions between dependent modules, which I've also cleaned up.
