### ISSUE TITLE
[Feature request] Add an option for Sensitive Output variable store export as Variable

### ISSUE THREAD

**Issue by nrv-96** [opentofu/opentofu#1757]
### OpenTofu Version

```shell
v1.7.2
```

### Use Cases

I'm working with a pipeline that utilizes a combination of Opentofu and Ansible for managing Virtual Machines. The password is marked as 'Sensitive' in the output variable, so I cannot retrieve its value directly. While this restriction makes sense, the requirement is to use this password as an input for Ansible. Currently, there isn't a straightforward way to achieve this. Therefore, I propose adding an `EXPORT` option to the output variable. This would allow the sensitive value to remain hidden from display but could still be exported as a variable. This approach would enable the pipeline to use the variable as input for Ansible without fetching the value from Azure Keyvault or AWS Secret Manager.

### Attempted Solutions

NA

### Proposal

Export default value should be false.

**Scenario 1:  db_password will output as `db_password= (sensitive value)` but it will export variable.**
```hcl
output "db_password" {
  value       = aws_db_instance.db.password
  description = "The password for logging in to the database."

  sensitive   = true
  export      = true

}
```

**Scenario 2: db_password will output as `db_password= (sensitive value)` but it will not be export variable.**
```hcl
output "db_password" {
  value       = aws_db_instance.db.password
  description = "The password for logging in to the database."

  sensitive   = true
  export      = false

}
```

**Scenario 3: nothing happen!**
```hcl
output "db_password" {
  value       = aws_db_instance.db.password
  description = "The password for logging in to the database."

  sensitive   = false
  export      = false

}
```

**Scenario 4: db_password will output as currently running code there no changes for this scenario.**
``` hcl
output "db_password" {
  value       = aws_db_instance.db.password
  description = "The password for logging in to the database."

  sensitive   = false
  export      = true

}
```

**Scenario 5: db_password will output as currently running code there no changes for this scenario**
```hcl
output "db_password" {
  value       = aws_db_instance.db.password
  description = "The password for logging in to the database." 
  export      = true
}
```

**Scenario 6: db_password will not export! (Optional Scenario)**
```hcl
output "db_password" {
  value       = aws_db_instance.db.password
  description = "The password for logging in to the database." 
  export      = false
}
```

### References

https://opentofu.org/docs/language/values/outputs/

**Comment by cam72cam** [comment]
There is now a `-show-sensitive` flag merged that will be in the 1.9.0 release of OpenTofu which should solve this issue, though @janosdebugs' suggestion is the recommended solution
