### ISSUE TITLE
Using local variables in for modules definition doesn't work in Tofu v1.8.0-alpha1 (but it should)

### ISSUE THREAD

**Issue by mm-chia** [opentofu/opentofu#1762]
### OpenTofu Version

```shell
OpenTofu v1.8.0-alpha1
on darwin_arm64
+ provider registry.opentofu.org/datadog/datadog v3.39.0
+ provider registry.opentofu.org/hashicorp/aws v5.56.1
+ provider registry.opentofu.org/hashicorp/local v2.5.1
+ provider registry.opentofu.org/hashicorp/null v3.2.2
+ provider registry.opentofu.org/hashicorp/random v3.6.2
+ provider registry.opentofu.org/pagerduty/pagerduty v1.11.0
```

### OpenTofu Configuration Files

```
locals {
    module_version = "1.5.5"
}

module {
    source = "git@bitbucket.org:myorg/mymodule.git/?ref=v${local.module_version}"
}
```

### Debug Output

No need, it can be verified by anyone, by using a variable for a module version.

### Expected Behavior

Should have not thrown errors

### Actual Behavior

It throws some errors and cannot continue

### Steps to Reproduce

1. tofu init
2. tofu plan

### Additional Context

According to this discussion here, this feature should have been already implemented in Tofu 1.8.0
https://github.com/opentofu/opentofu/issues/1042

**Comment by cam72cam** [comment]
@mm-chia Your example is invalid, your module block needs a label.

```hcl
locals {
    module_version = "1.5.5"
}

module "mod" {
    source = "git@bitbucket.org:myorg/mymodule.git/?ref=v${local.module_version}"
}
```

works just fine

**Comment by cam72cam** [comment]
Can you post the actual error you received?

**Comment by cam72cam** [comment]
@mm-chia As far as I can tell, you are not running OpenTofu 1.8. Can you double check your setup to confirm you are on 1.8?

```hcl
terraform {
        required_version = ">= 1.8"
}
```

**Comment by mm-chia** [comment]
Hi @cam72cam,
Thanks for the quick response!
You are actually correct. I was using 'tofu init' command, but my bash alias for 'plan' was using 'terraform' command instead.
It actually works as expected.
Thanks for your help!
