### ISSUE TITLE
Running "tofu show" brings back errors not seen on plan and apply

### ISSUE THREAD

**Issue by liam-witterick** [opentofu/opentofu#1768]
### OpenTofu Version

```shell
v1.8.0-alpha1
```

### OpenTofu Configuration Files

**main.tf**
```hcl
variable "module_version" {}

module "security_group" {
  source  = "cloudposse/security-group/aws"
  version = var.module_version

  attributes       = ["primary"]
  allow_all_egress = true
  vpc_id = "vpc-111111111111"
}
```
**input.tfvars**
```hcl
module_version = "2.2.0"
```

### Debug Output

╷
│ Error: Variable not provided via -var, tfvars files, or env
│
│   on main.tf line 23:
│   23: variable "module_version" {}
│
╵

╷
│ Error: Unable to compute static value
│
│   on main.tf line 31, in module "security_group":
│   31:   version = var.module_version
│
│ module.security_group.version depends on var.module_version which is not available

### Expected Behavior

Running `tofu plan` doesn't return any errors, therefore no errors were expected when examining the outputted file with `tofu show`. I can also run `tofu apply` successfully. 

### Actual Behavior

`tofu show plan.json` returns errors that are not seen when running `tofu plan` or `tofu apply`. 

### Steps to Reproduce

1. `tofu init -var-file=input.tfvars`
2. `tofu plan -out plan.json -var-file=input.tfvars`
3. `tofu show plan.json`

**Comment by cam72cam** [comment]
Thanks for the clear report, I'm taking a look.

**Comment by cam72cam** [comment]
It looks like the error is produced by the encryption setup code, which is trying to load the files in the current directory.

I moved it to a new directory and got:
```
../tofu show ../plan.json
╷
│ Error: Couldn't show local plan
│ 
│ Plan read error: 2 problems:
│ 
│ - Variable not provided via -var, tfvars files, or env
│ - Unable to compute static value: module.src.source depends on var.src which is not available
```
Which is a related but distinct bug.

**Comment by cam72cam** [comment]
The workaround at the moment is:
```
