### ISSUE TITLE
Ignore/prevent resources destruction without modifying base module

### ISSUE THREAD

**Issue by alelb22** [opentofu/opentofu#1773]
Hi folks,
I'm opening a separate issue because I think this use case is not covered by the `removed` block.

I'm using ACM in a multi-account/multi-region structure. I'm using the same domain name in different regions but within the same account. So, the CNAME record needed for validation is the same for those certificates.

The community module ( [LINK](https://registry.terraform.io/modules/terraform-aws-modules/acm/aws/latest#usage-with-route53-dns-validation-recommended) ), as you probably know, supports automatically creating the DNS record in the zone. This works as expected, but when the cert is removed from a region, the DNS record is also removed, as it's in the state, even if it's still required by a certificate in a different region.

@ArbitraryCritter in [this comment](https://github.com/opentofu/opentofu/issues/548#issuecomment-1968908218) posted something similar, but that issue was closed and requested that new use cases be covered in a separate issue:
> This is for certificate validation dns records. I have multiple pieces of code, requesting separate certificates that are using the same dns records for validation. (This is for AWS ACM).
> Currently terraform/OpenTofu will delete all validation dns records used by the certificates, if I delete one of the certificates, which will cause the other certificates to eventually expire (after lots of event/email notices) because they cannot auto-renew without these records.
> For these dns records I would prefer that OpenTofu create them if they're missing (which is supported) and just forget the state when it deletes them.
> 
> Admittedly this does leak dns records, indicating that this is certainly not a perfect solution. However, without this I would be forced to creation dependencies between resources that have nothing in common except that I want to host them on the same overall domain names.
> 
> From the top of my head, another case would be things like AWS KMS keys, which cannot be deleted until a certain amount of time has passed. Leaking those with a warning is useful in many takedown cases.

I also found [this issue](https://github.com/opentofu/opentofu/issues/1615), which is for a different scenario, but the behavior of the feature should be mostly the same.

Do you think it's possible to review this feature enhancement?
Thanks!

**Comment by Evi1Pumpkin** [comment]
Hey, @alelb22, thanks for opening this issue!

Today, the `removed` block does support "forgetting" a resource in a deleted module:
```hcl
// main.tf
# module "mod" {         <---- previously applied module
#   source   = "./mod"
# }

removed {
  from = module.mod.null_resource.null_module
}

// mod/main.tf
resource "null_resource" "null_module" {
}
``` 

The problem with this solution is that it does not support instance keys (as mentioned in a note in our [docs](https://opentofu.org/docs/language/resources/syntax/#removing-resources)). So, if you have a module with `for_each` and want to remove one of its iterations, you won't be able to use the `removed` block. But there is a workaround that allows that.

Could you give me more details about your scenario? Sharing a code example of your configuration would really help in understanding the issue you are facing.

**Comment by alelb22** [comment]
Hi @Evi1Pumpkin !

Thank you for your reply. :)

Sure thing! Here's an example repo: [LINK](https://github.com/alelb22/multi-region-acm-issue/tree/main)
I also added the steps to reproduce the issue in the README, along with a suggestion below it.

Let me know if that works for you. :)

Kind regards!

**Comment by Evi1Pumpkin** [comment]
Thanks for providing this repository, @alelb22. It was very helpful to understand the problem.

Unfortunately, I don't think we'll be able to support this kind of enhancement for two reasons:
1. Technical reason - In the [enhancement we accepted](https://github.com/opentofu/opentofu/issues/1615) (which still requires a better specification in an RFC), the suggested solution relies on the configuration set in the `lifecycle` block in the resource. You'll need access to the resources to put the new property, so this is something you cannot do from a wrapping module.  If you have another proposal on how to do that, we would be happy to hear it.
2. Overall, we do not want to implement functionality that overrides modules from the outside. Doing so would shift responsibility away from the module authors, who have carefully designed and implemented their solutions. This could lead to unintended consequences, such as breaking the module's integrity or causing issues in the environment.
If you want an existing module to support new functionality, you can open an issue and ask them to do that.

I hope you understand our reasoning and find it fair.

**Comment by cam72cam** [comment]
Closing for now, feel free to re-open if you wish to continue the discussion @alelb22.
