### ISSUE TITLE
External provider: exec format error

### ISSUE THREAD

**Issue by stokedout** [opentofu/opentofu#1775]
### OpenTofu Version

```shell
OpenTofu v1.7.1
on darwin_arm64
+ provider registry.opentofu.org/hashicorp/aws v5.49.0
+ provider registry.opentofu.org/hashicorp/external v2.3.3
```

### OpenTofu Configuration Files

```hcl
data "external" "gitlab_ci_runner_ip_ranges" {
  program = ["${path.module}/gitlab_ci_runner_ip_ranges.sh"]
}

output "name" {
  value = data.external.gitlab_ci_runner_ip_ranges.result
}

```

gitlab_ci_runner_ip_ranges.sh
```
!/bin/bash

# Exit if any of the intermediate steps fail
set -e

# https://docs.gitlab.com/ee/user/gitlab_com/#ip-range
# Fetches all us-east1 IP ranges from Google Cloud Platform and prints them in JSON format
curl -sS https://www.gstatic.com/ipranges/cloud.json | jq '[.prefixes[] | select(.scope == "us-east1") | .ipv4Prefix | select(. != null)]'
```

### Debug Output

Planning failed. OpenTofu encountered an error while generating this plan.

╷
│ Error: External Program Execution Failed
│ 
│   with module.production.module.example.data.external.gitlab_ci_runner_ip_ranges,
│   on module/example/main.tf line 103, in data "external" "gitlab_ci_runner_ip_ranges":
│  103:   program = ["${path.module}/gitlab_ci_runner_ip_ranges.sh"]
│ 
│ The data source received an unexpected error while attempting to execute the program.
│ 
│ The program was executed, however it returned no additional error messaging.
│ 
│ Program: module/example/gitlab_ci_runner_ip_ranges.sh
│ State: fork/exec module/example/gitlab_ci_runner_ip_ranges.sh: exec format error
╵

### Expected Behavior

Should output the IP ranges

### Actual Behavior

Raised the above error. 

### Steps to Reproduce

`tofu apply`

### Additional Context

Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	Mac14,7
  Model Number:	5NEH3LL/A
  Chip:	Apple M2
  Total Number of Cores:	8 (4 performance and 4 efficiency)
  Memory:	8 GB
  System Firmware Version:	10151.101.3
  OS Loader Version:	10151.101.3

<img width="344" alt="image" src="https://github.com/opentofu/opentofu/assets/1408257/50a6d7ba-cc97-4ff1-8c1e-462e9068f4e2">

**Comment by cam72cam** [comment]
`!/bin/bash` should be `#!/bin/bash`

**Comment by stokedout** [comment]
😢 thank you and sorry at the same time
