### ISSUE TITLE
Case conversion issues with reference to the terraform fixed update 

### ISSUE THREAD

**Issue by Madhu-mohan86** [opentofu/opentofu#1794]
### OpenTofu Version

```shell
`[anony@archlinux main]$ tofu -version
OpenTofu v1.7.2
on linux_amd64
+ provider registry.opentofu.org/hashicorp/azurerm v3.110.0
+ provider registry.opentofu.org/hashicorp/local v2.5.1
+ provider registry.opentofu.org/hashicorp/random v3.6.2
+ provider registry.opentofu.org/hashicorp/tls v4.0.5
[anony@archlinux main]$ `
```

### OpenTofu Configuration Files

```
resource "azurerm_network_security_rule" "ssh" {
    for_each = var.vm_name
    name="AllowAnySSHInbound"
    direction="Inbound"
    priority = 100
    access="Allow"
    protocol="Tcp"
    source_port_range=22
    destination_port_range=22
    source_address_prefix="*"
    destination_address_prefix="*"
    network_security_group_name = azurerm_network_security_group.nsg_def[each.key].name
    resource_group_name = var.resource_group
}

```

### Debug Output

https://gist.github.com/Madhu-mohan86/0c51e4f6ec1f1c75a3bbf7d9e3601196

### Expected Behavior

![image](https://github.com/opentofu/opentofu/assets/124799557/804b9b06-1710-4644-8ea3-dec4d67daad8)

### Actual Behavior

![image](https://github.com/opentofu/opentofu/assets/124799557/d2bad23e-d942-4466-9895-7c4979d761fd)

### Steps to Reproduce

tofu init 
tofu plan
tofu apply

### Additional Context

The same issue has been created in the git repo with issue https://github.com/hashicorp/terraform-provider-azurerm/issues/16092 which is there is conversion of casing should be done in the atttibute of protocol where the value may be `Tcp` , `Udp` that is strictly required by azure to behave correctly supposed to be `TCP` , `UDP` . The issue was fixed in terraform update with fixed merge link https://github.com/hashicorp/terraform-provider-azurerm/pull/18799/commits/ba5859318ed5939bc96fab337ce869497d463b01. so please look into it

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/16092
https://github.com/hashicorp/terraform-provider-azurerm/pull/18799/commits/ba5859318ed5939bc96fab337ce869497d463b01

**Comment by Madhu-mohan86** [comment]
Although with the reference to given issue links there has been problem with both service and provider , I didn't ensure where the real problem happens and it has been fixed with terraform or not because I didn't checked with it but i am sure there is issue still persists , whether it is possible to make a bug fix in opentofu because none of them want to change in gui everytime after provisioning the infrastructure

**Comment by Madhu-mohan86** [comment]
@janosdebugs  thanks for considering the comment as you asked for the provider check . I have used the dedicated configuration for checking this latest version 
```
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "3.111.0"
    }
  }
}
```

For your additional reference to get a more clarity I have also included my specific configuration which is used for the verification 

```
resource "azurerm_network_security_group" "opentofubug" {
  resource_group_name = azurerm_resource_group.create_rg.name
  location = azurerm_resource_group.create_rg.location
  name = "tcp_check"
    security_rule {
    name                       = "Ssh"
    priority                   = 100
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = 22
    destination_port_range     = 22
    source_address_prefix      = "*"
    destination_address_prefix = "*"

  }
}
```

But the result persists and the required function is not executed successfully and here is the screenshot where it still having case conversion issues for the protocol attribute 

![image](https://github.com/user-attachments/assets/8df57d29-098a-4935-9a6b-50438ea060b3)

**Comment by cam72cam** [comment]
Closing due to lack of response.  Feel free to re-open if you have more context.
