### ISSUE TITLE
Plan output would miss a dynamic block if it is fully unknown

### ISSUE THREAD

**Issue by RLRabinowitz** [opentofu/opentofu#1805]
### OpenTofu Version

```shell
1.8.0-beta
```

### OpenTofu Configuration Files

```hcl
resource "random_integer" "a" {
  max = 10
  min = 1
}

resource "azurerm_firewall_policy" "random_policy" {
  name                = "random-policy"
  resource_group_name = "existing-resource-group"
  location            = "westeurope"

  dynamic "dns" {
    for_each = random_integer.a.result > 5 ? [] : [1]
    content {
      servers = ["8.8.8.8"]
    }
  }
}
```

### Debug Output

.

### Expected Behavior

OpenTofu should show the `dns` block as `(known after apply)`

### Actual Behavior

OpenTofu never shows the `dns` block as part of the creation, whether or not it is created

```
OpenTofu used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

OpenTofu will perform the following actions:

  # azurerm_firewall_policy.random_policy will be created
  + resource "azurerm_firewall_policy" "random_policy" {
      + child_policies           = (known after apply)
      + firewalls                = (known after apply)
      + id                       = (known after apply)
      + location                 = "westeurope"
      + name                     = "random_policy"
      + resource_group_name      = "existing-resource-group"
      + rule_collection_groups   = (known after apply)
      + sku                      = (known after apply)
      + threat_intelligence_mode = "Alert"
    }

  # random_integer.a will be created
  + resource "random_integer" "a" {
      + id     = (known after apply)
      + max    = 10
      + min    = 1
      + result = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy.

```

### Steps to Reproduce

1. `tofu init`
2. `tofu plan`

### Additional Context

This is reproducible with any resource that has a block field

### References

- Related issue in the Terraform Repository - https://github.com/hashicorp/terraform/issues/34933

**Comment by bunniseng** [comment]
Hi,

Please assign the issue to me, I would like to work on it thanks.

**Comment by ollevche** [comment]
Hey @bunniseng!

Thank you for volunteering, I've assigned you. Please read [the "I've been assigned an issue, now what?" section of the contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md#ive-been-assigned-an-issue-now-what) before you begin working.

Could you please also share what approach you want to take before opening a PR?

**Comment by buraksenn** [comment]
Hi @bunniseng are you still working on this issue? If not I would like to work on it

**Comment by ollevche** [comment]
Sure!

@buraksenn I've assigned you. Please read [the "I've been assigned an issue, now what?" section of the contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md#ive-been-assigned-an-issue-now-what) before you begin working.
