### ISSUE TITLE
`opentf test -test-directory` reading local and specified directories

### ISSUE THREAD

**Issue by eranelbaz** [opentofu/opentofu#181]
### OpenTF Configuration Files

```hcl
...opentf config...
```

### Expected Behavior

OpenTF should only read the files under the specified path

### Actual Behavior

When using `opentf test -test-directory /path/to/directory` opentf reads both current directory and specified directories files, which only needs to read the files from the specified directory.

Running the command from `opentf/internal/command/testdata/test/multiple_files` reads both testing files of `multiple_files` and of `no_providers_in_main`
```
$ opentf test -test-directory=../no_providers_in_main 
../no_providers_in_main/main.tftest.hcl... fail
  run "passes_validation"... fail
╷
│ Error: Missing required provider
│ 
│ This configuration requires provider registry.terraform.io/hashicorp/test, but that provider isn't available. You may be able to install it automatically by running:
│   opentf init
╵
one.tftest.hcl... fail
  run "validate_test_resource"... fail
╷
│ Error: Missing required provider
│ 
│ This configuration requires provider registry.terraform.io/hashicorp/test, but that provider isn't available. You may be able to install it automatically by running:
│   opentf init
╵
two.tftest.hcl... fail
  run "validate_test_resource"... fail
╷
│ Error: Missing required provider
│ 
│ This configuration requires provider registry.terraform.io/hashicorp/test, but that provider isn't available. You may be able to install it automatically by running:
│   opentf init
╵

Failure! 0 passed, 3 failed.
```

OpenTF reads both test files of `multiple_files` and of `no_providers_in_main`

**Comment by misha-slyusarev** [comment]
I would like to take ownership of this issue if you feel like it is ready to be worked on.

**Comment by m7modsaer** [comment]
لم افهم عليه شيئان`
