### ISSUE TITLE
tofu init response repetitive diags when configuration has extra label

### ISSUE THREAD

**Issue by TTTouper** [opentofu/opentofu#1812]
### OpenTofu Version

```shell
Any/Latest
```

### OpenTofu Configuration Files

```hcl
terraform {
  extra_label{
    required_providers {
      azurerm = {
        source  = "hashicorp/azurerm"
        version = "~> 3.0.2"
      }
    }
  }
}
```

### Debug Output

2024-07-12T10:59:02.775+0800 [INFO]  OpenTofu version: 1.8.0 dev
2024-07-12T10:59:02.784+0800 [DEBUG] using github.com/hashicorp/go-tfe v1.36.0
2024-07-12T10:59:02.784+0800 [DEBUG] using github.com/opentofu/hcl/v2 v2.0.0-20240416130056-03228b26f391
2024-07-12T10:59:02.784+0800 [DEBUG] using github.com/hashicorp/terraform-svchost v0.1.1
2024-07-12T10:59:02.784+0800 [DEBUG] using github.com/zclconf/go-cty v1.14.4
2024-07-12T10:59:02.784+0800 [INFO]  Go runtime version: go1.21.4
2024-07-12T10:59:02.784+0800 [INFO]  CLI args: []string{"E:\\Test_workspace\\test-template\\test-it\\tofu.exe", "init"}
2024-07-12T10:59:02.787+0800 [DEBUG] Attempting to open CLI config file: C:\Users\AppData\Roaming\terraform.rc
2024-07-12T10:59:02.787+0800 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2024-07-12T10:59:02.787+0800 [DEBUG] checking for credentials in "C:\\Users\\AppData\\Roaming\\terraform.d\\plugins"
2024-07-12T10:59:02.787+0800 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2024-07-12T10:59:02.787+0800 [DEBUG] will search for provider plugins in C:\Users\AppData\Roaming\terraform.d\plugins
2024-07-12T10:59:02.790+0800 [DEBUG] ignoring non-existing provider search directory C:\Users\AppData\Roaming\HashiCorp\Terraform\plugins
2024-07-12T10:59:02.791+0800 [DEBUG] Found the config directory: C:\Users\AppData\Roaming\terraform.d
2024-07-12T10:59:02.791+0800 [INFO]  CLI command args: []string{"init"}

### Expected Behavior

The configuration diags should only occur once

### Actual Behavior

$ ./tofu.exe init

Initializing the backend...
OpenTofu encountered problems during initialization, including problems
with the configuration, described below.

The OpenTofu configuration must be valid before initialization so that
OpenTofu can determine which modules and providers need to be installed.
╷
│ Error: Unsupported block type
│
│   on main.tf line 2, in terraform:
│    2:   extra_label{
│
│ Blocks of type "extra_label" are not expected here.
╵

╷
│ Error: Unsupported block type
│
│   on main.tf line 2, in terraform:
│    2:   extra_label{
│
│ Blocks of type "extra_label" are not expected here.

### Steps to Reproduce

tofu init

**Comment by TTTouper** [comment]
[#](https://github.com/opentofu/opentofu/blame/f668c48ffd57d1f5f5dcd7543f179b373643081a/internal/command/init.go#L295)

**Comment by TTTouper** [comment]
#https://github.com/opentofu/opentofu/blame/f668c48ffd57d1f5f5dcd7543f179b373643081a/internal/command/init.go#L295

**Comment by sekhar5031** [comment]
In your case, it seems like you're trying to use extra_label, which is not a valid Terraform block type. You should directly use required_providers within the terraform block to specify the providers your Terraform configuration depends on.

![image](https://github.com/user-attachments/assets/079514a2-d7d7-457c-9823-e1bc501aa72e)
So, your provider.tf file should be corrected to:

```
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0.2"
    }
  }
}

```

**Comment by TTTouper** [comment]
> In your case, it seems like you're trying to use extra_label, which is not a valid Terraform block type. You should directly use required_providers within the terraform block to specify the providers your Terraform configuration depends on.
> 
> ![image](https://private-user-images.githubusercontent.com/102132259/348193152-079514a2-d7d7-457c-9823-e1bc501aa72e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NzQ2NjIsIm5iZiI6MTcyMDc3NDM2MiwicGF0aCI6Ii8xMDIxMzIyNTkvMzQ4MTkzMTUyLTA3OTUxNGEyLWQ3ZDctNDU3Yy05ODIzLWUxYmM1MDFhYTcyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMlQwODUyNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNjA0ZTEyZTE0MTg4YzgzMjUyMmZiNTNkNjdlYTc2ZDQ0MWFiNTY5ODlkYTI4MzJjNmUyYmQ0MzNiYWE4YjcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0CPCMvRDlGSpjJQ-i_9Ir8I2G3A6if9Br3uMMalM-eU) So, your provider.tf file should be corrected to:
> 
> ```
> terraform {
>   required_providers {
>     azurerm = {
>       source  = "hashicorp/azurerm"
>       version = "~> 3.0.2"
>     }
>   }
> }
> ```

**Comment by TTTouper** [comment]
> In your case, it seems like you're trying to use extra_label, which is not a valid Terraform block type. You should directly use required_providers within the terraform block to specify the providers your Terraform configuration depends on.
> 
> ![image](https://private-user-images.githubusercontent.com/102132259/348193152-079514a2-d7d7-457c-9823-e1bc501aa72e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NzQ4MzUsIm5iZiI6MTcyMDc3NDUzNSwicGF0aCI6Ii8xMDIxMzIyNTkvMzQ4MTkzMTUyLTA3OTUxNGEyLWQ3ZDctNDU3Yy05ODIzLWUxYmM1MDFhYTcyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMlQwODU1MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMGIxMWUxNmVlODQzNTY0OWI3ZWYwNjg4MTU1ZWJlYjQ3YTk4MWEwZDVlYzBjZWVjMjYwNDkxMTE0MDMwYzJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MRkG2GXSzJzlBJy1J2LF7qVIBQKBHfEFdQoWvw5nvDg) So, your provider.tf file should be corrected to:
> 
> ```
> terraform {
>   required_providers {
>     azurerm = {
>       source  = "hashicorp/azurerm"
>       version = "~> 3.0.2"
>     }
>   }
> }
> ```
This is indeed an incorrect use case, but i think this diags only need to occur once

**Comment by buraksenn** [comment]
Is anyone working on this issue? I want to try fixing it

**Comment by cam72cam** [comment]
Thank you for volunteering @buraksenn! Please read [the "I've been assigned an issue, now what?" section of the contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md#ive-been-assigned-an-issue-now-what) before you begin working.

**Comment by buraksenn** [comment]
> Thank you for volunteering @buraksenn! Please read [the "I've been assigned an issue, now what?" section of the contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md#ive-been-assigned-an-issue-now-what) before you begin working.

Thanks @cam72cam, I start looking into it today and will start from the document.
