### ISSUE TITLE
Create a new definition for child modules / modules consumed by others

### ISSUE THREAD

**Issue by alex067** [opentofu/opentofu#1820]
### OpenTofu Version

```shell
Not relevant
```

### Use Cases

Terraform provides two definitions of a module. We have root modules, and child modules. Technically speaking, yes everything is a module and can be consumed by others.

However realistically, this ambiguity causes way more confusion than necessary. This has been my experience creating content teaching Terraform, and mentoring internal teams.

For example, best practices differ between root modules and child modules. However we simply cannot say modules, because it doesn't specify whether we're talking about root modules, or a child module. In the real world, when people say modules, they refer specifically to a child module. We expect the term "module" to reference a self contained unit of resources consumed by others.

Root modules should be scrapped entirely, and be replaced by a new definition. Modules should refer to child modules, or modules consumed by others. Root modules should be changed to something more akin to projects or environment.

### Attempted Solutions

No attempted solutions.

This is merely a high level discussion to change definitions, naming conventions and philosophy around differentiating root modules from child modules.

### Proposal

My proposal is to introduce a shift in naming. 

Documentation should refer root modules as projects or environments, allowing there to be a much cleaner and obvious distinction between child modules.

Child modules should simply be referred to as a module. That's how real operators use the term. 

Yes, technically they are all modules, however this technicality is not beneficial and adds an unnecessary layer of confusion and requires constant clarification.

**Comment by cam72cam** [comment]
At this point, there is a significant amount of information about root modules vs child modules in docs, books, blog posts, etc...

I worry changing the name/semantics at this point would be detrimental.  Additionally, we would want to keep that in-sync with terraform if possible, which I think is unlikely.

**Comment by alex067** [comment]
Thanks @cam72cam for your feedback.

It's very telling to me, that we have so much information attempting to differentiate technicalities between root vs child module. 

Yet still in the real world with real Terraform & Opentofu users, the term "module" always refers to a child module.

**Comment by cam72cam** [comment]
Unfortunately I believe that the ship has sailed on these terms and attempting a change at this point would add to the confusion, sorry.
