### ISSUE TITLE
.tofurc is ignored for "tofu providers lock" command

### ISSUE THREAD

**Issue by ollevche** [opentofu/opentofu#1822]
### OpenTofu Version

```shell
The latest commit from the main branch.
```

### OpenTofu Configuration Files

`main.tf`:

```hcl
# doesn't matter
resource null_resource a {
}
```

`~/.tofurc`:
```hcl
# must make tofu fail if used
provider_installation {
  network_mirror {
    url = "https://a.com/b/"
  }
}
```

### Debug Output

By request.

### Expected Behavior

I expect `tofu providers lock` to use `.tofurc` file (and fail) the same way `tofu init` does.

### Actual Behavior

`tofu providers lock` doesn't use `.tofurc` file and proceeds with no errors.

### Steps to Reproduce

1. Create `main.tf` and `.tofurc` files
2. Run `tofu init` (should fail)
3. Run `tofu providers lock` (should fail, but succeeds)

### Additional Context

We should also check what other commands are affected after finding the root cause.

**Comment by cam72cam** [comment]
From `tofu providers lock`:
```
  The "providers lock" subcommand addresses that by updating the lock file
  based on the official packages available in the origin registry, ignoring
  the currently-configured installation strategy.
```

**Comment by ollevche** [comment]
This is the intended behavior of `tofu provider lock`, which must not be altered. See https://opentofu.org/docs/cli/commands/providers/lock/#usage
