### ISSUE TITLE
Rename user agents.

### ISSUE THREAD

**Issue by roni-frantchi** [opentofu/opentofu#183]
Just to be on the safe side - do not identify our client as Terraform.  

Use `OpenTF`, for now.  

[Reference](https://github.com/opentffoundation/opentf/blob/ebcf7455ebde2b21344de1890d5c7ad69d1be8a3/internal/httpclient/useragent.go#L48)

**Comment by bgrant0607** [comment]
FYI, this change didn't affect the provider User-Agent strings. Those strings include the version, which could be prefixed:
https://github.com/opentofu/opentofu/blob/main/version/version.go#L61

**Comment by cam72cam** [comment]
@bgrant0607 can you expand on this?  Version is populated by https://github.com/opentofu/opentofu/blob/main/version/VERSION.

**Comment by bgrant0607** [comment]
The providers set User-Agent here:
https://github.com/hashicorp/terraform-plugin-sdk/blob/main/helper/schema/provider.go#L497
