### ISSUE TITLE
Allow for refactoring of variables similar to `moved` blocks

### ISSUE THREAD

**Issue by slaughtr** [opentofu/opentofu#1856]
### OpenTofu Version

```shell
This applies to any version of tofu
```

### Use Cases

My primary usecase for this feature would be the ability to rename variables in modules, though I could also see usecases involving changing variable types such as moving some properties of an object/map type into a distinct variable.

It isn't infrequent that a module has a variable renamed - `custom_tags` to `tags` for instance - which frequently causes confusion for end users when updating modules. This becomes especially frustrating in situations where CI/CD is required for deployment, so the user cannot know ahead of time and must re-submit their work for approval after addressing the issue.

As mentioned, I could also see a usecase for moving properties of object/map variables into dedicated variables or vice-versa. This would probably also apply to list type variables.

### Attempted Solutions

On occasion I've used `null_resource` blocks in hacky ways to give deprecation notices, however this approach leads to a need to refactor the module a second time later to remove those and any leftover variables.

I'm not aware of other approaches I could have tried in this instance.

### Proposal

Either modify the `moved` block such that it allows this functionality, add some other dedicated block for this purpose, or add a property to the `variable` block.

Imagining the `moved` block and the usecase of renaming, it should work something like this:

```
moved {
  from = var.custom_tags
  to     = var.tags
  }
  ```
  
  I would presume the use of `var.` for a variable that doesn't exist would cause some problems though I'm not sure of the internals. In that case I could also see a property (`aliases` makes sense) on `variable` blocks:
  
  ```
  variable "tags" {
      type = map(string)
      ....
      aliases = [ "custom_tags" ]
  }
  ```

**Comment by RLRabinowitz** [comment]
Hey @slaughtr, thanks for filing this issue!

If I understand your use-case correctly, then I think that https://github.com/opentofu/opentofu/issues/1005 for deprecating variables would cover this. That issue has been accepted.

I'm closing this issue for now, feel free to re-open if you feel that https://github.com/opentofu/opentofu/issues/1005 does not answer your use-case 🙏🏻

**Comment by slaughtr** [comment]
That's excellent, I didn't come across that in my searches somehow. 

I think that answers my core usecase, thanks!
