### ISSUE TITLE
Make -var-file process substitution possible with JSON content

### ISSUE THREAD

**Issue by rndph** [opentofu/opentofu#1872]
### OpenTofu Version

```shell
OpenTofu v1.8.0
on linux_amd64
```

### Use Cases

I need some variables with secrets, so I can't directly put them into tfvars files. I have a script (internally using Ansible Vault) to generate a JSON file with the unencrypted variables, but I don't want to (even temporarily) store the plain text JSON on disk.
(Note: I know the variables will be in the plan/state files)

### Attempted Solutions

This is what would ideally work:
```
tofu plan -var-file=<(./scripts/decrypt_vault.sh)
╷
│ Error: Argument or block definition required
│
│   on /dev/fd/63 line 1:
│    1: {"secret1": "value1"}
│
│ An argument or block definition is required here.
╵
```

It uses [process substitution](https://en.wikipedia.org/wiki/Process_substitution) to call the script generating the JSON file with input variables. This way no temporary file is written to disk, and also no [named pipe](https://en.wikipedia.org/wiki/Named_pipe) is used, which would need to be manually removed.

I can see the reason behind it not working is that the file needs to have the `.json` extension.
Checked in: https://github.com/opentofu/opentofu/blob/c3ddd51d8ca7ac3bc8780356964cac60dab3479f/internal/command/meta_vars.go#L185

### Proposal

One way to support this would be to add a new parameter `-var-file-json` to all commands supporting `-var-file`.
Example: `tofu plan -var-file-json=<(./scripts/decrypt_vault.sh)`

What do you think?

**Comment by cam72cam** [comment]
I think this issue makes sense, as you point out we already support json in other scenarios.  The big question is do we introduce yet another flag or do we autodetect it.

>  (Note: I know the variables will be in the plan/state files)

Have you taken a look at state/plan encryption?  It is a solution to that problem.

**Comment by rndph** [comment]
> I think this issue makes sense, as you point out we already support json in other scenarios. The big question is do we introduce yet another flag or do we autodetect it.

If it can be easily and unambiguously autodetected, then I would say that is the best way to go.


> Have you taken a look at state/plan encryption? It is a solution to that problem.

Yes thanks. I am aware of that feature and plan on using it.

**Comment by cam72cam** [comment]
Spoke with the core team, looking at the first char being `[` or `{` should be sufficient.
