### ISSUE TITLE
Import fails when Id of resource contains dashes [Microsoft Azure]

### ISSUE THREAD

**Issue by estebanz01** [opentofu/opentofu#1877]
### OpenTofu Version

```shell
$ tofu --version
OpenTofu v1.7.3
on darwin_arm64
+ provider registry.opentofu.org/hashicorp/azurerm v3.113.0
```

### OpenTofu Configuration Files

```hcl
resource "azurerm_communication_service" "example" {
  name                = "example-with-dashes"
  resource_group_name = "Resources"
  data_location       = "United States"
}
```

### Debug Output

```
azurerm_communication_service.example: Importing from ID "/subscriptions/<valid-SubscriptionId>/resourceGroups/ACS/providers/Microsoft.Communication/CommunicationServices/example-with-dashes"...
╷
│ Error: parsing "/subscriptions/<valid-SubscriptionId>/resourceGroups/ACS/providers/Microsoft.Communication/CommunicationServices/example-with-dashes": parsing segment "staticCommunicationServices": parsing the CommunicationService ID: the segment at position 6 didn't match
│ 
│ Expected a CommunicationService ID that matched:
│ 
│ > /subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/example-resource-group/providers/Microsoft.Communication/communicationServices/communicationServiceValue
│ 
│ However this value was provided:
│ 
│ > /subscriptions/<valid-SubscriptionId>/resourceGroups/ACS/providers/Microsoft.Communication/CommunicationServices/example-with-dashes
│ 
│ The parsed Resource ID was missing a value for the segment at position 6
│ (which should be the literal value "communicationServices").
```

### Expected Behavior

It should identify the name of the resource as `example-with-dashes` and try to import it.

### Actual Behavior

It fails because it cannot recognise the last segment of the ID as `example-with-dashes`

### Steps to Reproduce

As long as you have a working `azurerm` provider with a valid subscription, you can replicate this. No need for the resource to import to exists.

1. `tofu init`
2. `tofu import azure_communication_service.example <Id-Resource>`

### Additional Context

Not sure if this the correct place to report it of it's something with the provider itself 🤷 so forgive me in advance if this is not proper place to report. Here's the provider.tf:

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
}

provider "azurerm" {
  features {}
}
```

**Comment by ollevche** [comment]
Hey @estebanz01, thank you for your issue! If I understand correctly, the error message says:

> The parsed Resource ID was missing a value for the segment at position 6 (which should be the literal value "communicationServices").

In your example, it is `CommunicationServices` (with capital C). Could you please double-check if that's the root cause?

**Comment by estebanz01** [comment]
hey @ollevche thanks for chiming in! 

Alright, so it seems that whatever reads and parse the resource ID expects `communicationServices` (with lowercase C) but the real value (that comes from Azure Portal) is with capital C `CommunicationServices`. Changing it magically worked 🎉 

Not sure how I missed that. I'll close this report 😁
