### ISSUE TITLE
Support for a complete file tree

### ISSUE THREAD

**Issue by mcantinqc** [opentofu/opentofu#1897]
### OpenTofu Version

```shell
1.8.0
```

### Use Cases

Currently, the file structure in Tofu is flat, meaning it is limited to a single level. As the codebase grows larger and more complex, it can become challenging to read and navigate. Although additional modules can be created, complexity can still arise within these modules.

Why not allow files to be read from subdirectories instead of just the current directory? The rest of the concept would remain the same; this change would only offer a way to logically separate the code, while maintaining identical interpretation.

This enhancement would greatly improve readability without relying on third-party solutions.

### Attempted Solutions

n/a

### Proposal

We cannot simply decide to read subdirectories, as this would break all existing code. Inspired by Python, which requires an __init__.py file for a directory to be interpreted as a package, OpenTofu could adopt a similar approach. We could require a .tofu file in subdirectories for them to be interpreted.

This solution would maintain compatibility with existing code while allowing for logical separation of more complex codebases.

**Comment by Evi1Pumpkin** [comment]
Hello and thank you for this issue! The core team regularly reviews new issues and discusses them, but this can take a little time. Please bear with us while we get to your issue. If you're interested, the contribution guide has a section about the [decision-making process](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md#who-decides-if-a-feature-will-be-implemented-and-how-is-that-decision-made).

**Comment by cam72cam** [comment]
Closing as not active.  Feel free to re-open if you wish to discuss this further.
