### ISSUE TITLE
Slack community invite link is broken

### ISSUE THREAD

**Issue by jimbocoder** [opentofu/opentofu#1923]
### OpenTofu Version

```shell
nil
```

### OpenTofu Configuration Files

nil

### Debug Output

nil

### Expected Behavior

Slack link should work

### Actual Behavior

https://opentofu.org/slack/ redirects to https://opentofucommunity.slack.com/join/shared_invite/zt-2hhw3bo2f-3yDLch0SBu93wNulf6z2pQ#/shared-invite/error which yields

![image](https://github.com/user-attachments/assets/724604f3-91f6-4272-acd1-b7135ac8f498)

### Steps to Reproduce

nil

### Additional Context

I couldn't find a better place to submit this report, sorry, I know this isn't exactly the right forum for it but I hope you can escalate appropriately or point me in the right direction

**Comment by cam72cam** [comment]
Should be fixed by https://github.com/opentofu/opentofu.org/pull/326 which is deploying now.

**Comment by cam72cam** [comment]
@jimbocoder should be fixed, let me know if you still have issues!
