### ISSUE TITLE
Introduce Set data structure for readability instead of using map[string]struct{} And []string etc

### ISSUE THREAD

**Issue by buraksenn** [opentofu/opentofu#1949]
### OpenTofu Version

```shell
Any
```

### Use Cases

It is actually not a feature request but simply adding a `Set` data structure to use across the repository for better readability. Here some of example use cases of Set data structure in repository:

- https://github.com/search?q=map%5Bstring%5Dstruct%7B%7D+repo%3Aopentofu%2Fopentofu&type=code&ref=advsearch
- https://github.com/opentofu/opentofu/blob/b6cd97f957bb83ec86928fee36178099c3c8decc/internal/command/jsonformat/computed/renderers/block.go#L21-L25

### Attempted Solutions

I have seen across the repo map[string]struct{}, []string and []int types are used to have an Set functionality. 

### Proposal

There are basically two options:
1 - Implement a generic Set function that is simply map[T Comparable]struct{}
2 - Use already existing open source libraries such as https://github.com/deckarep/golang-set

I think there is no need to add a dependency for a Set data structure so my proposal is to implement this Set data structure and refactor the repository such that Set data structure is used where it is applicable. I would like to do the whole work if it is accepted.

**Comment by cam72cam** [comment]
As this is a large legacy codebase, we don't have the resources to spend on performing or reviewing refactorings of this nature.

Thank you for your idea though, if the project were in a different stage of it's lifecycle it might be a different story.
