### ISSUE TITLE
Forbidden on tofu init

### ISSUE THREAD

**Issue by Vetrenik** [opentofu/opentofu#1951]
### OpenTofu Version

```shell
OpenTofu v1.8.1
on darwin_arm64
+ provider registry.opentofu.org/hashicorp/local v2.5.1
+ provider registry.opentofu.org/selectel/selectel v5.1.0
+ provider registry.opentofu.org/terraform-provider-openstack/openstack v2.0.0
```

### OpenTofu Configuration Files

terraform {
  required_providers {
    selectel = {
      source  = "selectel/selectel"
      version = "5.1.0"
    }
    openstack = {
      source  = "terraform-provider-openstack/openstack"
      version = "2.0.0"
    }
  }
}

### Debug Output

Initializing the backend...

Initializing provider plugins...
- Reusing previous version of selectel/selectel from the dependency lock file
- Reusing previous version of terraform-provider-openstack/openstack from the dependency lock file
- Reusing previous version of hashicorp/local from the dependency lock file
╷
│ Error: Failed to resolve provider packages
│ 
│ Could not resolve provider selectel/selectel: could not connect to registry.opentofu.org: failed to request discovery document: 403 Forbidden
╵

╷
│ Error: Failed to resolve provider packages
│ 
│ Could not resolve provider terraform-provider-openstack/openstack: could not connect to registry.opentofu.org: failed to request discovery document: 403 Forbidden
╵

╷
│ Error: Failed to resolve provider packages
│ 
│ Could not resolve provider hashicorp/local: could not connect to registry.opentofu.org: failed to request discovery document: 403 Forbidden

### Expected Behavior

Expected successfull init 

### Actual Behavior

Getting forbidden

### Steps to Reproduce

1. tofu init

**Comment by marriva** [comment]
```
 Reusing previous version of yandex-cloud/yandex from the dependency lock file
╷
│ Error: Failed to resolve provider packages
│ 
│ Could not resolve provider yandex-cloud/yandex: could not connect to
│ registry.opentofu.org: failed to request discovery document: 403 Forbidden
```

**Comment by cam72cam** [comment]
https://github.com/opentofu/opentofu/blob/main/README.md#registry-access
https://github.com/opentofu/opentofu/blob/main/TSC_SUMMARY.md#sanctions-russia-vs-registry-access
