### ISSUE TITLE
Failed to pull docker image

### ISSUE THREAD

**Issue by kvendingoldo** [opentofu/opentofu#1958]
### OpenTofu Version

```shell
1.8.0
```

### Debug Output

```
➜  ~ docker pull ghcr.io/opentofu/opentofu:1.8
Error response from daemon: Head "https://ghcr.io/v2/opentofu/opentofu/manifests/1.8": denied: denied
```

### Expected Behavior

docker images pulled

### Actual Behavior

 denied: denied

### Steps to Reproduce

docker pull ghcr.io/opentofu/opentofu:1.8

### Additional Context

Location: EU

**Comment by cam72cam** [comment]
This looks to be a connection issue between you and ghcr.io.

```
docker pull ghcr.io/opentofu/opentofu:1.8
930bdd4d222e: Download complete 
48c6dba7e8da: Download complete 
5eef993619bf: Download complete 
a20107e50995: Download complete 
ghcr.io/opentofu/opentofu:1.8
```

**Comment by Yantrio** [comment]
@kvendingoldo Is it possible you're hitting issues similar to this post? https://stackoverflow.com/questions/74795993/unable-to-pull-public-image-from-github-container-registry-ghcr
