### ISSUE TITLE
Allow a module to directly contain content structured in folders

### ISSUE THREAD

**Issue by Demivan** [opentofu/opentofu#1971]
### OpenTofu Version

```shell
OpenTofu v1.8.1
on linux_amd64
```

### Use Cases

When writing complex modules or infrastructure, it would be nice to organize .tf files into folders. The problem it that subfolders are automatically considered modules and require changing source code to function.

### Attempted Solutions

I have tried organizing code using modules. But it adds a lot of boilerplate (inputs and outputs) and makes "modules" too tightly coupled.

Using filename prefixes is another solution:
```
aws_iam.tf
aws_ecs.tf
gcp_iam.tf
gcp_bigquery.tf
```
But this is just reinventing folders without most of their benefits.

### Proposal

```hcl
folder {
  source = "some-path" # Includes all .tf files in the folder
}
```

or 

```hcl
include {
  files = "some-path/*.tf" # More configurable version
}
```

This would include all files in a folder into the current folder, allowing file organization without module encapsulation.

### References

- This is a port of Terraform feature proposal: https://github.com/hashicorp/terraform/issues/23047
- Similar to #1767, but used for code organization and not reuse. Could be implemented using the same feature.

**Comment by Evi1Pumpkin** [comment]
Hello and thank you for this issue! The core team regularly reviews new issues and discusses them, but this can take a little time. Please bear with us while we get to your issue. If you're interested, the contribution guide has a section about the [decision-making process](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md#who-decides-if-a-feature-will-be-implemented-and-how-is-that-decision-made).
