### ISSUE TITLE
Support environment variables "TOFU_CLI_ARGS_x"

### ISSUE THREAD

**Issue by muffl0n** [opentofu/opentofu#1972]
### OpenTofu Version

```shell
OpenTofu v1.8.2
on darwin_arm64
```

### Use Cases

Currently, one can specify arguments for `plan` or `apply` like so:
```
export TF_CLI_ARGS_plan="-concise"
export TF_CLI_ARGS_apply="-concise"
```
This comes in very handy, if you wann get rid of those pesky "Refreshing..." messages on every run.

Unfortunately, Terraform does not know of `-concise` and will throw an error like this
```
╷
│ Error: Failed to parse command-line flags
│ 
│ flag provided but not defined: -concise
╵
```
As we're in the middle of the transition from Terraform to OpenTofu and are using both more or less in parallel on different projects, this is pretty annoying. Also Terraform is not going to get away any time soon here, cause $reasons.

### Attempted Solutions

I wrote aliases for OpenTofu, but I'm not sure if this is the best solution
```
alias ttp="tofu plan -consice"
alias tta="tofu apply -consice"
```

### Proposal

Add environment variables `TOFU_CLI_ARGS_x`:
* `TOFU_CLI_ARGS_plan`
* `TOFU_CLI_ARGS_apply`
* ...

**Comment by Evi1Pumpkin** [comment]
Thanks for opening this issue!
I'm closing it as a duplicate as an issue like this already exists: https://github.com/opentofu/opentofu/issues/641
Please make sure to upvote the issue I mentioned. The more upvotes, the more we are likely to work on it.
Thanks Again.
