### ISSUE TITLE
Update migration guides

### ISSUE THREAD

**Issue by abstractionfactory** [opentofu/opentofu#1981]
### OpenTofu Version

```shell
1.8
```

### OpenTofu Configuration Files

N/A

### Debug Output

N/A

### Expected Behavior

The migration guides located at https://opentofu.org/docs/intro/migration/terraform-1.8/ should reference OpenTofu 1.8, not 1.7

### Actual Behavior

The guides reference 1.7

### Steps to Reproduce

N/A

### References

https://opentofu.org/docs/intro/migration/terraform-1.8/

**Comment by arunim2405** [comment]
@abstractionfactory
