### ISSUE TITLE
init with debug logging doesn't show module name for available versions

### ISSUE THREAD

**Issue by wyardley** [opentofu/opentofu#1988]
### OpenTofu Version

```shell
OpenTofu v1.8.2
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v6.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.32.0
+ provider registry.terraform.io/hashicorp/random v3.6.3
```

### OpenTofu Configuration Files

```hcl
provider "google" {
  project = "xxxx"
  region  = "us-central1"
  zone    = "us-central1-f"
}

terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "6.2.0"
    }
  }
}

module "gke" {
  source                     = "terraform-google-modules/kubernetes-engine/google//modules/private-cluster"
  version                    = "33.0.2"   // This will be available at some point, but could put any non-existent version in here.
  project_id                 = "xxxx"
  name                       = "test-cluster"
  service_account_name       = "foobarbaz"
  grant_registry_access      = true
  kubernetes_version         = "1.30.3-gke.1969000"
  release_channel            = "UNSPECIFIED"
  region                     = "us-central1"
  zones                      = ["us-central1-f"]
  network                    = "default"
  subnetwork                 = "us-central1"
  horizontal_pod_autoscaling = true
  enable_private_nodes       = true
  dns_cache                  = true
  ip_range_pods              = "foo-pods"
  ip_range_services          = "foo-services"
}
```

### Debug Output

https://gist.github.com/wyardley/0cccc2a773d218db415e3c477b1d77a2

### Expected Behavior

The debug output should show the name of the module for each version found, as it does with Terraform 1.5.x and 1.9.x (the versions I checked) e.g.:

```
2024-09-13T11:40:14.782-0700 [DEBUG] found available version "29.0.0" for terraform-google-modules/kubernetes-engine/google
```

### Actual Behavior

```
2024-09-13T11:38:03.399-0700 [DEBUG] found available version "29.0.0" for
```

### Steps to Reproduce

1. `tofu init -upgrade`

### Additional Context

From what I remember, the equivalent code for providers (vs. modules) does work properly in OpenTofu, but I didn't test extensively.

**Comment by Evi1Pumpkin** [comment]
Hello and thank you for this issue! The core team regularly reviews new issues and discusses them, but this can take a little time. Please bear with us while we get to your issue. If you're interested, the contribution guide has a section about the [decision-making process](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md#who-decides-if-a-feature-will-be-implemented-and-how-is-that-decision-made).

**Comment by arunim2405** [comment]
Opened a PR https://github.com/opentofu/opentofu/pull/2009 to fix this, waiting for feedback.
