### ISSUE TITLE
default attribute values of object variables are ignored in tests

### ISSUE THREAD

**Issue by berahtlv** [opentofu/opentofu#2018]
### OpenTofu Version

```shell
OpenTofu v1.8.2
```

### OpenTofu Configuration Files

main.tf
```hcl
variable "root_disk" {
  type = object({
    type       = optional(string, "gp3")
    size       = optional(number, 40)
    iops       = optional(number)
    throughput = optional(number)
  })
}
```
tests.tftest.hcl
```hcl
run "root_disk_var" {

  command = plan

  variables {
    root_disk = {
      size = 60
    }
  }

  assert {
    condition = var.root_disk == {
      size = 60
    }
    error_message = "Value is incorrect"
  }
}

```

### Debug Output

terraform.tfvars
```hcl
root_disk = {
  size = 60
}
```
tofu console
```hcl
> var.root_disk
{
  "iops" = tonumber(null)
  "size" = 60
  "throughput" = tonumber(null)
  "type" = "gp3"
}

```

### Expected Behavior

Test should fail since `root_disk` object has default value for `type` attribute.

### Actual Behavior

Test is successful even though the attribute with a default value is missing.

### Steps to Reproduce

tofu test

**Comment by ollevche** [comment]
Hello @berahtlv and thank you for your issue!

I took a quick look and it works the same way for me. We handled variable defaults [here](https://github.com/opentofu/opentofu/blob/300_static_evaluate_provider_mappings_config_tests/internal/command/test.go#L1127), but didn't take into account variable type.

It looks like a bug indeed so let us get back to you after the core team discussion.

**Comment by apparentlymart** [comment]
Looking at the example from the original issue, I'd not that as currently written that test ought to also fail for a different reason as currently written, because:

- `var.root_disk` is declared as being of an object type with four attributes
- the `assert` block's `condition` is comparing it to a value of type `object({size = number})`, without the other three attributes.
- The `==` can only return `true` if the two operands have exactly the same type.

If the test harness were correctly setting `var.root_disk` to have the same value it would have when used inside the module -- which I assume is the intent -- then in order to pass this test would need to change to one of the two following forms:

```hcl
run "root_disk_var" {
  command = plan

  variables {
    root_disk = {
      size = 60
    }
  }

  assert {
    # This variation would fail immediately if any new
    # attributes were added to the variable's type
    # constraint in future.
    condition = var.root_disk == {
      size       = 60
      type       = "gp3"
      iops       = tonumber(null)
      throughput = tonumber(null)
    }
    error_message = "Value is incorrect"
  }
}
```

```hcl
run "root_disk_var" {
  command = plan

  variables {
    root_disk = {
      size = 60
    }
  }

  # This variation tolerates the addition of new attributes
  # without failing, by testing each attribute separately.
  assert {
    condition = (var.root_disk.size == 60)
    error_message = "Size is incorrect"
  }
  assert {
    condition = (var.root_disk.type == "gp3")
    error_message = "Type is incorrect"
  }
  assert {
    condition = (var.root_disk.iops == tonumber(null))
    error_message = "IOps is incorrect"
  }
  assert {
    condition = (var.root_disk.throughput == tonumber(null))
    error_message = "Throughput is incorrect"
  }
}
```

It seems like at the moment the bug reported by this issue is masking this problem. I'm mentioning it here only in the hope that it's helpful to someone working on this issue in future, since there is more than one way for the given example to fail and so it starting to fail does not necessarily mean that the bug is fixed.

**Comment by AdosH1** [comment]
Hey @cam72cam, may I take a look at this?

**Comment by ollevche** [comment]
Hey @AdosH1 thank you for volunteering! Let me assign you, but before opening a PR, please describe your approach here so we can sync on the chosen implementation path.

**Comment by AdosH1** [comment]
@ollevche I've been having a look around and I'm confused why the `test` command (with plan) appears to do things quite differently from the tests for `plan` command
I don't really have a strong opinion for ApparentlyMart's assertation methodology, but leaning towards the exact object matching given its for the test command (which we have full control over inputs)

In terms of the solution, I think the `configVariables` should contain a `Default` cty value of that object, and attempt to set each field that hasn't been set earlier. Would that be a reasonable start on this issue?

**Comment by ollevche** [comment]
Hey @AdosH1! Sorry for delay with reply from my side.

I think to resolve this particular issue (type defaults are not being applied to test variables), we need to extend `parseAndApplyDefaultValues` function to also handle `TypeDefaults` from config variables.

Object comparison is out of the scope of this particular bug in my opinion.

**Comment by AdosH1** [comment]
Thanks ollevche, I will take a look in the coming week :pray:

**Comment by ollevche** [comment]
Hey @AdosH1, thanks again for volunteering on this issue!

We plan to include it in the beta release this week and I am happy to help in any possible way. I can also take over the issue or finish the implementation if you are tight on time. Sorry for not making the timeline clear beforehand.

**Comment by AdosH1** [comment]
Apologies @ollevche I was intending to take a look near the end of this week since its been a bit hectic recently, please take over this issue 🙏
