### ISSUE TITLE
Intermittent tofu validate error when variable conditions use provider defined functions

### ISSUE THREAD

**Issue by david1437** [opentofu/opentofu#2051]
### OpenTofu Version

```shell
OpenTofu v1.8.3
on linux_amd64
```

### OpenTofu Configuration Files

```hcl
variable "obfuscated" {
  type = object({
    arns = optional(list(string))
  })
  description = "Configuration for xxx."

  validation {
    condition = alltrue([
      for arn in var.obfuscated.arns: can(provider::aws::arn_parse(arn))
    ])
    error_message = "All arns MUST BE a valid AWS ARN format."
  }
}
```

### Debug Output

trace log: https://gist.github.com/david1437/7453bac23c51643998c627ffdce54920

Error: BUG: Uninitialized function provider

  on ../../xxx/xxx/variables.tf line 47, in variable "loadbalancer_config":
  47:       can(provider::aws::arn_parse(var.loadbalancer_config.certificate_arn)),

Provider "provider[\"registry.opentofu.org/hashicorp/aws\"]" has not yet been
initialized

Error: BUG: Uninitialized function provider

  on ../../xxx/xxx/variables.tf line 160, in variable "keystore_config":
 160:     condition     = can(provider::aws::arn_parse(var.keystore_config.private_ca_arn)) || can(provider::aws::arn_parse(var.keystore_config.certificate_arn))

Provider "provider[\"registry.opentofu.org/hashicorp/aws\"]" has not yet been
initialized

Error: BUG: Uninitialized function provider

  on ../../xxx/xxx/variables.tf line 160, in variable "keystore_config":
 160:     condition     = can(provider::aws::arn_parse(var.keystore_config.private_ca_arn)) || can(provider::aws::arn_parse(var.keystore_config.certificate_arn))

Provider "provider[\"registry.opentofu.org/hashicorp/aws\"]" has not yet been
initialized

Error: BUG: Uninitialized function provider

  on ../../xxx/xxx/variables.tf line 183, in variable "tenant_manager_config":
 183:       for arn in var.tenant_manager_config.trusted_entity_arns : can(provider::aws::arn_parse(arn))

Provider "provider[\"registry.opentofu.org/hashicorp/aws\"]" has not yet been
initialized

### Expected Behavior

Configuration should be validated as successfull

### Actual Behavior

tofu crashes at runtime reporting that provider is not yet initialized

### Steps to Reproduce

It is intermittent issue so reccomend running multiple iterations. NOTE with trace log enabled it took over 150 iterations so it seems it somehow makes issue less likely?
`for i in {1..10}; do tofu init --backend=false &> /dev/null; tofu validate -no-color &> tf_trace_log_$i.txt; done;`

### Additional Context

It seems to be a very intermittent issue and sometimes no errors are returned.  In my testing seems to be about 1 in 10 chance that an error occurs.  I know nothing of this codebase so take with a grain of salt, but it seems to be some kind of concurrency issue?

**Comment by cam72cam** [comment]
Thanks for the issue report @david1437, I'm taking a look now.

**Comment by cam72cam** [comment]
```
2024-10-04T09:31:00.954-0700 [TRACE] Completed graph transform *tofu.AttachSchemaTransformer (no changes)
2024-10-04T09:31:00.954-0700 [TRACE] Executing graph transform *tofu.ProviderFunctionTransformer
2024-10-04T09:31:00.985-0700 [TRACE] Completed graph transform *tofu.ProviderFunctionTransformer (no changes)
2024-10-04T09:31:00.986-0700 [TRACE] Executing graph transform *tofu.PruneProviderTransformer
2024-10-04T09:31:00.990-0700 [TRACE] Completed graph transform *tofu.PruneProviderTransformer (no changes)
2024-10-04T09:31:00.991-0700 [TRACE] Executing graph transform *tofu.ModuleExpansionTransformer
```

Could you post the corresponding lines when it succeeds?

**Comment by cam72cam** [comment]
Digging a bit further in, it looks like there's an issue tracking references for that particular use case.

**Comment by cam72cam** [comment]
I think I've tracked down the source of the issue, I'll keep you posted.

**Comment by cam72cam** [comment]
```hcl
// main.tf 
terraform {
        required_providers {
                aws = ">=5.70.0"
        }
}

provider "aws" {
        region="us-east-1"
}

module "mod" {
        source = "./mod"
        providers = {
                aws = aws
        }
}
```

```hcl
// mod/mod.tf 
terraform {
        required_providers {
                aws = ">=5.70.0"
        }
}

variable "obfmod" {
  type = object({
    arns = optional(list(string))
  })
  description = "Configuration for xxx."

  validation {
    condition = alltrue([
      for arn in var.obfmod.arns: can(provider::aws::arn_parse(arn))
    ])
    error_message = "All arns MUST BE a valid AWS ARN format."
  }

  default = {
        arns = [
          "arn:partition:service:region:account-id:resource-id",
        ]
  }
}
```

**Comment by david1437** [comment]
thanks @cam72cam, is there a timeline on next release to 1.8.x that I can reference?

**Comment by cam72cam** [comment]
I should be wrapping up the PR today and am hoping to have the bugfix release out in the next 48 hours (pending team discussion).

**Comment by cam72cam** [comment]
@david1437 I found some other concerning behavior and am still digging in to those fixes.  I'll keep this thread linked to all of those changes.

**Comment by david1437** [comment]
Thanks @cam72cam I appreciate the dilligence in resolving these issues, please let me know if there is any info you need to help further.

**Comment by cam72cam** [comment]
Going to have a second PR to fix some of the related issues found when investigating this in depth.
