### ISSUE TITLE
Functions to convert to and between different identifier case schemes (camelcase, etc) 

### ISSUE THREAD

**Issue by alex067** [opentofu/opentofu#2053]
### OpenTofu Version

```shell
OpenTofu v1.8.3
on darwin_arm64
```

### The problem in your OpenTofu project

Direct copy of issue on Terraform: https://github.com/hashicorp/terraform/issues/25230 

> Hello,
> 
> I wanted to programmatically set names to a few resources (which requires some manipulation), however since the terraform language does not support user defined functions this has become a limitation
> 
> eg. I want to dynamically set the name of an AWS S3 bucket to the name of the current project
> so My Project -> my-project (kebab case)
> 
> My suggestion would be to add these utility functions which will greatly extend the flexibility of naming resources
> 
> camelCase
> kebab-case
> snake_case
> PascalCase

These conversion functions would be extremely helpful. At the moment the common workaround is simply use regex or chaining replace statements, but having native functions would encapsulate this logic (who wants to work with regex?).

### Attempted Solutions

Have not attempted a solution yet but will gladly try to do so soon.

### Proposal

Introduce native style conversion functions. Proposed naming:

1. tocamelcase(string) -> string 
2. tosnakecase(string) -> string
3. topascalcase(string) -> string 
4. tokebabcase(string) -> string 

An alternative would be to have a single function `tocase(string, string)` where the requested case is supplied as an argument.

**Comment by cam72cam** [comment]
Thanks for the issue @alex067, we are not planning on adding many, if any, additional functions to OpenTofu core.  Instead, provider defined functions are the recommended solution and work in both OpenTofu and Terraform.

You can either create a new provider using the provider SDK,like https://github.com/hashicorp/terraform-provider-assert, or use one of the experimental go or lua function providers to quickly define your own functions.

https://github.com/opentofu/terraform-provider-go
https://github.com/opentofu/terraform-provider-lua
