### ISSUE TITLE
Make tofu plan output iterable/machine readable for automation via flag

### ISSUE THREAD

**Issue by trc-rkorneev** [opentofu/opentofu#2066]
### OpenTofu Version

```shell
1.8.3
```

### The problem in your OpenTofu project

In order to automate Tofu deployments, it is sometimes useful to check how many resources are going to be changed for a specific tofu plan. Currently the output of the plan is written to terminal and text manipulation is required to quickly analyse on how many resources will be changed/created/destroyed

It would be nice to obtain a JSON that is quickly readable to check for expected amount of changes

### Attempted Solutions

Generating a plan to a file and doing string search magic to obtain info on how many resources will be created / replaced / destroyed 

### Proposal

create a flag for the plan command like --json-summary="path/to/file.json"
should only contain the minimum of output that is usually shown on the bottom of the plan
for eg. {
created : 4
replaced :1
destroyed : 0
}

With that automation tools could access this information faster and act based on pre-specified rules of a for e.g. pipeline

**Comment by Yantrio** [comment]
Hi @trc-rkorneev, there is currently a mechanism to do this in a bit of a round-about way.

You can use `tofu plan -out planfile` to save the planfile and then `tofu show -json planfile` to show the planfile in json format. 

You can then use JQ or any other json parsing tool to comprehend the output. If you'd like some more guidance around this or extracting specific data please feel free to reach out!
