### ISSUE TITLE
New Relic Provider: Dashboard widget_table doesn't support initial_sorting

### ISSUE THREAD

**Issue by Schbatzafresser** [opentofu/opentofu#2076]
### OpenTofu Version

```shell
v1.7.1
```

### The problem in your OpenTofu project

Tofus' New Relic provider does not support Dashboard widget_table  initial_sorting

### Attempted Solutions

Implement handling for initial_sorting nested block as in 
https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/one_dashboard#initial_sorting

### Proposal

```
  page {
    name = "SLIs"

    widget_table {
      title  = "Success Rate by Monitor"
      row    = 1
      column = 1
      height = 6
      width  = 4

      // Current version of Open ToFu does not support this feature yet
      /*
      initial_sorting {
        name      = "appName"
        direction = "asc"
      }
      */
```

**Comment by ollevche** [comment]
Hey @Schbatzafresser thank you for the issue!

OpenTofu Registry contains the latest version of newrelic provider (`3.50.0`). Please share an error you are getting and configuration to reproduce it.
