### ISSUE TITLE
opentofu init preprocessor - for rewritting modules source, including child modules

### ISSUE THREAD

**Issue by thoeng-nuuday** [opentofu/opentofu#2110]
### OpenTofu Version

```shell
not relevant
```

### The problem in your OpenTofu project

When initializing a terraform project rewrite a module source locations. This is for helping migrating terraform projects with many private modules from one private registry to another without changing the module src. 

Its one of the largest hindrance in our organization on adopting open-tofu and migrate away from tf cloud, since it requires a large effort on changing all private modules across all the versions in use.

### Attempted Solutions

n/a

### Proposal

module-src.hcl
```
module-source {
  from = "app.terraform.io/<private-xxxx>/my-module/aws"
  to      = "private-tf-registry.example.com/<private-xxxx>/my-module/aws"
}
module-source {
  from = "app.terraform.io/<private-xxxx>/another-my-module/aws"
  to      = "private-tf-registry.example.com/<private-xxxx>/another-my-module/aws"
}
```
tofu init -module-rewrite=./modul-src.hcl 

Expected outcome. 

The tofu init, replace the source prior to fetching the module, and does it recursive for fetched modules. This could also be expanded to rewrite provider location.

**Comment by apparentlymart** [comment]
In case it's useful in the meantime, I've written this small (and not very robust!) standalone program that I think could help with the specific situation described in the issue summary:

```hcl
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	hcl "github.com/hashicorp/hcl/v2"
	"github.com/hashicorp/hcl/v2/hclsyntax"
	"github.com/hashicorp/hcl/v2/hclwrite"
)

func main() {
	flag.Parse() // find and reject any option-shaped arguments, since we don't use any

	if len(os.Args) != 4 {
		failf("Usage: tofu-rewrite-module-sources <module-dir> <old-prefix> <new-prefix>\n")
	}
	moduleDir := os.Args[1]
	oldPrefix := []byte(os.Args[2])
	newPrefix := []byte(os.Args[3])

	allEntries, err := os.ReadDir(moduleDir)
	if err != nil {
		failf("Can't read entries from %s: %s\n", moduleDir, err)
	}

	for _, entry := range allEntries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if strings.HasPrefix(name, ".") {
			continue
		}
		if !(strings.HasSuffix(name, ".tf") || strings.HasSuffix(name, ".tofu")) {
			continue
		}

		filename := filepath.Join(moduleDir, name)

		src, err := os.ReadFile(filename)
		if err != nil {
			failf("Can't read %s: %s\n", filename, err)
		}

		f, diags := hclwrite.ParseConfig(src, filename, hcl.InitialPos)
		handleDiags(diags)

		modifiedBlocks := 0
		for _, block := range f.Body().Blocks() {
			if block.Type() != "module" {
				continue
			}

			attr := block.Body().GetAttribute("source")
			if attr == nil {
				// Weird because a module is required to have a source address,
				// but we'll tolerate it.
				continue
			}
			expr := attr.Expr()

			// Since we're working with hclwrite we're dealing with raw syntax
			// tokens here, rather than the higher-level HCL expressione evaluator.
			// That makes the following quite gnarly but not too bad if we assume
			// "source" always starts with a static string. (This makes only a best
			// effort to handle static-eval expressions in source; it works only
			// if using a quoted template with an interpolation somewhere after the
			// prefix.)
			tokens := expr.BuildTokens(nil)

			// There must be at least two tokens, the first one must be TokenOQuote,
			// and the second must be a quoted literal that we might then modify.
			if len(tokens) < 2 || tokens[0].Type != hclsyntax.TokenOQuote || tokens[1].Type != hclsyntax.TokenQuotedLit {
				continue
			}

			if bytes.HasPrefix(tokens[1].Bytes, oldPrefix) {
				newBytes := make([]byte, 0, len(tokens[1].Bytes)-len(oldPrefix)+len(newPrefix))
				newBytes = append(newBytes, newPrefix...)
				newBytes = append(newBytes, tokens[1].Bytes[len(oldPrefix):]...)
				tokens[1].Bytes = newBytes

				block.Body().SetAttributeRaw("source", tokens)
				modifiedBlocks++
			}
		}
		if modifiedBlocks > 0 {
			// We need to overwrite the file with our modifications, then.
			newBytes := f.Bytes()
			err := os.WriteFile(filename, newBytes, entry.Type().Perm())
			if err != nil {
				failf("failed to write changes to %s: %s", filename, err)
			}
			fmt.Printf("updated %s\n", filename)
		}
	}
}

func failf(f string, args ...any) {
	fmt.Fprintf(os.Stderr, f, args...)
	os.Exit(1)
}

func handleDiags(diags hcl.Diagnostics) {
	if len(diags) == 0 {
		return
	}
	w := hcl.NewDiagnosticTextWriter(os.Stderr, nil, 72, true)
	w.WriteDiagnostics(diags)
	if diags.HasErrors() {
		os.Exit(1)
	}
}
```

When I tested this I ran it as:

```shell
rewrite-module-sources . 'old-registry.example.com/' 'new-registry.example.com/'
```

...and it replaced all of the `old-registry.example.com/` source addresses in my test module with equivalent `new-registry.example.com/` addresses, retaining the remainder of each source address.

This program will _tolerate_ early eval interpolations in the source address string if they don't interfere with the specified prefix, but I intended this mainly for folks who are using literal string source addresses written in the usual way.

If you try to use this, please make sure you work in a temporary directory where you don't need to worry about losing work. This program is not super robust against complications like invalid input syntax, etc, so I can't promise that it won't mess up something else in your module if the input isn't ideal. But if you run in a clean directory then presumably you can use your version control system to inspect what it changed, make sure it makes sense, and discard the changes if not.

**Comment by apparentlymart** [comment]
The idea I discussed in https://github.com/opentofu/opentofu/issues/618#issuecomment-2435793347 seems like it might be another candidate solution to this use-case, although it would be considerably broader than what's proposed.

Specifically it would tell OpenTofu to use different endpoints for _all_ of the services belonging to the hostname you want to migrate away from, which would also include provider registry services. That would be handled as a dynamic redirection within the service discovery system rather than in the specific service clients.

**Comment by cam72cam** [comment]
Thanks for the issue, hopefully Martin's comments help you work around this limitation.
