### ISSUE TITLE
OpenTofu passes unknown values to custom functions as unitialized structs

### ISSUE THREAD

**Issue by isometry** [opentofu/opentofu#2126]
### OpenTofu Version

```shell
OpenTofu v1.8.4
on darwin_arm64
+ provider registry.opentofu.org/isometry/deepmerge v0.3.1
```

### OpenTofu Configuration Files

```hcl
terraform {
  required_providers {
    deepmerge = { source = "isometry/deepmerge" }
  }
}

resource "terraform_data" "test" {
  input            = { foo = "bar" }
}

output "builtin" {
  value = jsonencode(terraform_data.test.output)
}

output "custom" {
  value = provider::deepmerge::mergo({ bam = terraform_data.test.output })
}
```

### Debug Output

https://gist.github.com/isometry/4ae7b2fa45fd563d4dcf94be6debc231

### Expected Behavior

As it does for built-in functions, when OpenTofu calls a custom function with an unknown value parameter, and that custom function parameter is configured to not allow unknown values (i.e. `AllowUnknownValues: false`), the custom function call itself should return an unknown value.

```
OpenTofu used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

OpenTofu will perform the following actions:

  # terraform_data.test will be created
  + resource "terraform_data" "test" {
      + id     = (known after apply)
      + input  = {
          + foo = "bar"
        }
      + output = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + builtin = (known after apply)
  + custom  = (known after apply)  # <== EXPECTED
```

### Actual Behavior

When OpenTofu calls a custom function with an unknown value parameter, it actually passes an uninitialized value struct to the custom function. This leads to unexpected behaviour, including failure to converge in a single plan and custom functions being exposed to invalid data. In the worst cases this can result in unstable infrastructure and provider panics due to nil deref (even when trying to validate null values in accordance with the provider API).

```
OpenTofu used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

OpenTofu will perform the following actions:

  # terraform_data.test will be created
  + resource "terraform_data" "test" {
      + id     = (known after apply)
      + input  = {
          + foo = "bar"
        }
      + output = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + builtin = (known after apply)
  + custom  = {
      + bam = {}  # <== UNEXPECTED
    }
```

### Steps to Reproduce

1. `tofu init`
2. `tofu plan`

### Additional Context

I identified this issue whilst investigating isometry/terraform-provider-deepmerge#48. I've added a "workaround" to the provider to avoid the panic, but clearly the real issue is with OpenTofu's handling of custom function parameters.

This issue is *not* present in HashiCorp Terraform, which behaves as expected.

### References

- isometry/terraform-provider-deepmerge#48
- isometry/terraform-provider-deepmerge#50

**Comment by cam72cam** [comment]
`value = provider::deepmerge::mergo({ bam = terraform_data.test.output })` does not hit the standard cty IsKnown check because the map is partially known `{bam = cty.UnknownValue(...)}`.

`value = provider::deepmerge::mergo(terraform_data.test.output )` does hit the standard cty IsKnown check as the full value is unknown.

OpenTofu uses `msgpack.Marshal` to encode the value, which preserves the partially known state.  I need to dive into the provider sdk/tooling to see how it's handled on the provider plugin side.

My guess at this point is that terraform adds a check for "IsWhollyKnown" before calling the provider function directly and short cuts if it's not fully known.

**Comment by cam72cam** [comment]
Based on cty's stdlib concat function, `value = provider::deepmerge::mergo({ bam = terraform_data.test.output })` should probably return `{bam: <unknown value>}`.  It's unclear if what terraform is doing is a bug as you are being provided the true partially known argument to deal with as you wish.

**Comment by cam72cam** [comment]
I re-read the provider protocol and found a comment explaining this https://github.com/opentofu/opentofu/blob/main/internal/tfplugin6/tfplugin6.pb.go#L1957-L1961.  I'm not sure why this decision was made as it seems to function just fine when using the standard unknown/partial unknown conventions, but it does point at a mismatch in OpenTofu.

**Comment by isometry** [comment]
Thanks for jumping on this @cam72cam !

As you've identified in protocol, it seems pretty clear that `AllowUnknownValues: false` should short-circuit unless the the values are wholly known. If a function wants to opt-in to handling unknowns, then it's free to set `AllowUnknownValues: true` :-)
