### ISSUE TITLE
Error: provider provider["registry.opentofu.org/hashicorp/aws"].<alias> not initialized is not very explanatory

### ISSUE THREAD

**Issue by saimonn** [opentofu/opentofu#2149]
### OpenTofu Version

```shell
OpenTofu v1.9.0-alpha1
on linux_amd64
+ provider registry.opentofu.org/hashicorp/aws v5.74.0
```

### OpenTofu Configuration Files

```hcl
provider "aws" {
  for_each = var.students

  alias = "student"

  assume_role {
    role_arn = "arn:aws:iam::${module.student-account[each.key].account.id}:role/OrganizationAccountAccessRole"
  }
}

# create 1 AWS account per student
module "student-account" {
  source = "./mod-student-account"

  for_each   = var.students

  email      = each.value["email"]
  student_id = each.key
  parent_id  = aws_organizations_organizational_unit.training.id

}
```

### Debug Output

[available on request]

### Expected Behavior

I'd like to know what is wrong and how to fix it.
Should I decommission resources before I remove the providers ?
Do I have orphan resources ? Do I have a broken state ?

### Actual Behavior

The current error messages are not very explanatory: 
```
Planning failed. OpenTofu encountered an error while generating this plan.

╷
│ Error: provider provider["registry.opentofu.org/hashicorp/aws"].student not initialized
│
│
╵
╷
│ Error: provider provider["registry.opentofu.org/hashicorp/aws"].student not initialized
│
│
╵
```

### Steps to Reproduce

`tofu destroy`

### Additional Context

using tofu with the followin context:
 - env variables comming from `summon` (AWS credentials)
 - tf variables comming from `terragrunt`
 
the full command I used to get this error is:
`TF_LOG=debug summon -up tofu destroy --var-file=./terragrunt-debug.tfvars.json`

**Comment by cam72cam** [comment]
Thanks for the report, taking a deeper look this morning

**Comment by cam72cam** [comment]
I think I've got it nailed down, should have a PR shortly.

**Comment by cam72cam** [comment]
@saimonn 1.9.0-alpha2 is out with this fix :+1: 

Thanks for testing!
