### ISSUE TITLE
Functions used in module calls values don't work as expected

### ISSUE THREAD

**Issue by jonjohnsonjr** [opentofu/opentofu#2175]
### OpenTofu Version

```shell
(This is at commit `52cc91c87a3d5e0a365e0d96a27f76f2d24cb317`)

OpenTofu v1.9.0-dev
on darwin_arm64
```

### OpenTofu Configuration Files

```hcl
module "test-versioned" {
  for_each        = module.versions.versions
  crds_repository = provider::oci::parse(module.versioned[each.key].image_ref).registry_repo
  crds_tag        = provider::oci::parse(module.versioned[each.key].image_ref).pseudo_tag
}
```

### Debug Output

n/a

### Expected Behavior

No error.

### Actual Behavior

```
Error: BUG: Uninitialized function provider
 
   on .../main.tf line 39, in module "test-versioned":
   39:   crds_repository = provider::oci::parse(module.versioned[each.key].image_ref).registry_repo
 
 Provider function "provider::oci::parse" has not been tracked properly
```

### Steps to Reproduce

I have not come up with a repro for this but I can if needed.

### Additional Context

Everywhere else we call this function is inside a `locals {}` block, so I assume it's related to crossing module boundaries.

**Comment by cam72cam** [comment]
@jonjohnsonjr helped me check a patch, I'll have a PR tomorrow.  tl;dr is that variable evaluation scopes are complicated and needs to use GraphNodeReferenceOutside

**Comment by cam72cam** [comment]
This is linked to https://github.com/opentofu/opentofu/issues/1336
