### ISSUE TITLE
Avoid ModuleInstance.Module() allocations

### ISSUE THREAD

**Issue by jonjohnsonjr** [opentofu/opentofu#2253]
### OpenTofu Version

```shell
tofu version
OpenTofu v1.9.0-dev
on darwin_arm64
```

### The problem in your OpenTofu project

Our project is large, so we end up hitting any weird performance edges.

[`ModuleInstance.Module()`](https://github.com/opentofu/opentofu/blob/f6a1d8e2dd6505c2f60c39955a10c473ed2210a5/internal/addrs/module_instance.go#L463) gets called a lot, in large part because [this implementation in `DynamicExpand`](https://github.com/opentofu/opentofu/blob/f6a1d8e2dd6505c2f60c39955a10c473ed2210a5/internal/tofu/node_resource_plan.go#L106) is really inefficient (similar to https://github.com/opentofu/opentofu/issues/2252). We should probably fix that by revisiting the overall implementation to make it less quadratic, but a good portion of the current runtime is taken up by allocations in `Module()`.

Looking at what calls `makeslice`: 
<img width="1792" alt="image" src="https://github.com/user-attachments/assets/4e6753ab-3eaf-4d99-904a-b66dbba34db4">

You can see each call to `Module()` ends up allocating a slice, which slows things down a lot.

### Attempted Solutions

I added a little method that turns the [`.Module().Equal(addr)`](https://github.com/opentofu/opentofu/blob/f6a1d8e2dd6505c2f60c39955a10c473ed2210a5/internal/states/state.go#L97) into a single method so that it didn't have to allocate anything to compare a module to an address:

```
+func (m ModuleInstance) ModuleEqual(other Module) bool {
+       if len(m) != len(other) {
+               return false
+       }
+       for i := range m {
+               if m[i].Name != other[i] {
+                       return false
+               }
+       }
+       return true
+}
+
```

This _did_ help, speeding up that portion by ~10x (2s -> 200ms), and I did a similar but kind of gross thing in [`InstancesForConfigResource`](https://github.com/opentofu/opentofu/blob/f6a1d8e2dd6505c2f60c39955a10c473ed2210a5/internal/plans/changes.go#L95) to avoid calling `AbsResource.Config().Module()` and allocating, which did work but felt like I was reaching around the abstractions to try to get perf, and I didn't like it.

I think similarly, we probably want a better way to access resources such that we don't have to iterate over the entire thing. 

### Proposal

No great proposals here other than what I shared above. The `ModuleEqual` thing might be fine for now, but it's probably better to refactor this code a bit to allow faster access patterns.

**Comment by apparentlymart** [comment]
Thanks for this, @jonjohnsonjr.

There's a bunch of legacy here that dates back to much older versions of this codebase that were doing almost everything of this sort by dynamically building strings and then comparing them. 

`package addrs` started down the road of improving that by at least wrapping a layer of abstraction around it, but there are still various cases that still build and compare strings or slices as an implementation detail. Gradually replacing them with functions that can just compare directly without allocating anything new is a good goal, though I expect it won't be easy in all cases. We can at least do the ones that have a notable performance benefit, like this one, though.

**Comment by apparentlymart** [comment]
I went hunting in the code because I thought I remembered there already being a function that takes two `AbsModuleInstance` and determines whether they are instances of the same module. But I guess I was actually thinking of `ModuleInstance.IsDeclaredByCall`, which is a _similar_ idea but not the same:

https://github.com/opentofu/opentofu/blob/f6a1d8e2dd6505c2f60c39955a10c473ed2210a5/internal/addrs/module_instance.go#L486-L506

Still, there is definitely precedent for adding extra helper methods like this to be able to ask common questions more efficiently without having to first construct an address value of some other type.
