### ISSUE TITLE
Support OpenTofu in Terragrunt

### ISSUE THREAD

**Issue by roni-frantchi** [opentofu/opentofu#24]
We would want to make our presence in popular tools in the community.  
Being able to use OpenTF when using Terragrunt would be a great way to do taht.

**Comment by maunzCache** [comment]
Not sure if there is anything this project can provide. So i'd put a reference to the terragrunt issue https://github.com/gruntwork-io/terragrunt/issues/2690 for that feature.

What would be interesting, whether OpenTofu wants to adopt features of terragrunt and make them "canonical" to tofu.

**Comment by maunzCache** [comment]
One further addition to the topic to increase support would be to define an interface that would allow to use some OpenTofu internals. terragrunt still depends on `github.com/hashicorp/terraform v0.15.3` for some operations which is nothing terragrunt can depend on in the future as this "API" might drift further apart.
If this should desired one should consider to separate it from the opentofu repository and create something like an opentofu-lib so it is clearly defined what is accessible API and what not.

I am unsure whether @denis256 would like to support either variant or if a switch to OpenTofu is desired. Still other tools could benefit from it too.

**Comment by maunzCache** [comment]
Yes but not before i did the comment. I believe this issue might be closed then :)

**Comment by cube2222** [comment]
Closing as [done](https://terragrunt.gruntwork.io/docs/getting-started/supported-versions/).
