### ISSUE TITLE
Support OpenTofu in TFenv

### ISSUE THREAD

**Issue by roni-frantchi** [opentofu/opentofu#25]
We would want to make our presence in popular tools in the community.  
Being able to use OpenTF when using TFenv would be a great way to do that.

**Comment by skyzyx** [comment]
Cross-linking: https://github.com/tfutils/tfenv/issues/409

**Comment by xoxys** [comment]
Maybe having an opentofu community org or something similar would help to maintain such tools around the ecosystem in the future. Looks like getting this change into `tfenv` or `tfswitch` seems to be hard.

**Comment by Zordrak** [comment]
https://github.com/tfutils/tfenv/issues/409#issuecomment-1863021455

> We have reviewed this request and the associated PR in detail and given the question a lot of thought. In conclusion we do not believe this is an appropriate course of action.
> 
> The changes needed, as demonstrated in the PR, show that the inclusion of support for OpenTofu is not a minor case switch. It would be the wholesale adoption of an entirely new binary. This binary does its own thing, has its own release process and governance, and by design has no guaranteed or even implied contract to continue to be released and versioned in the same way as the terraform binary. An immediately obvious example of this is the hashicorp support for keybase that is not mentioned or accounted for in the OpenTofu work. Additionally a huge amount of work has gone into wrapping inconsistencies in the Hashicorp release management that would not apply consistently with any other tool.
> 
> We believe that incorporating OpenTofu would be equivalent to incorporating the Hashicorp Packer binary, converting tfenv into a generic "binaryenv"; except that at least in the case of Packer, there would be reasonable expectation for future release processes and signing mechanisms to remain in line with Terraform.
> 
> We believe that as an independent tool, OpenTofu needs its own versioning solution bespoke to its usage. If tfenv is desired as an approach for working with OpenTofu development, it ought to be forked to create "tofuenv", supported and managed by whomever is responsible for the OpenTofu release management mechanisms. tfenv is MIT-licenced and so this should not be a barrier for tofuenv.
> 
> We had hoped that Hashicorp would take more direct interest in superseding tfenv with their own versioning manager, written in Go, that implements the same features - or at least the same capabilities - but this has not yet happened.
> 
> In conclusion, the PR will be rejected as tfenv does not intend to directly support OpenTofu as an independent binary, but we wish you well in your endeavours.

**Comment by roni-frantchi** [comment]
As mentioned above, maintainers of `tfenv` had decided not to expand `tfenv` support of OpenTofu as described above.

**Comment by kvendingoldo** [comment]
Hello there,
[Tofuenv's](https://github.com/tofuutils/tofuenv) first stable release (v1.0) is now available! tofuenv is a fork of tfenv that only works with OpenTofu binaries. Our crew (me, @anastasiiakozlova245, @Nmishin) has been working on the fork over the past week. We worked hard to improve the usability of core [tofuenv](https://github.com/tofuutils/tofuenv) features, add some new capabilities, and, of course, fix a few bugs in the original [tfenv](https://github.com/tfutils/tfenv) program.

We'd appreciate your input and support on GitHub. Please feel free to submit issues and make contributions. Link to tofuenv: https://github.com/tofuutils/tofuenv

tofuenv can be installed manually from GitHub or via brew (for mac users).

**Comment by janosdebugs** [comment]
Hey @kvendingoldo thank you for your work. I've seen the todo for the GPG signing of releases and it should be available starting with the stable release. You can fetch the GPG key from https://get.opentofu.org/opentofu.asc |.gpg
