### ISSUE TITLE
OpenTF Index Endpoint

### ISSUE THREAD

**Issue by alfespa17** [opentofu/opentofu#270]
### OpenTF Version

```shell
N/A
```

### Use Cases

Create some endpoint to expose all the available opentf versions

Hashicorp expose this endpoint:
```
https://releases.hashicorp.com/terraform/index.json
```

They basically expose the following information:

```json
{
   "name":"terraform",
   "versions":{
      "1.3.9":{
         "builds":[
            {
               "arch":"amd64",
               "filename":"terraform_1.3.9_linux_amd64.zip",
               "name":"terraform",
               "os":"linux",
               "url":"https://releases.hashicorp.com/terraform/1.3.9/terraform_1.3.9_linux_amd64.zip",
               "version":"1.3.9"
            }
         ],
         "name":"terraform",
         "shasums":"terraform_1.3.9_SHA256SUMS",
         "shasums_signature":"terraform_1.3.9_SHA256SUMS.sig",
         "shasums_signatures":[
            "terraform_1.3.9_SHA256SUMS.72D7468F.sig",
            "terraform_1.3.9_SHA256SUMS.sig"
         ],
         "version":"1.3.9"
      }
   }
}
```

OpenTF could give something like the following:
```json
{
   "name":"opentf",
   "versions":{
      "1.6.0":{
         "builds":[
            {
               "arch":"amd64",
               "filename":"opentf_1.6.0_linux_amd64.zip",
               "name":"terraform",
               "os":"linux",
               "url":"https://releases.opentf.com/opentf/1.3.9/opentf_1.3.9_linux_amd64.zip",
               "version":"1.3.9"
            }
         ],
         "name":"opentf",
         "shasums":"opentf_1.6.0_SHA256SUMS",
         "shasums_signature":"opentf_1.6.0_SHA256SUMS.sig",
         "shasums_signatures":[
            "opentf_1.6.0_SHA256SUMS.72D7468F.sig",
            "opentf_1.6.0_SHA256SUMS.sig"
         ],
         "version":"1.6.0"
      }
   }
}
```

This could be useful for automation purposes to download any available opentf version

### Attempted Solutions

N/A

### Proposal

Create some endpoint like this to expose all the available version.
https://releases.opentf.com/opentf/index.json

**Comment by cube2222** [comment]
Hey @alfespa17, thanks for submitting this issue!

This makes sense to me and we should definitely do it once we have an alpha/stable release in place.

**Comment by codexanonymous** [comment]
@alfespa17 i can take this up, can i assign this to myself? let me know? also how can i assign any issues here?

**Comment by codexanonymous** [comment]
@alfespa17  no worries - it’s kept on frozen and hold till it’s officially declared to start the contribution and the ticket assignments it’s written well documented here FYI https://github.com/opentffoundation/opentf/blob/main/CONTRIBUTING.md

**Comment by Hefeweizen** [comment]
@codexanonymous I'm interested in helping as well.  I'm going to think out loud about some initial design questions.  I am just getting up to speed on the project (though, aren't we all) so if some of these questions are answered elsewhere, linking to them would be appreciated, as it consolidates details needed for this discussion.

1. What's the planned endpoint url?  Do we have resources (e.g. domains) outside of github to host this?  The index could be made available as a github page, but that ties us to this provider for some time.  Unless there are multiple endpoints?
2. What's the project's CI system?  Ideally, automation will update the index.  If we're not integrating into the CI system, an alternative could be to monitor github releases and packages page, and generate the index from them.
3. We're providing shasums of the binaries themselves for security/quality purposes; do we need to sign other portions of the software supply chain?  Should the index itself be signed or verifiable in some way?  Is a mechanism for updates/repudiation needed?  Let's say a build host runs out of disk, and so the binary is truncated.  However, the CI process finishes, and publishes a SHA on that truncated build.  How do we update the SHA once the build is corrected?

In asking these, I could be paddling too far away from the shore.  I'm fine with limited/quick solutions, I just want to make sure we're acknowledging the scope of what we're building.

**Comment by cube2222** [comment]
Hey, the willingness to contribute here is very appreciated! However, since this issue will most likely require access to our AWS account it will probably be owned by a core team developer. Feel free to continue the discussion, though.

**Comment by alfespa17** [comment]
Hello @cube2222 is there any update about the tofu index now that tofu is in beta?, I would like to integrate tofu with other terraform related tools and the index will be very usefull.

**Comment by janosdebugs** [comment]
Hey @alfespa17 I've just come across this issue since I'm new to the project. As far as I know no work has been done to provide this index yet, but all our releases are (and will be) available using the [GitHub releases API](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#list-releases). Does that suffice or would you still like to see a dedicated releases index?

**Comment by alfespa17** [comment]
I think I can use that one, thanks for the information @janosdebugs 🥇 , I will check if I can use it

**Comment by alfespa17** [comment]
This issue can be closed I can use the releases API to get the URL to download artifacts. thank you @janosdebugs
