### ISSUE TITLE
Build with go1.21

### ISSUE THREAD

**Issue by chenrui333** [opentofu/opentofu#284]
Build with the latest and greatest go1.21.0

**Comment by cube2222** [comment]
Thanks for submitting an issue for this!

I can't see any reason not to do this.

**Comment by dvaumoron** [comment]
trying `go test ./...` with `go version go1.21.1 linux/amd64` fail on "TestMTLSServer_NoCertFails"

got "remote error: tls: certificate required" where "remote error: tls: bad certificate" was required.

**Comment by Yantrio** [comment]
So I've been doing some research and testing and now that the `TestMTLSServer_NoCertFails` Work was completed by @alrs in #391, the only thing that needs to happen is the support for unicode v15.

This can be completed by bumping the go-textseg package to the v15 tag and bring in this commit. https://github.com/apparentlymart/go-textseg/commit/72b78f42484ddc3f58858f794da1771fb9559ad0
