### ISSUE TITLE
feature: variabilize module source 

### ISSUE THREAD

**Issue by nikuljain** [opentofu/opentofu#286]
module "your_project" {
  source = "${var.your_project_source}//<path>"
  ...
}

this can help in monorepo collection of modules

**Comment by elacheche** [comment]
This is a great idea, especially to be able to use a variable in `ref=` part of the url.

This can improve modules versions lifecycle and updates, especially when `version` is only allowed with [ModuleSourceRegistry](https://github.com/opentofu/opentofu/blob/main/internal/configs/module_call.go#L121C1-L121C241)

**Comment by cam72cam** [comment]
Hi @nikuljain, I've opened an RFC that captures this feature and expands upon it.  I believe that this can now be closed, let me know if the RFC encapsulates your use case.

**Comment by tb3088** [comment]
I completely side-step this issue for the most part by having my modules be a git sub-module. That way my 'live' and 'modules' are always moving together and I don't need to find/replace a zillion version references.

Granted this doesn't address the version directive that likely references a standard implementation that the project-specific module is referencing. On the other hand, chasing a vendor version tag is infrequent and done with due deliberate action, no? Or can just include vendor module code as a sub-module and avoid the whole NPM-like disaster of blindly trusting vendors for functional code...
