### ISSUE TITLE
ci: simplify go version handling

### ISSUE THREAD

**Issue by zekth** [opentofu/opentofu#290]
Currently the ci uses composite action to get the go version: https://github.com/opentffoundation/opentf/blob/main/.github/actions/go-version/action.yml

This is used in many places in CI and sometimes makes spawning a job and checking out the code just to get the version to be sent to other jobs: https://github.com/opentffoundation/opentf/blob/b24c89c4b2f5698b04469a645baa5ff451e9c85e/.github/workflows/build.yml#L58-L68

Setup-go v4 supports the `go-version-file` https://github.com/actions/setup-go#getting-go-version-from-the-gomod-file which supports either `go.mod` or raw version file like we have in `.go-version`. Ref: https://github.com/actions/setup-go/blob/883490dfd06f396ebe0b738bc313a53cf9d851e5/src/installer.ts#L420-L432

I suggest we simplify the workflows and get rid of the composite action.

I'm happy to make those changes in a PR

**Comment by cube2222** [comment]
Hey @zekth, thanks a lot for creating this issue!

This makes sense to me.

That said, it seems like @chenrui333 is adding this as well as part of their Go 1.21 update https://github.com/opentffoundation/opentf/pull/282, so I think it makes sense to wait a bit and see if that PR is merged and fixes this.

**Comment by Jake-Mok-Nelson** [comment]
> Hey @zekth, thanks a lot for creating this issue!
> 
> This makes sense to me.
> 
> That said, it seems like @chenrui333 is adding this as well as part of their Go 1.21 update https://github.com/opentffoundation/opentf/pull/282, so I think it makes sense to wait a bit and see if that PR is merged and fixes this.

Looks like #282 was dropped in favour of #718,  not sure yet if that also addresses this issue but didn't want to lose track of it.

**Comment by zekth** [comment]
Will follow-up when landed

**Comment by Yantrio** [comment]
This was a small oversight on my part when authoring #718 that I missed this version handling in CI.

Please feel free to put in a PR once #718 is merged (I'll try and get that in today)

**Comment by Jake-Mok-Nelson** [comment]
@zekth , I noticed that you've switched to pinning the minor version. I was curious and wanted to understand the reason for the change? 

Also I have some recollection of the releaser not working correctly when the go version had full semver but that might have had a different cause (I was testing a few things at the time and it also doesn't sound right), it would be good to test the release process with this version change.

**Comment by zekth** [comment]
It was mainly to be in sync with `.go-version` which was defining the complete semver to pass to the `setup-go` action
