### ISSUE TITLE
Render templates from strings e.g. `templatestring` function similar to `templatefile`

### ISSUE THREAD

**Issue by nitrocode** [opentofu/opentofu#301]
## Context

Suggest an existing issue in legacy Terraform to fix in OpenTF. 

- workaround is to use the forked template provider with arm support as a drop in replacement https://github.com/cloudposse/terraform-provider-template
- full context https://gist.github.com/nitrocode/cf40a24054a66afe2b19ca54b7be5d68

---

I'd like to use `template` from a string instead of a file. At the moment, `templatefile()` requires a file to be present on disk prior to plan. If I can instead use a string, then I no longer need a file and my string can be even more dynamic. This is the functionality that we used to have with the original hashicorp/terraform-provider-template. However, that has been deprecated by `templatefile` with the missing string functionality and never had an arm release which is why the original was forked as `cloudposse/terraform-provider-template`. Since this fork provider is a workaround, a new string function would be much more beneficial.

A few attempts have been made to PR the `templatestring` function and those have been closed.

**Comment by roni-frantchi** [comment]
Hey @nitrocode  thanks for submitting!

To help us maintain a clear separation between opentf and hashicorp's offerings, we're asking that people describe issues that are in other repositories rather than linking those directly.
I've thus scrubbed out any links to said issues/PRs.  

It is also worth mentioning that as an author of a PR to legacy your **_are_** permitted under legacy Terraform CLA to resubmit your code elsewhere as well. Of course a prior RFC would be appreciated 

Thanks!

**Comment by nitrocode** [comment]
Thanks @roni-frantchi . I added some more information above on why it's needed and the previous PRs. If I have time, I'd be happy to contribute the code that I previously submitted.

**Comment by janosdebugs** [comment]
Hey @nitrocode thank you for this issue. We believe this would be a great addition to OpenTofu and added the corresponding labels. When implementing this, it would be great to have as much reuse of existing code as possible.

**Comment by sanskruti-shahu** [comment]
Hey, I would like to work upon this issue.

**Comment by janosdebugs** [comment]
Hey @sanskruti-shahu , thank you for your help. I've assigned you to the issue. Please let us know what your estimate on time is so we can unassign the issue at that time if we don't hear back from you and someone else wants to work on it.

**Comment by sanskruti-shahu** [comment]
I hope to contribute by end of next week probably.

**Comment by sanskruti-shahu** [comment]
Hey, @janosdebugs, I have created a pull request for this issue. Could you please take a look at it? Thanks!
