### ISSUE TITLE
Concise mode for tofu plan

### ISSUE THREAD

**Issue by Laudenlaruto** [opentofu/opentofu#306]
It would be great to have a way to shrink the output of terraform, which is very noisy. 
A `--short` or `--concise` parameter where only the resources updated would show, and all the refresh and noisy info on apply or plan would be filtered out.

**Comment by roni-frantchi** [comment]
Hey @Laudenlaruto  thanks for submitting!  

To help us maintain a clear separation between opentf and hashicorp's offerings, we're asking that people describe issues that are in other repositories rather than linking those directly.  
I've thus scrubbed out any links to said issues.  

You're welcome to add some context to the brief overview if needs be

**Comment by flavono123** [comment]
i created a wrapper, `terraform plan -summary`, for enhancing the summary part of plan output.
it print the list of resource addresses would be added/changed/deleted from plan
https://github.com/flavono123/terraform-plan-summary
![image](https://raw.githubusercontent.com/flavono123/terraform-plan-summary/main/assets/demo.gif)

i think this would be an option if the verbose part removed.

**Comment by flavono123** [comment]
btw, @dex4er 's one is awesome 👍

**Comment by janosdebugs** [comment]
Hey community, we are working through our backlog of issues now that the stable release is out and this would be a great addition to OpenTofu.

**Comment by SypherSP** [comment]
Hi, I would like to have a go at this issue.

**Comment by janosdebugs** [comment]
Hey @SypherSP , thank you for your help. I've assigned you to the issue. Please let us know what your estimate on time is so we can unassign the issue at that time if we don't hear back from you and someone else wants to work on it.

**Comment by SypherSP** [comment]
I think ill be able to get this done by next week. This will be my first open source contribution and I will reach out on slack for help. Thanks for assigning the issue :)

**Comment by janosdebugs** [comment]
Thank you @SypherSP !

**Comment by SypherSP** [comment]
What details of the current plan output is considered important to be included in the concise mode output?
Also, when implementing the concise plan, which is a better approach of the following-

```
// The PlanHuman implementation renders human-readable text logs, suitable for
// a scrolling terminal.
type PlanHuman struct {
	view *View
	concise bool
	inAutomation bool
}
```
or 
```
// The PlanHuman implementation renders human-readable text logs, suitable for
// a scrolling terminal.
type PlanHuman struct {
	view *View
	inAutomation bool
}

type PlanHumanConcise struct {
        view *View
	inAutomation bool
```

This is present in internal/command/views/plan.go

**Comment by ilmax** [comment]
>What details of the current plan output is considered important to be included in the concise mode output?

Just my opinion here, but I'd vote to exclude everything before the legend and the change details. All the read/read complete/refreshing are just noise lowering the signal to noise ratio.

**Comment by skyzyx** [comment]
> What details of the current plan output is considered important to be included in the concise mode output?

IMO, seeing the changes (e.g., the `plan`, including `outputs`) is important. Refreshing is less important in a `-summary` or `-compact` view. I also think that instructions (when running `plan` without `-out`) can be omitted in this view.

NOTE: I don't think the compact view should be the default, but rather something that is opt-in. Not sure if that was in question or not, but…

**Comment by rdhar** [comment]
Agreed with @skyzyx that this should be opt-in/flag, and a great use-case for CI/CD to output concise summaries like with [tf-via-pr-comments](https://github.com/devsectop/tf-via-pr-comments), as @ilmax mentioned.

Although it's geared towards shell-usage, I'm a fan of @dex4er 's [tf wrapper](https://github.com/dex4er/tf) too -- it's so sleek!

|**Before (with `tofu`)**|**After (with `tf`)**|
|---|---|
|![](https://github.com/dex4er/tf/blob/main/assets/terraform.gif?raw=true)|![](https://github.com/dex4er/tf/blob/main/assets/tf.gif?raw=true)|

**Comment by skyzyx** [comment]
I love what @rdhar posted for an _interactive_ terminal session (nice!), but if the use-case is running in CI and reading the logs later, it might be that each rewritten line in the CLI (in the "after" example) results in a new log line.

@ilmax [said](https://github.com/opentofu/opentofu/issues/306#issuecomment-1708218770):

> Especially in CI scenario, I'd like to have a flag where I can hide the whole: "module x.y.z. Refreshing state...." and "module x.y.z. Reading...."
> Those are just pure noise in CI scenario and it would be awesome to have a flag to hide them from the stdout

Assuming that the CI use-case is part of the plans for this feature, the testing should include (at the very least) eyeballing it in popular CI services (e.g., Travis, CircleCI, GitHub Actions) and possibly internal CI services as well (e.g., Jenkins, TeamCity).

Not that the OpenTofu Foundation needs to be on-the-hook for all of this but it's something to be aware of.

I anticipate that a simpler approach that will _definitely_ address the cluttered log lines in CI systems would be (for example) combining a `-compact` flag **with** a `-quiet` flag that eliminates any changes to the CLI output that an interactive user would care about more than a non-interactive CI user.

**Comment by cristan** [comment]
FYI: this is available since OpenTofu [1.7.0](https://github.com/opentofu/opentofu/blob/ba4c3a5b462129cd61644a3ae760d746dc12b8fc/CHANGELOG.md). The flag is `-concise`

**Comment by tmccombs** [comment]
What output exactly is suppressed by `-concise`? The documentation isn't very clear, it just says "progress-related messages"? 

What I want is to suppress the "Refreshing state..." messages, but I would still like the messages about the actual actions taken during an apply ("Creating...", "Updating...", "Destroying...")

**Comment by cam72cam** [comment]
From the --help options: https://github.com/opentofu/opentofu/pull/1225/files#diff-0a278b6514278d7844709e822f4b8e33c372b3e3378603dd0cfadecb4e357cf0R279

`Displays plan output in a concise way, skipping the refreshing log lines.`

**Comment by tmccombs** [comment]
The current output (for 1.10.6) is just:

> Disable progress-related messages.

**Comment by nika-pr** [comment]
Even with the -concise flag, there are still some lines I want to exclude.

What we are currently filtering out via grep:

`"(Downloading Terraform configurations from)|(Initializing the backend)|(Reusing previous version of)|(Initializing provider plugins)|(Using previously-installed)|(has been successfully initialized)|(You may now begin working with)|(any changes that are required)|(should now work.)|(If you ever set or change modules)|(rerun this command to reinitialize)|(commands will detect it)|(has compared your real)|(found no differences, so)|(Caching terraform providers for)|(Note: You didn't use the )|(guarantee to take exactly)|(Refreshing state)|(Cached registry\.)|(Installing hashicorp)|(Initializing modules)|(Acquiring state lock)|(Installed hashicorp)|(Releasing state lock)|(tofu:\s*(\x1b\[[0-9;]*m)*\s*(?:$|─+))"`

**Comment by es-cs1** [comment]
concise is not actually very concise, for inspiration see
https://github.com/dineshba/tf-summarize
which supports concise 1 liners like terraform cloud gui output, and tree views
