### ISSUE TITLE
Snap package for OpenTF

### ISSUE THREAD

**Issue by jnsgruk** [opentofu/opentofu#319]
### OpenTF Version

```shell
1.6.0-beta1
```

### Use Cases

Easy installation and frequent updates on Ubuntu based machines

### Attempted Solutions

I've created a snap package which is published at https://snapcraft.io/opentf. It can be installed with `sudo snap install --classic opentf --channel beta`.

### Proposal

If there is any interest, I'm happy to contribute the package to this repo and help get the publishing setup, as well as assisting with getting "Verified Publisher" status on the Snap store. The purpose of this issue is really to gauge upstream interest. FWIW I've been maintaining the Terraform snap for about 18 months, and it's very low overhead!

**Comment by jnsgruk** [comment]
The code for my initial implementation is here: https://github.com/jnsgruk/opentf-snap

**Comment by Hefeweizen** [comment]
[GoReleaser](https://goreleaser.com/) is in use.  It offers [snap support](https://goreleaser.com/customization/snapcraft/).  I would expect the project to want to use homogeneous tooling where possible; consider aligning your contribution to take advantage of this.

There is related work from @thschue: https://github.com/opentffoundation/opentf/pull/362

**Comment by thschue** [comment]
Should I also take over this one?

**Comment by jnsgruk** [comment]
Yep using goreleaser will work fine too!

@tschue feel free, let me know if you want a review and when you're ready to start publishing and we can get the name transferred over to an "official" OpenTF account on the snap store etc.

**Comment by roni-frantchi** [comment]
Much appreciated @thschue ! ❤️

**Comment by thschue** [comment]
Could you please assign this to me?

**Comment by cube2222** [comment]
Seems like @jnsgruk jumped in instead? Not sure if you've been coordinating here @thschue @jnsgruk?

**Comment by thschue** [comment]
For me, it's no problem if @jnsgruk takes this over :-)
