### ISSUE TITLE
Add AWS SSO Session support on AWS S3 backend

### ISSUE THREAD

**Issue by pjaudiomv** [opentofu/opentofu#344]
### OpenTF Version

```shell
OpenTF v1.6.0-dev
on darwin_amd64
```

### Use Cases

Have opentf support AWS Config files configured using new aws sso configuration which makes use of a new `sso-session` block https://docs.aws.amazon.com/cli/latest/userguide/sso-configure-profile-token.html . Instead of having to use legacy config.

### Attempted Solutions

The legacy config still workes. However the aws provider already supports the new aws config and the s3 backend of opentf should as well.

### Proposal

Update the `AWS SDK Go` package to v2 to properly support there may be a v1 patch that supports as well but im unsure.

### References

https://docs.aws.amazon.com/cli/latest/userguide/sso-configure-profile-token.html

error

```
13:47:48 › opentf init

Initializing the backend...
╷
│ Error: Failed to configure AWS client
│
│ The "S3" backend encountered an unexpected error while creating the
│ AWS client: Error creating AWS session: profile "my-sso" is
│ configured to use SSO but is missing required configuration:
│ sso_region, sso_start_url
```

open tf config

```
terraform {
  required_version = "~>1.0"

  required_providers {
    aws = {
      version = "~>5.0"
      source  = "hashicorp/aws"
    }
  }

  backend "s3" {
    bucket  = "my-sso-testing-bucket"
    key     = "testing/sso.tfstate"
    region  = "us-east-1"
    profile = "my-sso"
  }
}
```

**Comment by marcinwyszynski** [comment]
It's up my alley. I'll look into it next week.

**Comment by skyzyx** [comment]
DO NOT WANT.

I feel that this is tight coupling, when something like `aws-vault exec {account} -- terraform plan` is more appropriate. Using a tool like AWS Vault or 1Password's `op run --` keeps things loosely coupled.

**Comment by pjaudiomv** [comment]
> DO NOT WANT.
> 
> I feel that this is tight coupling, when something like `aws-vault exec {account} -- terraform plan` is more appropriate. Using a tool like AWS Vault or 1Password's `op run --` keeps things loosely coupled.

It's not tight or loose coupling. It's reasonable for any aws client to fully support aws/config. This issue is simply asking for the aws s3 backend to properly support the latest `~/.aws/config` standards. opentf currently pukes trying to read a `~/.aws/config` file that has `[sso-session my-sso]` block in it. opentf  supports other parts of aws/config, and supports all the standard aws client environment variables, why would we explicitly not support this when other aws clients do? see https://docs.aws.amazon.com/cli/latest/userguide/sso-configure-profile-token.html

**Comment by eranelbaz** [comment]
Hey @pjaudiomv did you configure AWS SSO properly? 
please check your `~/.aws/config` file
It should look something like that

```
[profile example]
sso_account_id = -----
sso_role_name = YOUR_SSO_ROLE
region = us-east-1
output = json
sso_region = us-east-1
sso_registration_scopes = sso:account:access
sso_start_url = https://----.awsapps.com/start#/
```

```
> opentf init

Initializing the backend...

Successfully configured the backend "s3"! OpenTF will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding hashicorp/aws versions matching "~> 5.0"...
- Installing hashicorp/aws v5.16.1...
- Installed hashicorp/aws v5.16.1 (signed, key ID 34365D9472D7468F)

Providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.placeholderplaceholderplaceholder.io/docs/cli/plugins/signing.html

OpenTF has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that OpenTF can guarantee to make the same selections by default when
you run "opentf init" in the future.

OpenTF has been successfully initialized!

You may now begin working with OpenTF. Try running "opentf plan" to see
any changes that are required for your infrastructure. All OpenTF commands
should now work.

If you ever set or change modules or backend configuration for OpenTF,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

**Comment by eranelbaz** [comment]
BTW, seems like `hashicorp/aws-sdk-go-base@v0.7.1` is the package that initialize the AWS client

**Comment by eranelbaz** [comment]
I took my chance but found it harder than I'd thought...
Used https://github.com/hashicorp/terraform-provider-aws as references

b73b5dcf3e381215e2f65f4afd35ee9f7874fc00

**Comment by eranelbaz** [comment]
Linking #689 #690 #691

**Comment by cube2222** [comment]
Looks like this was implemented as part of the s3 backend improvements in 1.6.
