### ISSUE TITLE
Support Git as source for providers

### ISSUE THREAD

**Issue by NefixEstrada** [opentofu/opentofu#359]
### OpenTF Version

```shell
all
```

### Use Cases

- Avoid vendor lock in (don't be tied to GitHub releases, HashiCorp registry or OpenTF registry)
- Be able to use private Git repositories
- Avoid the hassle of setting up a private OpenTF registry
- Enhance the development experience (fork, modify, use)

### Attempted Solutions

Right now, you can use the Development overrides: https://developer.hashicorp.com/terraform/cli/config/config-file#development-overrides-for-provider-developers

However, this is limited to the local storage and it still requires manually building the provider

### Proposal

Since most of the plugins use Goreleaser as the build tool, it could be possible to:

1. Detect the provider source is Git:

```
git+https://url.to/the/repo.git
```

2. Ensure there's Goreleaser installed:

```sh
which goreleaser
```

3. Build the plugin locally:

```sh
git clone <>
goreleaser build --single-target # This builds only for the local architecture
```

4. Use it :)

**Comment by cube2222** [comment]
Hey, thanks for submitting the issue @NefixEstrada!

TBH, I don't think it'd be great to introduce a dependency on both the Go toolchain and GoReleaser to OpenTF.

This sounds to me like functionality that could be done in a custom tool that parses all such referenced providers, fetches and builds them, places them in the right directory to be picked up by OpenTF, and updates the .tf files to point at those local providers.

**Comment by skyzyx** [comment]
There's also the (comparatively minor) issue of updating `~/.terraformrc` with blocks in the correct order.

**Comment by janosdebugs** [comment]
Hey folks, we appreciate the input and the desire to use providers that don't release binaries. However, as indicated by @cube2222 this would require us introducing a dependency on Go build tools. Furthermore, OpenTofu is able to use providers implemented in other programming languages than Go. As such, we are sorry to say that we do not plan to implement this and will be closing this issue.

We would recommend speaking to the provider authors to release binaries as it is a simple process using GitHub Actions with goreleaser. If you need any help with getting this going, please ask in the [GitHub Discussions](https://github.com/orgs/opentofu/discussions) or on [Slack](https://opentofu.org/slack).
