### ISSUE TITLE
Support OpenTF in tfswitch

### ISSUE THREAD

**Issue by skyzyx** [opentofu/opentofu#361]
Same ticket as #25, but for tfswitch.

https://tfswitch.warrensbox.com

**Comment by skyzyx** [comment]
Cross-linking: https://github.com/warrensbox/terraform-switcher/issues/315

**Comment by roni-frantchi** [comment]
Thanks for opening the issue @skyzyx !  
We'd love to see this happening.  

Someone picked up the `tfenv` issue - we'd love for one to also pick this one up and look into contributing to `terraform-switcher` and make it support OpenTF

**Comment by gtirloni** [comment]
tfenv has decided not to support tofu binaries, explained here: https://github.com/tfutils/tfenv/issues/409#issuecomment-1863021455 -- I'd expect tfswitch would follow the same approach.

Would it make sense for opentofu to consider  implementing its own version management tool in that case?

**Comment by huang-jy** [comment]
Hi, I'm the OP on the tfenv issue mentioned.

`asdf` already provides plugins for terraform and opentofu, asdf is a bit fiddly to set up ,but does work as a version management tool.

**Comment by gtirloni** [comment]
I'm using asdf on my local computer but the shell integration is actually a problem in CI/CD environment. A single binary is much easier to manage.

**Comment by huang-jy** [comment]
Agreed. asdf is fiddly, but it does provide the version switch functionality. I resort to using the global switch instead of shell. If I'm running CI/CD in an agent/pod, then this isn't an issue ("global" in the context of a container is just within the container).

It _is_ of cours an issue if your runner state is shared (e.g. if your runner is an actual shared physical machine or VM)

**Comment by kvendingoldo** [comment]
Hello there,
[Tofuenv's](https://github.com/tofuutils/tofuenv) first stable release (v1.0) is now available! tofuenv is a fork of tfenv that only works with OpenTofu binaries. Our crew (me, @anastasiiakozlova245, @Nmishin) has been working on the fork over the past week. We worked hard to improve the usability of core [tofuenv](https://github.com/tofuutils/tofuenv) features, add some new capabilities, and, of course, fix a few bugs in the original [tfenv](https://github.com/tfutils/tfenv) program.

We'd appreciate your input and support on GitHub. Please feel free to submit issues and make contributions. Link to tofuenv: https://github.com/tofuutils/tofuenv

tofuenv can be installed manually from GitHub or via brew (for mac users).

**Comment by cam72cam** [comment]
Closing as there is nothing to do on the OpenTofu side here.
