### ISSUE TITLE
Show all warnings

### ISSUE THREAD

**Issue by schollii** [opentofu/opentofu#364]
### OpenTF Version

```shell
1.0
```

### Use Cases

When upgrading a provider eg the aws provider, many warnings can occur, but only the first of them is shown. Eg 
```
Warning: Argument is deprecated
  on .terraform/modules/spa.s3_logs/main.tf line 1, in resource "aws_s3_bucket" "this":
   1: resource "aws_s3_bucket" "this" {
Use the aws_s3_bucket_acl resource instead

(and 21 more similar warnings elsewhere)
```
There is currently no option to show those similar warnings. All these warnings could be in different files, so we are forced to first address the only one shown, then re-run the terraform plan. Sometimes this requires many cycles. TEDIOUS!

### Attempted Solutions

Run `terraform validate`. 

However this does not seem to catch these warnings, possibly because the warnings are not about invalid code, just deprecation warnings. 

### Proposal

Several possibilities: 
- Add a switch on the plan and apply commands, eg `--show-all-warnings`. This switch should work even if the output is json. 
- Add a new command, `show-warnings`: if the users runs an apply or a plan and sees deprecation warnings, then they could run this new command to get the details. This makes sense if there are steps of the plan / apply can be skipped when the user just wants these (eg one would expect that it would be sufficient for terraform to parse the code, and ask the provider for any warnings about it, without actually having to check the cloud resources status, which could save a ton of time)

### References

- The issue is mentioned in a few places but the biggest discussion I found is https://discuss.hashicorp.com/t/show-all-warnings/5606/18. This demonstrates that HC is not interested in implementing this much-needed and almost trivial capability.

**Comment by Hefeweizen** [comment]
I'm looking at implementing this and just dropping some notes here.

This functionality looks to be centralized in: https://github.com/opentffoundation/opentf/blob/main/internal/tfdiags/consolidate_warnings.go; it's called in two files.
```
internal/command/meta.go:696:   diags = diags.ConsolidateWarnings(1)
internal/command/views/view.go:88:      diags = diags.ConsolidateWarnings(1)
```

ConsolidateWarnings() takes the count of errors to show.  It uses an int.  Perhaps `-1` could be unlimited?  Though, I'm not sure passing this in is any simpler, I'll still have to do some work around the caller to pass in the count (as right now it's not a variable, just a '1').

While implementing, keep an eye on also implementing making the exact warning count a cli parameter.  i.e. `--show-similiar=5` to show the first five, summarizing the rest.  Most of this is already done, it's just not exposed.



There's an existing flag, `-compact-warnings` to further compact warnings.  The new option should conflict with it.
Once that's done, there should be no logic changes necessary as its invocation is specifically triggered by that flag.
The function is 'DiagnosticWarningsCompact'.  It's used twice as well:
```
internal/command/meta.go:713:                   msg := format.DiagnosticWarningsCompact(diags, m.Colorize())
internal/command/views/view.go:105:                     msg := format.DiagnosticWarningsCompact(diags, v.colorize)
```

```
$ g grep -B 14 -A 1 DiagnosticWarningsCompact
...
--
internal/command/meta.go-699-   if m.compactWarnings {
internal/command/meta.go-700-           // If the user selected compact warnings and all of the diagnostics are
internal/command/meta.go-701-           // warnings then we'll use a more compact representation of the warnings
internal/command/meta.go-702-           // that only includes their summaries.
internal/command/meta.go-703-           // We show full warnings if there are also errors, because a warning
internal/command/meta.go-704-           // can sometimes serve as good context for a subsequent error.
internal/command/meta.go-705-           useCompact := true
internal/command/meta.go-706-           for _, diag := range diags {
internal/command/meta.go-707-                   if diag.Severity() != tfdiags.Warning {
internal/command/meta.go-708-                           useCompact = false
internal/command/meta.go-709-                           break
internal/command/meta.go-710-                   }
internal/command/meta.go-711-           }
internal/command/meta.go-712-           if useCompact {
internal/command/meta.go:713:                   msg := format.DiagnosticWarningsCompact(diags, m.Colorize())
internal/command/meta.go-714-                   msg = "\n" + msg + "\nTo see the full warning notes, run OpenTF without -compact-warnings.\n"
--
internal/command/views/view.go-91-      if v.compactWarnings { // eliding remaining as it looks the same as meta.go
... 
```

Next step: review cli argument parsing.

**Comment by dvaumoron** [comment]
I take a look at ConsolidateWarnings, as the comment indicate, this method aggregate warnings with the same summary (which is "Argument is deprecated" in the example), the  -1 special case is not handled, a simple modification is needed : exit without doing work for that value.

**Comment by dvaumoron** [comment]
DiagnosticWarningsCompact can handle consolidated warnings, so conflicting when the two optional flags are present is not mandatory (even if it seems strange to use them at the same time).

The evaluation of useCompact could be moved in DiagnosticWarningsCompact method in order to share the common behaviour.

**Comment by Hefeweizen** [comment]
@dvaumoron I started working on this last night, but didn't finish.  I'll share my WIP.  I'd be interested in your thoughts and contributions.

> DiagnosticWarningsCompact can handle consolidated warnings, so conflicting when the two optional flags are present is not mandatory (even if it seems strange to use them at the same time).

Interesting.  I've started with `-verboseWarnings` but perhaps `-noConsolidatedWarnings` is better?

**Comment by schollii** [comment]
All CLI args use lowercase-with-dashes, eg `-auto-approve` and `-compact-warnings`. So it would have to be `-verbose-warnings` or such.

**Comment by dvaumoron** [comment]
@Hefeweizen, `-show-all-warnings` seems too long so maybe just `-all-warnings`

I'm unsure about the utility of  `-show-similiar=5`, if you want to show more warnings without consolidation, why keep a limit ?

**Comment by dvaumoron** [comment]
I have watched your PR, i think `-verbose-warnings` could be confusing side by side with `-compact-warnings`, i think `-all-warnings` is clearer

About your code, it looks similar to what i could have done, however i would change :
`var warningCount int
warningCount = 1`
with just :
`warningCount := 1`
and declare it nearer it use, with maybe a more explicit name like`warningLimit`

and the `|| threshold == -1 ` addition seems strange, the `threshold` var doesn't change, so i think it would be better to test it only one time before the loop to skip all the unnecessary processing (but after the `if len(diags) == 0` to still allows GC to clean unused capacity)

lastly, you didn't refactor the useCompact (ok, this one is just to nitpick, morover all the `Diagnostic*` function there return string, so returning (string, bool) for one would be inconsistent (but we can still create a wrapping function to do the common work with a differently formed name))

**Comment by schollii** [comment]
So where are things at, here?
