### ISSUE TITLE
Set up Scoop bucket

### ISSUE THREAD

**Issue by cpepper96** [opentofu/opentofu#372]
### OpenTF Version

```shell
N/A
```

### Use Cases

A Scoop bucket would provide Windows users any easy way to install openTF via the command line.

### Attempted Solutions

N/A

### Proposal

Would like to have a crack at this once the new name (+1 for tofu!) is decided and the alpha release :)

**Comment by Hefeweizen** [comment]
[GoReleaser](https://goreleaser.com/) is in use.  It offers [scoop support](https://goreleaser.com/customization/scoop/).  I would expect the project to want to use homogeneous tooling where possible.  You mention wanting to take a crack at this; consider aligning your contribution to take advantage of this.

There is related work from @thschue: https://github.com/opentffoundation/opentf/pull/362

**Comment by kdpuvvadi** [comment]
Not related to Scoop went ahead and added tofu manifesto to [winget](https://github.com/microsoft/winget-cli) for Windows users.

https://github.com/microsoft/winget-pkgs/pull/122146

**Comment by ilmax** [comment]
To automate winget package manifest updates, looks like there's a GitHub action [here](https://github.com/vedantmgoyal2009/winget-releaser) it may be interesting to automate that part

**Comment by cube2222** [comment]
We've decided that we won't be supporting this as the core team for now, we are however open to third-party supported packages.

> I've been managing terraform on winget. If it's okay with team, i would like continue that with tofu. please let me know.

Please do! Thanks!

**Comment by giggio** [comment]
It seems somebody added it to scoop, too.
