### ISSUE TITLE
Have some sort of automated backports of 1.5.x.

### ISSUE THREAD

**Issue by eranelbaz** [opentofu/opentofu#389]
### OpenTF Version

```shell
-
```

### Use Cases

HashiCorp is still publishing new versions of 1.5.x under the MPL license.
We should have some sort of way to automate the backporting process to OpenTF repository

### Attempted Solutions

-

### Proposal

* Once a day check for a new release where the version is under 1.6.0
   * New release where the publish day is under a day
* If so, list all commits between the last two releases and filter by commit message - `Merge Pull Request` and extract the pull request number
* Create an issue for our repository with list of all pull requests that needs backporting (Fine as under MPL)

**Comment by eranelbaz** [comment]
IMO, currently we are okay with having a bot to auto-create backport issue. We'll see how much pressure is if we also want to automate the code porting

**Comment by roni-frantchi** [comment]
We've decided not to pursue that automatically and rely on the community instead.
