### ISSUE TITLE
nonsensitive should not error-our if value already sensitive

### ISSUE THREAD

**Issue by joaocc** [opentofu/opentofu#394]
### OpenTF Version

```shell
1.5.x
```

### Use Cases

Pls see [PR](https://github.com/opentffoundation/opentf/pull/369) 

### Attempted Solutions

Pls see [PR](https://github.com/opentffoundation/opentf/pull/369) 

### Proposal

Make nonsensitive silently accept a value that is already non-sensitive

### References

Pls see [PR](https://github.com/opentffoundation/opentf/pull/369)

**Comment by eranelbaz** [comment]
Adding a summary here on the issue
IMO, this is a valid enhancement to OpenTofu as this action can be idempotent
We currently are waiting to release the alpha version before the committee will discuss this issue
