### ISSUE TITLE
Wrap Errors Everywhere

### ISSUE THREAD

**Issue by alrs** [opentofu/opentofu#395]
### Summary

Many of the errors in OpenTF are being flatted into `errors.errorString` because `%s` is being used as a formatting directive in `fmt.Errorf()` instead of `%w`, which wraps.

### Problem Statement

.

### User-facing description

.

### Technical Description

Use `%w` instead of `%s` with `fmt.Errorf()`

### Rationale and alternatives

.

### Downsides

.

### Unresolved Questions

.

### Related Issues

This was mentioned in https://github.com/opentffoundation/opentf/issues/363

**Comment by cube2222** [comment]
This makes sense to me, I can't see any reason not to do it.

Any objections @opentffoundation/opentf-core-team?

**Comment by eranelbaz** [comment]
Hey @alrs 
can you please write in the description all the packages that need such treatment? so we can follow on the progress here?

Thank you very much!

**Comment by dvaumoron** [comment]
A search with the re `fmt.Errorf\(.*, err` returns 511 results in 122 files and `fmt.Errorf\(.*%w` returns 57 results in 21 files, the first search returns files in :

file:///home/dvaumoron/go/src/github.com/dvaumoron/opentf/folder_list.txt

whole list of match :

file:///home/dvaumoron/go/src/github.com/dvaumoron/opentf/match_list.txt

**Comment by dvaumoron** [comment]
A search with the re fmt.Errorf\(.*, err returns 511 results in 122 files and fmt.Errorf\(.*%w returns 57 results in 21 files, the first search returns files in :

internal/builtin/provisioners/remote-exec
internal/builtin/provisioners/file
internal/modsdir
internal/providercache
internal/terminal
internal/getmodules
internal/e2e
internal/replacefile
internal/configs/hcl2shim
internal/configs/hcl2shim
internal/configs/configload
internal/command/workdir
internal/command/jsonplan
internal/command
internal/command/webbrowser
internal/command/cliconfig
internal/command/clistate
internal/command/testing
internal/legacy/helper/schema
internal/legacy/opentf
internal/backend/local
internal/backend/remote
internal/backend/remote-state/azure
internal/backend/remote-state/consul
internal/backend/remote-state/inmem
internal/backend/remote-state/s3
internal/backend/remote-state/http
internal/backend/remote-state/kubernetes
internal/backend/remote-state/oss
internal/backend/remote-state/gcs
internal/backend/remote-state/pg
internal/backend/remote-state/cos
internal/communicator/ssh
internal/registry
internal/plans/planfile
internal/plans
internal/initwd
internal/cloud
internal/getproviders
internal/states/remote
internal/states/statefile
internal/states/statemgr
internal/lang/funcs
internal/opentf
tools/protobuf-compile

**Comment by dvaumoron** [comment]
@alrs, do you want some help on this work ?

**Comment by alrs** [comment]
Thanks, @dvaumoron. At the moment I'm enjoying peeking into every corner of the project. Can I come back to you on Monday if I don't finish this week?

**Comment by dvaumoron** [comment]
Sure

**Comment by jenia** [comment]
You should definitely wrap all errors and use `is` and `as` for error handling further up the stack.
