### ISSUE TITLE
Breaking out useful internal packages so they can be imported.

### ISSUE THREAD

**Issue by verdverm** [opentofu/opentofu#401]
### OpenTF Version

```shell
n/a
```

### Use Cases

There are a bunch of useful packages in the internal directory, which are unfortunately impossible to import into other Go programs.

In particular, we want to use: https://github.com/opentffoundation/opentf/tree/main/internal/dag

### Attempted Solutions

copy out, vendor, fix import paths

This tends to create a cascading effect to the majority of an internal directory

### Proposal

1. lift them out of internal and into some other `pkg/...` dir
1. Doing something like: https://github.com/rogpeppe/go-internal

**Comment by cube2222** [comment]
Hey, thanks for submitting the issue @verdverm!

This is definitely something we'd like to do **eventually**. The problem is that we first have to think very hard what exactly we want to expose, and what the stability guarantees for that would be.

Right now the internal package is... internal, so can be refactored, the implementation can be changed, etc. as long as the resulting mechanics stay the same. It won't break anybody downstream.

If the internal package were exported **and stable**, then this would become **much** harder. Thus, we'd like to defer the discussion on this by a few months, until the core team feels a bit more comfortable with making such judgement calls. Once we export and commit to being stable on some API, there will be no going back from it.

**Comment by verdverm** [comment]
Cool, cool, understandable.

Mainly interested in the `dag` package, and `tfdiag` by dependency but also useful. The `dag` graph stuff looks really useful more generally outside of pure TF use cases. A few projects I am working on / around have taken an interest.

These two are pretty independent and should be easy to break out, we are going to extract and vendor them in the meantime.

Should I check back around the end of the year, or early next year?

Side Q, are y'all thinking anything about CUE in this space / initiative?

**Comment by verdverm** [comment]
> That said, I do wonder what the overlap with existing libraries like [Gonum Graph](https://pkg.go.dev/gonum.org/v1/gonum/graph) is.

This is a nice package with a wider feature set.

What makes `internal/dag` interesting is that it is purpose built for building up the graph while walking, where visits happen in parallel and can take a long while. This is the foundation of the TF execution engine as I understand it.

https://github.com/opentffoundation/opentf/blob/main/internal/dag/walk.go

We want to use it with our [hof/flow](https://docs.hofstadter.io/reference/hof-flow/) CUE DAG workflow engine.

**Comment by eranelbaz** [comment]
That might make the core engine hard to develop, that for each change in such packages, we'll have to work on a different repo, then install dependencies and run checks to make sure nothing broke / new features works correctly

**Comment by verdverm** [comment]
My take is

1. It can be "broken out" within the same repository, so that should not incur the multi-repo penalties
2. The SDK does not need the same support or maturity guarantees as the CLI, modules, and resources.

I would expect very few people to reach into this, it's really a power user thing, where, personally, I'm ok not having API stability guarantees to get access to these modules. I mean, I'm going to just pull it out and commit it to our tree anyway, which is more effort for me. My goal here is to have something all people can import and not go through what I'm about to, in getting access to this `dag` package.

**Comment by verdverm** [comment]
@alrs did you look at it??? totally unmaintained, not current... 🤦 

not interested in working with "tofu"

**Comment by clarkmcc** [comment]
@verdverm I'm happy to update it if needed. The library doesn't change often and without a need I don't do any preemptive maintenance.

**Comment by verdverm** [comment]
like "tofu", forking or creating alternatives will fracture the ecosystem, we were looking for something in-source, but are disliking this "tofu" thing more each day as we see the divergence coming, making more work for everyone, yea!

we've already vendored it into our source tree, save your time @clarkmcc
