### ISSUE TITLE
Choco package

### ISSUE THREAD

**Issue by m1rl0k** [opentofu/opentofu#430]
### OpenTF Version

```shell
1.6.0
```

### Use Cases

Could we get a handy dandy chocolatey package for easy opentf install?

### Attempted Solutions

Can currently run ubuntu runner with go install and build / symlink; however for windows runners would be nice for a chocolatey release

**Comment by Hefeweizen** [comment]
@thschue  has been on the ball with these; flagging him for visibility.

**Comment by cube2222** [comment]
We've decided that we won't be supporting this as the core team for now, we are however open to third-party supported packages.
