### ISSUE TITLE
Address missing documentation links

### ISSUE THREAD

**Issue by Roma36** [opentofu/opentofu#434]
### Summary

We have some broken links in our docs.

### Problem Statement

In the documentation website repo we've introduced a CI check for broken links. It highlighted to us that we have some broken links. The ones that could be addressed immediately are addressed here: https://github.com/opentffoundation/opentf/pull/435

But there are some links, which were inherited from the terraform documentation and currently have no alternative in our documentation. These should be addressed in some other way.  

### User-facing description

This is not user-facing problem

### Technical Description

Here's the list of the links which needs to be addressed:
- On source page path = /docs/cli/import/importability:
   -> linking to [/docs/plugin/sdkv2/resources/import](https://developer.hashicorp.com/terraform/plugin/sdkv2/resources/import)

- On source page path = /docs/cli/install/apt:
   -> linking to [/docs/downloads](https://developer.hashicorp.com/terraform/downloads)

- On source page path = /docs/cli/install/yum:
   -> linking to [/docs/downloads](https://developer.hashicorp.com/terraform/downloads)

- On source page path = /docs/internals/credentials-helpers:
   -> linking to [/docs/registry](https://developer.hashicorp.com/terraform/registry)
   -> linking to [/docs/plugin/how-opentf-works#plugin-locations](https://developer.hashicorp.com/terraform/plugin/how-terraform-works) (resolved as: /docs/plugin/how-opentf-works)

- On source page path = /docs/internals/module-registry-protocol:
   -> linking to [/docs/registry/api-docs](https://developer.hashicorp.com/terraform/plugin/how-terraform-works)

- On source page path = /docs/intro/:
   -> linking to [/docs/plugin](https://developer.hashicorp.com/terraform/plugin)

- On source page path = /docs/language/modules/develop/publish:
   -> linking to [/docs/registry/modules/publish](https://developer.hashicorp.com/terraform/registry/modules/publish)
   -> linking to [/docs/registry/private](https://developer.hashicorp.com/terraform/registry/private)

- On source page path = /docs/language/modules/sources:
   -> linking to [/docs/registry/private](https://developer.hashicorp.com/terraform/registry/private)
   -> linking to [/docs/registry/api-docs](https://developer.hashicorp.com/terraform/registry/api-docs)
   -> linking to [/docs/registry/modules/use#using-modules](https://developer.hashicorp.com/terraform/registry/modules/use) (resolved as: /docs/registry/modules/use)

- On source page path = /docs/language/providers/:
   -> linking to [/docs/registry/providers/docs](https://developer.hashicorp.com/terraform/registry/providers/docs)
   -> linking to [/docs/plugin](https://developer.hashicorp.com/terraform/plugin)

- On source page path = /docs/language/settings/backends/remote:
   -> linking to [/docs/cloud-docs/run/cli](https://developer.hashicorp.com/terraform/cloud-docs/run/cli)
   -> linking to [/docs/cloud-docs/run/run-environment#environment-variables](https://developer.hashicorp.com/terraform/cloud-docs/run/run-environment) (resolved as: /docs/cloud-docs/run/run-environment)

- On source page path = /docs/language/settings/tf-cloud:
   -> linking to [/docs/cloud-docs/run/cli](https://developer.hashicorp.com/terraform/cloud-docs/run/cli)

- On source page path = /docs/language/state/remote-state-data:
   -> linking to [/nomad/docs/job-specification/template](https://developer.hashicorp.com/nomad/docs/job-specification/template)

- On source page path = /docs/language/values/variables:
   -> linking to [/docs/plugin/sdkv2/best-practices/sensitive-state#using-the-sensitive-flag](https://developer.hashicorp.com/terraform/plugin/sdkv2/best-practices/sensitive-state#using-the-sensitive-flag) (resolved as: /docs/plugin/sdkv2/best-practices/sensitive-state)
 

### Rationale and alternatives

-

**Comment by Hefeweizen** [comment]
Just a quick call out:
in reading the issue, I saw the link to `/docs/downloads` and assumed it links internally to our repo (as a convenience to find what's been completed).  It does not.  It points to the documentation from the legacy project.

If others find this confusing, a pair of links might be better, perhaps tagged as `original` and `desired`.  For example, something like this:

> On source page path = /docs/cli/install/apt:
> -> Original Link [https://developer.hashicorp.com/terraform/downloads](https://developer.hashicorp.com/terraform/downloads)
> -> Desired Link [/docs/downloads](/opentffoundation/opentf/tree/main/docs/downloads)

**Comment by mahmod87** [comment]
T

**Comment by mahmod87** [comment]
Y

**Comment by mahmod87** [comment]
brew tap hashicorp/tap
brew install hashicorp/tap/terraform
