### ISSUE TITLE
Links in `docs/intro/#community` are broken

### ISSUE THREAD

**Issue by maheshrjl** [opentofu/opentofu#447]
### OpenTF Version

```shell
NA
```

### OpenTF Configuration Files

NA

### Debug Output

NA

### Expected Behavior

Link redirects on [the website](https://opentofu.org/docs/intro/#community) should not return 404.

### Actual Behavior

Below links return 404. 

- Ask questions in [OpenTF Discuss](https://github.com/placeholderplaceholderplaceholder/opentf/discussions).
- Read our [contributing guide](https://github.com/placeholderplaceholderplaceholder/opentf/blob/main/.github/CONTRIBUTING.md).
- [Submit an issue](https://github.com/placeholderplaceholderplaceholder/opentf/issues/new/choose) for bugs and feature requests.

### Steps to Reproduce

NA

### References

Similar to #264 & #443 but for the [website](https://opentofu.org/docs/intro/#community).

**Comment by yaronya** [comment]
Hi @maheshrjl 
Thank you very much for your contribution 🙏 

Please kindly note that it's best to first wait for a confirmation of a core maintainer to accept the issue, so no wasted work would be done.
Nonetheless, this is a trivial and acceptable change so I'm going to approve it.

**Comment by maheshrjl** [comment]
Noted! Thanks :)
