### ISSUE TITLE
Missing security contact for repo

### ISSUE THREAD

**Issue by maheshrjl** [opentofu/opentofu#449]
### OpenTF Version

```shell
NA
```

### Use Cases

A security contact would allow for responsible disclosure of vulnerabilities. 

### Attempted Solutions

NA

### Proposal

Having a SECURITY.md at [organization level](https://github.com/opentofu/.github) or [repo level](https://github.com/opentofu/manifesto) with an email contact would be great to start with.

**Comment by DicsyDel** [comment]
Duplicate for https://github.com/opentofu/opentofu/issues/423

**Comment by maheshrjl** [comment]
Ah I should have checked before creating an issue. My bad.
