### ISSUE TITLE
Support for init-time constants

### ISSUE THREAD

**Issue by valentindeaconu** [opentofu/opentofu#450]
### OpenTF Version

```shell
-
```

### Use Cases

Working with TF on large-scale projects or mono-repositories with a lot of duplicates can become overwhelming. For example, updating a module version or refactoring the name of the AWS profiles. In this feature request, I propose the idea of introducing init-time constants (values that can be evaluated at init-step) which can help us (TF developers) to follow the DRY principles and also can reduce a lot of hardcoded values.

### Attempted Solutions

For example, to define a module, the only possible way is:
```hcl
module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "3.15.0"
}
```
If we have two instances of the same module:
```hcl
module "vpc-1a" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "3.15.0"
  
  # ...
}
module "vpc-1b" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "3.15.0"

  # ...
}
```
Of course, we can use a `for_each = toset(["1a", "1b"])` to avoid repeating ourselves, but this problem can become more complex: what if we have 2 different TF projects, with two different backends, hitting different accounts? The `for_each` workaround no longer works. So we will end up with two actual module blocks copied in both places. The problem occurs when we want to bump the module version. We will have to update both places.

This problem can be solved outside of TF by introducing a wrapper (e.g. Terragrunt) or by using a dependency updater (e.g. RenovateBot) (for this use-case only).

There are a lot of use cases where we can use those constants to avoid hardcoding values - `provider` blocks, providers versions, OpenTF version, backends, modules, etc.

### Proposal

My suggestion to overcome this issue is to introduce init-time constants. The constants will be defined totally the same as the variables:
```hcl
constant "vpc_module_version" {
  type        = string
  description = "The VPC module version."
  default     = "3.15.0"
}

constant "vpc_module_name_suffix" {
  type        = string
  description = "The suffix for the VPC module name."
  default     = "1b"
}
```
And then used in code as:
```hcl
module "vpc-${const.vpc_module_name_suffix}" {
  source  = "terraform-aws-modules/vpc/aws"
  version = const.vpc_module_version
  
  # ...
}
```

Of course, the main point here is supporting them exactly the same as the variables:
- Providing constants' values with the `-const` flag;
- Providing constants' values with the `TF_CONST_` prefix environment variable;

More explicitly, they will behave like variables, the only difference here being the time when they are evaluated (pre-init, instead of post-init).

### References

There are a lot of references that can be given as examples on _the other repository_, I will provide them if they are requested.

**Comment by Hefeweizen** [comment]
Related issue:  https://github.com/opentofu/opentofu/issues/388

**Comment by StephanHCB** [comment]
Some kind of early-set variables would be great to have when defining state backends. This allows separate state storages for, say, development and production (permission reasons) while using the same code (prod parity).

**Comment by cube2222** [comment]
Thanks for creating the issue!

We've discussed this a bit and agreed that introducing a new keyword (constant) would most likely be overkill for this.

Right now there is an RFC that is proposing something similar, but implicitly via variables: https://github.com/opentofu/opentofu/issues/1042
