### ISSUE TITLE
Change the release process to use `tofu`

### ISSUE THREAD

**Issue by eranelbaz** [opentofu/opentofu#452]
Binary, docker images, git references needs to be changed to `opentofu`

**Comment by pdecat** [comment]
It would be great to also be able to build the CLI with `go build`/`go install`, maybe with a new Make target.

**Comment by eranelbaz** [comment]
Hey @pdecat thanks for the feedback
we didn't make it yet, if you would like to you are welcome to create a PR for that :)

**Comment by eranelbaz** [comment]
Closing this issue and will create another one regarding `go build/go install`
