### ISSUE TITLE
Update copyright notice

### ISSUE THREAD

**Issue by nemobis** [opentofu/opentofu#454]
At least the primary LICENSE file should be updated from
> Copyright (c) 2014 HashiCorp, Inc.

to a generic attribution/copyright holder, for example:

> Copyright (c) 2014-2023 HashiCorp, Inc.
> Copyright (c) 2023- OpenTofu contributors

See also https://reuse.software/spec/#format-of-copyright-notices

To avoid any confusion it could also be useful to explicitly state that contributors are not assigning or transferring any copyrights to HashiCorp.

**Comment by cube2222** [comment]
Hey @nemobis!

Agreed it would be good to clarify the copyright notices. We'll be working on the details of this, and how to exactly express this, with lawyers. Until then they'll have to remain unchanged.

**Comment by kislerdm** [comment]
Hey folks! I noticed that the forked files contain the copyright header which we may want to change as well. For example, [build.sh](https://github.com/opentofu/opentofu/blob/0930a908227376f0647f759cdfbadfc71f32fad5/scripts/build.sh#L1-L4). WDYT?

**Comment by cube2222** [comment]
Yeah, it's in most of the repo. We still have to figure out (by talking with lawyers) what exactly we want to put there.

I like the approach proposed above and it seems reasonable to me:
> Copyright (c) 2014-2023 HashiCorp, Inc.
Copyright (c) 2023- OpenTofu contributors

but we need to make sure that it's sound first.

**Comment by nemobis** [comment]
BTW I've just noticed that many hashicorp repositories have pending pull requests to add copyright headers which would declare HashiCorp as the only copyright holder, which sounds unlikely to be correct in repositories where there was no CLA (and may be copyfraud if intentionally misleading).

Hopefully it's just a misunderstanding or some unfinished work which they're willing to revise, but see https://github.com/hashicorp/copywrite/issues/100

So just to be clear my suggestion to use
> 2014-2023 HashiCorp, Inc.

was only an example, as something more vague (either in time or copyright holder naming) may be required on repositories with less clear copyright status.

**Comment by cube2222** [comment]
Just to provide an update here, the updated notice should look as follows:
```
// Copyright (c) The OpenTofu Authors
// SPDX-License-Identifier: MPL-2.0
// Copyright (c) 2023 HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
```

**Comment by cube2222** [comment]
We should also apply this to the registry-address repo.

**Comment by namgyalangmo** [comment]
I would like to resolve this issue!

**Comment by janosdebugs** [comment]
Hi @namgyalangmo I've assigned you.

**Comment by janosdebugs** [comment]
Hey @namgyalangmo I agree that this solution is a bit of a workaround. If there's a good alternative solution which just lets us statically provide the header, that would be better, but ultimately, this may work too.

**Comment by namgyalangmo** [comment]
Noted, will try out a few other methods and push the changes soon.

**Comment by namgyalangmo** [comment]
@janosdebugs  I raised a PR for now, meanwhile if there are any other possible alternatives I will accordingly let the community know. 
PR: [https://github.com/opentofu/opentofu/pull/1216](url)

**Comment by namgyalangmo** [comment]
I have just pushed the PR, will let the OpenTF community know if I find a better alternative to  update the copyrights. 
You can review the PR here: [https://github.com/opentofu/opentofu/pull/1218](url)

**Comment by namgyalangmo** [comment]
Should I add copyright headers to files in the OpenTOFU repository that didn't originally have them and are not listed under "header_ignore"? Also, "copyright headers" is adding copyright to the "internal/cloudplugin/cloudproto1/cloudproto1.proto" file , a file that should not have copyright (PFA screenshot for context). Should I modify the code to exclude ".proto" files by updating the "header_ignore" list?
<img width="922" alt="Screenshot 2024-02-03 at 11 51 09 AM" src="https://github.com/opentofu/opentofu/assets/75657887/c5fa1d78-9a26-4dbc-a8e3-93d1be08e30b">
<img width="951" alt="Screenshot 2024-02-03 at 12 09 40 PM" src="https://github.com/opentofu/opentofu/assets/75657887/e0c193f5-c4a0-4e70-9868-6d25ed835ec3">
<img width="1191" alt="Screenshot 2024-02-03 at 12 26 33 PM" src="https://github.com/opentofu/opentofu/assets/75657887/bf0bf0ec-20de-43d5-99bd-e3ff9741e367">

**Comment by MarkAtwood** [comment]
The "(c)" part is pointless and useless, and should be removed. The year part is not needed for open source projects that are in widely replicated git repos.

The copyright statement should be:

Copyright  2014-2023 HashiCorp, Inc.
Copyright  by the OpenTofu contributors
