### ISSUE TITLE
Rename http://opentofu.org to https://opentofu.org

### ISSUE THREAD

**Issue by kutysam** [opentofu/opentofu#460]
### OpenTF Version

```shell
NA
```

### OpenTF Configuration Files

NA

### Debug Output

NA

### Expected Behavior

NA

### Actual Behavior

NA

### Steps to Reproduce

nA

### Additional Context

![image](https://github.com/opentofu/opentofu/assets/1703663/e6eb8b19-aa7b-499c-8619-bf0ffd6a23f2)

Just a simple improvement. Would be good to change it to https to prevent an unnecessary https 302 redirect call.
This is on github org page.

**Comment by marcinwyszynski** [comment]
This is done now, good job noticing that!
