### ISSUE TITLE
Tag Docker images to internal registry 

### ISSUE THREAD

**Issue by alex067** [opentofu/opentofu#507]
Hey folks 👋 

Apologizes if this is a bit too premature, as there isn't an official release out yet. 

The current build pipeline includes a job for building and tagging a public Docker image release. However the images are being tagged under:
` docker.io/hashicorp/...` 
`public.ecr.aws/hashicorp/...`

Although this isn't publishing the image to the mentioned repositories, it does contain in the final archive metadata referencing the repository.

Since this isn't actually publishing the image to the mentioned repositories and creating tags, I'm happy to change the tags to something more suitable like:

`docker.io/opentofu/...`

**Comment by Hefeweizen** [comment]
[GoReleaser](https://goreleaser.com/) is in use.  I just submitted [PR 523](https://github.com/opentofu/opentofu/pull/523) which updates it with the new project name.

I could have missed something though.  Is there labeling outside of this that needs updated?

**Comment by alex067** [comment]
Thanks @Hefeweizen ! 

The tagging I saw was in in the `build.yaml` workflow under the `package-docker` step where we're tagging images under the HashiCorp namespace.
