### ISSUE TITLE
Provide confirmation for State changes

### ISSUE THREAD

**Issue by alex067** [opentofu/opentofu#509]
### OpenTF Version

```shell
OpenTF v1.6.0-dev
on darwin_arm64
```

### Use Cases

The default behavior for running state commands, is to directly execute the command without requiring a manual approval process.

This differs from actions like plan, apply, and destroy, which by default does ask the user for a manual confirmation before proceeding to execute the command.

The state commands should adopt this type of process, as they can be equally destructive as accidentally running an apply or destroy.

### Attempted Solutions

I have not attempted to provide a solution in OpenTF yet.

However I have hastily written a wrapper around `terraform state` to provide a manual approval process, along with an output stating what the proposed changes are. https://github.com/alex067/tfstate 

### Proposal

The proposal is to include two additional outputs to `state mv` and `state rm` commands.

1. Require the user to manually confirm the changes, similar to plan, apply and destroy. An additional `--auto-approve` flag can be supplied to skip this process. 
2. An output on what the proposed changes would affect. For example, with `state rm` proposed changes should include the removal of the resource from the state file, along with affected resource dependencies.

**Comment by Hefeweizen** [comment]
The --help for the `state` subcommand describes the entire set of operations as: "This command has subcommands for advanced state management."  Given that it's _advanced_ state management, and not standard operations (i.e. `plan`/`apply`) isn't some form of caution implied?

Strengthening this warning, making it more explicit with "proceed at your own peril," would certainly underscore the dangerous nature of these operations.

I consider `tofu state rm` or `tofu state mv` the standard form of these operations.  I'd be tagging `--auto-approve` with every usage.  In contrast, I do not consider `tofu apply --auto-approve` as the standard form of that operation; the plan was skipped and the `--auto-approve` forces the user to acknowledge that they're operating outside the intention of the tool.  I'm not against providing the user with more warning, but `--auto-approve` would obstruct standard usage.

**Comment by alex067** [comment]
I don't agree that the `state` subcommand is for "advanced" state management. 

There are two ways to alter your state:
1. Using the `state` subcommand
2. Manually editing the state file, updating the serial, and pushing the state to your backend

Considering that, the `state` subcommand becomes the user friendly way of altering your state. Therefore, the command should behave similar to an `apply` or `destroy` by providing safe guard rails + better output on what resources are affected by your state changes.

**Comment by cube2222** [comment]
There are also declarative state management blocks: move, import, and in 1.7 removed is coming as well.

If you'd like to have an approval flow, that will also show you a plan of things to be changed, please use those declarative blocks in your config.
