### ISSUE TITLE
Stale field in PR template regarding backport bot

### ISSUE THREAD

**Issue by jenia** [opentofu/opentofu#514]
### OpenTF Version

```shell
N/A
```

### OpenTF Configuration Files

N/A

### Debug Output

N/A

### Expected Behavior

N/A

### Actual Behavior

N/A

### Steps to Reproduce

N/A

### Additional Context

In the PR template, there is a field pertaining to `x.y-backport label to enable the backport bot.` which is a [relic left over from hashicorp project and not used anymore](https://opentofucommunity.slack.com/archives/C05RKE7PS72/p1695193046859649?thread_ts=1695158449.030969&cid=C05RKE7PS72).

### References

Slack [conversation](https://opentofucommunity.slack.com/archives/C05RKE7PS72/p1695193046859649?thread_ts=1695158449.030969&cid=C05RKE7PS72).

**Comment by lfacchinelli** [comment]
Hey guys, I'd like to help on this one. Seems a quite simple change for a new joiner

**Comment by cube2222** [comment]
Go ahead @lfacchinelli !
