### ISSUE TITLE
Allow real variable definitions in OpenTofu

### ISSUE THREAD

**Issue by dwgillies-bluescape** [opentofu/opentofu#521]
### OpenTF Version

```shell
1.0
```

### Use Cases

We run a series of clusters and have - fundamentally - about 10 parameter that determines the values used by the cluster.  These parameters are typically located in a single file and all of our other files are soft links to 10 files per project and about 10kloc of terraform (at the first level) and about 27kloc to instantiate all our services via helm.

From these 10 parameters we want to generate about 30 meta-parameters which are more suitable for input to AWS terraform module creation.   These 30 meta-parameters are calculated with string concatenations, map lookups, by sensing the environment [ is_govcloud = (var.aws_partition == "aws-us-gov") ], or possibly in the future, by function calls.  Variables should be a first-class object in terraform.  They should crazy constants whereby locals and variables are not equivalent.

### Attempted Solutions

no solution.   the design of the language is overly restrictive and broken.

### Proposal

There should be not be separate definitions for "variable" and "local".  There should not be a rule that a variable must always be initialized with a constant.  It should be possible to define a new variable based upon an expression involving other variables.

In fact we should drop the idea of locals altogether, just alias local = variable in the next version of terraform.  Also, the idea of a language that behaves differently based on the filename suffix (file.tf vs. file.auto.tfvars) is a mistake.  Please get rid of that.

Please fix all these problems in terraform.

If I want to hang myself, I should be permitted the privilege.  

### References

none.

**Comment by psantus** [comment]
I beg to disagree. 
Locals are useful to factorize variable without making them externally accessible. 
Quite useful in a module context.

**Comment by mikery** [comment]
>  It should be possible to define a new variable based upon an expression involving other variables.

This is one of the use cases for `locals`:

```terraform
variable "aws_partition" {}
locals {
  is_govcloud = var.aws_partition == "aws-us-gov"
  foo = lower("FOO")
  bar = "${local.is_govcloud}-${local.foo}"
  baz = local.is_govcloud ? "green" : "blue"
}
```

**Comment by jwenz723** [comment]
I think this could be accomplished by allowing variables to be defined as public/exported (variables that can be accessed outside of the module) or private/internal (variables that cannot be accessed outside of the module). This would make the hcl language more similar to traditional coding languages. 

But this would be a huge breaking change and would break a lot of existing modules. So I don’t think I would support removing the existence of locals.

**Comment by cube2222** [comment]
As discussed above, locals are the language construct to use here.
