### ISSUE TITLE
C API

### ISSUE THREAD

**Issue by SamuelMarks** [opentofu/opentofu#544]
### OpenTofu Version

```shell
N/A
```

### Use Cases

- Link—statically or dynamically—with frontends (e.g., a CLI or RPC frontend written in C, or wrapped into a library that is statically/dynamically linked into another language, such as Rust)
- Contend with multicloud interfaces in other languages, Terraform is better funded and often more maintained than, e.g., Python's [libcloud](https://libcloud.apache.org/), Java's [jclouds](https://jclouds.apache.org/), and Ruby's [fog](https://fog.io/).

With everything unified and made trivially multilingual through FFI, the entire elastic scaling lifecycle can be managed from a single binary. Which will [I expect] lower the barrier to entry for moving between cloud providers, initial de/provisioning, scaling, and maintenance.

### Attempted Solutions

N/A

### Proposal

Years ago I wrote a wrappers around Apache Libcloud in Python for my multi-cloud abstraction libraries. It’s great, and supports 50+ different public and private clouds.

Now, I’m tossing up betwixt the different languages to rewrite the whole system in. Likely, I’ll write the bulk of it in C (C89, the old ANSI C); maybe with some configuration management done in Rust.

Unfortunately there are no good/maintained abstracted cloud [de]provisioning/upload/configuration libraries. Cursory research shows Terraform as the only [maintained & large] library written with a non-VM language. Congrats!

Are you planning to expose C-APIs; perhaps via Go’s builtin C meta-package; so this can be used from other languages?

Thanks for considering this feature

### References

- 3 years ago I asked on the forum https://discuss.hashicorp.com/t/c-api-to-terraform-providers/14195
- Over 2.5 years ago I asked on https://github.com/hashicorp/terraform-cdk/issues/513
- Over 2.5 years ago I asked on https://github.com/hashicorp/terraform/issues/27581

**Comment by cube2222** [comment]
Thanks for creating the issue @SamuelMarks!

TBH it sounds like a fairly niche use-case (though I'm happy to be proven wrong), and I imagine it would make more sense to consume OpenTofu as a CLI? Maybe it could be done by the community as an external library that builds on top of the providers?

It's worth noting that OpenTofu doesn't create a cloud provider-agnostic abstraction. The providers are modelled after the specific cloud provider, so e.g. the tf code to provision a GCP VM is completely different than the tf code to provision an AWS VM.

**Comment by SamuelMarks** [comment]
Hey @cube2222,

Actually I don't think it's a niche use-case at all. Advantages of a C API are many, and facilitate the [trivial] engineering of:
  - GUIs
  - CLIs
  - SDKs
  - Language wrappers
    - Python
    - Rust
    - Swift
    - Kotlin
    - Java
    - Fortran
    - Ruby
    - Perl
    - &etc.
  - Database integration
  - Server interfaces (e.g., for maintaining inventories across multiple clouds)
    - Clients (CLIs, SDKs, GUIs) for these server interfaces

Not to mention the regular advantages that Go provides, like support for running on different operating systems.

**Comment by cube2222** [comment]
We've discussed this and agreed that we won't be doing a C api for OpenTofu nor the SDKs for now.

Regarding exposing OpenTofu as a library, there's a lot of complexity discussed in #758 and #810.

I would recommend using https://github.com/hashicorp/terraform-exec for this purpose or similarly executing tofu as a sub-process.
