### ISSUE TITLE
Existed integration still run ip

### ISSUE THREAD

**Issue by tnfsmith** [opentofu/opentofu#559]
### OpenTofu Version

```shell
Alpha version and early final
```

### Use Cases

Hi, I use TF for a long time ago. Now consider switch to tofu after changed from HC. I suggest we keep all the code work and migrate to open source within our aim and path ahead. Thanks team mates

### Attempted Solutions

Keep code running well

**Comment by cube2222** [comment]
Hey @tnfsmith! We're indeed planning to remain fully backwards-compatible.
