### ISSUE TITLE
Update email contact in Code of Conduct

### ISSUE THREAD

**Issue by keivinonline** [opentofu/opentofu#565]
Description: The email contact in `Code of Conduct` page should be using an updated email contact e.g. contact@opentofu.org 
The new email contact needs confirmation from the opentofu team.

**Comment by keivinonline** [comment]
This should relate to #451

**Comment by swastik959** [comment]
@keivinonline  hi I resolved this issue however I was able to directly oush to main branch I think main branch is not protected . Should I make a issue for it

**Comment by keivinonline** [comment]
that's weird. 
`main` should be protected already. perhaps you got it confused with a local fork. 

also, I don't think `contact@opentofu.org` is a valid mailing address just yet.
let's wait for the opentofu team to get back on the finalized address.

**Comment by cube2222** [comment]
Good catch, thanks for creating this issue!

**Comment by swastik959** [comment]
@cube2222 can I make a pr

**Comment by eranelbaz** [comment]
Also related to #528

**Comment by janosdebugs** [comment]
Hey folks, I believe this is resolved as the CoC contains an email address. Please reopen the issue if that is not sufficient.
