### ISSUE TITLE
Support linux package repositories for tofu distribution

### ISSUE THREAD

**Issue by kislerdm** [opentofu/opentofu#567]
### OpenTofu Version

```shell
1.6.0-beta1
```

### Use Cases

As a Ubuntu/Debian/Fedora/CentOS user, I want to use native package manager to install `tofu`, so I could seamlessly migrate from terraform.

### Attempted Solutions

-

### Proposal

Configure goreleaser to package the distribution and publish it to linux pkg repositories.

- _deb_ for Debian/Ubuntu users:
   - [config](https://goreleaser.com/customization/nfpm/)
   - [registry docs](https://www.debian.org/doc/manuals/developers-reference/pkgs.html#upload).

- _rpm_ for CentOS, Fedora and Amazon Linux users:
   - [config](https://goreleaser.com/customization/nfpm/)
   - [tutorial](https://www.redhat.com/sysadmin/create-rpm-package)

### References

- #418 
- #430 

## Open questions

- What package repositories shall be used? 
- Shall we rely on public repositories (like Debian ftp), or would we rather setup a custom repository (similar to how hashicorp distribute linux packages)?

### Hosted options

- [packagecloud with GitHub packages](https://blog.packagecloud.io/resources/how-to-publish-debian-packages-on-github-packages/) 
- [jfrod artifactory](https://jfrog.com/help/r/jfrog-artifactory-documentation/debian-repositories)
- [custom debian repo](https://wiki.debian.org/DebianRepository/Setup)
- [aptly with s3](https://www.aptly.info/)

**Comment by catouc** [comment]
Might be worth noting the open PR for nixpkgs https://github.com/NixOS/nixpkgs/pull/256307 where some questions are somewhat open for the compatibility guarantees of OpenTofu.

Is this going to maintain the same guarantees as terraform to their v1 promises https://developer.hashicorp.com/terraform/language/v1-compatibility-promises?

**Comment by cube2222** [comment]
Hey @kislerdm, thanks for creating the issue!

I think the goreleaser part of this was already contributed in #362. I believe we already have a packagecloud account set up for this, too.

**Comment by davidjeddy** [comment]
Do we want to consider apk and flatpak as a release target as well?

**Comment by cube2222** [comment]
We should also update [this docs page](https://opentofu.org/docs/cli/install/yum/#repository-configuration) as part of this issue.

**Comment by marziply** [comment]
Any love for the Arch Linux Package repository?

**Comment by cube2222** [comment]
@marziply Isn't that usually maintained in an unofficial capacity by Arch users?

**Comment by keithpitt** [comment]
Hey, CEO of Buildkite here.

We'd be happy to sponsor hosting the packages as we recently acquired PackageCloud and are building support directly into the product https://buildkite.com/releases/2023-09

**Comment by cube2222** [comment]
Thanks @keithpitt, that would be awesome!

How would we go about setting this up? You can reach me at kubam@spacelift.io, if you prefer to discuss this via email.

**Comment by cube2222** [comment]
(also, no need to do alpine, they've already added us on their own to their official registry)

**Comment by Yantrio** [comment]
@vtrenton FWIW: As far as I'm aware it's already available as a snap here: https://snapcraft.io/opentofu

**Comment by cube2222** [comment]
> Thanks @keithpitt, that would be awesome!
How would we go about setting this up? You can reach me at [kubam@spacelift.io](mailto:kubam@spacelift.io), if you prefer to discuss this via email.

Haven't gotten a response from @keithpitt unfortunately (also tried via email).

Thus, we'll just use CloudFlare R2 for this.

**Comment by tommeier** [comment]
@cube2222 hi 👋 sorry for the delayed response (we've been travelling a fair bit and this fell through the cracks) - the team will get back to you today with some steps and get you going (assuming you haven't already gone deep on CF R2)

**Comment by cube2222** [comment]
@tommeier Awesome, thanks! Got the email, will set up a packagecloud account.
