### ISSUE TITLE
Prune Unused pluginSHA256LockFile From internal/command

### ISSUE THREAD

**Issue by alrs** [opentofu/opentofu#574]
### OpenTofu Version

```shell
.
```

### Use Cases

.

### Attempted Solutions

.

### Proposal

There is a long-untouched (save for my recent `io/ioutil` deprecations) struct type in the `internal/command` package called `pluginSHA256LockFile` that is used only by its receiver function `Read()` and its test.

We can remove this struct, its function, and its test.

### References

.

**Comment by cube2222** [comment]
Makes sense to me, thanks for creating the issue!
