### ISSUE TITLE
Managing local state could be much faster

### ISSUE THREAD

**Issue by jonjohnsonjr** [opentofu/opentofu#578]
### OpenTofu Version

```shell
OpenTofu v1.6.0-dev
on darwin_arm64
```

### Use Cases

We manage a few thousand resources that each contribute a nontrivial amount of state to our `tfstate` file. As the number of resources has grown, we have noticed that `tofu apply` has slowed down tremendously.

I would like to make it feasible to manage large numbers of resources and large amounts of state in a single `tfstate` file.

### Attempted Solutions

https://github.com/opentofu/opentofu/pull/397

We have experimented with sharding the state across multiple invocations using terragrunt, but that doesn't feel like a proper solution.

### Proposal

I have described the problem with a repro and possible solutions here: https://github.com/jonjohnsonjr/slow-tfstate

Fixing the `Filesystem` implementation such that it doesn't `PersistState` constantly is fairly straightforward and makes things remarkably faster.

In the linked repro, I have a `fast` directory and a `slow` directory. The slow directory reads a local file with 1MB of random data. That inflates the `tfstate` file to be ~5MB. When I apply this, it takes almost 3 minutes, spending most of its time in WriteState:

![image](https://github.com/opentofu/opentofu/assets/17863526/a941c22b-7d95-4916-8a0d-6641ebcc44b8)

If I "fix" `Filesystem` to behave like other state backends, it only takes ~9 seconds:

![image](https://github.com/opentofu/opentofu/assets/17863526/7448aabf-5ebb-497f-a690-13a4da60149a)'

Now... taking 9 seconds in order to sleep for 1 second seems not great, but we can tackle that next.

**Comment by alex067** [comment]
offtopic, apologizes in advance:

what did you use to generate the traces and the flame graph?

**Comment by jonjohnsonjr** [comment]
> what did you use to generate the traces and the flame graph?

This is [`samply`](https://github.com/mstange/samply), which is wonderful.

**Comment by cube2222** [comment]
This is an excellent finding, thanks for describing it in so much detail @jonjohnsonjr!

To summarize what you've described in your repo here in the issue (and correct me if I'm wrong) with some background about the interfaces there:
- State managers have a transient and persistent interface they implement.
- Transient methods like WriteState are supposed to do an in-memory checkpoint only.
- Persistent methods like PersistState should operate on persistent storage, in this case the filesystem.
- In this case, PersistState is called every 20 seconds, and should be the one making on-disk changes.
- WriteState is implemented as persistent, and called after each resource update, which makes the on-disk change happen after each resource update.
- Your proposed solution fixes WriteState to work on in-memory data only, relying on PersistState for persistent changes. This reduces the run time for your test scenario from 3 minutes, to ~9 secs.

I definitely think we should accept this fix. The only possible nit being that we might only want to do so **after** the first stable release (1.6.0).

**Comment by marcinwyszynski** [comment]
The original bug had interesting side effects which alleviated somewhat the impact of crashes. I agree that we should fix this bug *and* think about how to best achieve the same safety across different backends. That said, I would like to document this change heavily in our changelog in case someone actually depended on this bug.

**Comment by jonjohnsonjr** [comment]
> The original bug had interesting side effects which alleviated somewhat the impact of crashes. I agree that we should fix this bug and think about how to best achieve the same safety across different backends.

Yeah this is the only thing I can imagine as a benefit of leaving it this way. There are nicer ways to achieve this property, e.g. write-ahead logging, but that seems like a fairly invasive change that I'd like to avoid if we can.

I'm not sure how feasible it would be, but we might be able to call a last resort `PersistState` from inside a high level `recover()` if we can get a handle to the state manager. This could also be useful for other backends on a crash, but I haven't really investigated this much. If anybody has thoughts/pointers around this, I'd love to hear them.

> The only possible nit being that we might only want to do so after the first stable release (1.6.0).
> ...
> That said, I would like to document this change heavily in our changelog in case someone actually depended on this bug.

Totally reasonable, let me know how I can help make this easier to release. Is there any precedent for doing an opt-in rollout for something like this? We could have `WriteState` call `PersistState` with an environment variable (or something) to skip it.

**Comment by marcinwyszynski** [comment]
> I'm not sure how feasible it would be, but we might be able to call a last resort PersistState from inside a high level `recover()` if we can get a handle to the state manager.

I think it would still not be bulletproof, because it would depend on the exact nature of the crash.

My intuition is to test it thoroughly and then aim for the 1st release after GA. Longer term we could revisit better state behavior in face of failures as you suggest in your 1st paragraph.

**Comment by Hefeweizen** [comment]
nice summary @cube2222

I think it'd be useful to capture this more permanently, but I'm not sure what's best?  Do we start a `docs/state-management.md` or `docs/backend.md` doc?  Do we add comments to the tests, or additional tests?

This also feels a bit tangential, should I start a separate issue around extending the backend documentation?

**Comment by eranelbaz** [comment]
Is #397 also relevant here?

**Comment by jonjohnsonjr** [comment]
> Is https://github.com/opentofu/opentofu/pull/397 also relevant here?

Yeah, I link to it under `Attempted Solutions`. That kind of optimization becomes much less necessary if we stop marshaling state on every `WriteState` and instead only marshal state before we persist it.
