### ISSUE TITLE
Release action doesn't work - fail for `craft-store error: Credentials could not be parsed.`

### ISSUE THREAD

**Issue by eranelbaz** [opentofu/opentofu#591]
Action link - https://github.com/opentofu/opentofu/actions/runs/6313959167/job/17143181189

Https://github.com/opentofu/opentofu/pull/418 added a step to the release process
With this note
> Note: This should not be merged without a token being added that logs in correctly or the CI for the project will start failing.

I guess we didn't add that token to our secrets, we need to fix it

**Comment by cube2222** [comment]
That's interesting. I did add these credentials, I'll look into it tomorrow/Thursday.

**Comment by eranelbaz** [comment]
Thanks
currently it blocks my pr as I can't QA the full process #590
