### ISSUE TITLE
Port cdktf to OpenTofu

### ISSUE THREAD

**Issue by sebs** [opentofu/opentofu#601]
### OpenTofu Version

```shell
does not apply
```

### Use Cases

* use OpenTofu on Terraform with a little layer of CDK on top of it 
* better unit testing of more aspects of the stacks
* get user influx from people knowing CDK and using the OpenTofu Variant on other cloud providers

### Attempted Solutions

* using CDKTF has no alternative (yet) 

### Proposal

Port CDKTF to work with OpenTofu.

**Comment by denmanveer** [comment]
The major advantage is that it provides support to use any familiar programming languages to define and provision infrastructure.
Which by default OpenTofu lacks, as it uses HCL.

This will give an added advantage over tools like Pulumi & Paid Terraform with CDKTF (https://developer.hashicorp.com/terraform/cdktf)

Please add this roadmap, thank you.

**Comment by mornindew** [comment]
I agree with the need for this.  Using native languages (procedural) is important for many use cases.

Upvote for sure

**Comment by Yantrio** [comment]
I'm happy to say this is working and we can close this issue. Thank you @joshpollara for testing this <3

**Comment by jmservier** [comment]
does CDK support other cloud providers than AWS (such as GCP, Azure …) ?

**Comment by janosdebugs** [comment]
@jmservier this may be something best asked on the OpenTofu Slack or the GitHub Discussions as the issue here will get few eyeballs.

**Comment by baterja** [comment]
Will OpenTofu be kept compatible with Terraform's CDK or have it own? I mean: it's nice it currently is compatible, but what will happen with CDK if OpenTofu will break Terraform compatibility at some point in the future?

**Comment by kvendingoldo** [comment]
btw. you can also integrate [tenv](https://github.com/tofuutils/tenv) that support Terraform as well as OpenTofu (and Terragrunt :) ) in one tool. It allow you to simplify version management.

**Comment by keidarcy** [comment]
If you install the provider by package.json(TS) not cdktf.json, the only thing you need to change to use OpenTofu is `TERRAFORM_BINARY_NAME=tofu`!

**Comment by commiterate** [comment]
CDKTF has been [deprecated](https://github.com/hashicorp/terraform-cdk/commit/a0c56138e2b4c7b6c128bd7ba08a8e317df852af).

**Comment by benglewis** [comment]
Does the CDKTF deprecation make this more or less likely?

**Comment by shinebayar-g** [comment]
> Does the CDKTF deprecation make this more or less likely?

https://github.com/opentofu/opentofu/issues/2402#issuecomment-3638632752 less

**Comment by so0k** [comment]
for future visitors - community effort is gathering at https://cdk.dev -> `#terraform-cdk` channel

CDK Terrain - https://cdktn.io is the name the port landed on (and it supports opentofu core functions such as `urldecode` and `cidrcontains`.
