### ISSUE TITLE
Build WF checks wrong directory

### ISSUE THREAD

**Issue by serdardalgic** [opentofu/opentofu#609]
### OpenTofu Version

```shell
main
```

### OpenTofu Configuration Files

-

### Debug Output

-

### Expected Behavior

Packages should be correctly built

### Actual Behavior

Builds are failing. For example:
https://github.com/opentofu/opentofu/actions/runs/6326021974/job/17178753249

Quoting @eranelbaz 
> It seems to look for opentofu under $BIN_PATH but since we change it to build tofu it fails

### Steps to Reproduce

Build system related, no tofu commands are necessary

### Additional Context

Slack discussion: https://opentofucommunity.slack.com/archives/C05R0FD0VRU/p1695828644334969

**Comment by eranelbaz** [comment]
Hey @serdardalgic 
I'm on it
Thank you for reporting!

**Comment by eranelbaz** [comment]
Seems like `BIN_PATH` is generated using `BIN_NAME`
and `BIN_NAME` defaults to `product_name`
