### ISSUE TITLE
Print warning for `hashicorp/terraform` provider usage

### ISSUE THREAD

**Issue by yaronya** [opentofu/opentofu#613]
### OpenTofu Version

```shell
N/A
```

### OpenTofu Configuration Files

```hcl
terraform {
    required_providers {
        terraform = {
            source = "hashicorp/terraform"
        }
    }
}
```

### Debug Output

When executing above code with `terraform`, you get a warning output coming from Hashicorp's registry saying:
```
╷
│ Warning: Additional provider information from registry
│ 
│ The remote registry returned warnings for registry.terraform.io/hashicorp/terraform:
│ - This provider is archived and no longer needed. The terraform_remote_state data source is built into the latest Terraform release.
╵
```

This warning is not present when executing with `tofu` using the new registry

### Expected Behavior

Warning should be displayed for the deprecated `hashicorp/terraform` provider usage.

### Actual Behavior

It's not displayed using `tofu`.

### Steps to Reproduce

1. `tofu init`

### Additional Context

These warning prints are handled by `internal/command/init.go:getProviders(...)`.

Since we don't wanna solve it on the registry side, we should add an if to `internal/providercache/installer.go:EnsureProviderVersions(...)` that will catch this, and print a similar use-facing warning.

**Comment by endocrimes** [comment]
> Since we don't wanna solve it on the registry side,

Is there an issue for that anywhere? - having a server-side ability to issue warnings for a package can be super useful (for managing things like deprecation's) - and hard coding them into the client is going to result in worse behavior.

**Comment by marcinwyszynski** [comment]
@endocrimes Fair point but I think this is a feature very specific to a handful of Hashi providers, not the rest of the registry. We should totally think about a mechanism to allow any provider author to distribute warnings, but this may be somewhat orthogonal.

**Comment by Yantrio** [comment]
I did some digging into the code, and it looks like the warnings come from the registry api as part of the version listing response

https://github.com/opentofu/opentofu/blob/main/internal/getproviders/registry_client.go#L133-L143

We should be able to add this pretty easily to the registry (just a simple file that we can look up to see if packages have warnings)

I don't see the need to do this on the clientside.

**Comment by yaronya** [comment]
Fair point @Yantrio
I had the assumption that it wouldn't be a trivial effort as adding it to the client

Converted to an issue in the registry repo: https://github.com/opentofu/registry/issues/108
