### ISSUE TITLE
How should the OpenTofu registry handle signatures and public keys?

### ISSUE THREAD

**Issue by cube2222** [opentofu/opentofu#619]
## Problem

This is an issue related to replacing the registry. Right now we’re ironing out the list of requirements for the official registry replacement (the one that we’ll use for the stable release) and one of the core requirements we need to settle is how do we handle public keys and their submission. Long-term we’d ideally adopt something like keyless signatures, but short-term we need to be a drop-in replacement for how things already worked.

## Background

It’s worth noting that the security baseline we need to achieve here is what the HashiCorp registry was doing. To give some context, there you’d log in via GitHub to the registry and if you’re a github org admin you can add public keys to the org namespace in the registry. This does mean that compromising a single github admin of the org lets you 1. replace the keys 2. replace the artifacts with malicious ones signed by your key. Compromising the registry itself also lets you change the artifact download location served and the signing keys served, so this is another attack angle.

## Some Approaches

Right now the alpha registry is accepting public keys via pull requests to its repository. This is not a bad approach by any means, as we can still verify organization membership of a key submitter and whether they match existing provider signatures. It also decouples the lifecycle a bit more in that the org admin can only create a PR to submit a key replacement, while we’d obviously ask a lot of questions in such a situation and would make sure this is not a malicious replacement + the delay of accepting a PR already makes the attack much harder to execute. The disadvantage of this is that it’s not fully self-service to add new keys, though we could introduce automation here that does the verification submitter account and makes sure this is a new key, and not existing key replacement.

Alternatively, we could also do it similar to how the HashiCorp registry does it. Letting a user sign-in via GitHub and provide their keys there. Fully self-service but easier to attack. Less work for OpenTofu maintainers though.

Another approach is to have a conventionally named repository in the organization store the public key. Then you’d need to compromise the account of any person who can both modify provider releases and have edit rights to that repo (while preferably you’d just let your admins edit that repo).

## Ask for Feedback

It’s important to note that we need to remain backwards-compatible with existing providers, even if we want to add new, better mechanisms here in the future, that provider authors will be able to opt in to.

It’s a tradeoff, and we’d love to hear more about how everybody feels about this issue, what you think about the proposed approaches, whether there are any critical issues to them that we haven't noticed, and if you have ideas for a better approach.

**Comment by cube2222** [comment]
You've previously created RFC's related to this topic @imjasonh @developer-guy, tagging in case you'd like to join the discussion here as well?

**Comment by mwarkentin** [comment]
> Long-term we’d ideally adopt something like keyless signatures

This would be something like https://www.sigstore.dev?

**Comment by maunzCache** [comment]
Let's do some number crunching maybe?
First i'd like to find out how many keys we assume are necessary to handle short term.

As of writing there are 3566 providers in the [hashicorp terraform registry](https://registry.terraform.io/browse/providers). 
35 of those are part of the hashicorp namespace. So 1 key at best.
304 providers are from hashicorp partners. It is safe to assume that some namespaces provide multiple providers. We have >304 keys to support from them. Digging through [the JSON](https://[registry.terraform.io/v2/providers?filter%5Btier%5D=partner&page%5Bnumber%5D=1&page%5Bsize%5D=100&sort=-featured%2Ctier%2Cname](https://registry.terraform.io/v2/providers?filter%5Btier%5D=partner&page%5Bnumber%5D=1&page%5Bsize%5D=100&sort=-featured%2Ctier%2Cname)) for each page we result in 230 namespaces. That is ~1.3 providers per namespace.

That would be 231 namespaces to support all hashicorp and partner providers. That is 10.59% of all providers. Not weighted in how much they are used by the community.

Now the tricky part of 3227 community providers. Right now i am to lazy to write a script counting all namespaces but lets say this: There is a potentially a lot of keys to manage here. Adapting the reference of 1.3 providers per namespace (might not be representative) that would still be ~2482 keys

Summing it up: We can roughly estimate to require management for 2714 keys at least if OpenTofu wants to support the terraform registry as is.

Next up would be what has higher value: Security or community support? Based on what we have i guess solution 1 (alpha registry) or 3 (conventional repository) seem to value security higher than solution 2 (github). My gut says - which is usually bad - 3 might be a valid compromise if no other solution is found.

**Comment by Hefeweizen** [comment]
@maunzCache Thanks for the attempt at numbers.  "if you can't engineer from numbers, do something that generates numbers."  -- sorry, don't remember where I got that aphorism.

Can you help me count where and how keys are necessary?  I expect there's a long tail here.  People will care about signatures for AWS modules, but for alices-custom-module, and similar specialty modules, users might be fine waving signature validation.  Such a distribution would skew the distribution on keys we have to manage.

But, I"m probably miscounting keys we care about, so to make sure I"m on the same page, please help me with your counts.

**Comment by maunzCache** [comment]
@Hefeweizen A good call. I hope we are talking about what is dealt with at https://developer.hashicorp.com/terraform/cli/plugins/signing the need to sign providers so users can verify what they downloaded.
