### ISSUE TITLE
Code DRY (do not repeat) help text prints

### ISSUE THREAD

**Issue by eranelbaz** [opentofu/opentofu#623]
### OpenTofu Version

```shell
-
```

### Use Cases

Currently, in #622 there is a need to alter the help print in 5 different places
A better way it to refactor the code so we will only need to change that in only one place

### Attempted Solutions

-

### References

#622

**Comment by misha-slyusarev** [comment]
I could work on this one. Shall I wait till this ticket gets the "accepted" label? @eranelbaz
