### ISSUE TITLE
[docs] wrong `terraform -> tofu` swap for some strings in the docs

### ISSUE THREAD

**Issue by serdardalgic** [opentofu/opentofu#630]
### OpenTofu Version

```shell
before alpha
```

### OpenTofu Configuration Files

```hcl
...tofu config...
```

### Debug Output

-

### Expected Behavior

For the places where we are using `terraform` as a code block, we need to double-check that they are not incorrectly swapped to `tofu`. Those are probably the configuration related docs and the examples. 

### Actual Behavior

As a part of #571, `terraform` strings are swapped to `tofu`, but there are some false friends between them that should not have been changed, for example the following documentation:  https://github.com/opentofu/opentofu/blob/ffaec585ef3ab9118fb8e18f37650e2421069492/website/docs/language/settings/index.mdx#L14-L30

The generated documentation is [here](https://opentofu.org/docs/language/settings).

There might be some more in the other configurations and examples. It would be beneficial to check if there are any other occurrences like this in the website directory. 

### Steps to Reproduce

Read the documentation.

**Comment by serdardalgic** [comment]
Oh, btw, if we decide to change the `terraform block` to `tofu block`, please feel free to replace this issue with `Swap terraform->tofu in the configurations` issue as well :) However, for compatibility reasons, I think we should continue using `terraform block`.

**Comment by cube2222** [comment]
🤦‍♂️

Great catch! We're not planning to change the block for now. At some point we can possibly add support for both.
