### ISSUE TITLE
eslint errors in the opentofu/website directory

### ISSUE THREAD

**Issue by serdardalgic** [opentofu/opentofu#639]
### OpenTofu Version

```shell
before alpha
```

### OpenTofu Configuration Files

```hcl
...tofu config...
```

### Debug Output

-

### Expected Behavior

fix the errors and warnings.

### Actual Behavior

See steps to reproduce 

### Steps to Reproduce

1. `cd website/`
2. 
```
npm run lint
```
the output is:
```
> lint
> eslint . --ext mdx


/Users/serdar/Development/OPENTOFU_Project/opentofu/website/docs/cli/install/apt.mdx
  21:39  warning  Link to https://www.placeholderplaceholderplaceholder.com/official-packaging-guide is dead  remark-lint-no-dead-urls

/Users/serdar/Development/OPENTOFU_Project/opentofu/website/docs/cli/plugins/signing.mdx
  9:2  error  Parsing error: Unexpected character `!` (U+0021) before name, expected a character that can start a name, such as a letter, `$`, or `_` (note: to create a comment in MDX, use `{/* text */}`)

/Users/serdar/Development/OPENTOFU_Project/opentofu/website/docs/language/providers/configuration.mdx
  185:2  error  Parsing error: Unexpected character `!` (U+0021) before name, expected a character that can start a name, such as a letter, `$`, or `_` (note: to create a comment in MDX, use `{/* text */}`)

/Users/serdar/Development/OPENTOFU_Project/opentofu/website/docs/language/upgrade-guides/index.mdx
  16:5  warning  Link to https://github.com/opentofu/opentofu/blob/v1.6/CHANGELOG.md is dead  remark-lint-no-dead-urls

✖ 4 problems (2 errors, 2 warnings)
  0 errors and 1 warning potentially fixable with the `--fix` option.
```

### Additional Context

Not a huge issue. For the future, we can provide a more maintainable way to lint the doc changes for the contributors. 

1. a GH Action to check the PRs when there is a change requested for the docs
2. a pre-commit hook to run doc linter in the website directory when there are code changes in this directory. 

### References

It would be helpful to check if there are any relatable issues in the https://github.com/opentofu/opentofu.org/issues repository.

**Comment by jeffallen** [comment]
Also, website/docs/intro/index.mdx has a broken link to /docs/plugin

**Comment by cam72cam** [comment]
Closing as completed by https://github.com/opentofu/opentofu/issues/1563
