### ISSUE TITLE
`tofu sso login`

### ISSUE THREAD

**Issue by mik3h0** [opentofu/opentofu#643]
### OpenTofu Version

```shell
`latest`
```

### Use Cases

As outlined in [this request](https://github.com/opentofu/opentofu/issues/386), `tf` has always stored login credentials in a local file. Hypothetically, this means a compromised laptop could also mean a compromised state. And, long-lived credentials are bad.

### Attempted Solutions

There's not much I can do to attempt to work around this. I did throw a janky credential helper together to pull my creds from 1password via CLI, but it's not really a product-led solution.

### Proposal

Most, if not all of OpenTOFU's sponsors have SSO login support for their platforms. We use Scalr, via Okta.

We do not use any long-lived AWS credentials. Instead we rely on AWS SSO login, which creates an access key, secret key, and session token - all of which get written to `~/.aws/credentials` with a validity period of 4 hours.

I would propose OpenTofu adopt a similar method, with documented standards for TACOS providers to adopt and implement.

**CONCERNS**
There's definitely a concern here about tokens expiring in the middle of a run, or between refresh/plan/apply. Terraform is not fond of interruptions so perhaps something is needed TACOS-side to extend validity in these scenarios?

**Comment by anthonyangel** [comment]
https://developer.1password.com/docs/cli/shell-plugins/terraform/ works well, but is still a 3rd party option and requires the user to use 1password, rather than a tofu-led solution

**Comment by cube2222** [comment]
> I would propose OpenTofu adopt a similar method, with documented standards for TACOS providers to adopt and implement.

`tofu login` I believe can work just as well with a temporary token, no? It depends on the backend implementation.

I only know how the Spacelift implementation works in detail (as I work at Spacelift), but there tofu will get a temporary session token that will expire after 8 hours.
