### ISSUE TITLE
1.6 Changelog implies that previous releases offered experimental `tofu test`

### ISSUE THREAD

**Issue by sftim** [opentofu/opentofu#653]
### OpenTofu Version

```
1.6.0-alpha1
```

### Context

https://github.com/opentofu/opentofu/blob/98bd62453522350e31ee420ff50f76a2977f9647/CHANGELOG.md#160-unreleased says that `tofu test` was previously experimental. Strictly speaking, this isn't true.

**Comment by cube2222** [comment]
Hey, thanks for creating the issue!

Eh, to be honest I assume people will read this as what it is, which is "changed since last MPL version of Terraform".

**Comment by sftim** [comment]
We could add “_The changelog for OpenTofu 1.6 is a comparison against_ Terraform _1.5; OpenTofu started as a fork of Terraform. Terraform is a trademark of HashiCorp, Inc._”
