### ISSUE TITLE
Install guide in readme.md

### ISSUE THREAD

**Issue by kmgrime** [opentofu/opentofu#654]
### OpenTofu Version

```shell
v1.6.0-alpha1 and onwards
```

### Use Cases

# Install
When wanting to install openTofu on your client you can easily have a look at the readme.md to install the binary.

### Attempted Solutions

One solution right now is to install from a git clone with the earlier description where you install Go and it's dependencies. For a newcomer there may me easier to have a command to input in the command-line to install the binary.

### Proposal

# Install guide
Short description on how to install the binary for the different OS's.

**Comment by kmgrime** [comment]
> Would something as short as `use the package manager of your OS` with some examples or community projects like `tfenv` satisfy this request @kmgrime ?

I think that either a install guide on how to build the code from source on mac/linux helps alot, or as you said, when we build the binaries into package manager format it is very sufficient @davidjeddy. 

e.g. `sudo apt install tofu.deb` `brew install tofu`

**Comment by eranelbaz** [comment]
I guess this one is relevant after we https://github.com/opentofu/opentofu/issues/14 and [ choco and more](https://github.com/opentofu/opentofu/issues/430)

**Comment by DavidGamba** [comment]
There is also an asdf plugin: https://github.com/virtualroot/asdf-opentofu which might be officially listed by asdf if this is merged: https://github.com/asdf-vm/asdf-plugins/pull/893

**Comment by kislerdm** [comment]
@kmgrime Hey! WDYT about the installation instructions [page](https://opentofu.org/docs/intro/install/) on the opentofu.org website - does it resolve the issue? Thanks!

**Comment by kmgrime** [comment]
@kislerdm Hi, defently - a good simple description there! I also think it needs a link in the main readme.md for those coming from the Github side :+1:

**Comment by kislerdm** [comment]
@kmgrime Hey Kjell-Magnus!

Thanks for your feedback. Would you be open to proposing a change? Feel free to open PR with an additional to readme.

**Comment by kmgrime** [comment]
@kislerdm I will do that 😊👍

**Comment by kislerdm** [comment]
Thank you @kmgrime 🙏

**Comment by kmgrime** [comment]
@kislerdm Pull request up, hope I can contribute more 👍
