### ISSUE TITLE
Authentication signature from unknown issuer

### ISSUE THREAD

**Issue by denis256** [opentofu/opentofu#656]
### OpenTofu Version

```shell
OpenTofu v1.6.0-alpha1
on linux_amd64
```

### OpenTofu Configuration Files

```hcl
terraform {
  required_version = ">= 1.0.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "< 4.0"
    }
  }
}


```

### Debug Output

https://gist.github.com/denis256/ed9fb97a77279d1973f065df029a52e4

### Expected Behavior

tofu init to pass without errors

### Actual Behavior

tofu fails with error:
```
╷
│ Error: Failed to install provider
│ 
│ Error while installing hashicorp/aws v3.76.1: authentication signature from unknown issuer
╵
```

terraform finish execution without errors

### Steps to Reproduce

create `main.tf` with content

```
terraform {
  required_version = ">= 1.0.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "< 4.0"
    }
  }
}


```

run `tofu init`

### Additional Context

No errors in tofu when I set:
```
    aws = {
      source  = "hashicorp/aws"
      version = "= 5.0"
    }
```

### References

Simplified example: https://github.com/denis256/terragrunt-tests/tree/master/tofu-signature

**Comment by pdecat** [comment]
Also happens with old versions of the vault provider: https://opentofucommunity.slack.com/archives/C05R0FD0VRU/p1696461821153299?thread_ts=1696461821.153299&cid=C05R0FD0VRU

**Comment by Yantrio** [comment]
We've identified a cause and are working on a fix now.

**Comment by pdecat** [comment]
Fix confirmed :rocket:
