### ISSUE TITLE
Block release if `version/VERSION` content isn't the same / bumped since last release

### ISSUE THREAD

**Issue by eranelbaz** [opentofu/opentofu#663]
When we release a new version of OpenTofu, we should also bump the content of `version/VERSION` to contain the correct version.
The correct version is based on the tag name without the `v`
for example 

|  tag name | file content  | 
|---|---|
| v1.6.0-alpha1  | 1.6.0-alpha1  |  
| v1.6.0-alpha2  | 1.6.0-alpha2  |  

Add a check to our release process to make sure we indeed bumped the file content.

Note that this check shouldn't run if the branch name doesn't start with `v` if we would like to check the release process (also might be the same rule as the [go release snapshot rule](https://github.com/opentofu/opentofu/blob/86866bff0c7f2b8997fb95a23e3b4827219efc10/.github/workflows/release.yml#L67))

**Comment by Jake-Mok-Nelson** [comment]
I'd like to work on this issue. Could it be assigned to me please?

It could go under the checks workflow with some slightly complex github magic but under release.yml as a breaking step might make more sense?

**Comment by Yantrio** [comment]
Sure, I'll assign you.

**Comment by Yantrio** [comment]
Sure, I'll assign you. @Jake-Mok-Nelson

**Comment by Jake-Mok-Nelson** [comment]
Did you mean to self-assign also @Yantrio ? Thanks for assigning, I will work on this soon!

**Comment by Jake-Mok-Nelson** [comment]
PR raised @Yantrio . I'm not able to assign it.

**Comment by Yantrio** [comment]
Hey @Jake-Mok-Nelson ! thanks for this, I've just reviewed it and it looks great.

As for the self-assignment, It was mainly so I can keep an eye on the issue, not that I was working on it. Should've made that clearer, sorry!
