### ISSUE TITLE
The s3 backend does not respect the NO_PROXY variable

### ISSUE THREAD

**Issue by Yantrio** [opentofu/opentofu#675]
### OpenTofu Version

```
1.6.0
```

### OpenTofu Configuration Files

```hcl
terraform {
  backend "s3" {
    bucket="tf-state-test"
    region="eu-central-1"
    key="test/test.tfstate"
  }
}
```

### Debug Output

External gist link: [Debug Output](https://gist.github.com/mnival/cb0857de9b72e2020bdc46b3ae00fbba)

### Expected Behavior

OpenTofu should respect the `NO_PROXY` environment variable, specifically for requests to `http://169.254.169.254`. The `NO_PROXY` variable is set as follows:

```bash
export NO_PROXY="169.254.169.254"
```

### Actual Behavior

OpenTofu only honors `HTTP_PROXY` and `HTTPS_PROXY` variables, ignoring the `NO_PROXY` setting. As a result, certain local requests use a proxy when they shouldn't.

### Steps to Reproduce

1. Run `terraform init`

### Additional Context

```bash
export HTTP_PROXY="http://proxy:3128"
export HTTPS_PROXY="http://proxy:3128"
export NO_PROXY="169.254.169.254"
```

### References

- Original report: [hashicorp/terraform#33987](https://github.com/hashicorp/terraform/issues/33987)
- Original functionality was added: [backend/s3: add http_proxy and related arguments #33748](https://github.com/hashicorp/terraform/issues/33748)
- Looks like this is an issue in [aws-sdk-go-base](https://github.com/hashicorp/aws-sdk-go-base) as mentioned in [this comment](https://github.com/hashicorp/terraform/issues/33987#issuecomment-1750317951)

**Comment by tarruda** [comment]
Even though the issue appears to be in aws-sdk-go-base, we can probably fix this locally by resetting the `HTTP_PROXY` /`HTTPS_PROXY` env vars if `NO_PROXY` is set. I can investigate/tackle this one @cube2222
