### ISSUE TITLE
GIT_SSH_COMMAND env var ignored when downloading modules

### ISSUE THREAD

**Issue by Yantrio** [opentofu/opentofu#676]
### OpenTofu Version

```
1.6.0
```

### OpenTofu Configuration Files

```hcl
module "this" {
  source = "git@github.com:org/tf-module?ref=1.0.1"
}
```

### Debug Output

N/A

### Expected Behavior

OpenTofu should correctly download modules when using the following git configuration and SSH settings:

```bash
git config --global url.ssh://git@github.com/.insteadOf https://github.com/
export GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no"
```

### Actual Behavior

tofu fails to download modules, throwing the following error:

```
 ╷
 │ Error: Failed to download module
 │ 
 │   on file.tf line 11:
 │   11: module "this" {
 │ 
 │ Could not download module "this" (file.tf:11)
 │ source code from
 │ "git::ssh://git@github.com/org/tf-module.git?ref=1.0.1":
 │ error downloading
 │ 'ssh://git@github.com/org/tf-module.git?ref=1.0.1':
 │ /usr/bin/git exited with 128: Cloning into
 │ '.terraform/modules/this'...
 │ Host key verification failed.
 │ fatal: Could not read from remote repository.
 │ 
 │ Please make sure you have the correct access rights
 │ and the repository exists.
 
```

### Steps to Reproduce

1. Configure git and SSH as follows:

```bash
git config --global url.ssh://git@github.com/.insteadOf https://github.com/
export GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no"
```

2. Run `tofu init`

### References

- Possibly caused by PR: [go-getter#300](https://github.com/hashicorp/go-getter/pull/300)
- Related issues in original Terraform repository: 
  - [GIT_SSH_COMMAND env var ignored when downloading modules #33985](https://github.com/hashicorp/terraform/issues/33985)
  - [Version 1.6.0 - Host Key Verification Failed when using git ssh #33986](https://github.com/hashicorp/terraform/issues/33986)

**Comment by cube2222** [comment]
Fixed by https://github.com/opentofu/opentofu/pull/717
