### ISSUE TITLE
Instructions reference non-existant placeholder domains

### ISSUE THREAD

**Issue by markenzie** [opentofu/opentofu#678]
On the following lines placeholderplaceholderplaceholder.com is used

The domain is not registered and in yum.mdx it is being used as an argument for --add-repo which then influences the following yum install command. If someone were to register this domain, they could set up a malicious repositiory and cause users into installing a malicious program.  Problematic content could also be placed on that domain which then OpenTofu would be seen linking to.

https://github.com/opentofu/opentofu/blob/570ee9efdbd456d8e1bf030fbadb5550b6b71f3b/website/docs/cli/install/apt.mdx#L21
https://github.com/opentofu/opentofu/blob/570ee9efdbd456d8e1bf030fbadb5550b6b71f3b/website/docs/cli/install/yum.mdx#L35
https://github.com/opentofu/opentofu/blob/570ee9efdbd456d8e1bf030fbadb5550b6b71f3b/website/docs/cli/install/yum.mdx#L35

**Comment by Hefeweizen** [comment]
Would it be sufficient to replace them with example.com?  (or example.net, or example.org)

These are reserved in rfc 2606, so they shouldn't be found on the open internet.  However, this may not be true for local or corporate networks.  Though at that point, it feels like we're talking about susceptibility to DNS poisoning attacks; we can't do anything for the end-user in that regard.

**Comment by markenzie** [comment]
I agree example.com would be better to use as a placeholder...

But aren't these meant to be real working links? These are directions on the install page that is being linked from the homepage. 

I agree a placeholder was needed immediately after the fork to avoid linking or mentioning the original project, but shouldn't these install directions actually work?

**Comment by benmoss** [comment]
There is a warning at the top of both of these pages:
<img width="734" alt="Screenshot 2023-10-22 at 1 42 09 PM" src="https://github.com/opentofu/opentofu/assets/239754/92ccaba2-6f12-4f3b-ae06-d23184b1e980">

So yes there is a plan to have apt and yum repositories, but for now we don't have them setup.

**Comment by markenzie** [comment]
That was added after I opened this issue and the offending sections have been removed - this can be closed.
