### ISSUE TITLE
Error trying to load custom provider in file system

### ISSUE THREAD

**Issue by FulecoRafa** [opentofu/opentofu#679]
### OpenTofu Version

```shell
OpenTofu v1.6.0-alpha2
on linux_amd64
```

### OpenTofu Configuration Files

```hcl
provider_installation {
  dev_overrides {
    "registry.terraform.io/<organization>/<project>" = "/path/to/provider/folder"
    "registry.opentofu.io/<organization>/<project>" = "/path/to/provider/folder"
  }
  direct {
    exclude = ["registry.opentofu.io/<organization>/<project>" ]
  }
}
```

### Debug Output

[gist](https://gist.github.com/FulecoRafa/bea043dac064418d43581a6776ad2aca)

### Expected Behavior

Should plan actions to take using local custom provider

### Actual Behavior

Fails to find custom provider and errors out

### Steps to Reproduce

1. Generate a custom provider in local file system
2. Add dev override to .tofurc
3. Run either `tofu init` or `tofu plan`

### Additional Context

I'm trying to test if my provider is working. I have the provider compiled in my local machine and using dev overrides I can add the provider to Terraform. However, doing the same thing using OpenTF does not work.

**Comment by Yantrio** [comment]
I think this is due to using the wrong url. The registry url is `registry.opentofu.org` not `.io`

**Comment by FulecoRafa** [comment]
Thanks, tested it with this change and it worked
