### ISSUE TITLE
Support for UUIDv7 (adding function uuidv7)

### ISSUE THREAD

**Issue by joaocc** [opentofu/opentofu#682]
### OpenTofu Version

```shell
1.6.x
```

### Use Cases

As 1.6.x, UUID formats v4 and v5 are supported. 
https://developer.hashicorp.com/terraform/language/functions/uuid
https://developer.hashicorp.com/terraform/language/functions/uuidv5

Some time ago, new UUID formats were launched by IETF and, one of them (UUID v7) has some very interesting properties that make it a need in many scenarios where distributed generation of quasi-sequential numbers is desired (up to 50ns resolution + 48 random bits)
Currently generating them requires launching external commands.
This request is to add support for UUID v7.

### Attempted Solutions

Launching external commands

### Proposal

Add uuidv7 function.

### References

Some supporting material:
* https://datatracker.ietf.org/doc/html/draft-peabody-dispatch-new-uuid-format#name-uuid-version-7
* https://buildkite.com/blog/goodbye-integers-hello-uuids

**Comment by alrs** [comment]
I've looked at replacing the Hashicorp UUID library used in Opentofu outright. Because Hashi's UUID library is being used for encryption purposes as well as generating UUIDs some care should be taken to make sure that encryption primitives don't get nerfed.

**Comment by maunzCache** [comment]
Please consider that this format specification is still in draft mode - which has expired by the way - and has not been accepted yet.

Refer to the newest draft for further discussion here: https://datatracker.ietf.org/doc/draft-ietf-uuidrev-rfc4122bis/12/
