### ISSUE TITLE
Configure aws provider settings fully via env variables

### ISSUE THREAD

**Issue by hans-d** [opentofu/opentofu#683]
### OpenTofu Version

```shell
N/a
```

### Use Cases

Deploying complex projects to localstack.
eg including various nested (multilevel) modules

### Attempted Solutions

Currently endpoints need to be configured per aws provider. Tflocal (by localstack) does provide some help with that, but it does not cover the aws providers from imported modules

### Proposal

If this could be provided with env variables, just like the api credentials, this could be picked up by all modules referencing the provider.

**Comment by eranelbaz** [comment]
Hey @hans-d 
When configuring AWS credentials through environment variables, aws provider picks them up, for example
```
export AWS_ACCESS_KEY_ID="2HJI"
export AWS_SECRET_ACCESS_KEY="Qarm"
export AWS_SESSION_TOKEN="IQoJb3JpZ2luX"
```
Is there any other issue?

**Comment by hans-d** [comment]
Yes, the endpoint configuration should also be able to pickup config from
an env

Op zo 8 okt. 2023 om 10:44 schreef Elbaz ***@***.***>

**Comment by eranelbaz** [comment]
What is the endpoint configuration?
I'm trying to understand what's currently missing

**Comment by hans-d** [comment]
See
https://docs.localstack.cloud/user-guide/integrations/terraform/#endpoint-configuration


Op zo 8 okt. 2023 om 10:54 schreef Elbaz ***@***.***>

**Comment by eranelbaz** [comment]
WDYT about adding variable blocks and defining their values using environment variable?
```
TF_VAR_UN=foo TF_VAR_PW=bar tofu apply
```
Then you can use `var.un` in the provider block

**Comment by kislerdm** [comment]
@hans-d hey Hans! IMO this issue shall be resolved on the provider's side. 

Also, to make sure I understood you right, the issue does not concern [backend](https://opentofu.org/docs/language/settings/backends/s3)'s endpoint configuration, does it? Thanks!

**Comment by janosdebugs** [comment]
Hey folks, thank you for your input. We have discussed this issue in the core team. This is an issue with the AWS provider which is maintained by Hashicorp and we are only mirroring. Currently, we do not have any infrastructure set up to accept contributions to the AWS provider and we also do not want to add changes that could threaten the feature parity between our downstream version and the upstream. As we have no way to actually implement this, we are closing this issue.
