### ISSUE TITLE
Backend/s3: Add support `assume_role_with_web_identity`

### ISSUE THREAD

**Issue by RLRabinowitz** [opentofu/opentofu#689]
## Summary

AWS provider [supports assuming a role with web identity](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#assume_role_with_web_identity-configuration-block), but the S3 backend does not

It would be good to have this option for the S3 backend as well, for feature parity

## References

- AWS provider code for reference - https://github.com/hashicorp/terraform-provider-aws/blob/3a33e810b7999e0f891c17940125831cf0ef49c2/internal/provider/provider.go#L229
- Related issue in Terraform Repository: https://github.com/hashicorp/terraform/issues/31244

**Comment by hajdukda** [comment]
Would be super useful to be able to also run terraform locally to troubleshoot.
