### ISSUE TITLE
Backend/S3: Support multiple config and credential files

### ISSUE THREAD

**Issue by RLRabinowitz** [opentofu/opentofu#690]
## Summary

The AWS SDK for Go v2 allows passing multiple shared credentials and shared config files. The S3 Backend should support that as wellNote that the corresponding environment variables, `AWS_SHARED_CREDENTIALS_FILE` and `AWS_CONFIG_FILE` accept single files only.

- Support `AWS_SHARED_CREDENTIALS_FILE` and `AWS_CONFIG_FILE` environment variables. Document support for them
- Add parameters to the S3 backend to allow to provide multiple shared credential files and multiple config files
- Deprecate shared_credentials_file
- Add documentation

## References:

- AWS provider code for reference - https://github.com/hashicorp/terraform-provider-aws/blob/3a33e810b7999e0f891c17940125831cf0ef49c2/internal/provider/provider.go#L229
- Related issue in Terraform Repository: https://github.com/hashicorp/terraform/issues/30493

**Comment by tomasmik** [comment]
Addressed in #701
