### ISSUE TITLE
Backend/S3: Upgrade to `aws-sdk-go-base/v2`

### ISSUE THREAD

**Issue by RLRabinowitz** [opentofu/opentofu#691]
## Summary

The AWS provider has upgraded the authentication to `aws-sdk-go-base/v2` [on 4.0](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v4.0.0). The authentication process of the S3 backend and the AWS provider should be aligned for configuration simplicity

## References

- Related issue in Terraform Repository: https://github.com/hashicorp/terraform/issues/30443
- Is a prerequisite to the following issues: https://github.com/opentofu/opentofu/issues/689 and https://github.com/opentofu/opentofu/issues/690

**Comment by eranelbaz** [comment]
7daf54e7(rollback attributes)
We need to introduce those new attributes, currently waiting for #701 and I'll introduce them again after
