### ISSUE TITLE
Backend/S3: Better parity with AWS provider

### ISSUE THREAD

**Issue by RLRabinowitz** [opentofu/opentofu#700]
## Summary

Currently there are some mismatches between the AWS provider, and the S3 backend. Mismatch in authentication process and configuration, mismatch in capabilities, etc.
The AWS provider had mad a lot of improvements, but they were not reflected in the S3 backend. We should make improvements to the S3 backend, and introduce better parity by better aligning the S3 backend with the AWS provider:

- [x] #689 
- [x] #747
- [x] #690 
- [x] #691 
- [x] #692 
- [x] #693 
- [x] #694 
- [x] #695 
- [x] #698 
- [x] #699 
- [x] #774 
- [x] #775
- [x] #783
- [x] #778

Not required for parity:
- [x] https://github.com/opentofu/opentofu/issues/753

**Comment by XP2600-hub** [comment]
Off topic: for a tool used with several cloud vendors, should not it support different types of backends as well ? something like Azure blob storage for instance.

**Comment by alexandrospanayi** [comment]
@XP2600-hub azure is already supported: https://github.com/opentofu/opentofu/blob/main/internal/backend/remote-state/azure/backend.go

**Comment by alex067** [comment]
@XP2600-hub azure blob storage is already a supported backend https://github.com/opentofu/opentofu/blob/main/internal/backend/remote-state/azure/backend.go
