### ISSUE TITLE
Remove leftover mentions of Terraform in user-facing occurrences of the codebase

### ISSUE THREAD

**Issue by RLRabinowitz** [opentofu/opentofu#702]
There are still some mentions of terraform in the codebase that are user-facing, like possible stdouts from the OpenTofu CLI, and `.md` files
Those should be altered

Mentions of Terraform Cloud - Those should be changed to a generic `cloud`, or TACOS:
- [x] `configs/module.go`
- [x] `cloud/backend.go`
- [x] `cloud/backend_apply.go`
- [x] `cloud/backend_plan.go`
- [x] `command/cloud.go`
- [x] `command/helper.go`
- [x] `command/init.go`
- [x] `command/jsonformat/README.md`
- [x] `login.go`
- [x] `meta_backend.go`
- [x] `meta_backend_migrate.go`
- [x] `command/show.go`

Mentions of Terraform in stdout of the CLI:
- [x] `remote/backend_context.go` - in DEBUG log
- [x] `data_source_state.go` - In the description of the `workspace` field
- [x] `configs/module.go` - In error when using prerelease verisons
- [x] `configs/provider.go` - `Visit https://learn.hashicorp.com/collections/terraform/provision`
- [x] `descriptions.go` - In description of the `sensitive` function
- [x] `state.go` - In the error displayed in case of multiple modules with same path
- [x] `panic.go` - In case of a crash
- [x] `session.go` - In the help message of the `tofu console`

Mentions of Terraform in documentation;
- [x] Some wrongful mentions of Terraform in the `CHANGELOG.md`
- [x] In the main `README.md`, mentions the `Terraform Registry ToS` - The warning there is no longer correct, as `OpenTofu` uses `registry.opentofu.org` by default
- [x] `architecture.md` mentions `terraform` as package name
- [x] `internal/ipaddr/README.md` - Mentions Terraform 1.0
- [x] Mentions of the Terraform Registry or Terraform Providers in `.mdx` files. Also we have links to the `registry.terraform.io`, for usage examples and also for documentation. **Edit: Mostly done, the Registry Documentation references were not yet changed, as the OpenTofu Registry does not currently have documentation**
- [x] `provider-registry-protocol.mdx` - Mentions Terraform CLI
- [x] `local.mdx` - Many mentions of Terraform

**Comment by kdpuvvadi** [comment]
What about the main block

```hcl
terraform {
  required_version = ""
  required_providers {
    aws = {
     .......
    }
  }
}
```
shouldn't we change it to `tofu {}` and support `terraform {}` for existing infra till they migrate?

**Comment by serdardalgic** [comment]
I'd suggest tackling the `terraform` block in a separate ticket, as it is more than just removing the hashicorp/terraform mentions, but changing the configuration block itself. 

I think creating an RFC-like proposal for the terraform->tofu configuration block change makes sense, a proposal similar to the OPENTOFU_ env vars in #641. 

It was previously swapped to tofu and switched back to terraform within #630 and in #633 I've added the following note to [the docs](https://opentofu.org/docs/language/settings/) about this configuration block:
> Note
> As a part of [OpenTofu v1.x Compatibility Promises](https://opentofu.org/docs/language/v1-compatibility-promises), the terraform block stays as-is. A tofu block may be introduced in the future, but it doesn't exist yet.

**Comment by RLRabinowitz** [comment]
> I'd suggest tackling the terraform block in a separate ticket, as it is more than just removing the hashicorp/terraform mentions, but changing the configuration block itself.

Yes, I agree there. Any such change that affects the functionality of OpenTofu (especially when it introduces backwards compatibility concerns), should be part of a seperate issue

**Comment by RLRabinowitz** [comment]
Everything mentioned in the issue has been removed as part of https://github.com/opentofu/opentofu/pull/703, https://github.com/opentofu/opentofu/pull/704 and https://github.com/opentofu/opentofu/pull/713

For other changes that affect OpenTofu's function (like changing the `terraform` block to `tofu` block), we'd need a separate issue with a detailed proposal
