### ISSUE TITLE
Plan detail for a resource's TypeSet block is hidden due to sensitive values

### ISSUE THREAD

**Issue by Integralist** [opentofu/opentofu#708]
### OpenTofu Version

```shell
OpenTofu v1.6.0-alpha2
on darwin_arm64
```

### OpenTofu Configuration Files

```hcl
terraform {
  required_providers {
    fastly = {
      source = "fastly/fastly"
      version = "5.5.0"
    }
  }
}

resource "fastly_service_vcl" "example" {
  name = "opentofu_example_block_sensitive"

  domain {
    name    = "opentofu_example_block_sensitive.integralist.co.uk"
  }

  backend {
    address = "127.0.0.1"
    name    = "localhost"
    port    = 80
  }

  force_destroy = true
}
```

### Debug Output

https://gist.github.com/Integralist/2820e49513ef22f0fd083c5ef316b742

### Expected Behavior

We should see a complete diff for the `backend` block, something like...

```
+ backend {
  + address               = "127.0.0.1"
  + auto_loadbalance      = false
  + between_bytes_timeout = 10000
  + connect_timeout       = 1000
  + error_threshold       = 0
  + first_byte_timeout    = 15000
  + healthcheck           = ""
  + max_conn              = 200
  + name                  = "localhost"
  + override_host         = ""
  + port                  = 80
  + request_condition     = ""
  + ssl_cert_hostname     = ""
  + ssl_check_cert        = true
  + ssl_sni_hostname      = ""
  + use_ssl               = false
  + weight                = 100
}
```

### Actual Behavior

Instead, we see the following...

```
+ backend {
  # At least one attribute in this block is (or was) sensitive,
  # so its contents will not be displayed.
}
```

### Steps to Reproduce

1. `tofu init`
2. `tofu plan`

### Additional Context

This was [originally reported](https://github.com/hashicorp/terraform/issues/33112) in the Terraform repository and is currently still open (the change in behaviour was introduced in the `terraform` CLI version 1.4.0, and OpenTofu forked from 1.5.0).

Now, although I appreciate the rationale of hiding sensitive data from the plan, there are two problems here...

1. We're hiding the _entire_ `backend` block's plan, and this makes it very dangerous for anyone to apply this configuration change (as we can't see what's changing). Yes, it's likely the author of the change is the one running the `tofu plan` but that's not always the case, and even still mistakes happen and it's important to be able to verify what is about to change in your infrastructure. It would be nice if just the _values_ for each sensitive attribute was hidden rather than hiding everything.
2. In this particular case, I'm not actually setting any of the 'sensitive' attributes defined in the `backend` block. So I shouldn't really have the block's entire plan hidden from me as there actually is no sensitive value being set.

### References

- https://github.com/hashicorp/terraform/issues/33112

**Comment by kdpuvvadi** [comment]
#716 might be related to this

**Comment by janosdebugs** [comment]
Hey folks, thank you very much for the input. We have discussed this in the core team and would be happy for a PR for this. If you would like to work on this issue, please comment on this issue so we can assign it to you.

**Comment by namgyalangmo** [comment]
I would like to resolve this.

**Comment by janosdebugs** [comment]
Hi @namgyalangmo thank you for volunteering, I've assigned you. I don't have any specific input apart from what is discussed in this issue, unfortunately.

**Comment by namgyalangmo** [comment]
I tried recreating the issue but on running tofu plan, instead of seeing 
```
+ backend {
  # At least one attribute in this block is (or was) sensitive,
  # so its contents will not be displayed.
}
```
I am encountering this error, 
```
% tofu plan
Planning failed. OpenTofu encountered an error while generating this plan.
Error: Invalid provider configuration
 
Provider "registry.opentofu.org/fastly/fastly" requires explicit configuration. Add a provider block to the root module and configure the provider's required arguments as described in the provider
documentation.
 


 Error: no API key for Fastly
 
   with provider["registry.opentofu.org/fastly/fastly"],
   on <empty> line 0:
   (source code not available)
```
Even if I proceed and add a provider block, what do I do about the API key?

**Comment by kdpuvvadi** [comment]
Apart from provider block `api_key`, you can add env varible `FASTLY_API_KEY`. 

More's here: https://github.com/fastly/terraform-provider-fastly/blob/main/docs/index.md#static-api-key

**Comment by Integralist** [comment]
This issue will exist for any provider that uses a TypeSet with a field marked sensitive. So might be best to implement a failing test around that behaviour (I've no idea how OpenTofu is implemented so maybe there are no "mock provider" tests)

**Comment by chenzejun** [comment]
Hi @cam72cam @janosdebugs, I'd like to share some investigation on this issue:
1. Opentofu use MarkWithPaths(in package go-cty) to render the after sensitive of the plan:
https://github.com/opentofu/opentofu/blob/5125db58410c9a67bab0bd53ccd3f063b9743b1e/internal/command/jsonplan/plan.go#L467
2.  If some sub-fileds of an object in a set with a sensitive mark,  go-cty will strip off it and move to the set value. So the whole set will be marked as sensitive, in case in this issue, the whole backend was marked sensitive
https://github.com/zclconf/go-cty/blob/50ce6d3544a103fe4b8eea922f3ab5780b4a285b/cty/walk.go#L177 
https://github.com/zclconf/go-cty/blob/50ce6d3544a103fe4b8eea922f3ab5780b4a285b/cty/value_init.go#L273
3. This is a designed behavoir of go-cty，See this pr: https://github.com/zclconf/go-cty/commit/17a9781286193db5009410ac25b50b021ef8c50a

If we want to fix it in opentofu, we may need some tricky. Do you have any idea of an acceptable approch?
I am interested to fix it if @namgyalangmo hasn't started to work on it yet.

**Comment by namgyalangmo** [comment]
Hey @chenzejun , I have been investigating this issue, I agree with your observations, and came to the same conclusion. I could tell that the solution would be tricky,  if you have a approach in mind feel free to go for it.

**Comment by chenzejun** [comment]
Hi @janosdebugs, I have an idea to fix it with a custom cty transformer, can you also add me to the assignees and I can submit an initial draft PR to discuss if it is a doable way.

**Comment by janosdebugs** [comment]
Hey @chenzejun I've added you as an additional assignee, thank you very much, I'm curious about your solution.

**Comment by chenzejun** [comment]
Hi @janosdebugs @namgyalangmo,  PTAL on my PR https://github.com/opentofu/opentofu/pull/1313
I think we may need more discuss on the solution so I turn it into draft. If this approch is ok for every one, I will add some tests for the patch and ask for your review.

**Comment by cam72cam** [comment]
I was re-reading some of the comments on one of the linked issues and attempting to reproduce some of the behavior.

```hcl
resource "tfcoremock_complex_resource" "example" {
  id = "my-complex-resource"

  list_block {
    string = "list_block.one"
  }

  list_block {
    string = "list_block.two"
  }

  list_block {
    string = "list_block.three"
    number = sensitive(42)
  }

  set_block {
    string = "set_block.one"
  }

  set_block {
    string = "set_block.two"
    number = sensitive(54)
  }
}
```

Produces the expected result for list, but set is still hidden.

**Comment by cam72cam** [comment]
Ok, I've run the real fastly code in the example and it works as expected.

I see now that if any of the provided fields are sensitive it correctly hides the whole block.  If the schema contains sensitive keys, with no value specified it is not hidden as expected.

Outputs are still handled correctly as well.  I misunderstood the issue coming back to it months later.

**Comment by cam72cam** [comment]
This produces the expected full output
```
resource "fastly_service_vcl" "example" {
  name = "opentofu_example_block_sensitive"

  domain {
    name    = "opentofu_example_block_sensitive.integralist.co.uk"
  }

  backend {
    address = "127.0.0.1"
    name    = "localhost"
    port    = 80
  }

  force_destroy = true
}
```

This only hides the sensitive ssl_client_key
```
resource "fastly_service_vcl" "example" {
  name = "opentofu_example_block_sensitive"

  domain {
    name    = "opentofu_example_block_sensitive.integralist.co.uk"
  }

  backend {
    address = "127.0.0.1"
    name    = "localhost"
    port    = 80
    ssl_client_key = "foo"
  }

  force_destroy = true
}
```

This hides the whole block:
```
resource "fastly_service_vcl" "example" {
  name = "opentofu_example_block_sensitive"

  domain {
    name    = "opentofu_example_block_sensitive.integralist.co.uk"
  }

  backend {
    address = "127.0.0.1"
    name    = "localhost"
    port    = sensitive(80)
  }

  force_destroy = true
}
```

**Comment by cam72cam** [comment]
It does get a bit trickier when you have more than one backend block:

Shows a single backend block with all values hidden:
```hcl
resource "fastly_service_vcl" "example" {
  name = "opentofu_example_block_sensitive"

  domain {
    name    = "opentofu_example_block_sensitive.integralist.co.uk"
  }

  backend {
    address = "127.0.0.1"
    name    = "localhost"
    port    = 80
  }

  backend {
    address = "127.0.0.1"
    name    = "localhost"
    port    = sensitive(80)
  }

  force_destroy = true
}

Shows two backend blocks with all values hidden
```hcl
resource "fastly_service_vcl" "example" {
  name = "opentofu_example_block_sensitive"

  domain {
    name    = "opentofu_example_block_sensitive.integralist.co.uk"
  }

  backend {
    address = "127.0.0.1"
    name    = "localhost"
    port    = 80
  }

  backend {
    address = "127.0.0.1"
    name    = "localhost"
    port    = sensitive(81)
  }

  force_destroy = true
}
```

Only hides the ssl_client_key field
```
resource "fastly_service_vcl" "example" {
  name = "opentofu_example_block_sensitive"

  domain {
    name    = "opentofu_example_block_sensitive.integralist.co.uk"
  }

  backend {
    address = "127.0.0.1"
    name    = "localhost"
    port    = 80
  }

  backend {
    address = "127.0.0.1"
    name    = "localhost"
    port    = 80
    ssl_client_key = "foo"
  }

  force_destroy = true
}
```

**Comment by cam72cam** [comment]
So the only potential sensitive leak here is if you have two *identical* blocks in a set, one of which has a non-sensitive field with a sensitive value.  They will be condensed into a single entry, implying that they are the same.  It however behaves identically to how tofu operates today, which should be fine.

There is not a scenario I could find in which we fully hide one of the sensitive blocks, but leave the other visible.
