### ISSUE TITLE
Readme disclaimer is not up to date

### ISSUE THREAD

**Issue by kislerdm** [opentofu/opentofu#715]
### OpenTofu Version

```shell
NA
```

### OpenTofu Configuration Files

NA

### Debug Output

NA

### Expected Behavior

The readme contains the disclaimer mentioning the first alpha release:

> Important Note: This repository is currently a work in progress while we're preparing it for the first alpha release and fine-tuning the community contribution process.

### Actual Behavior

WDYT about: 

> Important Note: This repository is currently a work in progress while we're preparing it for the first stable release and fine-tuning the community contribution process.

### Steps to Reproduce

NA

**Comment by Yantrio** [comment]
I think this has been stealthily done as part of https://github.com/opentofu/opentofu/pull/713/files
