### ISSUE TITLE
META: issue label for functions

### ISSUE THREAD

**Issue by Hefeweizen** [opentofu/opentofu#728]
### OpenTofu Version

```shell
n/a
```

### Use Cases

This is a project request; not associated with the codebase.

We've seen a handful of tickets requesting new language functions:
https://github.com/opentofu/opentofu/issues/681
https://github.com/opentofu/opentofu/issues/680
https://github.com/opentofu/opentofu/issues/334

For searching and referencing, it would be helpful if they were specifically labeled.

### Attempted Solutions

n/a

### Proposal

Add 'f-function' for features related to functions.

**Comment by kislerdm** [comment]
Hey @Hefeweizen! Thanks for your proposal: it makes absolute sense to me given that such kind of requests is quite popular. I created the label.
