### ISSUE TITLE
Add installation instructions.

### ISSUE THREAD

**Issue by cube2222** [opentofu/opentofu#729]
Create a file named `install.mdx` in the [`website/docs` directory](https://github.com/opentofu/opentofu/tree/main/website/docs) that we can render on the website.

**Comment by Yantrio** [comment]
Should we also deprecate/move the docs already here? https://github.com/opentofu/opentofu/tree/f661d47a29c1e8d80f479d0dfd60debed1302f89/website/docs/cli/install

(Or link to them?
