### ISSUE TITLE
Compare Terraform to OpenTofu in docs

### ISSUE THREAD

**Issue by sftim** [opentofu/opentofu#736]
### OpenTofu Version

```shell
n/a
```

### Use Cases

n/a

### Attempted Solutions

Go direct to https://opentofu.org/faq/#opentofu-terraform-differences

### Proposal

Update https://opentofu.org/docs/intro/vs/ to help readers compare OpenTofu to Terraform. Hyperlink to https://opentofu.org/faq/#opentofu-terraform-differences

**Comment by serdardalgic** [comment]
I like the idea of comparing OpenTofu and Terraform, when we have actual differences between them. That's why, my 2 cents go to keeping this GH Issue but instead of linking to`actually, there is no difference` part of the FAQ, we explain the differences when there are some.

**Comment by cube2222** [comment]
Agreed. This makes sense to add once there actually are some notable differences.
