### ISSUE TITLE
Backend/S3: Properly propagate the context in backend and client interfaces

### ISSUE THREAD

**Issue by tomasmik** [opentofu/opentofu#753]
## Summary

After upgrading the S3 backend in https://github.com/opentofu/opentofu/pull/701 most calls to S3 now require a context to be passed. The pull request used context.TODO() as that was the easiest option not requiring any changes to interface of the backend or the client used.

Alter the `backend.Backend` and `remote.Client` interfaces to accept contexts and properly propagate it through out the codebase dropping the `context.TODO()`

**Comment by marcinwyszynski** [comment]
This is quite a bit of work so in order to keep the review manageable I will go over the interface methods one by one.
