### ISSUE TITLE
Extra newline in validate output

### ISSUE THREAD

**Issue by wyardley** [opentofu/opentofu#765]
### OpenTofu Version

```shell
OpenTofu v1.6.0-dev
on darwin_arm64
```

### OpenTofu Configuration Files

n/a

### Debug Output

n/a

### Expected Behavior

```
% tofu validate
Success! The configuration is valid.
```

### Actual Behavior

```
% tofu validate
Success! The configuration is valid.

```

### Steps to Reproduce

1. tofu init
2. tofu validate

### References

https://github.com/hashicorp/terraform/issues/28996

**Comment by janosdebugs** [comment]
Hey @wyardley thank you very much for this issue and apologies for the late response. We have discussed this issue in the core team and would be very happy about a PR for this. Would you like to reopen #764 for review?

**Comment by wyardley** [comment]
Sure! I reopened and rebased.
