### ISSUE TITLE
Backend/S3: Custom Service Endpoint Configuration

### ISSUE THREAD

**Issue by mbialon** [opentofu/opentofu#775]
# Summary

Add support for the `endpoints` block to allow customizing service endpoints.

```hcl
terraform {
  backend "s3" {
    endpoints {
      dynamodb = "http://localhost:4569"
      s3       = "http://localhost:4572"
    }
  }
}
```

# References

- [provider docs](https://github.com/hashicorp/terraform-provider-aws/blob/e659dc834b66c4985daf0aa3df64005c1e0ed626/website/docs/guides/custom-service-endpoints.html.markdown#L29)

**Comment by egorksv** [comment]
@mbialon need help with this? I have a bit of time on my hands, happy to help

**Comment by mbialon** [comment]
@egorksv I missed your comment, sorry. I had almost everything ready at the time.

Thank you for considering contributing to the project.
