### ISSUE TITLE
Terraform Cloud 

### ISSUE THREAD

**Issue by agelosnm** [opentofu/opentofu#785]
Is there any roadmap for "terraform cloud clone" in order to use a UI or an API to call OpenTofu projects?

**Comment by cube2222** [comment]
It is not currently on the roadmap.

There are already open-source tools to orchestrate Terraform/OpenTofu (e.g. Atlantis). I believe this is out of scope for the core project.

**Comment by Yantrio** [comment]
Just to add: I've also seen a few people mention OSS products such as https://github.com/leg100/otf

But there are also other alternatives products to TFC/TFE that you can find out there!

**Comment by agelosnm** [comment]
> It is not currently on the roadmap.
> 
> There are already open-source tools to orchestrate Terraform/OpenTofu (e.g. Atlantis). I believe this is out of scope for the core project.

yeap, it is indeed. Just wanted a place to communicate this. Thanks!
