### ISSUE TITLE
Hashes missmatch in .terraform.lock.hcl for Terraform and Tofu

### ISSUE THREAD

**Issue by denis256** [opentofu/opentofu#796]
### OpenTofu Version

```shell
OpenTofu v1.6.0-alpha3
on linux_amd64
```

### OpenTofu Configuration Files

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "5.23.0"
    }
  }
}
```

### Debug Output

https://gist.github.com/denis256/4e7f5cb5cc000b592a0694cd853c9d57

### Expected Behavior

Checksums in `.terraform.lock.hcl` should match with the same values as after Terraform execution

### Actual Behavior

Checksums in `.terraform.lock.hcl` are different after Tofu execution compared with Terraform, which adds suspicious about used dependencies

### Steps to Reproduce

1. terraform init
1. tofu init

### References

https://github.com/denis256/terragrunt-tests/tree/master/checkum-missmatch

**Comment by cube2222** [comment]
Hey! Thanks for raising the issue @denis256!

This is expected behavior. The providers also have different keys in the lockfile (registry.terraform.io vs registry.opentofu.org) so Tofu won't complain about the hash mismatch.
