### ISSUE TITLE
Root module toil

### ISSUE THREAD

**Issue by schollii** [opentofu/opentofu#797]
### OpenTofu Version

```shell
N/a (as of today)
```

### Use Cases

I want to define multiple environments all based on the exact same stack code but with different settings. Eg a dev environment, a staging, a demo, and a prod env. 

Currently, it is quite involved to create this: even if you create a re-usable module that encapsulates the entire stack, say the module is called `Foo`, then to create 4 Foos you would need 4 folders (say `foo1`, `2`, `3`, `4`), each with a `backend.tf`, `main.tf`, `variables.tf`, `outputs.tf`, `providers.tf` (where providers are configured), `terraform.tf` (where the `terraform` block is given) and `versions.tf` (for provider versions). Moreover, 

1. the root module's `variables.tf` and `outputs.tf` end up being copies of the `Foo` module folder `variables.tf` and `outputs.tf`. So any changes in those 2 `Foo` files requires changes in the same files in the root module, PLUS changing the corresponding module `Foo` arguments for the changed variables. 
2. it is quite likely that the backend is identical in all 4 envs except for the bucket name and/or key. 
3. And finally, the providers and would likely be all identical, and any differences  except for a few variables. 

### Attempted Solutions

manually duplicate code and maintain 
use opinionated tools like terragrunt, etc

### Proposal

It should be sufficient to specify which modules to use in the root module, and differences, via something akin to "module" inheritance. Note that this concept can still be declarative, it is merely a convenience to decrease code duplication. 

The main idea is for the engine to clone definitions as though they had been written manually. This could look something like this: 
```hcl
# in root main.tf
module "foo1" {
  source = ..../Foo

  config = var.config // will be defined by the variables cloning
}

variable "config" {
  clone = foo1.config
}

output "out1" {
  clone = foo1.out1
}

provider "aws" {
  clone = foo1.provider.aws
  ...overrides...
}

terraform {
  clone = foo1.terraform

  backend "s3" {
    ...overrides...
  }
}


# in terraform.tfvars
import foo1/terraform.tfvars
...overrides...
```

(an alternative to "clone" could be "import" or "include")

So basically a new `clone` argument in a few places, and a module folder can define (as it can now, but against recommendation) providers. The above declarations would pull *definitions* from the called module into the caller module, and allow for overrides. 

In that case, the minimum that would be required for each `fooN` environment is 2 files, a `main.tf` that has the clone declarations. and a `.tfvars` that does same and provides overrides. 

If possible, it would be nice to make the "declaration clone" argument usable in any module, although this would have be used with caution (like several other capabilities in terraform such as null resources and the like), as it could like to breakage of encapsulation. But at the very least for root module, encapsulation is preserved, since the variables, outputs, and providers are technically part of a module's API. The backend is somewhat special here, as it configures terraform itself, not resources.

**Comment by janosdebugs** [comment]
Hey @schollii thank you for this issue and apologies for the delayed reply. We have discussed this issue with the core team and this would be a large change to the language as it is currently implemented. We feel that it is currently not feasible to implement this feature and Terragrunt already solves this issue quite well. Since a working tool exists that seems to implement what you are looking for, we are closing this issue. If you feel that Terragrunt does not adequately address your needs, please reopen the issue and/or explain how it does not solve the problem.
