### ISSUE TITLE
Get 1.6 Testing Feature Production-ready

### ISSUE THREAD

**Issue by cube2222** [opentofu/opentofu#8]
- Investigate exactly how the feature currently works and is supposed to work.
- Investigate how much is implemented already.
- Investigate the tests to see how well-tested it is.
- Add tests for any scenarios not covered.
- Understand what else we need to implement and improve for it to be usable, stable and secure.
- Write out the necessary work left in this issue.
- Implement it.
- Write documentation for it.

**Comment by eranelbaz** [comment]
What left here is #292

**Comment by kislerdm** [comment]
#292 has been resolved, see the [page](https://opentofu.org/docs/cli/commands/test/).

**Comment by Yantrio** [comment]
I'm happy to close this one if you guys are @cube2222 @RLRabinowitz @kislerdm

**Comment by kislerdm** [comment]
I'm up for it :)

**Comment by cube2222** [comment]
@kislerdm @Yantrio I believe it would be valuable to have a second-page. Less reference-like, and more guide-like, in the [Language Docs](https://opentofu.org/docs/language/). With more end2end examples of a project and testing it.

Reading the current page all **options** are described there, as well as the directory layout, but in practice I could still feel a bit lost. This page is a really good example: https://opentofu.org/docs/language/import/
