### ISSUE TITLE
Need to change location of `/usr/share/doc/nfpm/copyright` in `tofu` package conflicting with the `nfpm` package

### ISSUE THREAD

**Issue by vitkin** [opentofu/opentofu#805]
The presence of `/usr/share/doc/nfpm/copyright` specified in [.goreleaser.yaml](https://github.com/opentofu/opentofu/blob/a1e110c679fa32c96601c9abf531e2888d79e69f/.goreleaser.yaml#L180) conflicts with the one that is provided by the package `nfpm` provided in the goreleaser repository:
- https://github.com/goreleaser/nfpm
- https://nfpm.goreleaser.com/install

For instance, in Debian/Ubuntu one cannot install both `*.deb` packages of `tofu` and `nfpm` because they both contain `/usr/share/doc/nfpm/copyright`.

**Comment by Yantrio** [comment]
Looking at the goreleaser code, this shouldn't be `/usr/share/doc/nfpm/copyright` at all, it should probably be something OpenTofu specific, or it should be removed.

I don't see an advantage of us installing the license into `/usr/share/doc`.

WDYT @mbialon ?

**Comment by Yantrio** [comment]
Hi @professorabhay . Yes this still needs resolving. 

I'll assign this to you. In my opinion we should remove this part of the goreleaser file

**Comment by mbialon** [comment]
@Yantrio Sorry for taking so long to reply.

Looking at the [Debian documentation](https://www.debian.org/doc/debian-policy/ch-archive.html#copyright-considerations), I believe we should include the copyright file in the package.

It should be `/usr/share/doc/opentofu/copyright` rather than `/usr/share/doc/nfpm/copyright`.

**Comment by professorabhay** [comment]
@mbialon Great !

**Comment by professorabhay** [comment]
Hey @Yantrio, Can you please share the link of the slack channel ?

**Comment by Yantrio** [comment]
Opentofu.org/slack
