### ISSUE TITLE
Wrong user agent header on create workspace via the `tofu init` command

### ISSUE THREAD

**Issue by emocharnik** [opentofu/opentofu#806]
### OpenTofu Version

```shell
latest
```

### OpenTofu Configuration Files

```hcl
terraform {
  backend "remote" {
    hostname = "<hostname>"
    organization = "<org>"

    workspaces {
      name = "<workspace>"
    }
  }
}
```

### Debug Output

Debug logs are unnecessary as tofu doesn't print headers in the debug log for internal requests 

### Expected Behavior

All API requests sent by tofu should be sent with the user agent "tofu <version>" (the value is arguable). 

### Actual Behavior

All API requests sent by tofu have the user agent header with the value "go-tfe"

### Steps to Reproduce

1. tofu init and review the sent requests headers

**Comment by cube2222** [comment]
Thanks for the report @emocharnik, this should now be fixed in the next OpenTofu release.
