### ISSUE TITLE
`tofu init` with `cloud` block and `TF_WORKSPACE` doesn't work

### ISSUE THREAD

**Issue by RLRabinowitz** [opentofu/opentofu#814]
### OpenTofu Version

```shell
1.6.0-alpha3
```

### OpenTofu Configuration Files

```hcl
terraform {
  cloud {
    organization = "<MY_CLOUD_ORGANIZATION>"
    hostname     = "<MY_CLOUD_BACKEND_HOSTNAME>"

    workspaces {
      tags = ["<MY_WORKSPACE_TAGS>"]
    }
  }
}
```

### Debug Output

None relevant

### Expected Behavior

Should initialize successfully

### Actual Behavior

Initializing cloud backend...
╷
│ Error: Invalid workspaces configuration
│
│   on main.tf line 2, in terraform:
│    2:   cloud {
│
│ Only one of workspace "tags" or "name" is allowed.
│
│ The 'workspaces' block configures how OpenTofu CLI maps its workspaces for this single
│ configuration to workspaces within a cloud backend organization. Two strategies are available:
│
│ tags - A set of tags used to select remote cloud backend workspaces to be used for this single
│ configuration. New workspaces will automatically be tagged with these tag values. Generally, this
│ is the primary and recommended strategy to use. This option conflicts with "name".
│
│ name - The name of a single cloud backend workspace to be used with this configuration.
│ When configured, only the specified workspace can be used. This option conflicts with "tags".

### Steps to Reproduce

`TF_WORKSPACE="any_workspace" tofu init`

### Additional Context

Using `TF_WORKSPACE` should completely overwrite the workspace used, and overwrite the `workspaces` block configuration

### References

- Relevant issue in Terraform repository: https://github.com/hashicorp/terraform/issues/33976

**Comment by kislerdm** [comment]
It appears that the proposed change will lead to inconsistency:
- `TF_WORKSPACE` does overwrite `workspace`;
- `TF_CLOUD_HOSTNAME` does _not_ overwrite `hostname`;
- `TF_CLOUD_ORGANIZATION` does _not_ overwrite `organization`.

Is it intended behaviour?

**Comment by kislerdm** [comment]
Followup on the [comment](https://github.com/opentofu/opentofu/issues/814#issuecomment-1809303405). It was decided to implement changes following the rule "configuration takes precedence over env variables if both are specified".
