### ISSUE TITLE
Not possible to lock remote state

### ISSUE THREAD

**Issue by Scorpil** [opentofu/opentofu#816]
### OpenTofu Version

```shell
OpenTofu v1.6.0-dev
on darwin_arm64

(commit 16c6432c3a)
```

### OpenTofu Configuration Files

```hcl
terraform {
  backend "http" {}
}
```

### Debug Output

https://gist.github.com/Scorpil/283191fbbe03853df4be6d0f531923bf

### Expected Behavior

Successfully acquire lock, execute command, and return the lock.

### Actual Behavior

Failing to acquire lock due to "context deadline exceeded" error.

### Steps to Reproduce

1. Initialize opentofu remote state. Any remote state storage will work, for example with gitlab: https://docs.gitlab.com/ee/user/infrastructure/iac/terraform_state.html#set-up-the-initial-backend
2. Run `tofu apply`

### Additional Context

I did some initial debugging and found out that the crux of the issue is in this call's context: https://github.com/opentofu/opentofu/blob/main/internal/backend/remote-state/http/client.go#L87

Replacing the argument with a new unbound context solves the issue. Of course, proper fix involves finding the underlying problem with context propagation, which is a bit harder.

I'd like to get this issues assigned to me if possible, I could come up with a PR fairly quickly.

**Comment by Yantrio** [comment]
Hi! Sorry for the slow reply here, this has been a bit of a strange one to solve. We've been discussing this internally and looking at the larger picture of context propagation and how we want to handle it.

We recently introduced a few PRs that introduced some better context propagation but this approach caused this regression. We have decided to revert those PRs (#835) for now and re-visit the context propagation story once we've had a stable release out. 

If you pull the latest main branch and build again things should work just fine for you. Please reach out if it's still broken.

Thanks for your patience on this one.

**Comment by cam72cam** [comment]
@Scorpil Now that alpha4 has been released, would you be able to try your workflow with the new release?

**Comment by Scorpil** [comment]
@cam72cam yes it's fixed in `alpha4` 👍

**Comment by cam72cam** [comment]
Excellent!
