### ISSUE TITLE
`tofu` crashes when failing to upload state the `cloud` backend

### ISSUE THREAD

**Issue by RLRabinowitz** [opentofu/opentofu#818]
### OpenTofu Version

```shell
1.6.0-alpha3
```

### OpenTofu Configuration Files

Any configuration with a `cloud` block

### Debug Output

.

### Expected Behavior

`tofu` should show an error log, and not crash.
For example, when receiving a 409 HTTP error from the state-versions "Create" API, it should display:
```
Error: Failed to save state

Error saving state: Error uploading state: 409 Conflict

Error: Failed to persist state to backend

The error shown above has prevented OpenTofu from writing the updated state to the configured backend. To allow for recovery, the state has been written to the file "errored.tfstate" in the current working directory.

Running "tofu apply" again at this point will create a forked state, making it harder to recover.

To retry writing this state, use the following command:
    tofu state push errored.tfstate
```

### Actual Behavior

`tofu` crashes

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x11e9936]

goroutine 1150 [running]:
github.com/hashicorp/go-tfe.(*stateVersions).Upload.func1()
	/home/runner/go/pkg/mod/github.com/hashicorp/go-tfe@v1.34.0/state_version.go:294 +0xb6
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 39
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0x96

```

### Steps to Reproduce

`tofu apply` when there's some issue upload state to the `cloud` backend

### Additional Context

Reproducing the issue consistently might be a bit troublesome, as this requires to receive specific errors from the `cloud` backend

### References

- The cause of this issue has been fixed in `go-tfe` 1.36.0 - https://github.com/hashicorp/go-tfe/issues/791. Simply updating the `go-tfe` dependency to 1.36.0 should solve this issue

**Comment by tarruda** [comment]
@cube2222 can I take this one?

**Comment by cube2222** [comment]
Go ahead @tarruda, assigned you!
