### ISSUE TITLE
Subsequent `tofu init` causes "backend configuration changed" error

### ISSUE THREAD

**Issue by RLRabinowitz** [opentofu/opentofu#819]
### OpenTofu Version

```shell
1.6.0-alpha3
```

### OpenTofu Configuration Files

```hcl
terraform {
  backend "s3" {
  }
}
```

### Debug Output

.

### Expected Behavior

Both `tofu init`s should succeed

### Actual Behavior

Second `tofu init` fails:

```
Initializing the backend...
╷
│ Error: Backend configuration changed
│
│ A change in the backend configuration has been detected, which may require migrating existing state.
│
│ If you wish to attempt automatic migration of the state, use "tofu init -migrate-state".
│ If you wish to store the current configuration with no changes to the state, use "tofu init -reconfigure".
```

### Steps to Reproduce

1. `tofu init -backend-config=bucket=arel-temp-opentf-driftsszzaaabcdefg -backend-config=encrypt=true -backend-config=key=qwe.tfstate -backend-config=region=us-west-2`
2. `tofu init -backend-config=bucket=arel-temp-opentf-driftsszzaaabcdefg -backend-config=encrypt=true -backend-config=key=qwe.tfstate -backend-config=region=us-west-2`

### Additional Context

Example - https://github.com/denis256/terragrunt-tests/tree/master/tf-init-error

### References

- Related issue in Terraform repository: https://github.com/hashicorp/terraform/issues/34066
- Should be fixed by upgrading to [HCL 2.19.1](https://github.com/hashicorp/hcl/releases/tag/v2.19.1)

**Comment by kislerdm** [comment]
The issue was addressed in #820.
