### ISSUE TITLE
S3, IAM, DynamoDB and STS endpoints do not allow bare hostname

### ISSUE THREAD

**Issue by RLRabinowitz** [opentofu/opentofu#821]
### OpenTofu Version

```shell
1.6.0-alpha3
```

### OpenTofu Configuration Files

```hcl
terraform {
  backend "s3" {
    endpoint = "s3.us-east-1.amazonaws.com"
  }
}
```

### Debug Output

.

### Expected Behavior

Should initialize successfully

### Actual Behavior

```
Initializing the backend...
╷
│ Warning: Deprecated Parameter
│
│   on main.tf line 3, in terraform:
│    3:     endpoint = "s3.us-east-1.amazonaws.com"
│
│ The parameter "endpoint" is deprecated. Use parameter "endpoints.s3" instead.
╵

╷
│ Error: Invalid Value
│
│   on main.tf line 3, in terraform:
│    3:     endpoint = "s3.us-east-1.amazonaws.com"
│
│ The value must be a valid URL containing at least a scheme and hostname. Had "s3.us-east-1.amazonaws.com"
╵
```

### Steps to Reproduce

`terraform init -backend-config=bucket=my_bucket -backend-config=encrypt=true -backend-config=key=qwe.tfstate -backend-config=region=us-east-1`

### Additional Context

The following behaviour happens for S3, IAM, DynamoDB and STS endpoints as well

### References

- Related issue in the Terraform repository: https://github.com/hashicorp/terraform/issues/33981

**Comment by cam72cam** [comment]
Adding `-backend-config=skip_credentials_validation=true -backend-config=skip_region_validation=true` to the init command makes it easier to test
