### ISSUE TITLE
Tofu failed to request a lock for a workspace with remote backend

### ISSUE THREAD

**Issue by AsafZalcman** [opentofu/opentofu#825]
### OpenTofu Version

```shell
OpenTofu v1.6.0-alpha3
on linux_arm64
```

### OpenTofu Configuration Files

```hcl
terraform {
  backend "remote" {
    hostname = ""
    organization = ""
    workspaces {
      name = "test1"
    }
  }
}
```

### Debug Output

partially:

```including .terraform/providers/registry.opentofu.org/hashicorp/null/3.2.1/linux_arm64 as a candidate package for registry.opentofu.org/hashicorp/null 3.2.1
2023-11-06T12:57:14.886Z [DEBUG] checking for provisioner in "."
2023-11-06T12:57:14.886Z [DEBUG] checking for provisioner in "/usr/local/bin"
2023-11-06T12:57:14.887Z [TRACE] Meta.Backend: backend *remote.Remote supports operations
2023-11-06T12:57:14.897Z [DEBUG] Remote backend is delegating OperationTypeApply to the local backend
2023-11-06T12:57:14.897Z [INFO]  backend/local: starting Apply operation
_2023-11-06T12:57:14.897Z [TRACE] backend/local: requesting state manager for workspace "test1"
2023-11-06T12:57:14.905Z [TRACE] backend/local: requesting state lock for workspace "test1"
Error: Error acquiring the state lockError message: context deadline exceeded
```

### Expected Behavior

Tofu should send the lock request to the configured backend

### Actual Behavior

Tofu sending the request to a different URL, or doesn't send at all

### Steps to Reproduce

tofu init.
tofu workspace new test
tofu apply

**Comment by Yantrio** [comment]
Hi @AsafZalcman, thanks for reporting this one. 

Is it possible that the remote backend has timed out generating a lock on this file at this time? I suspect the issue here is server side and not clientside.

this is because of the error: `context deadline exceeded` being reported.

**Comment by AsafZalcman** [comment]
Hey.
This is why I think that the client tries to reach to a wrong url, because the last request that my reverse proxy got is GET workspaces/{workspaceName}, but no request for lock after it

**Comment by Yantrio** [comment]
Hi @AsafZalcman I've been able to reproduce this and provide a fix here #834 

It's worth noting that this has been broken AFTER alpha3 was released, so in theory you should be able to use alpha3 here without any issues.

**Comment by cam72cam** [comment]
@AsafZalcman Now that alpha4 has been released, would you be able to try your workflow with the new release?

**Comment by AsafZalcman** [comment]
Works perfectly.
Thanks!

בתאריך שבת, 11 בנוב׳ 2023, 18:05, מאת Christian Mesh ‏<
***@***.***>:

**Comment by cam72cam** [comment]
Excellent!
