### ISSUE TITLE
[RFC] Stable Registry: Repository Folder Structure

### ISSUE THREAD

**Issue by RLRabinowitz** [opentofu/opentofu#827]
## Overview

This proposal is part of the [Homebrew-like Registry Design](https://github.com/opentofu/opentofu/issues/741). It's a prerequisite for all other parts of the design, as most of them will rely on the folder structure of the main repository

The folder structure of the registry repository should allow for easy addition / change / removal of provider and module metadata, so it could later be transformed and hosted for the CLI to access. The design would take into account the sheer amount of files that could be part of this repository

## Folder Structure

The folder structure would include a `modules` and `providers` folders. Each should be sharded by the first character of the namespace of the provider/module, to help with GitHub UI performance when scrolling through providers or viewing commits. This sharding is based on how `homebrew-core` has sharded its Formulae, More info in https://github.com/opentofu/opentofu/issues/741#issuecomment-1777544250

```
├── modules
│   ├── ≈ (first letter of the module namespace)
│   │   ├── bridgecrewio (module namepsace that starts with "b")
│   │   │   ├── apigateway-cors
│   │   │   │   ├── aws.json 
│   │   │   ├── bridgecrew-read-only
│   │   │   │   ├── aws.json 
│   ├── c (first letter of the module namespace)
│   │   ├── claranet (module namepsace that starts with "c")
│   │   │   ├── detectors
│   │   │   │   ├── signalfx.json 
├── providers
│   ├── a (first letter of the module namespace)
│   │   ├── aliyun (module namepsace that starts with "a")
│   │   │   ├── alibabacloudstack.json
│   │   │   ├── alicloud.json
│   ├── o (first letter of the module namespace)
│   │   ├── oracle (module namepsace that starts with "o")
│   │   │   ├── oci.json
```

There will be a folder for `modules` and a folder for `providers`

### Providers

- The main `providers` folder should contain folders named with single characters (either letters or digits). Those represent the **first character of the provider namespace**
- In each "single character" folder (for example `a`) there will be folders per each provider namespace that starts with "a" (For example - `aliyun`)
- In each provider namespace folder (for example `aliyun`), there will be JSON files named with the name of the provider with `.json` suffix (for example - `alicloud.json`)
- In each provider namespace folder, there might also be a folder `keys` containing the public keys of GPG keys used to sign the provider artifacts (This part will be adjusted/elaborated once we have a design on managing GPG keys in the repository)

#### JSON file content

```json
{
  "repository": "https://github.com/aliyun/terraform-provider-alibabacloudstack",
  "versions": [
    {
      "version": "1.0.19",
      "protocols": [
        "5.0"
      ],
      "shasums_url": "https://github.com/aliyun/terraform-provider-alibabacloudstack/releases/download/v1.0.19/terraform-provider-alibabacloudstack_1.0.19_SHA256SUMS",
      "shasums_signature_url": "https://github.com/aliyun/terraform-provider-alibabacloudstack/releases/download/v1.0.19/terraform-provider-alibabacloudstack_1.0.19_SHA256SUMS.sig",
      "targets": [
        {
          "os": "windows",
          "arch": "amd64",
          "filename": "terraform-provider-alibabacloudstack_1.0.19_windows_amd64.zip",
          "download_url": "https://github.com/aliyun/terraform-provider-alibabacloudstack/releases/download/v1.0.19/terraform-provider-alibabacloudstack_1.0.19_windows_amd64.zip",
          "shasum": "f6644af3c6c5d41819315e7a80466f403d185c11fbf3d25bd4fad7cf208a3033"
        },
        {
          "os": "linux",
          "arch": "386",
          "filename": "terraform-provider-alibabacloudstack_1.0.19_linux_386.zip",
          "download_url": "https://github.com/aliyun/terraform-provider-alibabacloudstack/releases/download/v1.0.19/terraform-provider-alibabacloudstack_1.0.19_linux_386.zip",
          "shasum": "e7f8e9327fc706865dbcbbaa5adda2f350beae904bee386a9ee452280126d9db"
        }
      ]
    },
    ...
  ]
}
```

- `repository` - (optional) Used to help the automatic version bump process, to tell what repository to use when attempting to make API calls. Defaults to `https://github.com/<NAMESPACE>/terraform-provider-<PROVIDER_NAME>`. (Might not be necessary. This part will be adapted once we create a design doc for existing provider version update)
- `versions` - Contains each provider version
  - `version` - The provider version. Should always be in [semver](https://semver.org/) format (without a `v` prefix)
  - `protocols` - The list of supported plugin protocol of the provider version. This data could be inferred from the `_manifest.json` artifact, if it exists (otherwise, default to `5.0`)
  - `shasums_url` - Download link to the SHASUMs URL for the provider version artifacts
  - `shasums_signature_url` - Download link to the SHASUMs signature artifact
  - `targets` - Entity per released platform of this provider version
    - `os` and `arch` make up the platform
    - `filename` - The name of the artifact to download
    - `download_url` - The download URL of the artifact
    - `shasum` - The shasum of the artifact

### Modules

- The main `modules` folder should contain folders named with single characters (either letters or digits). Those represent the **first character of the module namespace**
- In each "single character" folder (for example `b`) there will be folders per each module namespace that starts with "b" (For example - `bridgecrewio`)
- In each module namespace folder (for example `aliyun`), there will be folders named with the "name" of the module (for example - for module `bridgecrewio/apigateway-cors/aws` it's `apigateway-cors`)
- In each module name folder (for example `apigateway-cors`), there will be a JSON file named with the system of the module, with `.json` suffix (for example - for module `bridgecrewio/apigateway-cors/aws` it's `aws`)

#### JSON file content

```json
{
  "versions": [
    {
      "version": "v1.0.0"
    },
    {
      "version": "v1.0.1"
    },
    ...
  ]
}
```

The JSON file only contains the module tags that could be used as versions of the provider.
The versions should always be in [semver](https://semver.org/) format, optionally prefixed with a `v` (like `v1.1.1`), based on the actual tag in the GitHub repository of the module

## Justification for this folder structure

- Sharding the folders will help dealing with sheer amount of files that the repository will end up having, making the GitHub UI nicer and more responsive
- This simple folder structure makes it easy to see all of the relevant metadata of each provider and module easily

**Comment by cube2222** [comment]
Generally, LGTM! Some minor comments:

> repository - Used to help the automatic version bump process, to tell what repository to use when attempting to make API calls (Might not be necessary. This part will be adapted once we create a design doc for existing provider version update)

I propose we just make this optional so that we can use it when needed (like for the hashicorp namespace).

> version - The provider version. Should always be in format X.X.X

I believe this can be a prerelease too, right? So in effect this is just semver. I think it's the same for modules, though not 100% sure.

**Comment by RLRabinowitz** [comment]
> I propose we just make this optional so that we can use it when needed (like for the hashicorp namespace).

The thing is, we'd probably want this information when adding a new provider/module to the registry, and not just for updating providers/modules that already exist in the registry.
So let's say there's a new hashicorp provider - When creating it from scratch we'd want to this "repository" data as well.

That's why my current thinking is that the logic for resolving the repository would be shared between the parts of code that update existing providers and the parts that add completely new providers. And therefore, this part would probably be a bit more static

However, the `repository` part here would be solidified further once we have RFCs for the update process and for the process of adding new providers to the registry

> I believe this can be a prerelease too, right? So in effect this is just semver. I think it's the same for modules, though not 100% sure

I think this is correct, I'll update the phrasing here

**Comment by Yantrio** [comment]
Regarding the location of GPG keys and how we would like to store those, I'd like to propose that we store them separately from the providers.

Right now providers and GPG keys go hand-in-hand and only work for eachother. This is because right now we're only supporting modules and providers and modules don't use the keys.

However, in the future we could be introducing plugins or other things that may use gpg keys to be validated.  Some examples of things we could do here:

- Distributing backends: https://github.com/opentofu/opentofu/issues/382
- Distributing functions: https://github.com/opentofu/opentofu/issues/793

And there is also the possibilities of other things.

Therefore I would like to propose a separate directory at the root that handles keys.

This means we would have the following:
```
├── keys
│   ├── a
│   ├── b
│   ├── c
│   └── o
│       └── opentofu
│           ├── 20220304.asc
│           └── 20230101.asc
├── modules
│   ├── a
│   ├── b
│   ├── c
│   └── o
│       └── opentofu
└── providers
    ├── a
    ├── b
    ├── c
    └── o
        └── opentofu
            ├── aws.json
            └── google.json
```
and the keys provided in the keys directory relate to the providers via the namespace commonality for now.

There is one downside to this, in that we are creating a bit more difficulty to manage both versions and keys in one single place, but I believe the overhead is worth the cost.

**Comment by cube2222** [comment]
> However, the repository part here would be solidified further once we have RFCs for the update process and for the process of adding new providers to the registry

My point @RLRabinowitz is, wouldn't it just default to github.com/<namespace>/<name>? And the repository would only be explicitly passed when it doesn't follow the default naming scheme?

**Comment by RLRabinowitz** [comment]
> My point @RLRabinowitz is, wouldn't it just default to github.com//? And the repository would only be explicitly passed when it doesn't follow the default naming scheme?

That's one option. But that would mean that the process of adding a new provider to the registry would also need to be aware of this somehow (or would require the person adding the provider to explicitly provider the `registry` there). Which is probably OK

Another alternative, is to have a more static "redirection" logic, so that in most cases providers are mapped to their `github.com/<namespace>/terraform-provider-<provider>` repository, but in other cases it could be mapped to a different namespace. This approach doesn't require us to store `repository`, or to ask of it from the person adding the new provider to the registry

I tend to go with your suggestion here, of using an optional `registry` field, which must be filled out in special cases for some providers. The reason I wrote that "This part will be adapted once we create a design doc for existing provider version update", is because we will dig deeper into this once we create an RFC on the process of adding new providers to the registry. But I do believe we will go with your suggestion

So, I'm marking `repository` as optional, per your comment

**Comment by RLRabinowitz** [comment]
@Yantrio regarding [your suggestion](https://github.com/opentofu/opentofu/issues/827#issuecomment-1798337846) for the placement of keys: Personally I don't mind too much whether they would be in a separate folder structure from the root of the repository, or sit next to the actual providers (or eventually, be part of a different repository altogether)

As for the downside you've mentioned:
> There is one downside to this, in that we are creating a bit more difficulty to manage both versions and keys in one single place, but I believe the overhead is worth the cost.

I do agree that this is a bit annoying when adding a new provider, but not a deal breaker

But TBH - I think that moving the `keys` folder/s later would probably be very easy to accomplish, if we'd like to. So personally, I'd keep the current design of having the `keys` folders closer to the actual providers, and later on we could change that
But I'm also OK with starting off with having the `keys` folder be as you have suggested

**Comment by cube2222** [comment]
> Another alternative, is to have a more static "redirection" logic, so that in most cases providers are mapped to their github.com/<namespace>/terraform-provider-<provider> repository, but in other cases it could be mapped to a different namespace. This approach doesn't require us to store repository, or to ask of it from the person adding the new provider to the registry

This is exactly what I had in mind @RLRabinowitz

> But TBH - I think that moving the keys folder/s later would probably be very easy to accomplish, if we'd like to. So personally, I'd keep the current design of having the keys folders closer to the actual providers, and later on we could change that
But I'm also OK with starting off with having the keys folder be as you have suggested

I propose then, if nobody cares too much, to split it off initially, so that each "directory prefix" has only one clear purpose / schema.

**Comment by cube2222** [comment]
Anyhow, other than those tiny changes, I think we can treat this design as settled for now.

**Comment by kislerdm** [comment]
**(nitpick)** I assume that you meant "provider" instead of "module" when you were describing the `providers` directory tree 🙂 

```commandline
├── modules
│   ├── ≈ (first letter of the module namespace)
│   │   ├── bridgecrewio (module namepsace that starts with "b")
│   │   │   ├── apigateway-cors
│   │   │   │   ├── aws.json (module name)
├── providers
│   ├── a (first letter of the provider namespace)
│   │   ├── aliyun (provider namepsace that starts with "a")
│   │   │   ├── alibabacloudstack.json (provider name)
│   │   │   ├── alicloud.json
```

**(question)** Could you please clarify if the following illustrations are correct?

- Given that developer created a _brand new_ provider `bar` hosted in "https://github.com/foo/terraform-provider-bar", and released its version "0.0.1" with binaries stored as github release artefacts. Would they need to submit the following JSON file to the OpenTofu repo for the provider to appear in the OpenTofu registry?

```json
{
  "repository": "https://github.com/foo/terraform-provider-bar",
  "versions": [
    {
      "version": "0.0.1",
      "protocols": ["5.0"],
      "shasums_url": "https://github.com/foo/terraform-provider-bar/releases/download/v0.0.1/terraform-provider-bar_0.0.1_SHA256SUMS",
      "shasums_signature_url": "https://github.com/foo/terraform-provider-bar/releases/download/v0.0.1/terraform-provider-bar_0.0.1_SHA256SUMS.sig",
      "targets": [
        {
          "os": "windows",
          "arch": "amd64",
          "filename": "terraform-provider-bar_0.0.1_windows_amd64.zip",
          "download_url": "https://github.com/foo/terraform-provider-bar/releases/download/v0.0.1/terraform-provider-bar_0.0.1_windows_amd64.zip",
          "shasum": "xxxxx"
        },
        ...
      ]
    }
  ]
}
```

- Given that the provider `bar` is available in the OpenTofu registry now, and the provider developer released its version "0.0.2", would they need to modify existing JSON and submit it to the OpenTofu repo as following:

```json
{
  "repository": "https://github.com/foo/terraform-provider-bar",
  "versions": [
    {
      "version": "0.0.1",
      "protocols": ["5.0"],
      "shasums_url": "https://github.com/foo/terraform-provider-bar/releases/download/v0.0.1/terraform-provider-bar_0.0.1_SHA256SUMS",
      "shasums_signature_url": "https://github.com/foo/terraform-provider-bar/releases/download/v0.0.1/terraform-provider-bar_0.0.1_SHA256SUMS.sig",
      "targets": [
        {
          "os": "windows",
          "arch": "amd64",
          "filename": "terraform-provider-bar_0.0.1_windows_amd64.zip",
          "download_url": "https://github.com/foo/terraform-provider-bar/releases/download/v0.0.1/terraform-provider-bar_0.0.1_windows_amd64.zip",
          "shasum": "xxxxx"
        },
        ...
      ]
    },
    {
      "version": "0.0.2",
      "protocols": ["5.0"],
      "shasums_url": "https://github.com/foo/terraform-provider-bar/releases/download/v0.0.2/terraform-provider-bar_0.0.2_SHA256SUMS",
      "shasums_signature_url": "https://github.com/foo/terraform-provider-bar/releases/download/v0.0.2/terraform-provider-bar_0.0.2_SHA256SUMS.sig",
      "targets": [
        {
          "os": "windows",
          "arch": "amd64",
          "filename": "terraform-provider-bar_0.0.2_windows_amd64.zip",
          "download_url": "https://github.com/foo/terraform-provider-bar/releases/download/v0.0.2/terraform-provider-bar_0.0.2_windows_amd64.zip",
          "shasum": "yyyyyy"
        },
        ...
      ]
    }
  ]
}
```

**(idea)** Given that we rely on the artefacts stored on GitHub, WDYT about making the schema more developer friendly by unifying it with the schema for modules? 

Illustrations:
- _Given_ that developer created a _brand new_ provider `bar` hosted in "https://github.com/foo/terraform-provider-bar", and released its version "0.0.1" with binaries stored as github release artefacts; _when_ they submit JSON of the following, _then_ the provider will be available in the OpenTofu registry:
```json
{
  "repository": "https://github.com/foo/terraform-provider-bar",
  "versions": [
   {
     "version": "0.0.1",
     "gpg_key": "KEY"
   }
 ]
}
```
- _Given_ that the provider `bar` is available in the OpenTofu registry now, and the provider developer released its version "0.0.2", _when_ they submit JSON of the following, _then_ newly release provider's version will be available in the OpenTofu registry:

```json
{
  "repository": "https://github.com/foo/terraform-provider-bar",
  "versions": [
   {
     "version": "0.0.1",
     "gpg_key": "KEY0"
   },
   {
     "version": "0.0.2",
     "gpg_key": "KEY1"
   }
  ]
}
```

This proposal is based on the assumption that released artifacts names follow the standard naming convention. IMO the main con of such proposal: OpenTofu scrapper will have to extract the artifacts shasum. The main pro: developer will update gpg keys, and map keys to releases. Moreover, such JSON schema seems more human readable which will facilitate developers onboarding, and simplify manual PR review.

Thanks!

**Comment by kislerdm** [comment]
@cam72cam Yes, precisely. My idea is based on the assumption of the naming convention we rely on. In other words, users don't really have to provide us more details than the repo URL.

**Comment by cube2222** [comment]
@kislerdm There will be a separate RFC for submitting new providers, in practice I expect it to contain **no** versions. You just provide the file and optionally the repo.

New version detection (and initial version detection) will be handled by a script ran on a schedule.
