### ISSUE TITLE
[REFACTORING] Replace `os.Setenv&t.Unset` with `t.Setenv` in tests

### ISSUE THREAD

**Issue by kislerdm** [opentofu/opentofu#838]
### OpenTofu Version

```shell
1.6.0
```

### Use Cases

N/A

### Attempted Solutions

N/A

### Proposal

An enhancement to follow best practices and simplify readability of the tests.

**Comment by janosdebugs** [comment]
Hey @kislerdm thanks for this and sorry for the long delay. We have discussed this issue in the core team and would be happy about a PR to this effect.

**Comment by janosdebugs** [comment]
Thanks @kislerdm !
