### ISSUE TITLE
Will the OpenToffu stay compatible with the future terraform providers like terraform/aws

### ISSUE THREAD

**Issue by luedigernet** [opentofu/opentofu#851]
### OpenTofu Version

```shell
I would like to know if the OpenTofu project will keep compatability of terraform providers.
```

### Use Cases

.

### Attempted Solutions

.

### Proposal

.

**Comment by Yantrio** [comment]
Hi @luedigernet

OpenTofu is and will be compatible with all existing public providers. We intend to maintain this compatibility going forward too.
