### ISSUE TITLE
As an opentofu.org/github repo visitor, I want to have clear instructions how to install `tofu`

### ISSUE THREAD

**Issue by kislerdm** [opentofu/opentofu#859]
## Problem

`tofu` installation instructions are spread across the documentation website:
- In the [introduction section](https://opentofu.org/docs/intro/install)
- In the [CLI section](https://opentofu.org/docs/cli/install/apt)

Moreover, the installation instructions don't cover installation using docker - see the [discussion](https://github.com/orgs/opentofu/discussions/733).

## Proposed Solution

1. Combine all installation instructions in a single subsection
2. Colocate them in the "HOWTO" section

**The motivation**: ease of the tool's adoption.

### Mock

<img width="904" alt="image" src="https://github.com/opentofu/opentofu/assets/13434797/16c76e0e-7c7f-4c2b-99fc-c3d9e2128912">

## References
- [How-to guidelines](https://documentation.divio.com/how-to-guides.html)

**Comment by janosdebugs** [comment]
I would be more direct about it and add a `Download` link to the main menu. Right now, the installation instructions are way too hidden if you are not entering from the front page. However, at the same time the main menu is currently "full" on the minimum non-mobile size, so something would need to go. (FAQs maybe?)

**Comment by kislerdm** [comment]
@janosdebugs IMO FAQ is useful page, and it will be even more useful moving forward. About `Downloads/HOWTO`, WDYT about including it to the `Docs` as dedicated dropdown option right after `Intro`?

**Comment by janosdebugs** [comment]
Oh, no doubt about the FAQ being useful! My train of thought was that OpenTofu will need to transition from being an idea into being an actual tool, so people will be looking for things like downloads, tutorials, reference manuals rather than explanations on what OpenTofu actually is.

Maybe there should be a section called "About OpenTofu"? Not sure.

**Comment by kislerdm** [comment]
@janosdebugs You are totally right about 

> [...] people will be looking for things like downloads, tutorials, reference manuals [...]

however, this bit is non-less important

> [...] rather than explanations on what OpenTofu actually is

I feel that it will be beneficial to make more clear distinction between `tofu` as the tool (howto's, tutorials, implementation details, feedback forms) and OpenTofu as the projects (manifesto, blog, FAQ, roadmap etc.) to ease docs digestion by the reader. WDYT?

**Comment by Yantrio** [comment]
Let's also not forget that we have the `Try it out` button on the landing page.
![image](https://github.com/opentofu/opentofu/assets/237469/4144e356-8799-4d0c-9924-ae0093bfd0b4)

//cc @damianstasik @Roma36 as you guys may have some opinions on where this goes and also limitations of docusaurus

**Comment by cube2222** [comment]
Let's get rid of https://opentofu.org/docs/cli/install/apt and https://opentofu.org/docs/cli/install/yum
