### ISSUE TITLE
Change the name in the snap store to tofu

### ISSUE THREAD

**Issue by jadolg** [opentofu/opentofu#872]
Because the name doesn't match the name of the app, instead of executing only `tofu` you need to call `opentofu.tofu`. 
Yes, you can create an alias and trick the completions too, but it's far from optimal.
This will be an inconvenient for new users and a gotcha in future automation.

https://github.com/opentofu/opentofu/blob/b8e2fad8e24cdd98c5a81d5c08bc8fe417cfdfc5/.goreleaser.yaml#L185

note: I have registered the snap name (tofu) so it doesn't get used for another purpose. I'll release it when/if I get confirmation that the rename is happening.

**Comment by jadolg** [comment]
Yes, that's pretty much it. Plus creating the app in Snapcraft and updating the token so it can be pushed automatically on release.

**Comment by cube2222** [comment]
Hey @jadolg, thanks for creating the issue!

The app is called opentofu, while the binary is called tofu. I believe that was fully intentional, and is also how it works on other package managers, like Homebrew. Pure tofu would be imo be confusing.

cc @jnsgruk who contributed this originally but is also affiliated with the snap store, I believe.

**Comment by jadolg** [comment]
It's a minor inconvenience. In the end, I can just create an alias and it works, but the lack of consistency in naming compared to the other install methods is not nice.
I ended up doing the following:
```
alias tofu=opentofu.tofu
complete -C /snap/opentofu/current/tofu tofu
```
If I'm working with other people, this is necessary as they might not be using snap to get their binaries.

**Comment by cube2222** [comment]
@jadolg The snap should create an alias automatically, this should be handled by this line: https://github.com/opentofu/opentofu/blob/main/.goreleaser.yaml#L199

If it's not, then it's a bug and that we should fix.

I did just try though, and the following:
```
~> sudo apt install snapd
...
~> sudo snap install --classic opentofu
...
~> tofu -version
OpenTofu v1.6.0-alpha5
on linux_amd64
```
worked out of the box on a fresh ubuntu VM for me.

**Comment by jadolg** [comment]
Oh, I see. It looks like I installed before https://github.com/opentofu/opentofu/commit/27512903dca074a6ad98fef532adb0c992b1463c got merged.
It works for me too in a fresh install.
Thanks all.
