### ISSUE TITLE
Failed to read terraform_remote_state data

### ISSUE THREAD

**Issue by denis256** [opentofu/opentofu#875]
### OpenTofu Version

```shell
OpenTofu v1.6.0-alpha5
on linux_amd64
```

### OpenTofu Configuration Files

```hcl
data "terraform_remote_state" "vpc" {
  backend = "s3"
  config = {
    region = "us-west-2"
    bucket = "terragrunt-test-bucket-2ttejd"
    key    = "mgmt/vpc/terraform.tfstate"
  }
}

```

### Debug Output

https://gist.github.com/denis256/341a3042d60cd885d3fc918446acce2d

### Expected Behavior

Read remote state as data

Terraform is reading it, Tofu fails

### Actual Behavior

╷
│ Error: Invalid backend configuration
│ 
│   with data.terraform_remote_state.vpc,
│   on main.tf line 3, in data "terraform_remote_state" "vpc":
│    3:   config = {
│    4:     region = "us-west-2"
│    5:     bucket = "terragrunt-test-bucket-2ttejd"
│    6:     key    = "mgmt/vpc/terraform.tfstate"
│    7:   }
│ 
│ The given configuration is not valid for backend "s3": attribute "assume_role" is required.

### Steps to Reproduce

1. tofu init
2. tofu plan

**Comment by denis256** [comment]
If I run multiple times `tofu plan`, in some cases it fails with:
```
│ 
│ The given configuration is not valid for backend "s3": attribute "endpoints" is required.
╵
```

**Comment by cube2222** [comment]
Thanks for the bug report @denis256! We'll look into it.

**Comment by cam72cam** [comment]
Investigation so far:

Schema is missing some Optional attributes.  This was not found due to the config population / schema checking paths differing between data / backend configuration.

Schema is the same for both cases, but the initial meta backend config mapping creates empty maps for unspecified fields in the schema which allows it to pass the broken schema validation

backend{}
```
cty.ObjectVal(map[string]cty.Value{"access_key":cty.NullVal(cty.String), "acl":cty.NullVal(cty.String), "allowed_account_ids":cty.NullVal(cty.Set(cty.String)), "assume_role":cty.NullVal(cty.Object(map[string]cty.Type{"duration":cty.String, "external_id":cty.String, "policy":cty.String, "policy_arns":cty.Set(cty.String), "role_arn":cty.String, "session_name":cty.String, "tags":cty.Map(cty.String), "transitive_tag_keys":cty.Set(cty.String)})), "assume_role_duration_seconds":cty.NullVal(cty.Number), "assume_role_policy":cty.NullVal(cty.String), "assume_role_policy_arns":cty.NullVal(cty.Set(cty.String)), "assume_role_tags":cty.NullVal(cty.Map(cty.String)), "assume_role_transitive_tag_keys":cty.NullVal(cty.Set(cty.String)), "assume_role_with_web_identity":cty.NullVal(cty.Object(map[string]cty.Type{"duration":cty.String, "policy":cty.String, "policy_arns":cty.Set(cty.String), "role_arn":cty.String, "session_name":cty.String, "web_identity_token":cty.String, "web_identity_token_file":cty.String})), "bucket":cty.StringVal("com.dkisler.opentofu"), "custom_ca_bundle":cty.NullVal(cty.String), "dynamodb_endpoint":cty.NullVal(cty.String), "dynamodb_table":cty.NullVal(cty.String), "ec2_metadata_service_endpoint":cty.NullVal(cty.String), "ec2_metadata_service_endpoint_mode":cty.NullVal(cty.String), "encrypt":cty.NullVal(cty.Bool), "endpoint":cty.StringVal("s3.eu-west-1.amazonaws.com"), "endpoints":cty.NullVal(cty.Object(map[string]cty.Type{"dynamodb":cty.String, "iam":cty.String, "s3":cty.String, "sts":cty.String})), "external_id":cty.NullVal(cty.String), "forbidden_account_ids":cty.NullVal(cty.Set(cty.String)), "force_path_style":cty.NullVal(cty.Bool), "http_proxy":cty.NullVal(cty.String), "iam_endpoint":cty.NullVal(cty.String), "insecure":cty.NullVal(cty.Bool), "key":cty.StringVal("terraform.tfstate"), "kms_key_id":cty.NullVal(cty.String), "max_retries":cty.NullVal(cty.Number), "profile":cty.NullVal(cty.String), "region":cty.StringVal("eu-west-1"), "retry_mode":cty.NullVal(cty.String), "role_arn":cty.NullVal(cty.String), "secret_key":cty.NullVal(cty.String), "session_name":cty.NullVal(cty.String), "shared_config_files":cty.NullVal(cty.Set(cty.String)), "shared_credentials_file":cty.NullVal(cty.String), "shared_credentials_files":cty.NullVal(cty.Set(cty.String)), "skip_credentials_validation":cty.NullVal(cty.Bool), "skip_metadata_api_check":cty.NullVal(cty.Bool), "skip_region_validation":cty.NullVal(cty.Bool), "skip_requesting_account_id":cty.NullVal(cty.Bool), "skip_s3_checksum":cty.NullVal(cty.Bool), "sse_customer_key":cty.NullVal(cty.String), "sts_endpoint":cty.NullVal(cty.String), "sts_region":cty.NullVal(cty.String), "token":cty.NullVal(cty.String), "use_dualstack_endpoint":cty.NullVal(cty.Bool), "use_fips_endpoint":cty.NullVal(cty.Bool), "use_legacy_workflow":cty.NullVal(cty.Bool), "use_path_style":cty.NullVal(cty.Bool), "workspace_key_prefix":cty.NullVal(cty.String)})
```

data{}
```
cty.ObjectVal(map[string]cty.Value{"bucket":cty.StringVal("christianm-opentofu-test-bucket"), "key":cty.StringVal("mgmt/vpc/terraform.tfstate"), "region":cty.StringVal("us-west-2")})
```

This is likely broken for other backends as well.  I think I'm going to do two different PRs, one to fix the schema, one to fix the population/validation path for backends.

**Comment by cam72cam** [comment]
Oh!  The config validation uses an unsorted set of keys which is why the message changes

**Comment by cam72cam** [comment]
There are two paths to "fix" the validation for the backends, we might want both long term.

Change backendInitFromConfig:hcldec.Decode() to not populate nulls in for fields by default.  This gets deep into hcldec and related libraries, not sure if this is viable.  You can see all the nulls in backend block in `.terraform/terraform.tfstate`.  Preferred, not sure if possible. 

Change the meta backend to validate the schema in a few additional places.  Also change the schema coerce function to not allow nulls for required fields.  Possible, might have conflicts / undesired consequences.

I'm implementing the second option tonight and will create a Draft PR.  Either way, this is a non-trival fix to apply proper validation to backends.

You can see some of the side effects here.  Adding nulls for the (incorrectly) required map fields bypasses validation.
```
data "terraform_remote_state" "vpc" {
  backend = "s3"
  config = {
    region = "us-west-2"
    bucket = "christianm-opentofu-test-bucket"
    key    = "mgmt/vpc/terraform.tfstate"
    endpoints = null
    assume_role = null
    assume_role_with_web_identity = null
  }
}
```
This slight modification to the original example runs fine on alpha5 and really shouldn't.  I'm curious if terraform allows nulls for required maps.
