### ISSUE TITLE
[COSMETICS] Cleanup test by replacing app.terraform.io and hashicorp occurances

### ISSUE THREAD

**Issue by kislerdm** [opentofu/opentofu#882]
A minor cosmetics issue meant to replace occurrences of the following strings in the tests:

- app.terraform.io
- registry.terraform.io
- hashicorp

Also, it may make sense to investigate whether `localterraform.com` and `tfe.v2.1` can be replaced to avoid confusion (find [here](https://github.com/opentofu/opentofu/blob/637c65f6f2d7af65a9ad967be5ce489f2aaac05a/internal/backend/remote/backend.go#L41-L42) for details).

Examples:
- [internal/backend/remote/backend_test:go](https://github.com/opentofu/opentofu/blob/637c65f6f2d7af65a9ad967be5ce489f2aaac05a/internal/backend/remote/backend_test.go#L745-L753)

**Comment by cam72cam** [comment]
This was handled as part of #898.  Feel free to re-open if I missed anything critical.
