### ISSUE TITLE
Improve `tofu test` output if no tests found

### ISSUE THREAD

**Issue by kislerdm** [opentofu/opentofu#885]
### OpenTofu Version

```shell
v1.6.0-alpha5
```

### Use Cases

**GIVEN**

- Module is defined correctly
- State is initialised
- No tests defined, or no test files (*.tftest.hcl) found by OpenTofu

**WHEN**

Run `tofu test`

**THEN**

The `tofu` outputs:

```commandline
Success! 0 passed, 0 failed.
```

Such message is misleading because there is no evidence for any conclusion if tests are not found.

### Attempted Solutions

N/A

### Proposal

I find a warning message similar to the one which `go test` would output in the absence of test files to be more appropriate.

For example, assuming no test files found, the following message will be expected

```commandline
/path/to/tofu/module   No tests found!
```

**Comment by tannerjones4075** [comment]
I would like to help with this :)

**Comment by janosdebugs** [comment]
Hey @tannerjones4075 thank you very much for helping out. This feature still needs a bit of definition (do we exit with a non-zero exit code or not, etc) and no decision has been made yet wether to implement it and how. If you have a vision on how to implement this please document it here. While it is likely not going to make it into 1.6.0, it may work out for 1.6.1.

**Comment by janosdebugs** [comment]
Hey folks, thank you very much for the issue and comments. We have discussed this issue in the core team and have decided that the message currently clearly indicates what the situation is. If you strongly feel that this is not the case, please comment with your specific use case below. (What is it that this will enable you to do that you can't do today?)

As such, we are closing this issue pending reopening if any valid use case comes up.
