### ISSUE TITLE
[COSMETICS] Change links to the tofu documentation in the comments

### ISSUE THREAD

**Issue by kislerdm** [opentofu/opentofu#891]
## Problem

It was spotted that in-code comments contain links to the terraform documentation. Find an example [here](https://github.com/opentofu/opentofu/blob/c5170df91a6d4e511c0742ea6baefa97232b6448/internal/configs/test_file.go#L76).

## Proposed solution

Swap the links with the ones pointing to respective pages of opentofu.org.

**Comment by haidong** [comment]
I would like to take the ownership of this issue. Thanks!
