### ISSUE TITLE
Introduce better rendering of GPG Key information during init provider authentication

### ISSUE THREAD

**Issue by Yantrio** [opentofu/opentofu#892]
### OpenTofu Version

```shell
1.6.0
```

### Use Cases

When we originally forked, we removed part of the logic around package authentication that would give special treatment to hashicorp providers and would render `signed by Hashicorp` for hashicorp packages, but not others.

We removed this in https://github.com/opentofu/opentofu/pull/185

I believe that whenever we're authenticating providers, we should attempt to show atleast a human friendly string because Key IDs do not mean much to people.

### Attempted Solutions

It looks like we could just edit the generation of this message [here](https://github.com/opentofu/opentofu/blob/34b210d600e73144af34fc594ef12b5bddd7d175/internal/command/init.go#L824-L837). 

### Proposal

I propose that instead of checking against a list of known values in a keyring, we should instead we could use the name of the organization that signed it (the provider namespace).

For example, if someone were to pull the provider for `oracle/oci` then they would currently see:
```
- Installed oracle/oci v5.21.0 (signed, key ID 1533A49284137CEB)
```

But instead we could show:
```
- Installed oracle/oci v5.21.0 (signed by Oracle - Key ID 1533A49284137CEB)
```

Note: The reason that I do not recommend pulling identities out from the keys and using that as the name is because identities usually contain quite large strings or strings that are not nice for humans to read for the names, for example:

Gitlab: `Timo Furrer on behalf of thte GitLab Terraform Provider (Signing Key for the GitLab Terraform Provider releases. Created by Timo Furrer <tfurrer@gitlab.com>) <contact-project+gitlab-org-terraform-provider-gitlab-40916776-issue-@incoming.gitlab.com>`

Oracle: `Tf_oci_pub (GPG key for the signing) <TF-OCI-PUB_WW@ORACLE.COM>`

### References

We removed similar functionality in #185

**Comment by janosdebugs** [comment]
Hey, I'm reading through the open issues and I have a question about this one: what part would provide the name of the signer? Would that simply be the org/person named in the key itself, or would it use some sort of a keyserver? If it's a keyserver, who gets to validate the trust part of they keys downloaded? (GPG keyservers typically don't validate trust, anyone can upload any key with any ID.)

**Comment by Yantrio** [comment]
I need to give this some thought to come up with the best solution.

IMHO we should just use the namespace/github org name used, however this doesn't take into account situations where a registry has redirected the provider namespace (For example, all hashicorp/* providers are pulled from opentofu repositories)

Maybe we can handle something on the registry side to include a name of the signing entity. 

I'd love to pull it from the identity of the key but I think that the identities used are just far too long in most cases.

**Comment by janosdebugs** [comment]
We could make a GitHub-independent login system where people could register their API keys, potentially with an org verification for larger organizations or Linux Foundation projects. I'd personally prefer not treating GitHub preferentially to alternative providers.

**Comment by Yantrio** [comment]
I don't think that fits with our current registry design that we're implementing right now. (See #741). 

I do agree that we shouldn't tie too much directly with github, however this is the known "standard" in the provider authoring world right now.

**Comment by Yantrio** [comment]
Also once this has been completed, we should be sure to update the documentation to reflect how it works. (just like #965 recommends now)

mainly this page: https://opentofu.org/docs/cli/plugins/signing

**Comment by janosdebugs** [comment]
As discussed in the core team, we currently have no good way to validate the legal identity of the signer. Simply copying over the organization name will not provide any additional benefit and assuming the identity based on the GPG key name is not a good solution. As such, this issue will be closed.
