### ISSUE TITLE
[REFACTORING] Remove unused parameters

### ISSUE THREAD

**Issue by kislerdm** [opentofu/opentofu#893]
## Problem statement

There are several places with unused parameters throughout the codebase. For example, the variable passed as an argument [here](https://github.com/opentofu/opentofu/blob/0a0787edf2cdae536160428b04ef49ee88818ad6/internal/command/test.go#L256) is not used in the method. Moreover, the value of the passed variable are the method receiver's attribute.

## Proposed solution

1. Go through the codebase
2. Identify unused parameters
3. Remove them

**Comment by janosdebugs** [comment]
I would argue that this should be done on a bit-by-bit basis. Creating a commit that touches all parts of the codebase will create a mess with other pending PRs as well as increase the potential impact zone for introduced bugs. [golangci-lint](https://github.com/opentofu/opentofu/pull/624) has an `unused` linter that could be set up to warn about unused variables.

**Comment by kislerdm** [comment]
@janosdebugs Hey János, you are right about scope segregation. This issue is a placeholder to keep the topic in mind.

**Comment by janosdebugs** [comment]
Hey @kislerdm we have discussed this issue in the core team and decided that this refactoring would yield very little practical benefit if applied to all the existing code and would touch almost all current packages. As such, we will not be taking on this issue at this time.
