### ISSUE TITLE
Swap `hashicorp`, or `terraform` CLI identification occurrences in the codebase with `OpenTofu`

### ISSUE THREAD

**Issue by kislerdm** [opentofu/opentofu#898]
## Problem

The codebase contains several places where `tofu` is identified as `terraform`. Also, `app.hashicorp.io` is used as URL for tests, and URL.

Examples:
- [cmd/tofu/telemetry.go](https://github.com/opentofu/opentofu/blob/d077a33939ddbe07f8a71d75d8d61c127fee6cd1/cmd/tofu/telemetry.go#L65)
- [internal/backend/remote/testing.go](https://github.com/opentofu/opentofu/blob/d077a33939ddbe07f8a71d75d8d61c127fee6cd1/internal/backend/remote/testing.go#L73-L74)
- [internal/cloud/backend.go](https://github.com/opentofu/opentofu/blob/d077a33939ddbe07f8a71d75d8d61c127fee6cd1/internal/cloud/backend.go#L43-L46)
- [internal/registry/regsrc/friendly_host_test.go](https://github.com/opentofu/opentofu/blob/d077a33939ddbe07f8a71d75d8d61c127fee6cd1/internal/registry/regsrc/friendly_host_test.go#L36-L43)

**Note** please do no change occurrences mentioned in #530, for example:
- `terraform.tfstate.d`
- `terraform.tfstate`
- `X-Terraform-Get`
- Please do not change [internal/version/version.go](https://github.com/opentofu/opentofu/blob/d077a33939ddbe07f8a71d75d8d61c127fee6cd1/version/version.go#L54)

## Proposed solution

- Replace terraform occurrences with `OpenTofu`
- Fix the links to the OpenTofu documentation (see #891)

**Comment by Yantrio** [comment]
We should also replace usages of things like this: https://github.com/opentofu/opentofu/blob/d077a33939ddbe07f8a71d75d8d61c127fee6cd1/internal/registry/regsrc/friendly_host_test.go#L36-L43

**Comment by lplazas** [comment]
Is there any place you are collecting examples of this? I'd be happy to start working on this if there isn't anyone on the task yet.

**Comment by janosdebugs** [comment]
To document what's going on, we rolled back this change because it had side effects for people referencing providers without a namespace (e.g. `aws` instead of `hashicorp/aws`).

**Comment by cam72cam** [comment]
We also decided to keep app.terraform.io for the tests, but make sure that any endpoints that actually connects to them uses a TF_TFC_TEST env flag to enable them.  The idea is it's similar to TF_ACC, but only gates the TFC connections.
