### ISSUE TITLE
Modify get module logic to be compliant with the OpenTofu registry protocol

### ISSUE THREAD

**Issue by kislerdm** [opentofu/opentofu#900]
## Problem

The OpenTofu registry "v1" protocol will be implemented for the stable OpenTofu registry:

_GIVEN_ that a client attempts to download the module `foo/terraform-bar-baz@v0.0.1`

_WHEN_ CLI calls the corresponding URL `https://registry.opentofu.org/v1/modules/foo/baz/bar/0.0.1/download` and the module is found in the registry

_THEN_ the following response is expected:

|Attribute|OpenTofu BW implementation|OpenTofu V1|
|:---|:---|:---|
|Status code|204|200|
|Body||`{"location": "git::https://github.com/foo/terraform-bar-baz?ref=v0.0.1"}`|
|Header: `X-Terraform-Get`|`git::https://github.com/foo/terraform-bar-baz?ref=v0.0.1`||

## Proposed solution

Adjust the OpenTofu CLI to be compatible with the OpenTofu registry "v1" protocol.

## Acceptance criteria

- [x] OpenTofu CLI is compatible with the "v1" protocol, i.e. it reads the module location from the response body.
- [x] OpenTofu CLI is BW compatible with other registry implementation, i.e. it reads the location from the response header in the absence of body.
- [x] The documentation is [adjusted](https://opentofu.org/docs/internals/module-registry-protocol/#sample-response-1).

**Comment by Yantrio** [comment]
For reference: We're currently returning this object.

https://github.com/opentofu/registry-stable/blob/c54f44a6b912bcb134c9727ab594af0be0e2e5bd/src/internal/v1api/responses.go#L5-L9

However I'm happy to swap the word "Location" to something else if needed.

**Comment by cube2222** [comment]
Just saying, it's either/or.

Either there's the header, or there's the body (both simultaneously are allowed, but we should be explicit in which gets priority (imo body, as it can contain more metadata in the future); in practice, only one of them is required).

**Comment by RLRabinowitz** [comment]
Regarding the Registry Stable, the content type will not necessarily be `application/json`
