### ISSUE TITLE
install of tofu-1.6.0~alpha5-1.x86_64.rpm fails - rpm not signed

### ISSUE THREAD

**Issue by sjpb** [opentofu/opentofu#913]
### OpenTofu Version

```shell
N/A
```

### OpenTofu Configuration Files

N/A

### Debug Output

N/A

### Expected Behavior

opentofu should have installed

### Actual Behavior

```
Package tofu-1.6.0~alpha5-1.x86_64.rpm is not signed
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: GPG check FAILED
```

### Steps to Reproduce

1. Create repo file following https://opentofu.org/docs/intro/install/rpm
2. Run `sudo dnf install tofu`

**Comment by kislerdm** [comment]
@sjpb Hey Steve! Thank you for reporting the issue!

Could you please share if you also tried to use the [script](https://opentofu.org/docs/intro/install/rpm/#installing-using-the-convenience-script)? Thanks!

**Comment by janosdebugs** [comment]
@sjpb could you please also share which OS/version you tested this on?

**Comment by sjpb** [comment]
```
$ cat /etc/redhat-release 
Rocky Linux release 8.5 (Green Obsidian)
```

I should upgrade 😆

**Comment by sjpb** [comment]
I didn't use the install script. Interestingly the .repo file that points to at https://packagecloud.io/install/repositories/opentofu/tofu/config_file.repo?os=rpm_any&dist=rpm_any&source=script is different from the one defined at https://opentofu.org/docs/intro/install/rpm/#adding-the-opentofu-repository:


```
$ diff -y /etc/yum.repos.d/opentofu.repo config_file.repo 
[opentofu]                                                    | [opentofu_tofu]
name=opentofu                                                 | name=opentofu_tofu
baseurl=https://packagecloud.io/opentofu/tofu/rpm_any/rpm_any | baseurl=https://packagecloud.io/opentofu/tofu/rpm_any/rpm_any
repo_gpgcheck=1                                                 repo_gpgcheck=1
gpgcheck=1                                                    | gpgcheck=0
enabled=1                                                       enabled=1
gpgkey=https://packagecloud.io/opentofu/tofu/gpgkey             gpgkey=https://packagecloud.io/opentofu/tofu/gpgkey
sslverify=1                                                     sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt                      sslcacert=/etc/pki/tls/certs/ca-bundle.crt
metadata_expire=300                                             metadata_expire=300

[opentofu-source]                                             | [opentofu_tofu-source]
name=opentofu-source                                          | name=opentofu_tofu-source
baseurl=https://packagecloud.io/opentofu/tofu/rpm_any/rpm_any   baseurl=https://packagecloud.io/opentofu/tofu/rpm_any/rpm_any
repo_gpgcheck=1                                                 repo_gpgcheck=1
gpgcheck=1                                                    | gpgcheck=0
enabled=1                                                       enabled=1
gpgkey=https://packagecloud.io/opentofu/tofu/gpgkey             gpgkey=https://packagecloud.io/opentofu/tofu/gpgkey
sslverify=1                                                     sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt                      sslcacert=/etc/pki/tls/certs/ca-bundle.crt
metadata_expire=300                                           / metadata_expire=300
```

One on the left is the one from the instructions, one on the right is the one from the script

**Comment by sjpb** [comment]
So the scripted install just disables GPG check, but the instructions don't.

**Comment by janosdebugs** [comment]
@sjpb thanks for the info. Yes, we made the manual installation process simpler since we don't need most of the logic from Packagecloud anyway. Could you please check if the `pygpgme` package is installed / can be installed and if that resolves the issue?

**Comment by sjpb** [comment]
Not sure if that is dnf or python, but anyway, its not:
```
$ dnf list --installed pygpgme
Error: No matching Packages to list
$ pip show pygpgme
WARNING: Package(s) not found: pygpgme
```

**Comment by janosdebugs** [comment]
@sjpb thanks again, that would solve the mystery. We are trying to replicate this in a container setup so we can update the instructions.

**Comment by sjpb** [comment]
Looking at the install script pygpgme is a rpm. I've got epel-release installed (so, access to EPEL packages) and dnf doesn't find pygpgme.

**Comment by sjpb** [comment]
In fact out of the RH clones, pkgs.org shows pygpgme is only available for oraclelinux 7.

**Comment by sjpb** [comment]
The base repos do provide a package `gpgme` but I have that installed already.

**Comment by janosdebugs** [comment]
Thanks @sjpb we are trying to replicate it on the RPM OS'es and see if we can figure out what's causing this.

**Comment by janosdebugs** [comment]
I think I found the problem, I don't know how I missed this before:

```
# rpm -qpi tofu-1.6.0~alpha5-1.x86_64.rpm
...
Signature   : (none)
```

So the packages are indeed not signed.

**Comment by janosdebugs** [comment]
@sjpb thanks for all your help, it seems there was a bit of an oversight on my part when I wrote the new instructions. The DEB and RPM packages are currently only signed with cosign, which doesn't play well with yum/dnf. The repo metadata is signed by Packagecloud, but not the packages.

I'm afraid, the only current option is to disable the gpgcheck and I'll update the instructions accordingly. #915 tracks the RFC to add GPG signing to the packages.

I'm sorry for the confusion and the unnecessary work caused. Thank you so much for reporting this issue, this really helps.

**Comment by sjpb** [comment]
Just a thought, but maybe it's better to leave the gpgcheck enabled in the .repo file and run (interactively) with `dnf install  --nogpgcheck`? Then at least its obvious what's happening & when rpms do get signed the repo file doesn't need updating. 🤷 

Thanks though, other than that install issue my first go at tf -> tofu seemed seamless which is really impressive.

**Comment by janosdebugs** [comment]
That's a really good suggestion, thanks! I'll try to make sure our instructions are tested better in the next docs PR.

**Comment by janosdebugs** [comment]
Thanks again @sjpb your help has been invaluable. We have temporarily fixed the installation instructions and made an automated test to prevent this from happening again. Longer term (hopefully soon) we'll GPG-sign the packages (see #915) and then update the instructions accordingly.
