### ISSUE TITLE
Revise and enhance integration tests for `pg` backend

### ISSUE THREAD

**Issue by kislerdm** [opentofu/opentofu#921]
## Integration test

See: `internal/backend/remote-state/pg_test.go`

- [ ] Structure
  - Use `cty.Value` as the test argument instead of `map[string]interface{}`
  - Split tests for `PrepareConfig` and `Configure`

**Comment by kush-work** [comment]
Hi @kislerdm I would love to work on this issue; if this hasn't been resolved yet.

**Comment by janosdebugs** [comment]
Hey folks, thank you for this issue. We have discussed it in the core team and decided not to take it on at the present time since it does not resolve any current issue.
