### ISSUE TITLE
Public opentofu registry issue

### ISSUE THREAD

**Issue by askadhum** [opentofu/opentofu#927]
Public OpenTofu registry (registry.opentofu.org) website is not working properly.. it shows "**Missing Authentication Token**" every time

**Comment by Yantrio** [comment]
Hi @askadhum , Thanks for raising this.

Right now the registry is only written to be consumed by the `tofu` binary it's self. And we do not yet have a webpage for the registry. 

This will be implemented after the first stable release of opentofu.

**Comment by kislerdm** [comment]
Hey @askadhum! This issue is being closed because reported behaviour is expected. Please keep an eye on our announcements: we will come back to the registry webpage after the OpenTofu stable version is released.

Thanks for you contribution!
