### ISSUE TITLE
-backend-config not behaving same as declaring var in file

### ISSUE THREAD

**Issue by vivian-rook** [opentofu/opentofu#947]
### OpenTofu Version

```shell
OpenTofu v1.6.0-alpha4
on linux_amd64
+ provider registry.opentofu.org/hashicorp/local v2.4.0
+ provider registry.opentofu.org/terraform-provider-openstack/openstack v1.51.1
```

### OpenTofu Configuration Files

```
terraform {
  backend "s3" {
    bucket                      = "tofu-state"
    endpoint                    = "https://object.eqiad1.wikimediacloud.org"
    key                         = "paws-state"
    region                      = "default"
    skip_credentials_validation = "true"
    skip_region_validation      = "true"
    use_path_style              = "true"
  }
```

### Debug Output

```
Initializing the backend...
╷
│ Error: Backend configuration changed
│ 
│ A change in the backend configuration has been detected, which may require migrating existing state.
│ 
│ If you wish to attempt automatic migration of the state, use "tofu init -migrate-state".
│ If you wish to store the current configuration with no changes to the state, use "tofu init -reconfigure".
╵
```

### Expected Behavior

Should use s3 for backend

### Actual Behavior

Does not seem to use or update s3

### Steps to Reproduce

`tofu init -backend-config "access_key=${ACCESS_KEY}" -backend-config "secret_key=${SECRET_KEY}"`

### Additional Context

Running tofu as described will fail. If I place access_key and secret_key directly in main.tf tofu will succeed and manage the state in s3. 

It does seem that the key I am giving it is correct, as if I change the key I will get an error:
```
│ Error: Failed to get existing workspaces: operation error S3: ListObjectsV2, https response error StatusCode: 404, RequestID: tx00000f0a7d3e6f1f63ec2-006568bfe6-2d9ae1e0-default, HostID: 2d9ae1e0-default-default, api error NoSuchKey: UnknownError
```

I'm looking to get around the problem described in https://github.com/hashicorp/terraform/issues/13022 where variables are not allowed in the backend config block. The primary way that is suggested in the issue is to use -backend-config variables on the command itself. Though I'm not finding that to work.

**Comment by kislerdm** [comment]
@vivian-rook hello Vivian! Could you please update your tofu CLI to the latest version and retry? Thanks!

**Comment by cam72cam** [comment]
Closing due to lack of response.
