### ISSUE TITLE
[REFACTORING] Revise `internal/tofu/eval_context_builtin.go:BuiltinEvalContext` and `internal/tofu/context_plugins.go:contextPlugins`

### ISSUE THREAD

**Issue by kislerdm** [opentofu/opentofu#953]
I appears that `internal/tofu/eval_context_builtin.go:BuiltinEvalContext` is a decorator of `internal/tofu/context_plugins.go:contextPlugins` for schema caching - maybe we could simplify the design because the value of such complexity is not clear.

Followup on #944

**Comment by cube2222** [comment]
Do you mean specifically the schema cache handling part of BuiltinEvalContext?

Cause overall it's basically a helper object that carries a lot of helper functions and state that's required all across the evaluation graph, which makes sense to me.

**Comment by janosdebugs** [comment]
Hey @kislerdm we have discussed this issue in the core team and decided not to take on the refactoring of this part of the code without having to work on it for other reasons.
