### ISSUE TITLE
UI for browsing available Registry provider/modules availability and docs

### ISSUE THREAD

**Issue by roni-frantchi** [opentofu/opentofu#964]
This is a followup to the already accepted https://github.com/opentofu/opentofu/issues/258 and an ask to followup with a more structured RFC submission of supporting a UI that allows for browsing/searching through available providers/modules, as well as their documentation, in a similar fashion to the closed source HashiTF Registry.

**Comment by cam72cam** [comment]
Closing as this is now being done through https://github.com/opentofu/opentofu/issues/1327
