### ISSUE TITLE
Unit tests should use a different useragent to help differentiate in logging

### ISSUE THREAD

**Issue by Yantrio** [opentofu/opentofu#966]
Right now, our unit tests are indistinguishable in our registry statistics, and we would like to try and omit any unit test hits to our registry by using a different user agent so we can determine what is real usage, and what is unit testing.

**Comment by SypherSP** [comment]
Hi @Yantrio, I would like to work on this issue.
Could you confirm if ive understood the issue well-
The registry needs to know where the hits are coming from so that unit tests being run on it do not pollute the statistics. To implement this a different useragent needs to be used for testing.

**Comment by cam72cam** [comment]
That is correct, there also may be a few different code-paths to update where the user agent is set.  Thanks!

**Comment by Yantrio** [comment]
I think this may just be a case of setting the env var `OPENTOFU_USER_AGENT` or `TF_APPEND_USER_AGENT` when we run tests.

See https://github.com/opentofu/opentofu/blob/main/internal/httpclient/useragent.go for more information.

However this will need some manual testing and validation that the user agent used here is the one used everywhere when hitting the registry.

**Comment by SypherSP** [comment]
> setting the env var `OPENTOFU_USER_AGENT` or `TF_APPEND_USER_AGENT` when we run tests

Are you referring to setting the env var in tests like this? 

https://github.com/opentofu/opentofu/blob/7054dda96eafdaeaf2fb257b2b883c94bbc8a901/internal/backend/remote-state/gcs/backend_test.go#L444C1-L444C90

If not, could you point me to any location where unit tests are being run on the registry? 

Also, how can I test any changes I make to this?

Regarding the solution: does it make sense to add a SetTestUserAgent function to the file you've mentioned that sets the required env vars which can be called right before OpenTofuUserAgent wherever tests are being run?

**Comment by Yantrio** [comment]
I'm not proposing we add this in code everywhere, that would be a nightmare. I'm proposing we set the env var when we run the tests.

The tests are being run here: https://github.com/opentofu/opentofu/blob/main/.github/workflows/checks.yml#L35

To be able to test this you should be able to set up a private registry (or reverse proxy) and check the requests sent to that. Or add some logging in the code to dump the http requests.

We can also validate it on our side as we have access to the registry analytics in cloudflare.
