### ISSUE TITLE
Plugin signing page is out of date

### ISSUE THREAD

**Issue by janosdebugs** [opentofu/opentofu#967]
The [plugin signing page](https://opentofu.org/docs/cli/plugins/signing) is no longer up to date as HashiCorp-signed providers no longer exist.

**Comment by Yantrio** [comment]
We should 100% update this since we made this change in https://github.com/opentofu/opentofu/pull/185

**Comment by RLRabinowitz** [comment]
Closed by https://github.com/opentofu/opentofu/pull/1046

**Comment by RLRabinowitz** [comment]
The plugin signing page should be updated to also explain the new signing verification behaviour, alongside the new environment variables `OPENTOFU_ENFORCE_GPG_VALIDATION` and `OPENTOFU_ENFORCE_GPG_EXPIRATION`
