### ISSUE TITLE
Ghosting: a mechanism to embed soft-delete (state removals) in .tf source

### ISSUE THREAD

**Issue by crdrost** [opentofu/opentofu#996]
### OpenTofu Version

```shell
OpenTofu v1.6.0-dev
on darwin_arm64
```

### Use Cases

I help to manage an internal Kubernetes multi-cloud framework for a big company, and the backend is written in .tf. So we have internal customers using v1 of the framework, then they migrate to v2, this is a big update of all of their resources that we manage.

One thing that we run into somewhat often is that we may need to remove a resource _without doing anything to prod_. This happens for instance when something that we were managing manually needs to now be managed with a Helm release, we want to delete all of the resources that were subsumed under the Helm chart, but we don't want the remote entities to be deleted -- we'll set up an idempotent migration so that they can be covered by Helm. 

### Attempted Solutions

The cleanest way to do this right now appears to be from Terragrunt, where a before_hook can be registered to remove the state before planning. Other external scripting also works -- this is something that Terrform/Tofu programs imperatively instead of declaratively. In Terraform/Tofu the cleanest way appears to require turning the requested resource into a no-op in a resource-dependent way, this resource can then host the necessary precondition that might remove the state via external command.

### Proposal

I believe the correct approach to solve this declaratively is to leave some "ghost" of the earlier config in the .tf files, as a way to specify what should happen. Ghosts MAY (as in rfc-may) correspond to something in the state(by definition) and MUST inherit their schema from a resource and hence they have a provider, but MUST NOT be given to that provider to resolve.

I propose a top-level classification, just like `data` and `resource`, called `ghost`, to do precisely this thing. A ghost is a piece of resource state which may be preserved after the resource backing it has disappeared, a `data` that has been created from a `resource`. The basic semantics would be:

1. It is a planning error to have both a `resource "kubernetes_manifest" "foo" {}` and a `ghost "kubernetes_manifest" "foo"`. 
2. You can reference that state like so: `kubernetes_manifest.foo.bar` becomes `ghost.kubernetes_manifest.foo.state.bar`.  This is under the `state` key because there is also a `.exists` key which is a bool. In this way ghosts kind of implicitly have a `count` of 0 or 1, depending on whether state by that name was found or not. Technically point (1) means that there is no confusion if we omit the `ghost` prefix but I think it is good practice.
3. Ghosts can be used as an explicit target for a `moved` declaration, or a target for a state import. This looks just like `moved { from = kubernetes_manifest.foo, to = ghost.kubernetes_manifest.bar }`. Some thought needs to go into what happens with `for_each` and `count` but I would expect `kubernetes_manifest.foo[0].bar` to correspond to `ghost.kubernetes_manifest.foo[0].state.bar`, i.e. the variadic attributes get "lifted" up to the ghost level while the state attributes are always under the `state` key.
4. Ghosts do not trigger refresh from the provider. They can still receive state-upgrades from it and imports, though.
5. Ghost deletion does not trigger provider actions. As far as the provider is concerned there was a `tofu state rm` that got rid of the resource.
6. If a ghost is not targeted by some explicit `moved` declaration, implicitly we write a `moved { from = kubernetes_manifest.foo; to = ghost.kubernetes_manifest.foo }`.

**Comment by crdrost** [comment]
Another use-case for ghost resources, it would be nice if their `lifecycle` could specify to `delete_upstream = true` (default `false`), which would restore the default behavior of deleting the resource, but would save the pre-deletion state to the ghost.

Here's what that gets you: we have a Kubernetes `PodDisruptionBudget` which conflicts with an `eks_addon` upgrade, we would like to delete our PDB and allow `eks_addon`'s version to take priority, however at present this is a *race condition* because there is no good way to specify that the delete (which is implicitly triggered by removing the resource's manifest) should happen _before_ the update. The deleted resource simply has no name to hook onto to specify a precondition or anything.

But with ghosting, we name the deleted resource and this becomes possible. We specify that the resource-to-update, in fact, `depends_on` the ghost. The meaning of this would be "it depends on the ghost's state becoming fully resolved/known," and the lifecycle `delete_upstream` would delay resolving that state until the upstream resource is deleted.

**Comment by janosdebugs** [comment]
Hi @crdrost thank you for your detailed description. I feel like this would better fit an RFC than an enhancement as it is a fundamental change how OpenTofu works.

I also have a question: am I understanding this right that your aim is basically to delete a resource from the state file without removing the resources? If that is correct, what prevents you from using `tofu state rm` to remove those resources and then deleting the corresponding resources from the .tf code?

**Comment by cube2222** [comment]
Hey, thanks for submitting the issue!

After reading your proposal, I still don't quite understand it. It seems like quite a big language change, and with something like this, in order to rationalize both the implementation effort and codebase complexity, we would need a very strong use-case.

Could you maybe write out in more detail the problem you are facing, without actually going into any specific solutions? Basically, a few usage scenarios, use-cases, with step by step explanations. Once everybody properly understands the problem, we'd then move to specific proposals for solving it.

Feel free to add it as a comment, or maybe for now rewrite the issue to describe the problem.

**Comment by kristian-lesko** [comment]
Hello,

Thanks for this proposal. A major use case I see are various refactors (e.g., when moving resources from one module to another) in scenarios where changes are applied by CI/CD.

With `import` and `moved` code blocks, any additions and movements in the state file can be transparently reviewed and approved in a PR, but removal from the state has to be done by a manual `state rm` call, which is much less transparent (and can lead to conflicts if a different change is applied at around the same time).

Thanks for considering this!

**Comment by cube2222** [comment]
I believe what was meant with "this would better fit and RFC" that it would be good to write it out as a full RFC, which uses a [different issue template](https://github.com/opentofu/opentofu/issues/new?assignees=&labels=rfc%2Cpending-decision&projects=&template=rfc.yml), that is much more extensive and structured.

However, I believe we should really first better understand the problem area, as writing out an RFC is quite a bit of work.

> With import and moved code blocks, any additions and movements in the state file can be transparently reviewed and approved in a PR, but removal from the state has to be done by a manual state rm call, which is much less transparent (and can lead to conflicts if a different change is applied at around the same time).

Thanks for adding your comment to the discussion! A "removed" block similar to those is planned for 1.7, which should help with that.

**Comment by crdrost** [comment]
yeah I was planning to edit it into RFC-format, but work got in the way.

"Removed" as an analogue of the "moved" block is interesting, though, and I think maybe I should rewrite this as a proposed enhancement to the removed block.
